/**
 * @file erro_code.show.inl
 * @author Javnson (javnson@zju.edu.cn)
 * @brief
 * @version 0.1
 * @date 2024-09-30
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

// This file is generated by `tools/error_code_gen` automatically.
// Please DO NOT change this file.

ec_gt gmp_std_return(ec_gt error_code)
{

    return error_code;
}
