/**
 * @file csp.config.h
 * @author Javnson (javnson@zju.edu.cn)
 * @brief
 * @version 0.1
 * @date 2025-01-18
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

// This file provide a Chip Support Package configuration for an example device

// Disable Liner CMD Tool support header call.
// This file may be generated by SyscConfig.
#define _C2000_CSP_DISBALE_LINKER_CMD_TOOL_

// Disable C2000 Device Support
// #define _C2000_CSP_DISABLE_DEVICE_SUPPORT_

// Disable C2000Ware Library support header call.
// This file may be generated by SysConfig.
#define _C2000_CSP_DISABLE_C2000WARE_LIBRARY_

// Disable C2000 CLB Configuration Tool
#define _C2000_CSP_DISABLE_CLB_CONFIG_TOOL_

// SPI Peripheral config
// For maximum extension device support, please use 8 instead of 16
#define _C2000_SPI_INTERFACE_DATA_LENGTH ((8))


// SPECIFY disable endless loop exit function
#define SPECIFY_DISABLE_CSP_EXIT

// TI String will not add a '\0' automatically, so use the following macro.
#define TEXT_STRING(str) str##"\0"

// Specify print function
#define USER_SPECIFIED_PRINT_FUNCTION(A, ...) gmp_base_print_c28xsyscfg(A, ##__VA_ARGS__)
