/**
 * @file im_ifoc_core.h
 * @brief Implements an Indirect Field-Oriented Control (IFOC) core for AC Induction Motors.
 * @details This module serves as the main current regulation loop for Induction Motors. 
 * It offloads the slip and synchronous angle calculation to the `im_pos_calc` module. 
 * It supports exact physical voltage feedforward decoupling and features a Consultant-based 
 * initialization for automatic PI tuning and scale factor generation.
 *
 * @version 2.0
 * @date 2024-10-26
 *
 */

#include <ctl/component/intrinsic/continuous/continuous_pid.h>
#include <ctl/component/intrinsic/discrete/discrete_filter.h>
#include <ctl/component/motor_control/interface/motor_universal_interface.h>
#include <ctl/math_block/coordinate/coord_trans.h>
#include <ctl/component/motor_control/consultant/acim_consultant.h>
#include <ctl/component/motor_control/consultant/pu_consultant.h>
#include <ctl/component/motor_control/observer/acim_pos_calc.h>

#ifndef _FILE_IM_IFOC_CORE_H_
#define _FILE_IM_IFOC_CORE_H_


#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

/*---------------------------------------------------------------------------*/
/* IM IFOC Current Controller                                                */
/*---------------------------------------------------------------------------*/

/**
 * @defgroup IM_IFOC_CONTROLLER IM Indirect Field-Oriented Controller
 * @brief The core current regulation and slip generation loop for IM.
 * @details Implements standard IFOC. Integrates slip frequency to generate the 
 * synchronous reference frame angle. Uses transient inductance for PI tuning 
 * and exact IM physical equations for voltage feedforward decoupling.
 * @{
 */

//================================================================================
// Type Defines
//================================================================================

/**
 * @brief Raw initialization parameters for the IM IFOC Controller.
 */
typedef struct _tag_im_ifoc_init
{
    parameter_gt fs;            //!< Controller execution frequency (Hz).
    parameter_gt v_bus;         //!< Nominal DC Bus voltage (V).
    parameter_gt v_phase_limit; //!< Phase voltage limitation (Vrms).
    parameter_gt v_base;        //!< Base Phase Voltage Peak for PU conversion (V).
    parameter_gt i_base;        //!< Base Phase Current Peak for PU conversion (A).
    parameter_gt spd_base;      //!< Nominal motor speed base (krpm).
    parameter_gt pole_pairs;    //!< Number of pole pairs.

    // --- IM Physical Parameters ---
    parameter_gt mtr_Rs; //!< Stator resistance (Ohm).
    parameter_gt mtr_Rr; //!< Rotor resistance (Ohm).
    parameter_gt mtr_Ls; //!< Stator self-inductance (H).
    parameter_gt mtr_Lr; //!< Rotor self-inductance (H).
    parameter_gt mtr_Lm; //!< Mutual inductance (H).

    // --- Tuning Targets ---
    parameter_gt current_loop_bw; //!< Target current loop bandwidth (Hz).

} im_ifoc_init_t;

/**
 * @brief Main structure for the IM IFOC current controller.
 */
typedef struct _tag_im_ifoc_ctrl
{
    uint32_t isr_tick;

    // --- Interfaces ---
    tri_adc_ift* adc_iuvw;
    adc_ift* adc_udc;
    rotation_ift* pos_if; //!< Rotor mechanical position interface

    velocity_ift spd_if; //!< (Velocity must be in PU).

    // --- Core Sub-modules ---
    ctl_im_pos_calc_t pos_calc; //!< Independent module for slip and sync angle calculation.

    // --- Setpoints ---
    ctl_vector2_t idq_ref; //!< d-q current reference [flux_ref, torque_ref] in PU.

    // --- Measurements & States ---
    ctrl_gt udc;
    ctl_vector3_t iuvw;
    ctl_vector3_t iab0;
    ctl_vector3_t idq0;

    ctl_vector2_t sync_phasor; //!< Phasor for Park/iPark transforms generated by pos_calc.

    // --- Controllers & Filters ---
    ctl_filter_IIR1_t filter_iuvw[3];
    ctl_filter_IIR1_t filter_udc;
    ctl_pid_t idq_ctrl[2];

    // --- Pre-calculated Decoupling Constants (PU Space) ---
    ctrl_gt sf_dec_lsigma;  //!< Transient inductance decoupling factor (sigma * Ls / L_base).
    ctrl_gt sf_dec_backemf; //!< Back-EMF decoupling factor (Lm^2 / Lr / L_base).

    // --- Limits ---
    ctrl_gt max_vs_mag;        //!< Maximum voltage vector magnitude limit (PU).
    ctrl_gt max_dcbus_voltage; //!< Nominal DC bus voltage (PU) for bus compensation.

    // --- Output Vectors ---
    ctl_vector2_t vdq_ctrl_out;
    ctl_vector2_t vdq_decouple;
    ctl_vector3_t vdq_out;
    ctl_vector2_t vdq_out_sat;
    ctl_vector3_t vab0;

    // --- Flags ---
    fast_gt flag_enable_current_ctrl;
    fast_gt flag_enable_decouple;
    fast_gt flag_enable_bus_compensation;

} im_ifoc_ctrl_t;

//================================================================================
// Function Prototypes & Inline Definitions
//================================================================================

/**
 * @brief Initializes the IFOC controller using raw physical parameters.
 */
void ctl_autotune_and_init_im_ifoc(im_ifoc_ctrl_t* mc, const im_ifoc_init_t* init);

/**
 * @brief Advanced initialization function utilizing the Consultant models.
 * @details Automatically tunes the PI current controllers and decoupling feedforward
 * matrices based on the exact transient inductance and equivalent resistance.
 */
void ctl_autotune_and_init_im_ifoc_consultant(im_ifoc_ctrl_t* mc, const ctl_consultant_im_t* motor,
                                              const ctl_consultant_pu_im_t* pu, parameter_gt fs, parameter_gt v_bus,
                                              parameter_gt v_phase_limit, parameter_gt current_loop_bw);

GMP_STATIC_INLINE void ctl_attach_im_ifoc_port(im_ifoc_ctrl_t* mc, tri_adc_ift* _iuvw, adc_ift* _udc,
                                               rotation_ift* _pos_if)
{
    mc->adc_iuvw = _iuvw;
    mc->adc_udc = _udc;
    mc->pos_if = _pos_if;
}

GMP_STATIC_INLINE void ctl_enable_im_ifoc(im_ifoc_ctrl_t* mc)
{
    mc->flag_enable_current_ctrl = 1;
    ctl_enable_im_pos_calc(&mc->pos_calc);
}

GMP_STATIC_INLINE void ctl_disable_im_ifoc(im_ifoc_ctrl_t* mc)
{
    mc->flag_enable_current_ctrl = 0;
    ctl_disable_im_pos_calc(&mc->pos_calc);
}

GMP_STATIC_INLINE void ctl_set_im_ifoc_ref(im_ifoc_ctrl_t* mc, ctrl_gt id_ref, ctrl_gt iq_ref)
{
    mc->idq_ref.dat[0] = id_ref;
    mc->idq_ref.dat[1] = iq_ref;
}

/**
 * @brief Executes one high-frequency step of the IM IFOC loop.
 */
GMP_STATIC_INLINE void ctl_step_im_ifoc(im_ifoc_ctrl_t* mc)
{
    mc->isr_tick++;

    gmp_base_assert(mc->adc_iuvw != NULL);
    gmp_base_assert(mc->pos_if != NULL);

    // ========================================================================
    // 1. ADC Filtering & Clarke Transform
    // ========================================================================
#if MC_CURRENT_SAMPLE_PHASE_MODE == 3
    mc->iuvw.dat[phase_U] = ctl_step_filter_iir1(&mc->filter_iuvw[phase_U], mc->adc_iuvw->value.dat[phase_A]);
    mc->iuvw.dat[phase_V] = ctl_step_filter_iir1(&mc->filter_iuvw[phase_V], mc->adc_iuvw->value.dat[phase_B]);
    mc->iuvw.dat[phase_W] = ctl_step_filter_iir1(&mc->filter_iuvw[phase_W], mc->adc_iuvw->value.dat[phase_C]);
    ctl_ct_clarke(&mc->iuvw, &mc->iab0);
#elif MC_CURRENT_SAMPLE_PHASE_MODE == 2
    mc->iuvw.dat[phase_U] = ctl_step_filter_iir1(&mc->filter_iuvw[phase_U], mc->adc_iuvw->value.dat[phase_A]);
    mc->iuvw.dat[phase_V] = ctl_step_filter_iir1(&mc->filter_iuvw[phase_V], mc->adc_iuvw->value.dat[phase_B]);
    ctl_ct_clarke_2ph((ctl_vector2_t*)&mc->iuvw, (ctl_vector2_t*)&mc->iab0);
    mc->iab0.dat[phase_0] = 0;
#endif

    if (mc->adc_udc)
        mc->udc = ctl_step_filter_iir1(&mc->filter_udc, mc->adc_udc->value);

    // ========================================================================
    // 2. Slip Calculation & Synchronous Angle Extraction
    // ========================================================================
    // IFOC heavily relies on using the Reference Iq rather than the noisy measured Iq
    // to calculate the slip speed smoothly. We feed it directly into our pos_calc.
    ctrl_gt sync_angle_pu =
        ctl_step_im_pos_calc(&mc->pos_calc, mc->idq0.dat[phase_d], mc->idq_ref.dat[phase_q], mc->spd_if.speed);

    ctl_set_phasor_via_angle(sync_angle_pu, &mc->sync_phasor);

    // ========================================================================
    // 3. Park Transform
    // ========================================================================
    ctl_ct_park(&mc->iab0, &mc->sync_phasor, &mc->idq0);

    // ========================================================================
    // 4. Current Loop PI Controllers & Decoupling
    // ========================================================================
    if (mc->flag_enable_current_ctrl)
    {
        ctrl_gt err_d = mc->idq_ref.dat[phase_d] - mc->idq0.dat[phase_d];
        ctrl_gt err_q = mc->idq_ref.dat[phase_q] - mc->idq0.dat[phase_q];

        mc->vdq_ctrl_out.dat[phase_d] = ctl_step_pid_ser(&mc->idq_ctrl[phase_d], err_d);
        mc->vdq_ctrl_out.dat[phase_q] = ctl_step_pid_ser(&mc->idq_ctrl[phase_q], err_q);

        // IM Specific Voltage Feedforward Decoupling
        if (mc->flag_enable_decouple)
        {
            // Sync speed is already cleanly extracted from pos_calc
            ctrl_gt w_e_pu = mc->pos_calc.w_sync_pu;
            ctrl_gt i_md_pu = mc->pos_calc.i_md_pu;

            // Vd_dec = -omega_e * (sigma * Ls) * Iq
            mc->vdq_decouple.dat[phase_d] = ctl_mul(-w_e_pu, ctl_mul(mc->sf_dec_lsigma, mc->idq0.dat[phase_q]));

            // Vq_dec = omega_e * (sigma * Ls) * Id + omega_e * (Lm^2/Lr) * I_md
            ctrl_gt vq_cross = ctl_mul(mc->sf_dec_lsigma, mc->idq0.dat[phase_d]);
            ctrl_gt vq_emf = ctl_mul(mc->sf_dec_backemf, i_md_pu);
            mc->vdq_decouple.dat[phase_q] = ctl_mul(w_e_pu, vq_cross + vq_emf);

            mc->vdq_out.dat[phase_d] = mc->vdq_ctrl_out.dat[phase_d] + mc->vdq_decouple.dat[phase_d];
            mc->vdq_out.dat[phase_q] = mc->vdq_ctrl_out.dat[phase_q] + mc->vdq_decouple.dat[phase_q];
        }
        else
        {
            ctl_vector2_clear(&mc->vdq_decouple);
            mc->vdq_out.dat[phase_d] = mc->vdq_ctrl_out.dat[phase_d];
            mc->vdq_out.dat[phase_q] = mc->vdq_ctrl_out.dat[phase_q];
        }

        // ====================================================================
        // 5. Bus Compensation & Circular Saturation
        // ====================================================================
        if (mc->flag_enable_bus_compensation && mc->udc > float2ctrl(0.5f))
        {
            ctrl_gt v_scale = ctl_div(mc->max_dcbus_voltage, mc->udc);
            mc->vdq_out.dat[phase_d] = ctl_mul(mc->vdq_out.dat[phase_d], v_scale);
            mc->vdq_out.dat[phase_q] = ctl_mul(mc->vdq_out.dat[phase_q], v_scale);
        }

        mc->vdq_out_sat.dat[phase_d] = ctl_sat(mc->vdq_out.dat[phase_d], mc->max_vs_mag, -mc->max_vs_mag);

        ctrl_gt abs_vd =
            (mc->vdq_out_sat.dat[phase_d] > 0) ? mc->vdq_out_sat.dat[phase_d] : -mc->vdq_out_sat.dat[phase_d];
        ctrl_gt max_vq = mc->max_vs_mag - abs_vd; // Circular approximation
        mc->vdq_out_sat.dat[phase_q] = ctl_sat(mc->vdq_out.dat[phase_q], max_vq, -max_vq);

        // Anti-Windup
        ctl_pid_clamping_correction_using_real_output(&mc->idq_ctrl[phase_d],
                                                      mc->vdq_out_sat.dat[phase_d] - mc->vdq_decouple.dat[phase_d]);
        ctl_pid_clamping_correction_using_real_output(&mc->idq_ctrl[phase_q],
                                                      mc->vdq_out_sat.dat[phase_q] - mc->vdq_decouple.dat[phase_q]);
    }
    else
    {
        ctl_vector2_clear(&mc->vdq_out_sat);
    }

    // ========================================================================
    // 6. Inverse Park Transform
    // ========================================================================
    ctl_ct_ipark((ctl_vector3_t*)&mc->vdq_out_sat, &mc->sync_phasor, &mc->vab0);
}

/** @} */

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _FILE_IM_IFOC_CORE_H_
