GMP - CTL: component/motor_control/motion/Trapezoidal_trajectory.m File Reference
Trapezoidal_trajectory.m File Reference
Functions
else profile_traj (i)
if (target_velocity >=v_limit) target_acceleration=0
elseif (target_velocity<=-v_limit) target_acceleration=0
record the result for debug target_acceleration_record (i, 1)
target_velocity_record (i, 1)
target_position_record (i, 1)
end figure subplot (3, 1, 1) plot(t
end figure target_acceleration_record (:, 1))
subplot (3, 1, 2) plot(t
target_velocity_record (:, 1))
subplot (3, 1, 3) plot(t
target_position_record (:, 1))
hold on plot (t, profile_traj)
if (target_acceleration >=a_limit) target_acceleration = a_limit
elseif (target_acceleration<=-a_limit) target_acceleration = -a_limit
record the result for debug target_acceleration_record (i, 2)
target_velocity_record (i, 2)
target_position_record (i, 2)
end figure target_acceleration_record (:, 2))
target_velocity_record (:, 2))
target_position_record (:, 2))
id pi ()
bode (spd_filter)
figure step (spd_filter)
record the result for debug target_acceleration_record (i, 3)
target_velocity_record (i, 3)
target_position_record (i, 3)
end figure target_acceleration_record (:, 3))
ylim ([-1.5, 1.5])
target_velocity_record (:, 3))
target_position_record (:, 3))
Variables
constrain v_limit = 1
p u a_limit = 0.5
p u aa_limit = 1
p u pos_deadband = 1e-4
time scale t_limit = 20
t = 0:0.001:t_limit
delta_t = 0.001
fs = 1 / delta_t
initial state
initial current state cur_pos = 5
cur_vel = -2
cur_acc = 0
debug record target_acceleration_record = zeros(length(t),3)
target_velocity_record = zeros(length(t),3)
target_position_record = zeros(length(t),3)
profile_traj = zeros(length(t),1)
user traj plan for i
traj plan I
target_velocity = cur_vel
target_position = cur_pos
step II
step III
position loop dead band if(abs(profile_pos - target_position) > pos_deadband) if(dir_judge > 0) % step IV else step VI
end end else step VII
end step VIII
end else The position feedforward has been in deadband target_acceleration = 0
end step IX
k3 = aa_limit / 6
k2 = target_acceleration / 2
k1 = target_velocity
k0 = target_position
brk_roots = roots([k3,k2,k1,k0])
brake_distance = brk_roots(1)
omega_spd = aa_limit * exp(1) / v_limit*10
xi = 1
q = 1/2/xi
spd_filter = omega_spd^2 / (s^2 + 2*xi*omega_spd*s + omega_spd^2)
fiugre
f0 = omega_spd*2*q
theta = f0 / 2/ pi/ fs
sin_theta = sin(theta)
cos_theta = cos(theta)
alpha = sin_theta / 2 / q
gain = 1
a0 = 1+alpha
a1 = -2*cos_theta/a0
a2 = (1 - alpha)/a0
b0 = gain * (1 - cos_theta) / (2*a0)
b1 = gain * (1 - cos_theta) / a0
b2 = gain * (1 - cos_theta) / (2*a0)
IIR filter parameter x1 = 0
x2 = 0
y1 = 0
y2 = 0
target_velocity_new
Function Documentation
bode()
bode (spd_filter)
References bode(), figure(), and spd_filter.
elseif() [1/2]
elseif (target_acceleration<=- a_limit) = -a_limit
References a_limit, delta_t, elseif(), if(), IX, step(), target_acceleration, target_position, target_velocity, v_limit, and VIII.
elseif() [2/2]
elseif (target_velocity<=- v_limit) pure virtual
References target_acceleration, target_velocity, and v_limit.
if() [1/2]
if (target_acceleration >= a_limit) = a_limit
References a_limit, if(), and target_acceleration.
if() [2/2]
if (target_velocity >= v_limit) pure virtual
References target_acceleration, target_velocity, and v_limit.
pi()
id pi () virtual
References omega_spd, and pi().
plot()
hold on plot (t , profile_traj)
References a_limit, brake_distance, cur_acc, cur_pos, cur_vel, I, i, II, plot(), profile_traj, S, step(), t, target_acceleration, target_position, and target_velocity.
profile_traj()
else profile_traj (i)
References i, profile_traj, and t.
step()
figure step (spd_filter)
References spd_filter, and step().
subplot() [1/3]
end figure subplot (3 , 1 , 1)
subplot() [2/3]
subplot (3 , 1 , 2)
References subplot().
subplot() [3/3]
subplot (3 , 1 , 3)
References subplot().
target_acceleration_record() [1/6]
end figure target_acceleration_record (: , 1)
References plot(), t, and target_acceleration_record.
target_acceleration_record() [2/6]
end figure target_acceleration_record (: , 2)
References plot(), subplot(), t, and target_acceleration_record.
target_acceleration_record() [3/6]
end figure target_acceleration_record (: , 3)
References plot(), t, and target_acceleration_record.
target_acceleration_record() [4/6]
record the result for debug target_acceleration_record (i , 1)
References i, and target_acceleration.
target_acceleration_record() [5/6]
record the result for debug target_acceleration_record (i , 2)
References i, target_acceleration, and target_acceleration_record.
target_acceleration_record() [6/6]
record the result for debug target_acceleration_record (i , 3)
References i, target_acceleration, and target_acceleration_record.
target_position_record() [1/6]
target_position_record (: , 1)
References on, plot(), t, and target_position_record.
target_position_record() [2/6]
target_position_record (: , 2)
References III, on, plot(), profile_traj, t, and target_position_record.
target_position_record() [3/6]
target_position_record (: , 3)
References on, plot(), profile_traj, t, and target_position_record.
target_position_record() [4/6]
target_position_record (i , 1)
References figure(), i, and target_position.
target_position_record() [5/6]
target_position_record (i , 2)
References figure(), i, subplot(), target_position, and target_position_record.
target_position_record() [6/6]
target_position_record (i , 3)
References figure(), i, subplot(), target_position, and target_position_record.
target_velocity_record() [1/6]
target_velocity_record (: , 1)
References plot(), t, and target_velocity_record.
target_velocity_record() [2/6]
target_velocity_record (: , 2)
References plot(), subplot(), t, and target_velocity_record.
target_velocity_record() [3/6]
target_velocity_record (: , 3)
References plot(), subplot(), t, and target_velocity_record.
target_velocity_record() [4/6]
target_velocity_record (i , 1)
References i, and target_velocity.
target_velocity_record() [5/6]
target_velocity_record (i , 2)
References i, target_velocity, and target_velocity_record.
target_velocity_record() [6/6]
target_velocity_record (i , 3)
References i, target_velocity, and target_velocity_record.
ylim()
ylim ()
References subplot(), and ylim().
Variable Documentation
a0
a0 = 1+alpha
Definition at line 230 of file Trapezoidal_trajectory.m.
a1
a1 = -2*cos_theta/a0
Definition at line 231 of file Trapezoidal_trajectory.m.
a2
a2 = (1 - alpha)/a0
Definition at line 232 of file Trapezoidal_trajectory.m.
a_limit
p u a_limit = 0.5
Definition at line 3 of file Trapezoidal_trajectory.m.
aa_limit
p u aa_limit = 1
Definition at line 4 of file Trapezoidal_trajectory.m.
alpha
alpha = sin_theta / 2 / q
Definition at line 226 of file Trapezoidal_trajectory.m.
b0
b0 = gain * (1 - cos_theta) / (2*a0)
Definition at line 233 of file Trapezoidal_trajectory.m.
b1
b1 = gain * (1 - cos_theta) / a0
Definition at line 234 of file Trapezoidal_trajectory.m.
b2
b2 = gain * (1 - cos_theta) / (2*a0)
Definition at line 235 of file Trapezoidal_trajectory.m.
brake_distance
brake_distance = brk_roots(1)
Definition at line 130 of file Trapezoidal_trajectory.m.
brk_roots
brk_roots = roots([k3,k2,k1,k0])
Definition at line 129 of file Trapezoidal_trajectory.m.
cos_theta
cos_theta = cos(theta)
Definition at line 225 of file Trapezoidal_trajectory.m.
cur_acc
cur_acc = 0
Definition at line 17 of file Trapezoidal_trajectory.m.
cur_pos
initial current state cur_pos = 5
Definition at line 15 of file Trapezoidal_trajectory.m.
cur_vel
cur_vel = -2
Definition at line 16 of file Trapezoidal_trajectory.m.
delta_t
delta_t = 0.001
Definition at line 11 of file Trapezoidal_trajectory.m.
f0
f0 = omega_spd*2*q
Definition at line 222 of file Trapezoidal_trajectory.m.
fiugre
fiugre
Definition at line 217 of file Trapezoidal_trajectory.m.
fs
fs = 1 / delta_t
Definition at line 12 of file Trapezoidal_trajectory.m.
gain
gain = 1
Definition at line 228 of file Trapezoidal_trajectory.m.
I
step I
Definition at line 37 of file Trapezoidal_trajectory.m.
i
for i
Initial value:
  = 1:length(t)
if(t(i) < 10)
    profile_traj(i) = 3
Definition at line 26 of file Trapezoidal_trajectory.m.
II
step II
Definition at line 48 of file Trapezoidal_trajectory.m.
III
step III
Definition at line 51 of file Trapezoidal_trajectory.m.
IX
end step IX
Definition at line 91 of file Trapezoidal_trajectory.m.
k0
k0 = target_position
Definition at line 127 of file Trapezoidal_trajectory.m.
k1
k1 = target_velocity
Definition at line 126 of file Trapezoidal_trajectory.m.
k2
k2 = target_acceleration / 2
Definition at line 125 of file Trapezoidal_trajectory.m.
k3
k3 = aa_limit / 6
Definition at line 124 of file Trapezoidal_trajectory.m.
omega_spd
omega_spd = aa_limit * exp(1) / v_limit*10
Definition at line 212 of file Trapezoidal_trajectory.m.
pos_deadband
p u pos_deadband = 1e-4
Definition at line 5 of file Trapezoidal_trajectory.m.
profile_traj
end end profile_traj = zeros(length(t),1)
Definition at line 23 of file Trapezoidal_trajectory.m.
q
q = 1/2/xi
Definition at line 214 of file Trapezoidal_trajectory.m.
sin_theta
sin_theta = sin(theta)
Definition at line 224 of file Trapezoidal_trajectory.m.
spd_filter
spd_filter = omega_spd^2 / (s^2 + 2*xi*omega_spd*s + omega_spd^2)
Definition at line 215 of file Trapezoidal_trajectory.m.
state
initial state
Definition at line 14 of file Trapezoidal_trajectory.m.
t
t = 0:0.001:t_limit
Definition at line 10 of file Trapezoidal_trajectory.m.
t_limit
time scale t_limit = 20
Definition at line 8 of file Trapezoidal_trajectory.m.
target_acceleration
end else The position feedforward has been in deadband target_acceleration = 0
Definition at line 87 of file Trapezoidal_trajectory.m.
target_acceleration_record
debug record target_acceleration_record = zeros(length(t),3)
Definition at line 20 of file Trapezoidal_trajectory.m.
target_position
target_position = cur_pos
Definition at line 40 of file Trapezoidal_trajectory.m.
target_position_record
target_position_record = zeros(length(t),3)
Definition at line 22 of file Trapezoidal_trajectory.m.
target_velocity
end target_velocity = cur_vel
Definition at line 39 of file Trapezoidal_trajectory.m.
target_velocity_new
target_velocity_new
Initial value:
                = b0 * speed_ref + b1 * x1 + b2 * x2  ...
- a1 * y1 - a2 * y2
Definition at line 287 of file Trapezoidal_trajectory.m.
target_velocity_record
target_velocity_record = zeros(length(t),3)
Definition at line 21 of file Trapezoidal_trajectory.m.
theta
theta = f0 / 2/ pi/ fs
Definition at line 223 of file Trapezoidal_trajectory.m.
v_limit
constrain v_limit = 1
Definition at line 2 of file Trapezoidal_trajectory.m.
VI
position loop dead band if (abs(profile_pos - target_position) > pos_deadband) if(dir_judge > 0) % step IV else step VI
Definition at line 65 of file Trapezoidal_trajectory.m.
VII
end else step VII
Definition at line 70 of file Trapezoidal_trajectory.m.
VIII
end step VIII
Definition at line 74 of file Trapezoidal_trajectory.m.
x1
x1 = 0
Definition at line 238 of file Trapezoidal_trajectory.m.
x2
x2 = 0
Definition at line 239 of file Trapezoidal_trajectory.m.
xi
xi = 1
Definition at line 213 of file Trapezoidal_trajectory.m.
y1
y1 = 0
Definition at line 240 of file Trapezoidal_trajectory.m.
y2
y2 = 0
Definition at line 241 of file Trapezoidal_trajectory.m.