GMP - CTL: framework/cia402_state_machine.h File Reference
cia402_state_machine.h File Reference
Data Structures
union cia402_ctrl_word_t
union cia402_state_word_t
struct cia402_sm_t
Macros
#define CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH
#define CIA402_CONFIG_DISABLE_CONTROL_WORD_DEFAULT
#define CIA402_CONFIG_MIN_DELAY_READY (100)
#define CIA402_CONFIG_MIN_DELAY_SHUTDOWN (100)
#define CIA402_CONFIG_MIN_DELAY_SWITCHON (100)
#define CIA402_CONFIG_MIN_DELAY_OPERATION_EN (100)
#define CIA402_CONTROLWORD_SWITCHON (0x0001)
#define CIA402_CONTROLWORD_ENABLE_VOLTAGE (0x0002)
#define CIA402_CONTROLWORD_QUICKSTOP (0x0004)
#define CIA402_CONTROLWORD_ENABLE_OPERATION (0x0008)
#define CIA402_CONTROLWORD_FAULT_RESET (0x0080)
#define CIA402_CONTROLWORD_HALT (0x0100)
#define CIA402_CMD_DISABLE_OPERATION CIA402_CMD_SWITCHON
#define CIA402_STATEWORD_READY_TO_SWITCH_ON (0x0001)
#define CIA402_STATEWORD_SWITCHED_ON (0x0002)
#define CIA402_STATEWORD_OPERATION_ENABLED (0x0004)
#define CIA402_STATEWORD_FAULT (0x0008)
#define CIA402_STATEWORD_VOLTAGE_ENABLED (0x0010)
#define CIA402_STATEWORD_QUICKSTOP (0x0020)
#define CIA402_STATEWORD_SWICH_ON_DISABLED (0X0040)
#define CIA402_STATEWORD_REMOTE (0x0200)
#define CIA402_STATEWORD_TARGET_REACHED (0x0400)
#define TIMEOUT_PRECHARGE_MS 3000
#define TIMEOUT_ADC_CALIB_MS 3000
#define TIMEOUT_ALIGNMENT_MS 5000
Typedefs
typedef cia402_sm_error_code_t(* cia402_cb_fn_t) (struct _tag_cia402_state_machine *sm)
Enumerations
enum cia402_cmd_t {
CIA402_CMD_NULL = 0 , CIA402_CMD_DISABLE_VOLTAGE = 1 , CIA402_CMD_SHUTDOWN , CIA402_CMD_SWITCHON ,
CIA402_CMD_ENABLE_OPERATION , CIA402_CMD_QUICK_STOP , CIA402_CMD_FAULT_RESET
}
enum cia402_state_t {
CIA402_SM_NOT_READY_TO_SWITCH_ON = 0 , CIA402_SM_SWITCH_ON_DISABLED , CIA402_SM_READY_TO_SWITCH_ON , CIA402_SM_SWITCHED_ON ,
CIA402_SM_OPERATION_ENABLED , CIA402_SM_QUICK_STOP_ACTIVE , CIA402_SM_FAULT_REACTION , CIA402_SM_FAULT ,
CIA402_SM_UNKNOWN = 0xFF
}
enum cia402_sm_error_code_t { CIA402_EC_KEEP = 0 , CIA402_EC_NEXT_STATE = 1 , CIA402_EC_ERROR = -1 }
Functions
cia402_cmd_t get_cia402_control_cmd (uint16_t control_word)
解析控制字 (0x6040) 并返回对应的命令枚举 基于 CiA 402 State Transition 逻辑表
cia402_state_t get_cia402_state (uint16_t status_word)
根据 StatusWord 解析当前 CiA 402 状态
void init_cia402_state_machine (cia402_sm_t *sm)
void cia402_update_status_word (cia402_sm_t *sm)
void cia402_fault_request (cia402_sm_t *sm)
void cia402_transit (cia402_sm_t *sm, cia402_state_t next_state)
void cia402_dispatch (cia402_sm_t *sm)
GMP_STATIC_INLINE void cia402_send_cmd (cia402_sm_t *sm, cia402_cmd_t cmd)
GMP_STATIC_INLINE void cia402_fault_reset (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_switch_on_disabled (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_ready_to_switch_on (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_switched_on (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_operation_enabled (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_quick_stop_active (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_fault_reaction (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_fault (cia402_sm_t *sm)
void ctl_enable_pwm (void)
硬件PWM输出使能/禁止
void ctl_disable_pwm (void)
void ctl_enable_main_contactor (void)
主接触器/直流继电器控制
void ctl_disable_main_contactor (void)
void ctl_enable_precharge_relay (void)
预充电继电器控制
void ctl_disable_precharge_relay (void)
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
fast_gt ctl_exec_dc_voltage_ready (void)
检查直流母线电压是否在允许范围内
void ctl_release_brake (void)
机械抱闸控制 (Holding Brake)
void ctl_restore_brake (void)
fast_gt ctl_check_encoder (void)
检查编码器/位置传感器状态
fast_gt ctl_exec_rotor_alignment (void)
启动转子初始位置检测 (IPD / Alignment)
fast_gt ctl_check_pll_locked (void)
启动/复位锁相环 (PLL)
fast_gt ctl_check_compliance (void)
检查电网电压/频率是否符合安规 (Grid Code)
void ctl_enable_grid_relay (void)
交流并网继电器/断路器控制
void ctl_disable_grid_relay (void)
Macro Definition Documentation
CIA402_CMD_DISABLE_OPERATION
#define CIA402_CMD_DISABLE_OPERATION CIA402_CMD_SWITCHON
Definition at line 98 of file cia402_state_machine.h.
CIA402_CONFIG_DISABLE_CONTROL_WORD_DEFAULT
#define CIA402_CONFIG_DISABLE_CONTROL_WORD_DEFAULT
Definition at line 16 of file cia402_state_machine.h.
CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH
#define CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH
Definition at line 13 of file cia402_state_machine.h.
CIA402_CONFIG_MIN_DELAY_OPERATION_EN
#define CIA402_CONFIG_MIN_DELAY_OPERATION_EN (100)
Definition at line 36 of file cia402_state_machine.h.
CIA402_CONFIG_MIN_DELAY_READY
#define CIA402_CONFIG_MIN_DELAY_READY (100)
Definition at line 21 of file cia402_state_machine.h.
CIA402_CONFIG_MIN_DELAY_SHUTDOWN
#define CIA402_CONFIG_MIN_DELAY_SHUTDOWN (100)
Definition at line 26 of file cia402_state_machine.h.
CIA402_CONFIG_MIN_DELAY_SWITCHON
#define CIA402_CONFIG_MIN_DELAY_SWITCHON (100)
Definition at line 31 of file cia402_state_machine.h.
CIA402_CONTROLWORD_ENABLE_OPERATION
#define CIA402_CONTROLWORD_ENABLE_OPERATION (0x0008)
Definition at line 54 of file cia402_state_machine.h.
CIA402_CONTROLWORD_ENABLE_VOLTAGE
#define CIA402_CONTROLWORD_ENABLE_VOLTAGE (0x0002)
Definition at line 48 of file cia402_state_machine.h.
CIA402_CONTROLWORD_FAULT_RESET
#define CIA402_CONTROLWORD_FAULT_RESET (0x0080)
Definition at line 57 of file cia402_state_machine.h.
CIA402_CONTROLWORD_HALT
#define CIA402_CONTROLWORD_HALT (0x0100)
Definition at line 60 of file cia402_state_machine.h.
CIA402_CONTROLWORD_QUICKSTOP
#define CIA402_CONTROLWORD_QUICKSTOP (0x0004)
Definition at line 51 of file cia402_state_machine.h.
CIA402_CONTROLWORD_SWITCHON
#define CIA402_CONTROLWORD_SWITCHON (0x0001)
Definition at line 45 of file cia402_state_machine.h.
CIA402_STATEWORD_FAULT
#define CIA402_STATEWORD_FAULT (0x0008)
Definition at line 121 of file cia402_state_machine.h.
CIA402_STATEWORD_OPERATION_ENABLED
#define CIA402_STATEWORD_OPERATION_ENABLED (0x0004)
Definition at line 118 of file cia402_state_machine.h.
CIA402_STATEWORD_QUICKSTOP
#define CIA402_STATEWORD_QUICKSTOP (0x0020)
Definition at line 127 of file cia402_state_machine.h.
CIA402_STATEWORD_READY_TO_SWITCH_ON
#define CIA402_STATEWORD_READY_TO_SWITCH_ON (0x0001)
Definition at line 112 of file cia402_state_machine.h.
CIA402_STATEWORD_REMOTE
#define CIA402_STATEWORD_REMOTE (0x0200)
Definition at line 133 of file cia402_state_machine.h.
CIA402_STATEWORD_SWICH_ON_DISABLED
#define CIA402_STATEWORD_SWICH_ON_DISABLED (0X0040)
Definition at line 130 of file cia402_state_machine.h.
CIA402_STATEWORD_SWITCHED_ON
#define CIA402_STATEWORD_SWITCHED_ON (0x0002)
Definition at line 115 of file cia402_state_machine.h.
CIA402_STATEWORD_TARGET_REACHED
#define CIA402_STATEWORD_TARGET_REACHED (0x0400)
Definition at line 136 of file cia402_state_machine.h.
CIA402_STATEWORD_VOLTAGE_ENABLED
#define CIA402_STATEWORD_VOLTAGE_ENABLED (0x0010)
Definition at line 124 of file cia402_state_machine.h.
TIMEOUT_ADC_CALIB_MS
#define TIMEOUT_ADC_CALIB_MS 3000
Definition at line 440 of file cia402_state_machine.h.
TIMEOUT_ALIGNMENT_MS
#define TIMEOUT_ALIGNMENT_MS 5000
Definition at line 444 of file cia402_state_machine.h.
TIMEOUT_PRECHARGE_MS
#define TIMEOUT_PRECHARGE_MS 3000
Definition at line 436 of file cia402_state_machine.h.
Typedef Documentation
cia402_cb_fn_t
typedef cia402_sm_error_code_t(* cia402_cb_fn_t) (struct _tag_cia402_state_machine *sm)
Definition at line 276 of file cia402_state_machine.h.
Enumeration Type Documentation
cia402_cmd_t
enum cia402_cmd_t
Enumerator
CIA402_CMD_NULL
CIA402_CMD_DISABLE_VOLTAGE
CIA402_CMD_SHUTDOWN
CIA402_CMD_SWITCHON
CIA402_CMD_ENABLE_OPERATION
CIA402_CMD_QUICK_STOP
CIA402_CMD_FAULT_RESET
Definition at line 87 of file cia402_state_machine.h.
cia402_sm_error_code_t
enum cia402_sm_error_code_t
Enumerator
CIA402_EC_KEEP
CIA402_EC_NEXT_STATE
CIA402_EC_ERROR
Definition at line 263 of file cia402_state_machine.h.
cia402_state_t
enum cia402_state_t
Enumerator
CIA402_SM_NOT_READY_TO_SWITCH_ON
CIA402_SM_SWITCH_ON_DISABLED
CIA402_SM_READY_TO_SWITCH_ON
CIA402_SM_SWITCHED_ON
CIA402_SM_OPERATION_ENABLED
CIA402_SM_QUICK_STOP_ACTIVE
CIA402_SM_FAULT_REACTION
CIA402_SM_FAULT
CIA402_SM_UNKNOWN
Definition at line 217 of file cia402_state_machine.h.
Function Documentation
cia402_dispatch()
void cia402_dispatch (cia402_sm_t * sm)
Definition at line 584 of file ctl_cia402_state_machine.c.
References cia402_ctrl_word_t::all, cia402_ctrl_word_t::bits, cia402_fault_request(), CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, cia402_transit(), cia402_update_status_word(), cia402_sm_t::control_word, cia402_sm_t::current_cmd, cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_ctrl_word_t::fault_reset, cia402_sm_t::flag_enable_control_word, cia402_sm_t::flag_fault_reset_request, get_cia402_control_cmd(), and cia402_sm_t::last_fault_reset_bit.
cia402_fault_request()
void cia402_fault_request (cia402_sm_t * sm)
Definition at line 564 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT_REACTION, cia402_update_status_word(), cia402_sm_t::current_state, cia402_sm_t::flag_delay_stage, and cia402_sm_t::flag_fault_reset_request.
cia402_fault_reset()
GMP_STATIC_INLINE void cia402_fault_reset (cia402_sm_t * sm)
Definition at line 389 of file cia402_state_machine.h.
References cia402_sm_t::flag_fault_reset_request.
cia402_send_cmd()
GMP_STATIC_INLINE void cia402_send_cmd (cia402_sm_t * sm, cia402_cmd_t cmd)
Definition at line 383 of file cia402_state_machine.h.
References cia402_sm_t::current_cmd.
cia402_transit()
void cia402_transit (cia402_sm_t * sm, cia402_state_t next_state)
Definition at line 275 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, cia402_update_status_word(), cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::entry_state_tick, and cia402_sm_t::flag_delay_stage.
cia402_update_status_word()
void cia402_update_status_word (cia402_sm_t * sm)
Definition at line 199 of file ctl_cia402_state_machine.c.
References cia402_state_word_t::all, cia402_state_word_t::bits, CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, CIA402_STATEWORD_QUICKSTOP, cia402_sm_t::current_state, cia402_state_word_t::fault, cia402_state_word_t::operation_enabled, cia402_state_word_t::quick_stop, cia402_state_word_t::ready_to_switch_on, cia402_sm_t::state_word, cia402_state_word_t::switch_on_disabled, and cia402_state_word_t::switched_on.
ctl_check_compliance()
fast_gt ctl_check_compliance (void)
检查电网电压/频率是否符合安规 (Grid Code)
Note
整个运行周期都需要检查
Definition at line 196 of file ctl_cia402_callback_fn.c.
ctl_check_encoder()
fast_gt ctl_check_encoder (void)
检查编码器/位置传感器状态
Note
在 Ready to Switch On 之前必须通过
Definition at line 153 of file ctl_cia402_callback_fn.c.
ctl_check_pll_locked()
fast_gt ctl_check_pll_locked (void)
启动/复位锁相环 (PLL)
Note
在 Ready to Switch On 状态下必须启动 PLL
Definition at line 183 of file ctl_cia402_callback_fn.c.
References ctl_abs, ctl_get_gfl_pll_error(), ctl_is_gfl_grid_connected(), CTRL_SPLL_EPSILON, and inv_ctrl.
ctl_disable_grid_relay()
void ctl_disable_grid_relay (void)
Definition at line 222 of file ctl_cia402_callback_fn.c.
ctl_disable_main_contactor()
void ctl_disable_main_contactor (void)
Definition at line 61 of file ctl_cia402_callback_fn.c.
ctl_disable_precharge_relay()
void ctl_disable_precharge_relay (void)
Definition at line 81 of file ctl_cia402_callback_fn.c.
ctl_disable_pwm()
void ctl_disable_pwm (void)
Definition at line 39 of file ctl_cia402_callback_fn.c.
References ctl_clear_gfl_inv(), ctl_clear_gfl_pq(), ctl_clear_neg_inv(), ctl_fast_disable_output(), inv_ctrl, neg_current_ctrl, and pq_ctrl.
ctl_enable_grid_relay()
void ctl_enable_grid_relay (void)
交流并网继电器/断路器控制
Note
在 Ready -> Switched On 跳转时闭合
Parameters
close true: 并网; false: 解列
Definition at line 214 of file ctl_cia402_callback_fn.c.
ctl_enable_main_contactor()
void ctl_enable_main_contactor (void)
主接触器/直流继电器控制
Note
通常在 Ready to Switch On 阶段闭合
Parameters
close true: 吸合; false: 断开
Definition at line 53 of file ctl_cia402_callback_fn.c.
ctl_enable_precharge_relay()
void ctl_enable_precharge_relay (void)
预充电继电器控制
Note
在 Switch On Disabled -> Ready to Switch On 过渡期间使用
Definition at line 73 of file ctl_cia402_callback_fn.c.
ctl_enable_pwm()
void ctl_enable_pwm (void)
硬件PWM输出使能/禁止
Note
在 Operation Enabled 状态下为 true，其他状态为 false
Parameters
enable true: 开启PWM驱动; false: 封锁PWM（高阻态或特定电平）
Definition at line 30 of file ctl_cia402_callback_fn.c.
References ctl_fast_enable_output().
ctl_exec_adc_calibration()
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
Note
通常在 Not Ready 或 Switch On Disabled 状态下调用
Returns
true: 校准完成且成功; false: 失败或正在进行中
Definition at line 98 of file ctl_cia402_callback_fn.c.
References adc_calibrator, clear_all_controllers(), ctl_clear_adc_calibrator(), ctl_clear_gfl_inv_with_PLL(), ctl_div, ctl_enable_adc_calibrator(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, inv_ctrl, iuvw, uuvw, and vabc.
ctl_exec_dc_voltage_ready()
fast_gt ctl_exec_dc_voltage_ready (void)
检查直流母线电压是否在允许范围内
Note
用于 Ready to Switch On 的准入条件
Definition at line 111 of file ctl_cia402_callback_fn.c.
ctl_exec_rotor_alignment()
fast_gt ctl_exec_rotor_alignment (void)
启动转子初始位置检测 (IPD / Alignment)
Note
针对同步电机。通常在 Switched On -> Operation Enabled 瞬间触发
Definition at line 166 of file ctl_cia402_callback_fn.c.
ctl_release_brake()
void ctl_release_brake (void)
机械抱闸控制 (Holding Brake)
Note
电机场景特有。通常 Operation Enabled 时 release (true)，否则 engage (false)
Parameters
release true: 松开抱闸(允许转动); false: 抱死(制动)
Definition at line 129 of file ctl_cia402_callback_fn.c.
ctl_restore_brake()
void ctl_restore_brake (void)
Definition at line 137 of file ctl_cia402_callback_fn.c.
default_cb_fn_fault()
cia402_sm_error_code_t default_cb_fn_fault (cia402_sm_t * sm)
Definition at line 900 of file ctl_cia402_state_machine.c.
References CIA402_EC_KEEP, ctl_disable_grid_relay(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), and cia402_sm_t::current_state_counter.
default_cb_fn_fault_reaction()
cia402_sm_error_code_t default_cb_fn_fault_reaction (cia402_sm_t * sm)
Definition at line 879 of file ctl_cia402_state_machine.c.
References CIA402_EC_NEXT_STATE, ctl_disable_grid_relay(), ctl_disable_pwm(), ctl_restore_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_operation_enabled()
cia402_sm_error_code_t default_cb_fn_operation_enabled (cia402_sm_t * sm)
Definition at line 834 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, ctl_check_compliance(), ctl_enable_pwm(), ctl_release_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_quick_stop_active()
cia402_sm_error_code_t default_cb_fn_quick_stop_active (cia402_sm_t * sm)
Definition at line 857 of file ctl_cia402_state_machine.c.
References CIA402_EC_NEXT_STATE, ctl_disable_pwm(), ctl_restore_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_ready_to_switch_on()
cia402_sm_error_code_t default_cb_fn_ready_to_switch_on (cia402_sm_t * sm)
Definition at line 754 of file ctl_cia402_state_machine.c.
References CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_check_pll_locked(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), ctl_enable_main_contactor(), ctl_enable_precharge_relay(), ctl_exec_dc_voltage_ready(), cia402_sm_t::current_state_counter, and cia402_sm_t::flag_delay_stage.
default_cb_fn_switch_on_disabled()
cia402_sm_error_code_t default_cb_fn_switch_on_disabled (cia402_sm_t * sm)
Definition at line 716 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_check_encoder(), ctl_disable_grid_relay(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), ctl_exec_adc_calibration(), ctl_restore_brake(), cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_sm_t::entry_state_tick, and TIMEOUT_ADC_CALIB_MS.
default_cb_fn_switched_on()
cia402_sm_error_code_t default_cb_fn_switched_on (cia402_sm_t * sm)
Definition at line 803 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_enable_grid_relay(), ctl_enable_main_contactor(), ctl_exec_rotor_alignment(), cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_sm_t::entry_state_tick, and TIMEOUT_ALIGNMENT_MS.
get_cia402_control_cmd()
cia402_cmd_t get_cia402_control_cmd (uint16_t control_word)
解析控制字 (0x6040) 并返回对应的命令枚举 基于 CiA 402 State Transition 逻辑表
Parameters
control_word 16位控制字
Returns
cia402_cmd 解析出的命令
Definition at line 22 of file ctl_cia402_state_machine.c.
References CIA402_CMD_DISABLE_VOLTAGE, CIA402_CMD_ENABLE_OPERATION, CIA402_CMD_FAULT_RESET, CIA402_CMD_NULL, CIA402_CMD_QUICK_STOP, CIA402_CMD_SHUTDOWN, and CIA402_CMD_SWITCHON.
get_cia402_state()
cia402_state_t get_cia402_state (uint16_t status_word)
根据 StatusWord 解析当前 CiA 402 状态
Parameters
status_word 16位的原始状态字 (0x6041)
Returns
cia402_state_t 对应的枚举状态
Definition at line 87 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, and CIA402_SM_UNKNOWN.
init_cia402_state_machine()
void init_cia402_state_machine (cia402_sm_t * sm)
Definition at line 161 of file ctl_cia402_state_machine.c.
References cia402_ctrl_word_t::all, cia402_state_word_t::all, CIA402_CMD_DISABLE_VOLTAGE, CIA402_CONFIG_MIN_DELAY_OPERATION_EN, CIA402_CONFIG_MIN_DELAY_READY, CIA402_CONFIG_MIN_DELAY_SHUTDOWN, CIA402_CONFIG_MIN_DELAY_SWITCHON, CIA402_EC_KEEP, CIA402_SM_NOT_READY_TO_SWITCH_ON, cia402_sm_t::control_word, cia402_sm_t::current_cmd, cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, default_cb_fn_fault(), default_cb_fn_fault_reaction(), default_cb_fn_operation_enabled(), default_cb_fn_quick_stop_active(), default_cb_fn_ready_to_switch_on(), default_cb_fn_switch_on_disabled(), default_cb_fn_switched_on(), cia402_sm_t::fault, cia402_sm_t::fault_reaction, cia402_sm_t::flag_enable_control_word, cia402_sm_t::flag_fault_reset_request, cia402_sm_t::last_cb_result, cia402_sm_t::last_fault_reset_bit, cia402_sm_t::minimum_transit_delay, cia402_sm_t::operation_enabled, cia402_sm_t::quick_stop_active, cia402_sm_t::ready_to_switch_on, cia402_sm_t::state_word, cia402_sm_t::switch_on_disabled, and cia402_sm_t::switched_on.