GMP - CTL: tb/GMP_CTL_Intrinsic_UT/GMP_CTL_Intrinsic_UT/continuous_pid_test.cpp File Reference
continuous_pid_test.cpp File Reference
#include "pch.h"
#include <ctl/component/intrinsic/continuous/continuous_pid.h>
Data Structures
class PID_Parallel_Test
Functions
TEST_F (PID_Parallel_Test, Initialization_CalculatesGainsCorrectly)
TEST_F (PID_Parallel_Test, Clear_ResetsInternalStates)
TEST_F (PID_Parallel_Test, Step_FirstStepOutputIsCorrect)
TEST_F (PID_Parallel_Test, Step_OutputSaturatesAtMaxLimit)
TEST_F (PID_Parallel_Test, Step_OutputSaturatesAtMinLimit)
TEST_F (PID_Parallel_Test, Step_IntegratorSaturatesAtMaxLimit)
Function Documentation
TEST_F() [1/6]
TEST_F (PID_Parallel_Test , Clear_ResetsInternalStates)
Definition at line 48 of file continuous_pid_test.cpp.
References ctl_clear_pid().
TEST_F() [2/6]
TEST_F (PID_Parallel_Test , Initialization_CalculatesGainsCorrectly)
Definition at line 29 of file continuous_pid_test.cpp.
References fs.
TEST_F() [3/6]
TEST_F (PID_Parallel_Test , Step_FirstStepOutputIsCorrect)
Definition at line 65 of file continuous_pid_test.cpp.
References ctl_step_pid_par().
TEST_F() [4/6]
TEST_F (PID_Parallel_Test , Step_IntegratorSaturatesAtMaxLimit)
Definition at line 163 of file continuous_pid_test.cpp.
References ctl_step_pid_par().
TEST_F() [5/6]
TEST_F (PID_Parallel_Test , Step_OutputSaturatesAtMaxLimit)
Definition at line 137 of file continuous_pid_test.cpp.
References ctl_step_pid_par().
TEST_F() [6/6]
TEST_F (PID_Parallel_Test , Step_OutputSaturatesAtMinLimit)
Definition at line 150 of file continuous_pid_test.cpp.
References ctl_step_pid_par().