GMP - CTL: component/motor_control/src/ctl_mc_basic.c File Reference
ctl_mc_basic.c File Reference
#include <gmp_core.h>
#include <ctl/component/motor_control/basic/encoder.h>
#include <ctl/component/motor_control/basic/vf_generator.h>
#include <ctl/component/motor_control/basic/mtr_protection.h>
Functions
void ctl_init_pos_encoder (pos_encoder_t *enc, uint16_t poles, uint32_t position_base)
Initializes the absolute position encoder structure.
void ctl_init_multiturn_pos_encoder (pos_multiturn_encoder_t *enc, uint16_t poles, uint32_t position_base)
Initializes the multi-turn position encoder structure.
void ctl_init_autoturn_pos_encoder (pos_autoturn_encoder_t *enc, uint16_t poles, uint32_t position_base)
Initializes the auto-turn position encoder structure.
void ctl_init_spd_calculator (spd_calculator_t *sc, rotation_ift *pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, parameter_gt speed_filter_fc)
Initializes the speed calculator.
void ctl_init_spd_calculator_elecpos (spd_calculator_t *sc, rotation_ift *pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, uint16_t pole_pairs, parameter_gt speed_filter_fc)
Initializes the speed calculator.
void ctl_init_const_f_controller (ctl_const_f_controller *ctrl, parameter_gt frequency, parameter_gt isr_freq)
Initializes the Constant Frequency Controller.
void ctl_init_const_slope_f_controller (ctl_slope_f_controller *ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller.
void ctl_set_slope_f_freq (ctl_slope_f_controller *ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the slope generator.
void ctl_init_const_slope_f_pu_controller (ctl_slope_f_pu_controller *ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt rated_krpm, parameter_gt pole_pairs, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller (PU).
void ctl_init_const_vf_controller (ctl_const_vf_controller *ctrl, parameter_gt frequency, parameter_gt freq_slope, ctrl_gt voltage_bound, ctrl_gt voltage_over_frequency, ctrl_gt voltage_bias, parameter_gt isr_freq)
void ctl_set_const_vf_target_freq (ctl_const_vf_controller *ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the V/F controller.
void ctl_init_mtr_protect (ctl_mtr_protect_t *prot, parameter_gt fs)
void ctl_attach_mtr_protect_port (ctl_mtr_protect_t *prot, ctrl_gt *u_dc, ctl_vector2_t *i_meas, ctl_vector2_t *i_ref, adc_ift *mtr_temp, adc_ift *inv_temp)
fast_gt ctl_dispatch_mtr_protect_slow (ctl_mtr_protect_t *prot)
Main Loop Protection Dispatch. This calling frequency of this function should be less than 1kHz.
Function Documentation
ctl_attach_mtr_protect_port()
void ctl_attach_mtr_protect_port (ctl_mtr_protect_t * prot, ctrl_gt * u_dc, ctl_vector2_t * i_meas, ctl_vector2_t * i_ref, adc_ift * mtr_temp, adc_ift * inv_temp)
Definition at line 327 of file ctl_mc_basic.c.
References ctl_mtr_protect_t::ptr_idq, ctl_mtr_protect_t::ptr_inv_temp, ctl_mtr_protect_t::ptr_mtr_temp, ctl_mtr_protect_t::ptr_ref, and ctl_mtr_protect_t::ptr_udc.
ctl_dispatch_mtr_protect_slow()
fast_gt ctl_dispatch_mtr_protect_slow (ctl_mtr_protect_t * prot)
Main Loop Protection Dispatch. This calling frequency of this function should be less than 1kHz.
Returns
1 if fault active, 0 if safe
Definition at line 342 of file ctl_mc_basic.c.
References mtr_protect_error_t::all, mtr_protect_error_t::bit, ctl_mtr_protect_t::cnt_inv_ot, ctl_mtr_protect_t::cnt_mtr_ot, ctl_mtr_protect_t::cnt_uv, ctl_is_greater_ot(), ctl_is_less(), ctl_mtr_protect_debounce(), ctl_mtr_protect_t::error_code, ctl_mtr_protect_t::error_mask, mtr_protect_error_t::inv_over_temp, ctl_mtr_protect_t::limit_cnt_inv_ot, ctl_mtr_protect_t::limit_cnt_mtr_ot, ctl_mtr_protect_t::limit_cnt_uv, ctl_mtr_protect_t::limit_inv_ot, ctl_mtr_protect_t::limit_mtr_ot, ctl_mtr_protect_t::limit_uv_pu, mtr_protect_error_t::mtr_over_temp, MTR_PROT_NONE, ctl_mtr_protect_t::ptr_inv_temp, ctl_mtr_protect_t::ptr_mtr_temp, ctl_mtr_protect_t::ptr_udc, and mtr_protect_error_t::under_voltage.
ctl_init_const_vf_controller()
void ctl_init_const_vf_controller (ctl_const_vf_controller * ctrl, parameter_gt frequency, parameter_gt freq_slope, ctrl_gt voltage_bound, ctrl_gt voltage_over_frequency, ctrl_gt voltage_bias, parameter_gt isr_freq)
Definition at line 240 of file ctl_mc_basic.c.
References ctl_init_ramp_generator_via_freq(), ctl_init_saturation(), ctl_init_slope_limiter(), rotation_ift::elec_position, ctl_const_vf_controller::enc, float2ctrl, ctl_const_vf_controller::freq_slope, rotation_ift::position, ctl_const_vf_controller::rg, ctl_const_vf_controller::target_frequency, ctl_const_vf_controller::target_voltage, ctl_const_vf_controller::v_bias, ctl_const_vf_controller::v_over_f, and ctl_const_vf_controller::volt_sat.
ctl_init_mtr_protect()
void ctl_init_mtr_protect (ctl_mtr_protect_t * prot, parameter_gt fs)
Definition at line 296 of file ctl_mc_basic.c.
References mtr_protect_error_t::all, ctl_clear_mtr_protect(), ctl_mtr_protect_t::error_mask, float2ctrl, fs, ctl_mtr_protect_t::limit_cnt_dev, ctl_mtr_protect_t::limit_cnt_inv_ot, ctl_mtr_protect_t::limit_cnt_mtr_ot, ctl_mtr_protect_t::limit_cnt_oc, ctl_mtr_protect_t::limit_cnt_ov, ctl_mtr_protect_t::limit_cnt_uv, ctl_mtr_protect_t::limit_dev_sq_pu, ctl_mtr_protect_t::limit_inv_ot, ctl_mtr_protect_t::limit_mtr_ot, ctl_mtr_protect_t::limit_oc_sq_pu, ctl_mtr_protect_t::limit_ov_pu, and ctl_mtr_protect_t::limit_uv_pu.