GMP - CTL: framework/src/ctl_cia402_state_machine.c File Reference
ctl_cia402_state_machine.c File Reference
#include <gmp_core.h>
#include <ctl/framework/cia402_state_machine.h>
Functions
cia402_cmd_t get_cia402_control_cmd (uint16_t control_word)
解析控制字 (0x6040) 并返回对应的命令枚举 基于 CiA 402 State Transition 逻辑表
cia402_state_t get_cia402_state (uint16_t status_word)
根据 StatusWord 解析当前 CiA 402 状态
void init_cia402_state_machine (cia402_sm_t *sm)
void cia402_update_status_word (cia402_sm_t *sm)
void cia402_transit (cia402_sm_t *sm, cia402_state_t next_state)
void cia402_fault_request (cia402_sm_t *sm)
void cia402_dispatch (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_switch_on_disabled (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_ready_to_switch_on (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_switched_on (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_operation_enabled (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_quick_stop_active (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_fault_reaction (cia402_sm_t *sm)
cia402_sm_error_code_t default_cb_fn_fault (cia402_sm_t *sm)
Function Documentation
cia402_dispatch()
void cia402_dispatch (cia402_sm_t * sm)
Definition at line 584 of file ctl_cia402_state_machine.c.
References cia402_ctrl_word_t::all, cia402_ctrl_word_t::bits, cia402_fault_request(), CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, cia402_transit(), cia402_update_status_word(), cia402_sm_t::control_word, cia402_sm_t::current_cmd, cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_ctrl_word_t::fault_reset, cia402_sm_t::flag_enable_control_word, cia402_sm_t::flag_fault_reset_request, get_cia402_control_cmd(), and cia402_sm_t::last_fault_reset_bit.
cia402_fault_request()
void cia402_fault_request (cia402_sm_t * sm)
Definition at line 564 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT_REACTION, cia402_update_status_word(), cia402_sm_t::current_state, cia402_sm_t::flag_delay_stage, and cia402_sm_t::flag_fault_reset_request.
cia402_transit()
void cia402_transit (cia402_sm_t * sm, cia402_state_t next_state)
Definition at line 275 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, cia402_update_status_word(), cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::entry_state_tick, and cia402_sm_t::flag_delay_stage.
cia402_update_status_word()
void cia402_update_status_word (cia402_sm_t * sm)
Definition at line 199 of file ctl_cia402_state_machine.c.
References cia402_state_word_t::all, cia402_state_word_t::bits, CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, CIA402_STATEWORD_QUICKSTOP, cia402_sm_t::current_state, cia402_state_word_t::fault, cia402_state_word_t::operation_enabled, cia402_state_word_t::quick_stop, cia402_state_word_t::ready_to_switch_on, cia402_sm_t::state_word, cia402_state_word_t::switch_on_disabled, and cia402_state_word_t::switched_on.
default_cb_fn_fault()
cia402_sm_error_code_t default_cb_fn_fault (cia402_sm_t * sm)
Definition at line 900 of file ctl_cia402_state_machine.c.
References CIA402_EC_KEEP, ctl_disable_grid_relay(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), and cia402_sm_t::current_state_counter.
default_cb_fn_fault_reaction()
cia402_sm_error_code_t default_cb_fn_fault_reaction (cia402_sm_t * sm)
Definition at line 879 of file ctl_cia402_state_machine.c.
References CIA402_EC_NEXT_STATE, ctl_disable_grid_relay(), ctl_disable_pwm(), ctl_restore_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_operation_enabled()
cia402_sm_error_code_t default_cb_fn_operation_enabled (cia402_sm_t * sm)
Definition at line 834 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, ctl_check_compliance(), ctl_enable_pwm(), ctl_release_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_quick_stop_active()
cia402_sm_error_code_t default_cb_fn_quick_stop_active (cia402_sm_t * sm)
Definition at line 857 of file ctl_cia402_state_machine.c.
References CIA402_EC_NEXT_STATE, ctl_disable_pwm(), ctl_restore_brake(), and cia402_sm_t::current_state_counter.
default_cb_fn_ready_to_switch_on()
cia402_sm_error_code_t default_cb_fn_ready_to_switch_on (cia402_sm_t * sm)
Definition at line 754 of file ctl_cia402_state_machine.c.
References CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_check_pll_locked(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), ctl_enable_main_contactor(), ctl_enable_precharge_relay(), ctl_exec_dc_voltage_ready(), cia402_sm_t::current_state_counter, and cia402_sm_t::flag_delay_stage.
default_cb_fn_switch_on_disabled()
cia402_sm_error_code_t default_cb_fn_switch_on_disabled (cia402_sm_t * sm)
Definition at line 716 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_check_encoder(), ctl_disable_grid_relay(), ctl_disable_main_contactor(), ctl_disable_precharge_relay(), ctl_disable_pwm(), ctl_exec_adc_calibration(), ctl_restore_brake(), cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_sm_t::entry_state_tick, and TIMEOUT_ADC_CALIB_MS.
default_cb_fn_switched_on()
cia402_sm_error_code_t default_cb_fn_switched_on (cia402_sm_t * sm)
Definition at line 803 of file ctl_cia402_state_machine.c.
References CIA402_EC_ERROR, CIA402_EC_KEEP, CIA402_EC_NEXT_STATE, ctl_enable_grid_relay(), ctl_enable_main_contactor(), ctl_exec_rotor_alignment(), cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, cia402_sm_t::entry_state_tick, and TIMEOUT_ALIGNMENT_MS.
get_cia402_control_cmd()
cia402_cmd_t get_cia402_control_cmd (uint16_t control_word)
解析控制字 (0x6040) 并返回对应的命令枚举 基于 CiA 402 State Transition 逻辑表
Parameters
control_word 16位控制字
Returns
cia402_cmd 解析出的命令
Definition at line 22 of file ctl_cia402_state_machine.c.
References CIA402_CMD_DISABLE_VOLTAGE, CIA402_CMD_ENABLE_OPERATION, CIA402_CMD_FAULT_RESET, CIA402_CMD_NULL, CIA402_CMD_QUICK_STOP, CIA402_CMD_SHUTDOWN, and CIA402_CMD_SWITCHON.
get_cia402_state()
cia402_state_t get_cia402_state (uint16_t status_word)
根据 StatusWord 解析当前 CiA 402 状态
Parameters
status_word 16位的原始状态字 (0x6041)
Returns
cia402_state_t 对应的枚举状态
Definition at line 87 of file ctl_cia402_state_machine.c.
References CIA402_SM_FAULT, CIA402_SM_FAULT_REACTION, CIA402_SM_NOT_READY_TO_SWITCH_ON, CIA402_SM_OPERATION_ENABLED, CIA402_SM_QUICK_STOP_ACTIVE, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCH_ON_DISABLED, CIA402_SM_SWITCHED_ON, and CIA402_SM_UNKNOWN.
init_cia402_state_machine()
void init_cia402_state_machine (cia402_sm_t * sm)
Definition at line 161 of file ctl_cia402_state_machine.c.
References cia402_ctrl_word_t::all, cia402_state_word_t::all, CIA402_CMD_DISABLE_VOLTAGE, CIA402_CONFIG_MIN_DELAY_OPERATION_EN, CIA402_CONFIG_MIN_DELAY_READY, CIA402_CONFIG_MIN_DELAY_SHUTDOWN, CIA402_CONFIG_MIN_DELAY_SWITCHON, CIA402_EC_KEEP, CIA402_SM_NOT_READY_TO_SWITCH_ON, cia402_sm_t::control_word, cia402_sm_t::current_cmd, cia402_sm_t::current_state, cia402_sm_t::current_state_counter, cia402_sm_t::current_tick, default_cb_fn_fault(), default_cb_fn_fault_reaction(), default_cb_fn_operation_enabled(), default_cb_fn_quick_stop_active(), default_cb_fn_ready_to_switch_on(), default_cb_fn_switch_on_disabled(), default_cb_fn_switched_on(), cia402_sm_t::fault, cia402_sm_t::fault_reaction, cia402_sm_t::flag_enable_control_word, cia402_sm_t::flag_fault_reset_request, cia402_sm_t::last_cb_result, cia402_sm_t::last_fault_reset_bit, cia402_sm_t::minimum_transit_delay, cia402_sm_t::operation_enabled, cia402_sm_t::quick_stop_active, cia402_sm_t::ready_to_switch_on, cia402_sm_t::state_word, cia402_sm_t::switch_on_disabled, and cia402_sm_t::switched_on.