GMP - CTL: component/intrinsic/discrete/fir32forc28x.m File Reference
fir32forc28x.m File Reference
Typedefs
using b = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens})
Functions
plot of the signal subplot (1, 2, 1)
plot of the signal plot (S)
axis ([0 BUFFER_SIZE-1 -2 2])
title ('Signal') xlabel('time(microseconds)') %plot of the filtered signal subplot(1
plot (S_filt)
Variables
clc clear all close all FREQ1 = 1e3
MATLAB code for the Finite Impulse Response Filter.
signal FREQ2 = 33e3
signal SAMPLING_FREQ = 100e3
FIR_ORDER = 63
BUFFER_SIZE = (FIR_ORDER+1) * 4
k1 = FREQ1/SAMPLING_FREQ
k2 = FREQ2/SAMPLING_FREQ
i = 1 : 1 : BUFFER_SIZE
S = 0.5*(sin(2*pi*k1*i) + sin(2*pi*k2*i))
N = FIR_ORDER
Order Fpass = 0.07
Passband Frequency Fstop = 0.15
Stopband Frequency Wpass = 1
Passband Weight Wstop = 1
Stopband Weight dens = 20
Hd = dfilt.dffir(b)
Fc = Hd.Numerator
S_filt = conv(S,Fc)
plot of the signal grid on
Typedef Documentation
b
using b = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens})
Definition at line 44 of file fir32forc28x.m.
Function Documentation
axis()
axis ()
Definition at line 105 of file generate_fuzzy_2d_src.m.
plot() [1/2]
plot of the signal plot (S)
plot() [2/2]
plot (S_filt)
References axis, BUFFER_SIZE, file, on, plot(), S_filt, title(), and xlabel().
subplot()
plot of the signal subplot (1 , 2 , 1)
title()
title ('Signal')
References plot(), subplot(), and xlabel().
Variable Documentation
BUFFER_SIZE
BUFFER_SIZE = (FIR_ORDER+1) * 4
Definition at line 26 of file fir32forc28x.m.
dens
Stopband Weight dens = 20
Definition at line 40 of file fir32forc28x.m.
Fc
Fc = Hd.Numerator
Definition at line 47 of file fir32forc28x.m.
FIR_ORDER
FIR_ORDER = 63
Definition at line 25 of file fir32forc28x.m.
Fpass
Order Fpass = 0.07
Definition at line 36 of file fir32forc28x.m.
FREQ1
clc clear all close all FREQ1 = 1e3
MATLAB code for the Finite Impulse Response Filter.
Author
C2000
Definition at line 21 of file fir32forc28x.m.
FREQ2
signal FREQ2 = 33e3
Definition at line 22 of file fir32forc28x.m.
Fstop
Passband Frequency Fstop = 0.15
Definition at line 37 of file fir32forc28x.m.
Hd
Hd = dfilt.dffir(b)
Definition at line 45 of file fir32forc28x.m.
i
i = 1 : 1 : BUFFER_SIZE
Definition at line 31 of file fir32forc28x.m.
k1
k1 = FREQ1/SAMPLING_FREQ
Definition at line 28 of file fir32forc28x.m.
k2
k2 = FREQ2/SAMPLING_FREQ
Definition at line 29 of file fir32forc28x.m.
N
N = FIR_ORDER
Definition at line 35 of file fir32forc28x.m.
on
grid on
Definition at line 53 of file fir32forc28x.m.
S
S = 0.5*(sin(2*pi*k1*i) + sin(2*pi*k2*i))
Definition at line 33 of file fir32forc28x.m.
S_filt
S_filt = conv(S,Fc)
Definition at line 49 of file fir32forc28x.m.
SAMPLING_FREQ
signal SAMPLING_FREQ = 100e3
Definition at line 23 of file fir32forc28x.m.
Wpass
Stopband Frequency Wpass = 1
Definition at line 38 of file fir32forc28x.m.
Wstop
Passband Weight Wstop = 1
Definition at line 39 of file fir32forc28x.m.