GMP - CTL: component/intrinsic/advance/fuzzy_preset/fuzzy_designer/generate_fuzzy_2d_src.m File Reference
generate_fuzzy_2d_src.m File Reference
Functions
This file generate a header file target_file is target source file and header file without suffix fuzzy_mat_name will define the name of source code matrix fuzzy_2d_mat give the souce fuzzy matrix content function generate_fuzzy_2d_src (target_file, fuzzy_mat_name,... fuzzy_2d_mat, dim1_mesh, dim2_mesh) % config setting type_name
id script ()
**copyright Copyright (c) 2024 "
*and the axis vectors for two input variables (Error and Error Rate). "
end fprintf (fs, "\r\n")
create fuzzy matrix fprintf (fs, "// fuzzy matrix content\r\n")
fprintf (fs, "%s %s_matrix [%d][%d] = {\r\n",... type_name, fuzzy_mat_name, fuzzy_mat_size(1), fuzzy_mat_size(2))
else fprintf (fs, " ,float2ctrl(%.6f)", fuzzy_2d_mat(i, j))
end end fprintf (fs, "},\r\n")
end fprintf (fs, "};")
fprintf (fs, "\r\n\r\n")
generate fuzzy variables if generate fuzzy variables fprintf (fs, "// fuzzy variable1 mesh\r\n")
else fprintf (fs, " ,float2ctrl(%.6f)", dim1_mesh(i))
end end fprintf (fs, "};\r\n\r\n")
generate fuzzy variables fprintf (fs, "// fuzzy variable2 mesh\r\n")
*brief The min value of e value (dimension 1) "
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(2), info_src2(3))
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(4), info_src2(3))
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(5), info_src2(3))
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(6), info_src2(3))
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(7), info_src2(3))
fprintf (fs, "%s\r\n%s\r\n%s\r\n", info_src2(1), info_src2(8), info_src2(3))
fprintf (fs, "\t\t%s_dim1_min, %s_dim1_max, %s_dim1_size,\r\n", fuzzy_mat_name, fuzzy_mat_name, fuzzy_mat_name)
fprintf (fs, "\t\t// error rate\r\n")
fprintf (fs, "\t\t// fuzzy matrix\r\n")
fprintf (fs, "\t\t%s_matrix,\r\n", fuzzy_mat_name)
fprintf (fs, "\t\t// gain \r\n\t\tgain_e, gain_ec, gain_u\r\n\t);\r\n}")
fprintf (fs, "that's all")
fclose (fs)
generate headere file necessary fuzzy header head fprintf (fh,"#ifndef _FILE_%s_H_\r\n", upper(target_file))
fprintf (fh, "#define _FILE_%s_H_\r\n", upper(target_file))
fprintf (fh, "\r\n\r\n")
fprintf (fh, "#ifdef __cplusplus\r\n")
fprintf (fh, 'extern"C"\r\n')
fprintf (fh, "{\r\n")
fprintf (fh, "#endif // __cplusplus\r\n\r\n\r\n")
variable declaration in header file fprintf (fh, "// Here's the fuzzy matrix declaration.\r\n")
fprintf (fh, "extern %s %s_matrix [%d][%d];\r\n\r\n",... type_name, fuzzy_mat_name, fuzzy_mat_size(1), fuzzy_mat_size(2))
fprintf (fh, "extern %s %s_segment1[%d];\r\n\r\n",... type_name, fuzzy_mat_name, fuzzy_mat_size(1))
fprintf (fh, "extern %s %s_segment2[%d];\r\n\r\n",... type_name, fuzzy_mat_name, fuzzy_mat_size(2))
fprintf (fh, "extern uint32_t %s_dim2_size;\r\n", fuzzy_mat_name)
fprintf (fh, "extern ctrl_gt %s_dim1_min ;\r\n", fuzzy_mat_name)
fprintf (fh, "extern ctrl_gt %s_dim1_max ;\r\n", fuzzy_mat_name)
fprintf (fh, "extern ctrl_gt %s_dim2_min ;\r\n", fuzzy_mat_name)
fprintf (fh, "extern ctrl_gt %s_dim2_max ;\r\n", fuzzy_mat_name)
function stops here fprintf (fh, "}\r\n\r\n")
fprintf (fh, "}\r\n")
fprintf (fh, "#endif // __cplusplus\r\n\r\n")
fprintf (fh,"#endif // _FILE_%s_H_\r\n\r\n", upper(target_file))
fclose (fh)
Variables
This file generate a header file target_file is target source file and header file name
header_file = strcat(target_file, ".h")
source_file = strcat(target_file, ".c")
fs = fopen(source_file, "w+")
fh = fopen(header_file, "w+")
generate information about the file info_src
*file fuzzy_2d c
*brief Defines the data for a specific fuzzy logic control surface
* version
*for a fuzzy logic controller The data includes the control surface matrix
*This file is typically generated automatically and should not be edited manually
*for i
generate fuzzy matrix fuzzy_mat_size = size(fuzzy_2d_mat)
end generate const values info_src2
*brief The number of grid points for the Error input axis
generate init function info_src3
*brief Initializes a specific FLC instance with the type1 fuzzy data
*ingroup fuzzy_logic_controller
**param[out] flc Pointer to the FLC instance to be initialized
*param[in] gain_e The gain for the Error input
*param[in] gain_u The gain for the final control output
**details This is a convenience wrapper function that calls the generic flc_init
* function
passing the specific type1 fuzzy data defined in this file
Function Documentation
Copyright()
**copyright Copyright (c)
fclose() [1/2]
fclose (fh)
References fclose(), and fh.
fclose() [2/2]
fclose (fs)
References fclose(), file, fs, and generate().
fprintf() [1/43]
fprintf (fh , "#define _FILE_%s_H_\r\n" , upper(target_file))
References fh, and fprintf().
fprintf() [2/43]
fprintf (fh , "#endif // __cplusplus\r\n\r\n")
References fh, and fprintf().
fprintf() [3/43]
fprintf (fh , "#endif // __cplusplus\r\n\r\n\r\n")
References fh, file, and fprintf().
fprintf() [4/43]
necessary fuzzy header ending fprintf (fh , "#ifdef __cplusplus\r\n")
References fh, and fprintf().
fprintf() [5/43]
variable declaration in header file fprintf (fh , "// Here's the fuzzy matrix declaration.\r\n")
References fh, and fprintf().
fprintf() [6/43]
fprintf (fh , "\r\n\r\n")
References fh, and fprintf().
fprintf() [7/43]
fprintf (fh , "extern %s %s_matrix ;\r\n\r\n" [%d][%d], ..., fuzzy_mat_name , fuzzy_mat_size(1) , fuzzy_mat_size(2))
References fh, fprintf(), and fuzzy_mat_size.
fprintf() [8/43]
fprintf (fh , "extern %s %s_segment1;\r\n\r\n" [%d], ..., fuzzy_mat_name , fuzzy_mat_size(1))
References fh, fprintf(), and fuzzy_mat_size.
fprintf() [9/43]
fprintf (fh , "extern %s %s_segment2;\r\n\r\n" [%d], ..., fuzzy_mat_name , fuzzy_mat_size(2))
References fh, fprintf(), and fuzzy_mat_size.
fprintf() [10/43]
fprintf (fh , "extern ctrl_gt %s_dim1_max ;\r\n" , fuzzy_mat_name)
References fh, and fprintf().
fprintf() [11/43]
fprintf (fh , "extern ctrl_gt %s_dim1_min ;\r\n" , fuzzy_mat_name)
References fh, and fprintf().
fprintf() [12/43]
fprintf (fh , "extern ctrl_gt %s_dim2_max ;\r\n" , fuzzy_mat_name)
References fh, fprintf(), and function.
fprintf() [13/43]
fprintf (fh , "extern ctrl_gt %s_dim2_min ;\r\n" , fuzzy_mat_name)
References fh, and fprintf().
fprintf() [14/43]
fprintf (fh , "extern uint32_t %s_dim2_size;\r\n" , fuzzy_mat_name)
References fh, and fprintf().
fprintf() [15/43]
fprintf (fh)
References fh, and fprintf().
fprintf() [16/43]
fprintf (fh , "}\r\n")
References fh, and fprintf().
fprintf() [17/43]
function stops here fprintf (fh , "}\r\n\r\n")
References fh, and fprintf().
fprintf() [18/43]
fprintf (fh , 'extern"C"\r\n')
References fh, and fprintf().
fprintf() [19/43]
fprintf (fh , "#endif // _FILE_%s_H_\r\n\r\n" , upper(target_file))
References fh, and fprintf().
fprintf() [20/43]
generate headere file necessary fuzzy header head fprintf (fh , "#ifndef _FILE_%s_H_\r\n" , upper(target_file))
References fh, and fprintf().
fprintf() [21/43]
else fprintf (fs , " , float2ctrl(%.6f)" , dim1_mesh(i))
References dim1_mesh, fprintf(), fs, and i.
fprintf() [22/43]
else fprintf (fs , " , float2ctrl(%.6f)" , fuzzy_2d_mat(i, j))
References fprintf(), fs, and i.
fprintf() [23/43]
fprintf (fs)
References fprintf(), fs, fuzzy_mat_size, generate(), i, if(), and matrix.
fprintf() [24/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(2) , info_src2(3))
References fprintf(), fs, fuzzy_mat_size, and info_src2.
fprintf() [25/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(4) , info_src2(3))
References fprintf(), fs, fuzzy_mat_size, and info_src2.
fprintf() [26/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(5) , info_src2(3))
References dim1_mesh, fprintf(), fs, and info_src2.
fprintf() [27/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(6) , info_src2(3))
References dim1_mesh, fprintf(), fs, fuzzy_mat_size, and info_src2.
fprintf() [28/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(7) , info_src2(3))
References dim2_mesh, fprintf(), fs, and info_src2.
fprintf() [29/43]
fprintf (fs , "%s\r\n%s\r\n%s\r\n" , info_src2(1) , info_src2(8) , info_src2(3))
References dim2_mesh, fprintf(), fs, function, fuzzy_mat_size, generate(), info_src2, and init().
fprintf() [30/43]
create fuzzy matrix fprintf (fs , "// fuzzy matrix content\r\n")
References fs.
fprintf() [31/43]
generate fuzzy variables if generate fuzzy variables fprintf (fs , "// fuzzy variable1 mesh\r\n")
References dim1_mesh, fprintf(), fs, fuzzy_mat_size, i, and if().
fprintf() [32/43]
generate fuzzy variables fprintf (fs , "// fuzzy variable2 mesh\r\n")
References dim1_mesh, fprintf(), fs, fuzzy_mat_size, generate(), i, and if().
fprintf() [33/43]
end fprintf (fs , "\r\n")
References fs, generate(), and matrix.
fprintf() [34/43]
fprintf (fs , "\r\n\r\n")
References fprintf(), fs, generate(), if(), and variables().
fprintf() [35/43]
fprintf (fs , "\t\t% s_dim1_min, % s_dim1_max, % s_dim1_size, \r\n" , fuzzy_mat_name , fuzzy_mat_name , fuzzy_mat_name)
References fprintf(), and fs.
fprintf() [36/43]
fprintf (fs , "\t\t% s_matrix, \r\n" , fuzzy_mat_name)
References fprintf(), and fs.
fprintf() [37/43]
fprintf (fs , "\t\t// error rate\r\n")
References fprintf(), and fs.
fprintf() [38/43]
fprintf (fs , "\t\t// fuzzy matrix\r\n")
References fprintf(), and fs.
fprintf() [39/43]
fprintf (fs , "\t\t// gain \r\n\t\ tgain_e, gain_ec , gain_u\r\n\ t)
References fprintf(), and fs.
fprintf() [40/43]
fprintf (fs , "that's all")
References fprintf(), and fs.
fprintf() [41/43]
end end fprintf (fs , "} , \r\n")
References fprintf(), and fs.
fprintf() [42/43]
end fprintf (fs , "};")
References fprintf(), and fs.
fprintf() [43/43]
end end fprintf (fs , "};\r\n\r\n")
References fprintf(), fs, generate(), and variables().
generate_fuzzy_2d_src()
This file generate a header file target_file is target source file and header file without suffix fuzzy_mat_name will define the name of source code matrix fuzzy_2d_mat give the souce fuzzy matrix content function generate_fuzzy_2d_src (target_file , fuzzy_mat_name , ..., dim1_mesh , dim2_mesh)
References dim1_mesh, and dim2_mesh.
script()
id script () virtual
value()
*brief The max value of ec value (dimension 1)
variables()
*and the axis vectors for two input variables (Error and Error Rate)
Variable Documentation
axis
axis
Definition at line 105 of file generate_fuzzy_2d_src.m.
c
* file fuzzy_2d c
Definition at line 23 of file generate_fuzzy_2d_src.m.
data
LUT data
Definition at line 138 of file generate_fuzzy_2d_src.m.
fh
fh = fopen(header_file, "w+")
Definition at line 18 of file generate_fuzzy_2d_src.m.
file
passing the specific type1 fuzzy data defined in this file
Definition at line 147 of file generate_fuzzy_2d_src.m.
flc_init
* * details This is a convenience wrapper function that calls the generic flc_init
Definition at line 146 of file generate_fuzzy_2d_src.m.
fs
fs = fopen(source_file, "w+")
Definition at line 17 of file generate_fuzzy_2d_src.m.
function
* function
Definition at line 147 of file generate_fuzzy_2d_src.m.
fuzzy_logic_controller
* ingroup fuzzy_logic_controller
Definition at line 139 of file generate_fuzzy_2d_src.m.
fuzzy_mat_size
generate fuzzy matrix fuzzy_mat_size = size(fuzzy_2d_mat)
Definition at line 48 of file generate_fuzzy_2d_src.m.
header_file
header_file = strcat(target_file, ".h")
Definition at line 14 of file generate_fuzzy_2d_src.m.
i
for i
Initial value:
 =1:18
fprintf(fs, "%s\r\n", info_src(i))
Definition at line 41 of file generate_fuzzy_2d_src.m.
info_src
generate information about the file info_src
Initial value:
         =
Definition at line 21 of file generate_fuzzy_2d_src.m.
info_src2
end generate const values info_src2
Initial value:
          =
Definition at line 103 of file generate_fuzzy_2d_src.m.
info_src3
generate init function info_src3
Initial value:
          =
Definition at line 136 of file generate_fuzzy_2d_src.m.
initialized
* * param [out] flc Pointer to the FLC instance to be initialized
Definition at line 141 of file generate_fuzzy_2d_src.m.
input
* param [in] gain_ec The gain for the Error Rate input
Definition at line 142 of file generate_fuzzy_2d_src.m.
manually
* This file is typically generated automatically and should not be edited manually
Definition at line 34 of file generate_fuzzy_2d_src.m.
matrix
* for a fuzzy logic controller The data includes the control surface matrix
Definition at line 32 of file generate_fuzzy_2d_src.m.
name
This file generate a header file target_file is target source file and header file name
Definition at line 3 of file generate_fuzzy_2d_src.m.
output
* param [in] gain_u The gain for the final control output
Definition at line 144 of file generate_fuzzy_2d_src.m.
source_file
source_file = strcat(target_file, ".c")
Definition at line 15 of file generate_fuzzy_2d_src.m.
surface
*It simplifies the setup process for a controller that uses this particular surface
Definition at line 25 of file generate_fuzzy_2d_src.m.
version
* version
Definition at line 26 of file generate_fuzzy_2d_src.m.