GMP - CTL: component/intrinsic/advance/fuzzy_preset/fuzzy_designer/get_fuzzy_matrix.m File Reference
get_fuzzy_matrix.m File Reference
Functions
LUT range ()
Calculate the step size so it will generate (mash_input+1) points. dim_div
range_input(2,:) max ()
id figure ()
surf (dim1_mesh, dim2_mesh, fuzzy_matrix)
title ('Fuzzy Logic Control Surface')
xlabel (fis.Inputs(1).Name)
ylabel (fis.Inputs(2).Name)
zlabel (fis.Outputs(1).Name)
Variables
mash = [50, 50]
function [fuzzy_matrix, dim1_mesh, dim2_mesh]
Only process the input case if dim_input
dim_min = min(range_input(1,:))
Calculate the step size Note
dim1_mesh = dim_min : dim_div : dim_max
dim_div = (dim_max - dim_min) / mash_input(2)
dim2_mesh = dim_min : dim_div : dim_max
Initialize the output matrix fuzzy_matrix = zeros(length(dim1_mesh), length(dim2_mesh))
Extern declaration for the 21x21 fuzzy control surface matrix.
colorbar
else For unsupported dimensions
Function Documentation
figure()
id figure () virtual
References figure(), and surface.
generate()
Calculate the step size so it will generate (mash_input+ 1)
References dim_div, and dim_min.
max()
range_input(2,:) max () virtual
References dim_min, and max().
range()
LUT range () virtual
References dim1_mesh, dim2_mesh, dim_input, dimensions, file, function, fuzzy_matrix, input, matrix, N, name, output, range(), surface, system, value(), variables(), and version.
surf()
surf (dim1_mesh , dim2_mesh , fuzzy_matrix)
References dim1_mesh, dim2_mesh, fuzzy_matrix, and surf().
title()
title ('Fuzzy Logic Control Surface')
References title().
xlabel()
xlabel (fis.Inputs(1). Name)
References xlabel().
ylabel()
ylabel (fis.Inputs(2). Name)
References ylabel().
zlabel()
zlabel (fis.Outputs(1). Name)
References zlabel().
Variable Documentation
colorbar
colorbar
Definition at line 70 of file get_fuzzy_matrix.m.
dim1_mesh
dim1_mesh = dim_min : dim_div : dim_max
Definition at line 44 of file get_fuzzy_matrix.m.
dim2_mesh
dim2_mesh = dim_min : dim_div : dim_max
Definition at line 50 of file get_fuzzy_matrix.m.
dim_div
dim_div = (dim_max - dim_min) / mash_input(2)
Definition at line 49 of file get_fuzzy_matrix.m.
dim_input
Only process the input case if dim_input
Initial value:
         == 2
% --- Create meshgrid for the first dimension ---
dim_max = max(range_input(1,:))
Definition at line 37 of file get_fuzzy_matrix.m.
dim_min
dim_min = min(range_input(1,:))
Definition at line 40 of file get_fuzzy_matrix.m.
dimensions
else For unsupported dimensions
Definition at line 73 of file get_fuzzy_matrix.m.
function
function[fuzzy_matrix, dim1_mesh, dim2_mesh]
Initial value:
          = get_fuzzy_matrix(fis_file, ...
    dim_input,   range_input,  mash_input)
% Read the .fis file
fis = readfis(fis_file)
Definition at line 30 of file get_fuzzy_matrix.m.
mash
mash = [50, 50]
Definition at line 27 of file get_fuzzy_matrix.m.
Note
Calculate the step size Note
Definition at line 41 of file get_fuzzy_matrix.m.