GMP - CTL: Resonant Controllers
Resonant Controllers
Control Template Library Intrinsic » Discrete Components
A library of discrete resonant controllers for AC signal tracking.
Data Structures
struct resonant_ctrl_t
Data structure for a pure Resonant (R) controller.
struct pr_ctrl_t
Data structure for a Proportional-Resonant (PR) controller.
struct qr_ctrl_t
Data structure for a Quasi-Resonant (QR) controller.
struct qpr_ctrl_t
Data structure for a Quasi-Proportional-Resonant (QPR) controller.
Functions
void ctl_init_resonant_controller (resonant_ctrl_t *r, parameter_gt kr, parameter_gt freq_resonant, parameter_gt fs)
Initializes a resonant controller.
GMP_STATIC_INLINE void ctl_clear_resonant_controller (resonant_ctrl_t *r)
Clears the internal states of the resonant controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_resonant_controller (resonant_ctrl_t *r, ctrl_gt input)
Executes one step of the resonant controller.
void ctl_init_pr_controller (pr_ctrl_t *pr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt fs)
Initializes a PR controller.
GMP_STATIC_INLINE void ctl_clear_pr_controller (pr_ctrl_t *pr)
Clears the internal states of the PR controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_pr_controller (pr_ctrl_t *pr, ctrl_gt input)
Executes one step of the PR controller.
void ctl_init_qr_controller (qr_ctrl_t *qr, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a quasi-resonant controller using Standard Tustin.
void ctl_init_qr_controller_prewarped (qr_ctrl_t *qr, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a quasi-resonant controller with Frequency Pre-warping.
GMP_STATIC_INLINE void ctl_clear_qr_controller (qr_ctrl_t *qr)
Clears the internal states of the QR controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_qr_controller (qr_ctrl_t *qr, ctrl_gt input)
Executes one step of the QR controller.
void ctl_init_qpr_controller (qpr_ctrl_t *qpr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a QPR controller using Standard Tustin.
void ctl_init_qpr_controller_prewarped (qpr_ctrl_t *qpr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a QPR controller with Frequency Pre-warping.
GMP_STATIC_INLINE void ctl_clear_qpr_controller (qpr_ctrl_t *qpr)
Clears the internal states of the QPR controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_qpr_controller (qpr_ctrl_t *qpr, ctrl_gt input)
Executes one step of the QPR controller.
Detailed Description
A library of discrete resonant controllers for AC signal tracking.
This file implements several variations of resonant controllers, which are essential for AC signal tracking, particularly in applications like grid-tied inverters. They provide infinite gain at a specific resonant frequency, allowing for zero steady-state error when tracking a sinusoidal reference. Implementations include pure Resonant (R), Proportional-Resonant (PR), Quasi-Resonant (QR), and Quasi-Proportional-Resonant (QPR) controllers.
Function Documentation
ctl_clear_pr_controller()
GMP_STATIC_INLINE void ctl_clear_pr_controller (pr_ctrl_t * pr)
Clears the internal states of the PR controller.
Parameters
[out] pr Pointer to the PR controller instance.
Definition at line 139 of file proportional_resonant.h.
References ctl_clear_resonant_controller(), and pr_ctrl_t::resonant_part.
ctl_clear_qpr_controller()
GMP_STATIC_INLINE void ctl_clear_qpr_controller (qpr_ctrl_t * qpr)
Clears the internal states of the QPR controller.
Parameters
[out] qpr Pointer to the QPR controller instance.
Definition at line 290 of file proportional_resonant.h.
References ctl_clear_qr_controller(), and qpr_ctrl_t::resonant_part.
ctl_clear_qr_controller()
GMP_STATIC_INLINE void ctl_clear_qr_controller (qr_ctrl_t * qr)
Clears the internal states of the QR controller.
Parameters
[out] qr Pointer to the QR controller instance.
Definition at line 215 of file proportional_resonant.h.
References qr_ctrl_t::input_1, qr_ctrl_t::input_2, qr_ctrl_t::output, qr_ctrl_t::output_1, and qr_ctrl_t::output_2.
ctl_clear_resonant_controller()
GMP_STATIC_INLINE void ctl_clear_resonant_controller (resonant_ctrl_t * r)
Clears the internal states of the resonant controller.
Parameters
[out] r Pointer to the resonant controller instance.
Definition at line 77 of file proportional_resonant.h.
References resonant_ctrl_t::input_1, resonant_ctrl_t::input_2, resonant_ctrl_t::output, resonant_ctrl_t::output_1, and resonant_ctrl_t::output_2.
ctl_init_pr_controller()
void ctl_init_pr_controller (pr_ctrl_t * pr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt fs)
Initializes a PR controller.
Parameters
[out] pr Pointer to the PR controller instance.
[in] kp Proportional gain.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz.
[in] fs Sampling frequency in Hz.
Definition at line 1161 of file ctl_component_discrete.c.
References ctl_init_resonant_controller(), fs, pr_ctrl_t::kp, and pr_ctrl_t::resonant_part.
ctl_init_qpr_controller()
void ctl_init_qpr_controller (qpr_ctrl_t * qpr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a QPR controller using Standard Tustin.
Parameters
[out] qpr Pointer to the QPR controller instance.
[in] kp Proportional gain.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz.
[in] freq_cut Cutoff frequency in Hz.
[in] fs Sampling frequency in Hz.
Definition at line 1291 of file ctl_component_discrete.c.
References ctl_init_qr_controller(), fs, qpr_ctrl_t::kp, and qpr_ctrl_t::resonant_part.
ctl_init_qpr_controller_prewarped()
void ctl_init_qpr_controller_prewarped (qpr_ctrl_t * qpr, parameter_gt kp, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a QPR controller with Frequency Pre-warping.
Parameters
[out] qpr Pointer to the QPR controller instance.
[in] kp Proportional gain.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz.
[in] freq_cut Cutoff frequency in Hz.
[in] fs Sampling frequency in Hz.
Definition at line 1298 of file ctl_component_discrete.c.
References ctl_init_qr_controller_prewarped(), fs, qpr_ctrl_t::kp, and qpr_ctrl_t::resonant_part.
ctl_init_qr_controller()
void ctl_init_qr_controller (qr_ctrl_t * qr, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a quasi-resonant controller using Standard Tustin.
Parameters
[out] qr Pointer to the QR controller instance.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz.
[in] freq_cut Cutoff frequency in Hz, which sets the controller's bandwidth.
[in] fs Sampling frequency in Hz.
Note
Use this only for low frequency resonances relative to Fs.
Use this only for low frequency resonances relative to Fs.
Definition at line 1239 of file ctl_component_discrete.c.
References ctl_clear_qr_controller(), CTL_PARAM_CONST_2PI, and fs.
ctl_init_qr_controller_prewarped()
void ctl_init_qr_controller_prewarped (qr_ctrl_t * qr, parameter_gt kr, parameter_gt freq_resonant, parameter_gt freq_cut, parameter_gt fs)
Initializes a quasi-resonant controller with Frequency Pre-warping.
Corrects the frequency warping effect of bilinear transformation at the resonant frequency. Essential for harmonic control (e.g., 6th, 12th harmonics).
Parameters
[out] qr Pointer to the QR controller instance.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz (Center Frequency).
[in] freq_cut Cutoff frequency in Hz (Bandwidth/2).
[in] fs Sampling frequency in Hz.
Corrects the frequency warping effect of bilinear transformation at the resonant frequency. Essential for harmonic control (e.g., 6th, 12th harmonics).
Parameters
[out] qr Pointer to the QR controller instance.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz (Center Frequency).
[in] freq_cut Cutoff frequency in Hz (Bandwidth/2).
[in] fs Sampling frequency in Hz.
Definition at line 1262 of file ctl_component_discrete.c.
References ctl_clear_qr_controller(), CTL_PARAM_CONST_2PI, CTL_PARAM_CONST_PI, and fs.
ctl_init_resonant_controller()
void ctl_init_resonant_controller (resonant_ctrl_t * r, parameter_gt kr, parameter_gt freq_resonant, parameter_gt fs)
Initializes a resonant controller.
Parameters
[out] r Pointer to the resonant controller instance.
[in] kr Gain of the resonant term.
[in] freq_resonant Resonant frequency in Hz.
[in] fs Sampling frequency in Hz.
Definition at line 1132 of file ctl_component_discrete.c.
References resonant_ctrl_t::a1, resonant_ctrl_t::a2, resonant_ctrl_t::b0, resonant_ctrl_t::b2, ctl_clear_resonant_controller(), CTL_PARAM_CONST_2PI, float2ctrl, and fs.
ctl_step_pr_controller()
GMP_STATIC_INLINE ctrl_gt ctl_step_pr_controller (pr_ctrl_t * pr, ctrl_gt input)
Executes one step of the PR controller.
Parameters
[in,out] pr Pointer to the PR controller instance.
[in] input The current input, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 150 of file proportional_resonant.h.
References ctl_mul, ctl_step_resonant_controller(), float2ctrl, input, pr_ctrl_t::kp, and pr_ctrl_t::resonant_part.
ctl_step_qpr_controller()
GMP_STATIC_INLINE ctrl_gt ctl_step_qpr_controller (qpr_ctrl_t * qpr, ctrl_gt input)
Executes one step of the QPR controller.
Parameters
[in,out] qpr Pointer to the QPR controller instance.
[in] input The current input, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 301 of file proportional_resonant.h.
References ctl_mul, ctl_step_qr_controller(), float2ctrl, input, qpr_ctrl_t::kp, and qpr_ctrl_t::resonant_part.
ctl_step_qr_controller()
GMP_STATIC_INLINE ctrl_gt ctl_step_qr_controller (qr_ctrl_t * qr, ctrl_gt input)
Executes one step of the QR controller.
Parameters
[in,out] qr Pointer to the QR controller instance.
[in] input The current input, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 230 of file proportional_resonant.h.
References qr_ctrl_t::a1, qr_ctrl_t::a2, qr_ctrl_t::b0, qr_ctrl_t::b2, ctl_mul, input, qr_ctrl_t::input_1, qr_ctrl_t::input_2, qr_ctrl_t::output, qr_ctrl_t::output_1, and qr_ctrl_t::output_2.
ctl_step_resonant_controller()
GMP_STATIC_INLINE ctrl_gt ctl_step_resonant_controller (resonant_ctrl_t * r, ctrl_gt input)
Executes one step of the resonant controller.
Parameters
[in,out] r Pointer to the resonant controller instance.
[in] input The current input, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 92 of file proportional_resonant.h.
References resonant_ctrl_t::a1, resonant_ctrl_t::a2, resonant_ctrl_t::b0, resonant_ctrl_t::b2, ctl_mul, input, resonant_ctrl_t::input_1, resonant_ctrl_t::input_2, resonant_ctrl_t::output, resonant_ctrl_t::output_1, and resonant_ctrl_t::output_2.