GMP - CTL: Single-Phase Inverter Topology API
Single-Phase Inverter Topology API
Digital Power Control Library » Digital Power Topology Presets
Defines the data structures, control flags, and function interfaces for a comprehensive single-phase inverter, including harmonic compensation and multiple operating modes.
Data Structures
struct sinv_ctrl_t
Main data structure for the single-phase inverter controller.
struct sinv_init_t
Initialization parameters for the single-phase inverter controller.
Macros
#define CTL_SINV_CTRL_ENABLE_SINE_ANALYZER
Selects the modulation strategy for the H-bridge.
Enumerations
enum single_phase_name_num { PHASE_N = 0 , PHASE_L = 1 }
Enumeration for single-phase leg indexing.
Functions
void ctl_upgrade_sinv_param (sinv_ctrl_t *sinv, sinv_init_t *init)
void ctl_init_sinv_ctrl (sinv_ctrl_t *sinv, sinv_init_t *init)
void ctl_attach_sinv_with_adc (sinv_ctrl_t *sinv, adc_ift *udc, adc_ift *idc, adc_ift *il, adc_ift *ugrid, adc_ift *igrid)
GMP_STATIC_INLINE void ctl_clear_sinv (sinv_ctrl_t *sinv)
Clears the states of the main controllers (PID, QPR, QR).
GMP_STATIC_INLINE void ctl_clear_sinv_with_pll (sinv_ctrl_t *sinv)
Clears the states of the main controllers and the PLL.
GMP_STATIC_INLINE ctrl_gt ctl_step_sinv (sinv_ctrl_t *sinv)
Executes one step of the single-phase inverter control algorithm.
GMP_STATIC_INLINE void ctl_set_sinv_openloop_inverter (sinv_ctrl_t *sinv)
Sets the controller to open-loop inverter mode.
GMP_STATIC_INLINE void ctl_set_sinv_current_closeloop_inverter (sinv_ctrl_t *sinv)
Sets the controller to current closed-loop inverter mode.
GMP_STATIC_INLINE void ctl_set_sinv_voltage_closeloop_inverter (sinv_ctrl_t *sinv)
Sets the controller to voltage closed-loop inverter mode.
GMP_STATIC_INLINE void ctl_set_sinv_voltage_closeloop_rectifier (sinv_ctrl_t *sinv)
Sets the controller to voltage closed-loop rectifier mode.
GMP_STATIC_INLINE void ctl_set_sinv_current_ref (sinv_ctrl_t *sinv, ctrl_gt i_target)
Sets the target current amplitude.
GMP_STATIC_INLINE void ctl_set_sinv_voltage_ref (sinv_ctrl_t *sinv, ctrl_gt v_target)
Sets the target voltage (DC or AC RMS).
GMP_STATIC_INLINE void ctl_set_sinv_power_factor (sinv_ctrl_t *sinv, ctrl_gt pf)
Sets the target power factor.
GMP_STATIC_INLINE void ctl_enable_sinv_ctrl (sinv_ctrl_t *sinv)
Enables the main system controller.
GMP_STATIC_INLINE void ctl_disable_sinv_ctrl (sinv_ctrl_t *sinv)
Disables the main system controller, stopping PWM output.
GMP_STATIC_INLINE void ctl_set_sinv_freerun (sinv_ctrl_t *sinv)
Sets the angle source to the internal ramp generator (freerun).
GMP_STATIC_INLINE void ctl_set_sinv_pll (sinv_ctrl_t *sinv)
Sets the angle source to the PLL (grid-tied).
GMP_STATIC_INLINE void ctl_enable_sinv_harm_ctrl (sinv_ctrl_t *sinv)
Enables the harmonic compensation controllers.
GMP_STATIC_INLINE void ctl_disable_sinv_harm_ctrl (sinv_ctrl_t *sinv)
Disables the harmonic compensation controllers.
GMP_STATIC_INLINE fast_gt ctl_is_sinv_inverter_mode (sinv_ctrl_t *sinv)
Checks if the controller is in inverter mode.
GMP_STATIC_INLINE void ctl_enable_sinv_ac_measurement (sinv_ctrl_t *sinv)
Enables the AC RMS measurement modules.
GMP_STATIC_INLINE void ctl_disable_sinv_ac_measurement (sinv_ctrl_t *sinv)
Disables the AC RMS measurement modules.
Detailed Description
Defines the data structures, control flags, and function interfaces for a comprehensive single-phase inverter, including harmonic compensation and multiple operating modes.
Macro Definition Documentation
CTL_SINV_CTRL_ENABLE_SINE_ANALYZER
#define CTL_SINV_CTRL_ENABLE_SINE_ANALYZER
Selects the modulation strategy for the H-bridge.
Enabled: Unipolar modulation where PWM is generated on one phase leg only.
Disabled: Bipolar modulation where both phase legs are driven symmetrically.
Enables the use of the Sine Analyzer module for true RMS calculations.
Note
This is the recommended method for accurate AC measurements. If disabled, a fallback mechanism would be required, but the original one was flawed.
Definition at line 49 of file single_phase_dc_ac.h.
Enumeration Type Documentation
single_phase_name_num
enum single_phase_name_num
Enumeration for single-phase leg indexing.
Enumerator
PHASE_N
Index for the 'N' phase leg (typically the lower or reference leg).
PHASE_L
Index for the 'L' phase leg (typically the upper or active leg).
Definition at line 58 of file single_phase_dc_ac.h.
Function Documentation
ctl_attach_sinv_with_adc()
void ctl_attach_sinv_with_adc (sinv_ctrl_t * sinv, adc_ift * udc, adc_ift * idc, adc_ift * il, adc_ift * ugrid, adc_ift * igrid)
Definition at line 67 of file ctl_dp_topology_sinv.c.
References sinv_ctrl_t::adc_idc, sinv_ctrl_t::adc_igrid, sinv_ctrl_t::adc_il, sinv_ctrl_t::adc_udc, sinv_ctrl_t::adc_ugrid, and il.
ctl_clear_sinv()
GMP_STATIC_INLINE void ctl_clear_sinv (sinv_ctrl_t * sinv)
Clears the states of the main controllers (PID, QPR, QR).
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 194 of file single_phase_dc_ac.h.
References ctl_clear_pid(), ctl_clear_qpr_controller(), ctl_clear_qr_controller(), sinv_ctrl_t::sinv_qpr_base, sinv_ctrl_t::sinv_qr_3, sinv_ctrl_t::sinv_qr_5, sinv_ctrl_t::sinv_qr_7, and sinv_ctrl_t::voltage_pid.
ctl_clear_sinv_with_pll()
GMP_STATIC_INLINE void ctl_clear_sinv_with_pll (sinv_ctrl_t * sinv)
Clears the states of the main controllers and the PLL.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 209 of file single_phase_dc_ac.h.
References ctl_clear_single_phase_pll(), ctl_clear_sinv(), and sinv_ctrl_t::spll.
ctl_disable_sinv_ac_measurement()
GMP_STATIC_INLINE void ctl_disable_sinv_ac_measurement (sinv_ctrl_t * sinv)
Disables the AC RMS measurement modules.
Definition at line 483 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_ac_measurement.
ctl_disable_sinv_ctrl()
GMP_STATIC_INLINE void ctl_disable_sinv_ctrl (sinv_ctrl_t * sinv)
Disables the main system controller, stopping PWM output.
Definition at line 441 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_system.
ctl_disable_sinv_harm_ctrl()
GMP_STATIC_INLINE void ctl_disable_sinv_harm_ctrl (sinv_ctrl_t * sinv)
Disables the harmonic compensation controllers.
Definition at line 465 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_harmonic_ctrl.
ctl_enable_sinv_ac_measurement()
GMP_STATIC_INLINE void ctl_enable_sinv_ac_measurement (sinv_ctrl_t * sinv)
Enables the AC RMS measurement modules.
Definition at line 477 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_ac_measurement.
ctl_enable_sinv_ctrl()
GMP_STATIC_INLINE void ctl_enable_sinv_ctrl (sinv_ctrl_t * sinv)
Enables the main system controller.
Definition at line 435 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_system.
ctl_enable_sinv_harm_ctrl()
GMP_STATIC_INLINE void ctl_enable_sinv_harm_ctrl (sinv_ctrl_t * sinv)
Enables the harmonic compensation controllers.
Definition at line 459 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_enable_harmonic_ctrl.
ctl_init_sinv_ctrl()
void ctl_init_sinv_ctrl (sinv_ctrl_t * sinv, sinv_init_t * init)
Definition at line 59 of file ctl_dp_topology_sinv.c.
References ctl_clear_sinv(), ctl_upgrade_sinv_param(), init(), and sinv_ctrl_t::pf_set.
ctl_is_sinv_inverter_mode()
GMP_STATIC_INLINE fast_gt ctl_is_sinv_inverter_mode (sinv_ctrl_t * sinv)
Checks if the controller is in inverter mode.
Definition at line 471 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_rectifier_mode.
ctl_set_sinv_current_closeloop_inverter()
GMP_STATIC_INLINE void ctl_set_sinv_current_closeloop_inverter (sinv_ctrl_t * sinv)
Sets the controller to current closed-loop inverter mode.
Note
This function configures flags for current-controlled operation but leaves the system disabled. Call ctl_enable_sinv_ctrl() to start operation.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 363 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun, sinv_ctrl_t::flag_enable_ac_measurement, sinv_ctrl_t::flag_enable_current_ctrl, sinv_ctrl_t::flag_enable_harmonic_ctrl, sinv_ctrl_t::flag_enable_ramp, sinv_ctrl_t::flag_enable_spll, sinv_ctrl_t::flag_enable_system, sinv_ctrl_t::flag_enable_voltage_ctrl, and sinv_ctrl_t::flag_rectifier_mode.
ctl_set_sinv_current_ref()
GMP_STATIC_INLINE void ctl_set_sinv_current_ref (sinv_ctrl_t * sinv, ctrl_gt i_target)
Sets the target current amplitude.
Definition at line 417 of file single_phase_dc_ac.h.
References sinv_ctrl_t::ig_set.
ctl_set_sinv_freerun()
GMP_STATIC_INLINE void ctl_set_sinv_freerun (sinv_ctrl_t * sinv)
Sets the angle source to the internal ramp generator (freerun).
Definition at line 447 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun.
ctl_set_sinv_openloop_inverter()
GMP_STATIC_INLINE void ctl_set_sinv_openloop_inverter (sinv_ctrl_t * sinv)
Sets the controller to open-loop inverter mode.
Note
This function configures flags for open-loop operation but leaves the system disabled. Call ctl_enable_sinv_ctrl() to start operation.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 343 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun, sinv_ctrl_t::flag_enable_ac_measurement, sinv_ctrl_t::flag_enable_current_ctrl, sinv_ctrl_t::flag_enable_harmonic_ctrl, sinv_ctrl_t::flag_enable_ramp, sinv_ctrl_t::flag_enable_spll, sinv_ctrl_t::flag_enable_system, sinv_ctrl_t::flag_enable_voltage_ctrl, and sinv_ctrl_t::flag_rectifier_mode.
ctl_set_sinv_pll()
GMP_STATIC_INLINE void ctl_set_sinv_pll (sinv_ctrl_t * sinv)
Sets the angle source to the PLL (grid-tied).
Definition at line 453 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun.
ctl_set_sinv_power_factor()
GMP_STATIC_INLINE void ctl_set_sinv_power_factor (sinv_ctrl_t * sinv, ctrl_gt pf)
Sets the target power factor.
Definition at line 429 of file single_phase_dc_ac.h.
References sinv_ctrl_t::pf_set.
ctl_set_sinv_voltage_closeloop_inverter()
GMP_STATIC_INLINE void ctl_set_sinv_voltage_closeloop_inverter (sinv_ctrl_t * sinv)
Sets the controller to voltage closed-loop inverter mode.
Note
This function configures flags for voltage-controlled operation but leaves the system disabled. Call ctl_enable_sinv_ctrl() to start operation.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 383 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun, sinv_ctrl_t::flag_enable_ac_measurement, sinv_ctrl_t::flag_enable_current_ctrl, sinv_ctrl_t::flag_enable_harmonic_ctrl, sinv_ctrl_t::flag_enable_ramp, sinv_ctrl_t::flag_enable_spll, sinv_ctrl_t::flag_enable_system, sinv_ctrl_t::flag_enable_voltage_ctrl, and sinv_ctrl_t::flag_rectifier_mode.
ctl_set_sinv_voltage_closeloop_rectifier()
GMP_STATIC_INLINE void ctl_set_sinv_voltage_closeloop_rectifier (sinv_ctrl_t * sinv)
Sets the controller to voltage closed-loop rectifier mode.
Note
This function configures flags for rectifier operation but leaves the system disabled. Call ctl_enable_sinv_ctrl() to start operation.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Definition at line 403 of file single_phase_dc_ac.h.
References sinv_ctrl_t::flag_angle_freerun, sinv_ctrl_t::flag_enable_ac_measurement, sinv_ctrl_t::flag_enable_current_ctrl, sinv_ctrl_t::flag_enable_harmonic_ctrl, sinv_ctrl_t::flag_enable_ramp, sinv_ctrl_t::flag_enable_spll, sinv_ctrl_t::flag_enable_system, sinv_ctrl_t::flag_enable_voltage_ctrl, and sinv_ctrl_t::flag_rectifier_mode.
ctl_set_sinv_voltage_ref()
GMP_STATIC_INLINE void ctl_set_sinv_voltage_ref (sinv_ctrl_t * sinv, ctrl_gt v_target)
Sets the target voltage (DC or AC RMS).
Definition at line 423 of file single_phase_dc_ac.h.
References sinv_ctrl_t::v_set.
ctl_step_sinv()
GMP_STATIC_INLINE ctrl_gt ctl_step_sinv (sinv_ctrl_t * sinv)
Executes one step of the single-phase inverter control algorithm.
Warning
The fallback RMS calculation (when SINE_ANALYZER is disabled) in the original code was flawed due to direct float comparison. It has been removed. It is highly recommended to keep CTL_SINV_CTRL_ENABLE_SINE_ANALYZER enabled.
Parameters
[out] sinv Pointer to the sinv_ctrl_t structure.
Returns
The final modulation signal before being mapped to PWM outputs.
Definition at line 225 of file single_phase_dc_ac.h.
References sinv_ctrl_t::ac_current_measure, sinv_ctrl_t::ac_voltage_measure, sinv_ctrl_t::adc_idc, sinv_ctrl_t::adc_igrid, sinv_ctrl_t::adc_il, sinv_ctrl_t::adc_udc, sinv_ctrl_t::adc_ugrid, ctl_add, ctl_cos, ctl_div2, ctl_get_lowpass_filter_result(), ctl_get_ramp_generator_output(), ctl_mul, ctl_sin, ctl_sqrt, ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctl_step_qpr_controller(), ctl_step_qr_controller(), ctl_step_ramp_generator(), ctl_step_sine_analyzer(), ctl_step_single_phase_pll(), ctl_sub, vector2_gt::dat, sinv_ctrl_t::flag_angle_freerun, sinv_ctrl_t::flag_enable_ac_measurement, sinv_ctrl_t::flag_enable_current_ctrl, sinv_ctrl_t::flag_enable_harmonic_ctrl, sinv_ctrl_t::flag_enable_ramp, sinv_ctrl_t::flag_enable_spll, sinv_ctrl_t::flag_enable_system, sinv_ctrl_t::flag_enable_voltage_ctrl, sinv_ctrl_t::flag_rectifier_mode, float2ctrl, sinv_ctrl_t::ig_ref, sinv_ctrl_t::ig_rms, sinv_ctrl_t::ig_set, sinv_ctrl_t::lpf_idc, sinv_ctrl_t::lpf_igrid, sinv_ctrl_t::lpf_il, sinv_ctrl_t::lpf_udc, sinv_ctrl_t::lpf_ugrid, sinv_ctrl_t::modulation, sinv_ctrl_t::pf_set, PHASE_L, PHASE_N, ctl_single_phase_pll::phasor, phasor_cos, phasor_sin, sinv_ctrl_t::rg, sinv_ctrl_t::sinv_pwm_pu, sinv_ctrl_t::sinv_qpr_base, sinv_ctrl_t::sinv_qr_11, sinv_ctrl_t::sinv_qr_13, sinv_ctrl_t::sinv_qr_15, sinv_ctrl_t::sinv_qr_3, sinv_ctrl_t::sinv_qr_5, sinv_ctrl_t::sinv_qr_7, sinv_ctrl_t::sinv_qr_9, sinv_ctrl_t::spll, sinv_ctrl_t::target_phase, sinv_ctrl_t::v_set, sinv_ctrl_t::vg_rms, and sinv_ctrl_t::voltage_pid.
ctl_upgrade_sinv_param()
void ctl_upgrade_sinv_param (sinv_ctrl_t * sinv, sinv_init_t * init)
Definition at line 23 of file ctl_dp_topology_sinv.c.
References sinv_ctrl_t::ac_current_measure, sinv_ctrl_t::ac_voltage_measure, ctl_init_lp_filter(), ctl_init_pid_Tmode(), ctl_init_qpr_controller(), ctl_init_qr_controller(), ctl_init_ramp_generator_via_freq(), ctl_init_sine_analyzer(), ctl_init_single_phase_pll(), init(), sinv_ctrl_t::lpf_idc, sinv_ctrl_t::lpf_igrid, sinv_ctrl_t::lpf_il, sinv_ctrl_t::lpf_udc, sinv_ctrl_t::lpf_ugrid, sinv_ctrl_t::rg, sinv_ctrl_t::sinv_qpr_base, sinv_ctrl_t::sinv_qr_3, sinv_ctrl_t::sinv_qr_5, sinv_ctrl_t::sinv_qr_7, sinv_ctrl_t::sinv_qr_9, sinv_ctrl_t::spll, and sinv_ctrl_t::voltage_pid.