GMP - CTL: ADC Gain Calculation Models
ADC Gain Calculation Models
GMP CTL interface » GMP CTL basic interface
A collection of functions to determine the correct gain for sensor signal conditioning.
Functions
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_generic (parameter_gt Vref, parameter_gt G_sensor, parameter_gt Base_physical)
A generic function to calculate the required system gain.
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_volt_divider (parameter_gt Vref, parameter_gt Vbase, parameter_gt R1, parameter_gt R2)
Calculates gain for a voltage sensor using a resistive divider.
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_shunt_amp (parameter_gt Vref, parameter_gt Ibase, parameter_gt R_shunt, parameter_gt G_opamp)
Calculates gain for a current sensor using a shunt resistor and an operational amplifier.
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_hall_sensor (parameter_gt Vref, parameter_gt Ibase, parameter_gt sensitivity)
Calculates gain for a Hall-effect current sensor.
Detailed Description
A collection of functions to determine the correct gain for sensor signal conditioning.
The gain is a crucial parameter for converting a per-unit ADC value back into a physical quantity (e.g., Volts, Amperes). These models simplify the process of determining the correct gain based on hardware components. These models calculate the gain required by the ADC channel modules to scale the normalized ADC output into a meaningful physical unit.
Function Documentation
ctl_gain_calc_generic()
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_generic (parameter_gt Vref, parameter_gt G_sensor, parameter_gt Base_physical)
A generic function to calculate the required system gain.
This function calculates the gain needed to convert a per-unit ADC value to a final value scaled by a physical base. The formula is:
\[\text{gain} = \frac{V_{\text{ref}}}{G_{\text{sensor}} \cdot \text{Base}_{\text{physical}}} \]
Parameters
Vref The ADC reference voltage (e.g., 3.3V).
G_sensor The hardware gain of the analog front-end (e.g., the ratio of a voltage divider or the V/A sensitivity of a current sensor).
Base_physical The maximum physical value that corresponds to 1.0 p.u. in the control system (e.g., 400V or 50A).
Returns
The calculated gain for the ADC channel module.
Definition at line 53 of file gain_model.h.
ctl_gain_calc_hall_sensor()
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_hall_sensor (parameter_gt Vref, parameter_gt Ibase, parameter_gt sensitivity)
Calculates gain for a Hall-effect current sensor.
This model is for integrated current sensors (e.g., ACS712) that have a specified sensitivity. The hardware gain is the sensor's sensitivity.
Parameters
Vref The ADC reference voltage.
Ibase The maximum current to be measured (the physical base).
sensitivity The sensor's sensitivity in Volts per Ampere (V/A).
Returns
The calculated gain for the ADC channel module.
Definition at line 106 of file gain_model.h.
References ctl_gain_calc_generic().
ctl_gain_calc_shunt_amp()
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_shunt_amp (parameter_gt Vref, parameter_gt Ibase, parameter_gt R_shunt, parameter_gt G_opamp)
Calculates gain for a current sensor using a shunt resistor and an operational amplifier.
The sensor measures current via the voltage drop across a shunt resistor, which is then amplified by an op-amp. The hardware gain is \(G_{\text{sensor}} = R_{\text{shunt}} \cdot G_{\text{opamp}} \) (in V/A).
Parameters
Vref The ADC reference voltage.
Ibase The maximum current to be measured (the physical base).
R_shunt The resistance of the shunt resistor in Ohms.
G_opamp The voltage gain of the operational amplifier.
Returns
The calculated gain for the ADC channel module.
Definition at line 90 of file gain_model.h.
References ctl_gain_calc_generic().
ctl_gain_calc_volt_divider()
GMP_STATIC_INLINE parameter_gt ctl_gain_calc_volt_divider (parameter_gt Vref, parameter_gt Vbase, parameter_gt R1, parameter_gt R2)
Calculates gain for a voltage sensor using a resistive divider.
The sensor hardware consists of two resistors, R1 and R2, forming a voltage divider. The hardware gain of this stage is \(G_{\text{sensor}} = \frac{R_2}{R_1 + R_2} \).
Parameters
Vref The ADC reference voltage.
Vbase The maximum voltage to be measured (the physical base).
R1 The resistance of the resistor connected between the source voltage and the ADC input.
R2 The resistance of the resistor connected between the ADC input and ground.
Returns
The calculated gain for the ADC channel module.
Definition at line 71 of file gain_model.h.
References ctl_gain_calc_generic().