GMP - CTL: Virtual Impedance module (Header)
Virtual Impedance module (Header)
Digital Power Control Library
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Data Structures
struct vir_imp_t
Virtual Impedance Module.
Functions
void ctl_init_vir_imp (vir_imp_t *imp, const parameter_gt R_vir, const parameter_gt L_vir, parameter_gt fs)
Initializes the Virtual Impedance module.
GMP_STATIC_INLINE void ctl_clear_vir_imp (vir_imp_t *imp)
GMP_STATIC_INLINE ctrl_gt ctl_step_vir_imp (vir_imp_t *imp, ctrl_gt input_current)
Executes one step of the Virtual Impedance simulation.
Detailed Description
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Function Documentation
ctl_clear_vir_imp()
GMP_STATIC_INLINE void ctl_clear_vir_imp (vir_imp_t * imp)
Definition at line 55 of file virtual_imp.h.
References ctl_clear_biquad_filter(), and vir_imp_t::diff_filter.
ctl_init_vir_imp()
void ctl_init_vir_imp (vir_imp_t * imp, const parameter_gt R_vir, const parameter_gt L_vir, parameter_gt fs)
Initializes the Virtual Impedance module.
Definition at line 187 of file ctl_dp_basic.c.
References ctl_biquad_filter_t::a, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), vir_imp_t::diff_filter, fs, vir_imp_t::gain_R, and vir_imp_t::out.
ctl_step_vir_imp()
GMP_STATIC_INLINE ctrl_gt ctl_step_vir_imp (vir_imp_t * imp, ctrl_gt input_current)
Executes one step of the Virtual Impedance simulation.
Parameters
imp Pointer to the module.
input_current Current (usually filtered) to apply impedance to.
Returns
Voltage injection value.
Definition at line 66 of file virtual_imp.h.
References ctl_mul, ctl_step_biquad_filter(), vir_imp_t::diff_filter, vir_imp_t::gain_R, and vir_imp_t::out.