GMP - CTL: Single Phase PLL API
Single Phase PLL API
Digital Power Control Library » Digital Power Components
A Phase-Locked Loop for single-phase grid synchronization.
Topics
Single Phase SOGI-DC PLL API
A Phase-Locked Loop with DC Offset Rejection for single-phase grid synchronization.
Data Structures
struct ctl_single_phase_pll
Data structure for the Single-Phase PLL controller.
Functions
void ctl_init_single_phase_pll (ctl_single_phase_pll *spll, parameter_gt gain, parameter_gt ki, parameter_gt fc, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase PLL module.
void ctl_init_single_phase_pll_T (ctl_single_phase_pll *spll, parameter_gt gain, parameter_gt Ti, parameter_gt fc, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase PLL module.
GMP_STATIC_INLINE void ctl_clear_single_phase_pll (ctl_single_phase_pll *spll)
Clears the internal states of the PLL.
GMP_STATIC_INLINE void ctl_step_single_phase_pll (ctl_single_phase_pll *spll, ctrl_gt ac_input)
Executes one step of the Single-Phase PLL algorithm.
GMP_STATIC_INLINE ctrl_gt ctl_get_spll_error_fbk (ctl_single_phase_pll *spll)
Gets the filtered q-axis component, which represents the phase error.
Variables
ctrl_gt ctl_single_phase_pll::frequency
ctrl_gt ctl_single_phase_pll::theta
vector2_gt ctl_single_phase_pll::phasor
ctrl_gt ctl_single_phase_pll::v_mag
vector2_gt ctl_single_phase_pll::uab
vector2_gt ctl_single_phase_pll::udq
ctrl_gt ctl_single_phase_pll::freq_error
ctrl_gt ctl_single_phase_pll::freq_sf
discrete_sogi_t ctl_single_phase_pll::sogi
ctl_pid_t ctl_single_phase_pll::spll_ctrl
ctl_low_pass_filter_t ctl_single_phase_pll::filter_uq
ctrl_gt ctl_single_phase_dc_pll::frequency
ctrl_gt ctl_single_phase_dc_pll::theta
ctl_vector2_t ctl_single_phase_dc_pll::phasor
ctrl_gt ctl_single_phase_dc_pll::v_mag
ctrl_gt ctl_single_phase_dc_pll::v_dc_est
ctl_vector2_t ctl_single_phase_dc_pll::uab
ctl_vector2_t ctl_single_phase_dc_pll::udq
ctrl_gt ctl_single_phase_dc_pll::freq_error
ctrl_gt ctl_single_phase_dc_pll::freq_sf
discrete_sogi_dc_t ctl_single_phase_dc_pll::sogi_dc
ctl_pid_t ctl_single_phase_dc_pll::spll_ctrl
ctl_low_pass_filter_t ctl_single_phase_dc_pll::filter_uq
Detailed Description
A Phase-Locked Loop for single-phase grid synchronization.
This file provides an implementation of a SOGI-based PLL, which is a robust method for tracking the phase and frequency of a single-phase AC signal. It is commonly used in grid-tied applications like PFC rectifiers and inverters.
The PLL operates as follows:
A Second-Order Generalized Integrator (SOGI) takes the single-phase input and generates a pair of orthogonal \((\alpha -\beta)\) signals.
A Park transform converts these \((\alpha -\beta)\) signals into a rotating d-q frame using the PLL's estimated phase angle.
A PI controller acts as a loop filter, driving the q-component of the transformed signal to zero.
A Voltage-Controlled Oscillator (VCO) integrates the output of the loop filter to generate the estimated frequency and phase, which closes the loop.
Function Documentation
ctl_clear_single_phase_pll()
GMP_STATIC_INLINE void ctl_clear_single_phase_pll (ctl_single_phase_pll * spll)
Clears the internal states of the PLL.
Resets the SOGI, filters, and phase angle to a known initial state.
Parameters
[in,out] spll Pointer to the Single-Phase PLL instance.
Definition at line 100 of file spll.h.
References ctl_clear_discrete_sogi(), ctl_clear_lowpass_filter(), ctl_clear_pid(), ctl_set_phasor_via_angle(), ctl_single_phase_pll::filter_uq, float2ctrl, ctl_single_phase_pll::phasor, ctl_single_phase_pll::sogi, ctl_single_phase_pll::spll_ctrl, and ctl_single_phase_pll::theta.
ctl_get_spll_error_fbk()
GMP_STATIC_INLINE ctrl_gt ctl_get_spll_error_fbk (ctl_single_phase_pll * spll)
Gets the filtered q-axis component, which represents the phase error.
Parameters
[in] spll Pointer to the Single-Phase PLL instance.
Returns
The filtered phase error signal (udq.q).
Definition at line 157 of file spll.h.
References ctl_get_lowpass_filter_result(), and ctl_single_phase_pll::filter_uq.
ctl_init_single_phase_pll()
void ctl_init_single_phase_pll (ctl_single_phase_pll * spll, parameter_gt gain, parameter_gt ki, parameter_gt fc, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase PLL module.
Parameters
[out] spll Pointer to the Single-Phase PLL instance.
[in] gain Proportional gain (Kp) for the PLL's PI loop filter.
[in] ki Integral time constant (s) for the PLL's PI loop filter.
[in] fc Cutoff frequency (Hz) for the q-axis low-pass filter.
[in] fg Nominal grid frequency (e.g., 50 or 60 Hz).
[in] fs Controller execution frequency (Hz).
Definition at line 22 of file ctl_dp_single_phase.c.
References ctl_clear_single_phase_pll(), ctl_init_discrete_sogi(), ctl_init_lp_filter(), ctl_init_pid_Tmode(), ctl_single_phase_pll::filter_uq, float2ctrl, ctl_single_phase_pll::freq_sf, fs, gain, ctl_single_phase_pll::sogi, and ctl_single_phase_pll::spll_ctrl.
ctl_init_single_phase_pll_T()
void ctl_init_single_phase_pll_T (ctl_single_phase_pll * spll, parameter_gt gain, parameter_gt Ti, parameter_gt fc, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase PLL module.
Parameters
[out] spll Pointer to the Single-Phase PLL instance.
[in] gain Proportional gain (Kp) for the PLL's PI loop filter.
[in] Ti Integral time constant (s) for the PLL's PI loop filter.
[in] fc Cutoff frequency (Hz) for the q-axis low-pass filter.
[in] fg Nominal grid frequency (e.g., 50 or 60 Hz).
[in] fs Controller execution frequency (Hz).
Definition at line 41 of file ctl_dp_single_phase.c.
References ctl_clear_single_phase_pll(), ctl_init_discrete_sogi(), ctl_init_lp_filter(), ctl_init_pid(), ctl_single_phase_pll::filter_uq, float2ctrl, ctl_single_phase_pll::freq_sf, fs, gain, ctl_single_phase_pll::sogi, and ctl_single_phase_pll::spll_ctrl.
ctl_step_single_phase_pll()
GMP_STATIC_INLINE void ctl_step_single_phase_pll (ctl_single_phase_pll * spll, ctrl_gt ac_input)
Executes one step of the Single-Phase PLL algorithm.
Parameters
[in,out] spll Pointer to the Single-Phase PLL instance.
[in] ac_input The instantaneous value of the single-phase AC input signal.
Definition at line 115 of file spll.h.
References ctl_ct_park2(), ctl_get_discrete_sogi_ds(), ctl_get_discrete_sogi_qs(), ctl_get_lowpass_filter_result(), ctl_mul, ctl_set_phasor_via_angle(), ctl_step_discrete_sogi(), ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctrl_mod_1, vector2_gt::dat, ctl_single_phase_pll::filter_uq, float2ctrl, ctl_single_phase_pll::freq_error, ctl_single_phase_pll::freq_sf, ctl_single_phase_pll::frequency, phase_alpha, phase_beta, phase_d, phase_q, ctl_single_phase_pll::phasor, ctl_single_phase_pll::sogi, ctl_single_phase_pll::spll_ctrl, ctl_single_phase_pll::theta, ctl_single_phase_pll::uab, ctl_single_phase_pll::udq, and ctl_single_phase_pll::v_mag.
Variable Documentation
filter_uq [1/2]
ctl_low_pass_filter_t ctl_single_phase_dc_pll::filter_uq
Low-pass filter for the q-axis component to reduce harmonics.
Definition at line 194 of file spll.h.
filter_uq [2/2]
ctl_low_pass_filter_t ctl_single_phase_pll::filter_uq
Low-pass filter for the q-axis component to reduce harmonics.
Definition at line 67 of file spll.h.
freq_error [1/2]
ctrl_gt ctl_single_phase_dc_pll::freq_error
The frequency error term from the loop filter (PI controller output).
Definition at line 186 of file spll.h.
freq_error [2/2]
ctrl_gt ctl_single_phase_pll::freq_error
The frequency error term from the loop filter (PI controller output).
Definition at line 59 of file spll.h.
freq_sf [1/2]
ctrl_gt ctl_single_phase_dc_pll::freq_sf
Scaling factor to convert per-unit frequency to per-step phase increment.
Definition at line 189 of file spll.h.
freq_sf [2/2]
ctrl_gt ctl_single_phase_pll::freq_sf
Scaling factor to convert per-unit frequency to per-step phase increment.
Definition at line 62 of file spll.h.
frequency [1/2]
ctrl_gt ctl_single_phase_dc_pll::frequency
Estimated grid frequency in per-unit (1.0 = nominal frequency).
Definition at line 177 of file spll.h.
frequency [2/2]
ctrl_gt ctl_single_phase_pll::frequency
Estimated grid frequency in per-unit (1.0 = nominal frequency).
Definition at line 51 of file spll.h.
phasor [1/2]
ctl_vector2_t ctl_single_phase_dc_pll::phasor
Output phasor containing sin(theta) and cos(theta).
Definition at line 179 of file spll.h.
phasor [2/2]
vector2_gt ctl_single_phase_pll::phasor
Output phasor containing sin(theta) and cos(theta).
Definition at line 53 of file spll.h.
sogi
discrete_sogi_t ctl_single_phase_pll::sogi
The SOGI-based orthogonal signal generator.
Definition at line 65 of file spll.h.
sogi_dc
discrete_sogi_dc_t ctl_single_phase_dc_pll::sogi_dc
The SOGI-DC based orthogonal signal generator.
Definition at line 192 of file spll.h.
spll_ctrl [1/2]
ctl_pid_t ctl_single_phase_dc_pll::spll_ctrl
The PI controller that acts as the loop filter.
Definition at line 193 of file spll.h.
spll_ctrl [2/2]
ctl_pid_t ctl_single_phase_pll::spll_ctrl
The PI controller that acts as the loop filter.
Definition at line 66 of file spll.h.
theta [1/2]
ctrl_gt ctl_single_phase_dc_pll::theta
Estimated grid phase angle in per-unit (0 to 1.0 represents 0 to 2*pi).
Definition at line 178 of file spll.h.
theta [2/2]
ctrl_gt ctl_single_phase_pll::theta
Estimated grid phase angle in per-unit (0 to 1.0 represents 0 to 2*pi).
Definition at line 52 of file spll.h.
uab [1/2]
ctl_vector2_t ctl_single_phase_dc_pll::uab
Alpha-Beta voltage (SOGI output).
Definition at line 184 of file spll.h.
uab [2/2]
vector2_gt ctl_single_phase_pll::uab
Alpha-Beta voltage (SOGI output)
Definition at line 57 of file spll.h.
udq [1/2]
ctl_vector2_t ctl_single_phase_dc_pll::udq
The input voltage transformed into the d-q rotating frame.
Definition at line 185 of file spll.h.
udq [2/2]
vector2_gt ctl_single_phase_pll::udq
The input voltage transformed into the d-q rotating frame.
Definition at line 58 of file spll.h.
v_dc_est
ctrl_gt ctl_single_phase_dc_pll::v_dc_est
[NEW] Estimated Grid Voltage DC Offset.
Definition at line 181 of file spll.h.
v_mag [1/2]
ctrl_gt ctl_single_phase_dc_pll::v_mag
Estimated Grid Voltage Amplitude (Peak Value).
Definition at line 180 of file spll.h.
v_mag [2/2]
ctrl_gt ctl_single_phase_pll::v_mag
Estimated Grid Voltage Amplitude (Peak Value).
Definition at line 54 of file spll.h.