GMP - CTL: Three-Phase Modulation API
Three-Phase Modulation API
Digital Power Control Library » Digital Power Components | GMP CTL interface » GMP CTL basic interface
Provides functions for generating three-phase PWM signals from voltage commands, including dead-time compensation based on current direction.
Data Structures
struct spwm_modulator_t
Data structure for the three-phase bridge SPWM modulation module.
struct npc_modulator_t
Macros
#define PWM_MODULATOR_USING_NEGATIVE_LOGIC (0)
This macro notice that using negative logic.
#define NPC_IDX_PHASE_A_OUTER 0
#define NPC_IDX_PHASE_A_INNER 1
#define NPC_IDX_PHASE_B_OUTER 2
#define NPC_IDX_PHASE_B_INNER 3
#define NPC_IDX_PHASE_C_OUTER 4
#define NPC_IDX_PHASE_C_INNER 5
#define NPC_OUTER_IDX(phase)
#define NPC_INNER_IDX(phase)
Functions
GMP_STATIC_INLINE void ctl_clear_spwm_modulator (spwm_modulator_t *mod)
Clears the internal states of the modulation module.
void ctl_init_spwm_modulator (spwm_modulator_t *mod, pwm_gt pwm_full_scale, pwm_gt pwm_deadband_comp_val, ctl_vector3_t *iuvw, ctrl_gt current_deadband, ctrl_gt current_hysteresis)
Initializes the three-phase bridge modulation module.
GMP_STATIC_INLINE void ctl_step_spwm_modulator (spwm_modulator_t *mod)
Executes one step of the three-phase modulation algorithm.
GMP_STATIC_INLINE void ctl_step_svpwm_modulator (spwm_modulator_t *mod)
Executes one step of the three-phase modulation algorithm.
GMP_STATIC_INLINE void ctl_clear_npc_modulator (npc_modulator_t *mod)
Clears the internal states of the modulation module.
void ctl_init_npc_modulator (npc_modulator_t *mod, pwm_gt pwm_full_scale, pwm_gt pwm_deadband_comp_val, ctl_vector3_t *iuvw, ctrl_gt current_deadband, ctrl_gt current_hysteresis)
Initializes the three-phase NPC bridge modulation module.
GMP_STATIC_INLINE pwm_gt ctl_npc_get_pwm_cmp (const npc_modulator_t *mod, int phase, int is_inner)
Get the computed PWM compare value for a specific switch.
GMP_STATIC_INLINE int get_current_zone (ctrl_gt i_sample, ctrl_gt deadband, ctrl_gt hysteresis, signed short *last_dir)
Determines the current direction zone for dead-time compensation.
GMP_STATIC_INLINE void ctl_step_npc_modulator (npc_modulator_t *mod)
Step to execute the modulator.
GMP_STATIC_INLINE void ctl_step_npc_svpwm_modulator (npc_modulator_t *mod)
Step to execute the modulator.
Detailed Description
Provides functions for generating three-phase PWM signals from voltage commands, including dead-time compensation based on current direction.
Macro Definition Documentation
NPC_IDX_PHASE_A_INNER
#define NPC_IDX_PHASE_A_INNER 1
Definition at line 347 of file pwm_modulator.h.
NPC_IDX_PHASE_A_OUTER
#define NPC_IDX_PHASE_A_OUTER 0
Definition at line 346 of file pwm_modulator.h.
NPC_IDX_PHASE_B_INNER
#define NPC_IDX_PHASE_B_INNER 3
Definition at line 349 of file pwm_modulator.h.
NPC_IDX_PHASE_B_OUTER
#define NPC_IDX_PHASE_B_OUTER 2
Definition at line 348 of file pwm_modulator.h.
NPC_IDX_PHASE_C_INNER
#define NPC_IDX_PHASE_C_INNER 5
Definition at line 351 of file pwm_modulator.h.
NPC_IDX_PHASE_C_OUTER
#define NPC_IDX_PHASE_C_OUTER 4
Definition at line 350 of file pwm_modulator.h.
NPC_INNER_IDX
#define NPC_INNER_IDX (phase)
Value:
((phase) * 2 + 1)
Definition at line 355 of file pwm_modulator.h.
NPC_OUTER_IDX
#define NPC_OUTER_IDX (phase)
Value:
((phase) * 2)
Definition at line 354 of file pwm_modulator.h.
PWM_MODULATOR_USING_NEGATIVE_LOGIC
#define PWM_MODULATOR_USING_NEGATIVE_LOGIC (0)
This macro notice that using negative logic.
Definition at line 31 of file pwm_modulator.h.
Function Documentation
ctl_clear_npc_modulator()
GMP_STATIC_INLINE void ctl_clear_npc_modulator (npc_modulator_t * mod)
Clears the internal states of the modulation module.
Parameters
[out] mod Pointer to the npc_modulator_t structure.
Definition at line 386 of file pwm_modulator.h.
References ctl_vector3_clear(), npc_modulator_t::last_current_dir, NPC_IDX_PHASE_A_INNER, NPC_IDX_PHASE_A_OUTER, NPC_IDX_PHASE_B_INNER, NPC_IDX_PHASE_B_OUTER, NPC_IDX_PHASE_C_INNER, NPC_IDX_PHASE_C_OUTER, phase_A, phase_B, phase_C, npc_modulator_t::pwm_out, and npc_modulator_t::vabc_out.
ctl_clear_spwm_modulator()
GMP_STATIC_INLINE void ctl_clear_spwm_modulator (spwm_modulator_t * mod)
Clears the internal states of the modulation module.
Parameters
[out] mod Pointer to the spwm_modulator_t structure.
Definition at line 72 of file pwm_modulator.h.
References ctl_vector3_clear(), spwm_modulator_t::last_current_dir, phase_A, phase_B, phase_C, spwm_modulator_t::pwm_out, and spwm_modulator_t::vabc_out.
ctl_init_npc_modulator()
void ctl_init_npc_modulator (npc_modulator_t * mod, pwm_gt pwm_full_scale, pwm_gt pwm_deadband_comp_val, ctl_vector3_t * iuvw, ctrl_gt current_deadband, ctrl_gt current_hysteresis)
Initializes the three-phase NPC bridge modulation module.
Parameters
[out] bridge Pointer to the three_phase_bridge_modulation_t structure.
[in] pwm_full_scale The maximum value of the PWM counter.
[in] pwm_deadband The total dead-time value in PWM timer counts.
[in] iuvw a pointer to inverter output current, point to ADC module or main controller.
[in] current_deadband The current threshold to enable dead-time compensation.
[in] current_hysteresis The current hysteresis to enable dead-time compensation.
Definition at line 258 of file ctl_component_interface.c.
References ctl_clear_npc_modulator(), npc_modulator_t::current_deadband, npc_modulator_t::current_hysteresis_band, npc_modulator_t::iuvw, npc_modulator_t::pwm_deadband_comp_val, and npc_modulator_t::pwm_full_scale.
ctl_init_spwm_modulator()
void ctl_init_spwm_modulator (spwm_modulator_t * mod, pwm_gt pwm_full_scale, pwm_gt pwm_deadband_comp_val, ctl_vector3_t * iuvw, ctrl_gt current_deadband, ctrl_gt current_hysteresis)
Initializes the three-phase bridge modulation module.
Parameters
[out] bridge Pointer to the three_phase_bridge_modulation_t structure.
[in] pwm_full_scale The maximum value of the PWM counter.
[in] pwm_deadband The total dead-time value in PWM timer counts.
[in] iuvw a pointer to inverter output current, point to ADC module or main controller.
[in] current_deadband The current threshold to enable dead-time compensation.
[in] current_hysteresis The current hysteresis to enable dead-time compensation.
Definition at line 245 of file ctl_component_interface.c.
References ctl_clear_spwm_modulator(), spwm_modulator_t::current_deadband, spwm_modulator_t::current_hysteresis_band, spwm_modulator_t::iuvw, spwm_modulator_t::pwm_deadband_comp_val, and spwm_modulator_t::pwm_full_scale.
ctl_npc_get_pwm_cmp()
GMP_STATIC_INLINE pwm_gt ctl_npc_get_pwm_cmp (const npc_modulator_t * mod, int phase, int is_inner)
Get the computed PWM compare value for a specific switch.
Parameters
mod Pointer to the modulator.
phase Phase index (0=A, 1=B, 2=C).
is_inner 0 for Outer Switch (S1/S4-like), 1 for Inner Switch (S2/S3-like).
Returns
The PWM compare value to be written to the register.
Definition at line 423 of file pwm_modulator.h.
References npc_modulator_t::pwm_out.
ctl_step_npc_modulator()
GMP_STATIC_INLINE void ctl_step_npc_modulator (npc_modulator_t * mod)
Step to execute the modulator.
Parameters
mod Pointer to the modulator.
Definition at line 488 of file pwm_modulator.h.
References ctl_ct_iclarke(), npc_modulator_t::current_deadband, npc_modulator_t::current_hysteresis_band, vector3_gt::dat, npc_modulator_t::flag_enable_deadband_compensator, float2ctrl, get_current_zone(), i, npc_modulator_t::iuvw, npc_modulator_t::last_current_dir, NPC_INNER_IDX, NPC_OUTER_IDX, npc_modulator_t::pwm_deadband_comp_val, npc_modulator_t::pwm_full_scale, pwm_mul, npc_modulator_t::pwm_out, pwm_sat, npc_modulator_t::vab0_out, and npc_modulator_t::vabc_out.
ctl_step_npc_svpwm_modulator()
GMP_STATIC_INLINE void ctl_step_npc_svpwm_modulator (npc_modulator_t * mod)
Step to execute the modulator.
Parameters
mod Pointer to the modulator.
Definition at line 604 of file pwm_modulator.h.
References ctl_abs, ctl_ct_svpwm_calc(), ctl_sub, npc_modulator_t::current_deadband, npc_modulator_t::current_hysteresis_band, vector3_gt::dat, npc_modulator_t::flag_enable_deadband_compensator, float2ctrl, get_current_zone(), i, npc_modulator_t::iuvw, npc_modulator_t::last_current_dir, NPC_INNER_IDX, NPC_OUTER_IDX, npc_modulator_t::pwm_deadband_comp_val, npc_modulator_t::pwm_full_scale, pwm_mul, npc_modulator_t::pwm_out, pwm_sat, npc_modulator_t::vab0_out, and npc_modulator_t::vabc_out.
ctl_step_spwm_modulator()
GMP_STATIC_INLINE void ctl_step_spwm_modulator (spwm_modulator_t * mod)
Executes one step of the three-phase modulation algorithm.
Converts per-unit voltage commands (-1.0 to 1.0) to PWM compare values, and applies dead-time compensation based on the direction of phase currents.
Parameters
[in,out] mod Pointer to the spwm_modulator_t structure.
Definition at line 107 of file pwm_modulator.h.
References ctl_add, ctl_ct_iclarke(), ctl_div2, spwm_modulator_t::current_deadband, spwm_modulator_t::current_hysteresis_band, vector3_gt::dat, spwm_modulator_t::flag_enable_deadband_compensator, float2ctrl, i, spwm_modulator_t::iuvw, spwm_modulator_t::last_current_dir, spwm_modulator_t::pwm_deadband_comp_val, spwm_modulator_t::pwm_full_scale, pwm_mul, spwm_modulator_t::pwm_out, pwm_sat, spwm_modulator_t::vab0_out, and spwm_modulator_t::vabc_out.
ctl_step_svpwm_modulator()
GMP_STATIC_INLINE void ctl_step_svpwm_modulator (spwm_modulator_t * mod)
Executes one step of the three-phase modulation algorithm.
Converts per-unit voltage commands (-1.0 to 1.0) to PWM compare values, and applies dead-time compensation based on the direction of phase currents. SPWM and SVPWM are using the same data structure.
Parameters
[in,out] mod Pointer to the spwm_modulator_t structure.
Definition at line 228 of file pwm_modulator.h.
References ctl_add, ctl_ct_svpwm(), ctl_div2, spwm_modulator_t::current_deadband, spwm_modulator_t::current_hysteresis_band, vector3_gt::dat, spwm_modulator_t::flag_enable_deadband_compensator, float2ctrl, i, spwm_modulator_t::iuvw, spwm_modulator_t::last_current_dir, spwm_modulator_t::pwm_deadband_comp_val, spwm_modulator_t::pwm_full_scale, pwm_mul, spwm_modulator_t::pwm_out, pwm_sat, spwm_modulator_t::vab0_out, and spwm_modulator_t::vabc_out.
get_current_zone()
GMP_STATIC_INLINE int get_current_zone (ctrl_gt i_sample, ctrl_gt deadband, ctrl_gt hysteresis, signed short * last_dir)
Determines the current direction zone for dead-time compensation.
Parameters
i_sample Current sample value (Per-Unit or Amps).
deadband The inner deadband threshold (Zone 3 limit).
hysteresis The hysteresis band width (Zone 4 width).
last_dir Pointer to the memory of the last state (-1, 0, 1).
Returns
int The new current direction state: 1 : Strong Positive (Current flows OUT) -1: Strong Negative (Current flows IN) 0 : Inside Deadband (Zero Crossing)
Definition at line 442 of file pwm_modulator.h.