GMP - CTL: Pole-Zero Compensators
Pole-Zero Compensators
Control Template Library Intrinsic » Discrete Components
A library of discrete IIR filters for control loop compensation.
Data Structures
struct ctrl_1p1z_t
Data structure for a 1-Pole-1-Zero compensator.
struct ctrl_2p2z_t
Data structure for a 2-Poles-2-Zeros compensator.
struct ctrl_3p3z_t
Data structure for a 3-Poles-3-Zeros compensator.
Functions
GMP_STATIC_INLINE void ctl_clear_1p1z (ctrl_1p1z_t *c)
Clears the internal states of the 1P1Z compensator.
void ctl_init_1p1z (ctrl_1p1z_t *c, parameter_gt gain, parameter_gt f_z, parameter_gt f_p, parameter_gt fs)
Initializes a 1P1Z compensator from a real pole and a real zero frequency.
GMP_STATIC_INLINE ctrl_gt ctl_step_1p1z (ctrl_1p1z_t *c, ctrl_gt input)
Executes one step of the 1P1Z compensator.
parameter_gt ctl_get_1p1z_phase_lag (ctrl_1p1z_t *c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 1P1Z compensator at a specific frequency.
parameter_gt ctl_get_1p1z_gain (ctrl_1p1z_t *c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 1P1Z compensator at a specific frequency.
GMP_STATIC_INLINE void ctl_clear_2p2z (ctrl_2p2z_t *c)
Clears the internal states of the 2P2Z compensator.
void ctl_init_2p2z_real (ctrl_2p2z_t *c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_p1, parameter_gt f_p2, parameter_gt fs)
Initializes a 2P2Z compensator with two real poles and two real zeros.
void ctl_init_2p2z_complex_zeros (ctrl_2p2z_t *c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_p1, parameter_gt f_p2, parameter_gt fs)
Initializes a 2P2Z compensator with two real poles and a pair of complex-conjugate zeros.
GMP_STATIC_INLINE ctrl_gt ctl_step_2p2z (ctrl_2p2z_t *c, ctrl_gt input)
Executes one step of the 2P2Z compensator.
parameter_gt ctl_get_2p2z_phase_lag (ctrl_2p2z_t *c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 2P2Z compensator at a specific frequency.
parameter_gt ctl_get_2p2z_gain (ctrl_2p2z_t *c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 2P2Z compensator at a specific frequency.
GMP_STATIC_INLINE void ctl_clear_3p3z (ctrl_3p3z_t *c)
Clears the internal states of the 3P3Z compensator.
void ctl_init_3p3z_real (ctrl_3p3z_t *c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_z3, parameter_gt f_p1, parameter_gt f_p2, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with three real poles and three real zeros.
void ctl_init_3p3z_complex_zeros (ctrl_3p3z_t *c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_z3, parameter_gt f_p1, parameter_gt f_p2, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate zero pair and one real zero.
void ctl_init_3p3z_complex_poles (ctrl_3p3z_t *c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_z3, parameter_gt f_cpr, parameter_gt f_cpi, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate pole pair and one real pole.
void ctl_init_3p3z_complex_pair (ctrl_3p3z_t *c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_z3, parameter_gt f_cpr, parameter_gt f_cpi, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate pole pair and one complex-conjugate zero pair.
GMP_STATIC_INLINE ctrl_gt ctl_step_3p3z (ctrl_3p3z_t *c, ctrl_gt input)
Executes one step of the 3P3Z compensator.
parameter_gt ctl_get_3p3z_phase_lag (ctrl_3p3z_t *c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 3P3Z compensator at a specific frequency.
parameter_gt ctl_get_3p3z_gain (ctrl_3p3z_t *c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 3P3Z compensator at a specific frequency.
Detailed Description
A library of discrete IIR filters for control loop compensation.
This file contains implementations for several discrete-time pole-zero compensators. These are fundamental building blocks for digital controllers, designed to shape the frequency response of a control loop. This version provides initialization functions based on desired pole and zero frequencies, including support for complex-conjugate pairs. Discretization from the s-domain to the z-domain is achieved using the Bilinear Transform.
Function Documentation
ctl_clear_1p1z()
GMP_STATIC_INLINE void ctl_clear_1p1z (ctrl_1p1z_t * c)
Clears the internal states of the 1P1Z compensator.
Parameters
[out] c Pointer to the 1P1Z compensator instance.
Definition at line 53 of file pole_zero.h.
References c.
ctl_clear_2p2z()
GMP_STATIC_INLINE void ctl_clear_2p2z (ctrl_2p2z_t * c)
Clears the internal states of the 2P2Z compensator.
Parameters
[out] c Pointer to the 2P2Z compensator instance.
Definition at line 122 of file pole_zero.h.
References c.
ctl_clear_3p3z()
GMP_STATIC_INLINE void ctl_clear_3p3z (ctrl_3p3z_t * c)
Clears the internal states of the 3P3Z compensator.
Parameters
[out] c Pointer to the 3P3Z compensator instance.
Definition at line 214 of file pole_zero.h.
References c, and i.
ctl_get_1p1z_gain()
parameter_gt ctl_get_1p1z_gain (ctrl_1p1z_t * c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 1P1Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 1P1Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the gain (Hz).
Returns
parameter_gt The linear gain (magnitude).
References c, and fs.
ctl_get_1p1z_phase_lag()
parameter_gt ctl_get_1p1z_phase_lag (ctrl_1p1z_t * c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 1P1Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 1P1Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the phase lag (Hz).
Returns
parameter_gt The phase lag in radians. A positive value indicates lag.
References c, and fs.
ctl_get_2p2z_gain()
parameter_gt ctl_get_2p2z_gain (ctrl_2p2z_t * c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 2P2Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 2P2Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the gain (Hz).
Returns
parameter_gt The linear gain (magnitude).
Definition at line 1057 of file ctl_component_discrete.c.
References c, CTL_PARAM_CONST_PI, and fs.
ctl_get_2p2z_phase_lag()
parameter_gt ctl_get_2p2z_phase_lag (ctrl_2p2z_t * c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 2P2Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 2P2Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the phase lag (Hz).
Returns
parameter_gt The phase lag in radians.
Definition at line 1074 of file ctl_component_discrete.c.
References c, CTL_PARAM_CONST_PI, and fs.
ctl_get_3p3z_gain()
parameter_gt ctl_get_3p3z_gain (ctrl_3p3z_t * c, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 3P3Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 3P3Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the gain (Hz).
Returns
parameter_gt The linear gain (magnitude).
Definition at line 1091 of file ctl_component_discrete.c.
References c, CTL_PARAM_CONST_PI, and fs.
ctl_get_3p3z_phase_lag()
parameter_gt ctl_get_3p3z_phase_lag (ctrl_3p3z_t * c, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 3P3Z compensator at a specific frequency.
Parameters
[in] c Pointer to the 3P3Z compensator instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the phase lag (Hz).
Returns
parameter_gt The phase lag in radians.
Definition at line 1109 of file ctl_component_discrete.c.
References c, CTL_PARAM_CONST_PI, and fs.
ctl_init_1p1z()
void ctl_init_1p1z (ctrl_1p1z_t * c, parameter_gt gain, parameter_gt f_z, parameter_gt f_p, parameter_gt fs)
Initializes a 1P1Z compensator from a real pole and a real zero frequency.
Parameters
[out] c Pointer to the 1P1Z compensator instance.
[in] gain The desired DC gain of the compensator.
[in] f_z The frequency of the zero in Hz.
[in] f_p The frequency of the pole in Hz.
[in] fs The sampling frequency in Hz.
Definition at line 813 of file ctl_component_discrete.c.
References a1, b0, b1, c, ctl_clear_1p1z(), CTL_PARAM_CONST_PI, float2ctrl, fs, and gain.
ctl_init_2p2z_complex_zeros()
void ctl_init_2p2z_complex_zeros (ctrl_2p2z_t * c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_p1, parameter_gt f_p2, parameter_gt fs)
Initializes a 2P2Z compensator with two real poles and a pair of complex-conjugate zeros.
Parameters
[out] c Pointer to the 2P2Z compensator instance.
[in] gain The desired DC gain.
[in] f_czr Real part of the complex zero location in the s-plane (-sigma, in Hz).
[in] f_czi Imaginary part of the complex zero location in the s-plane (wd, in Hz).
[in] f_p1 Frequency of the first pole (Hz).
[in] f_p2 Frequency of the second pole (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 865 of file ctl_component_discrete.c.
References a1, a2, c, ctl_clear_2p2z(), float2ctrl, fs, and gain.
ctl_init_2p2z_real()
void ctl_init_2p2z_real (ctrl_2p2z_t * c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_p1, parameter_gt f_p2, parameter_gt fs)
Initializes a 2P2Z compensator with two real poles and two real zeros.
Parameters
[out] c Pointer to the 2P2Z compensator instance.
[in] gain The desired DC gain.
[in] f_z1 Frequency of the first zero (Hz).
[in] f_z2 Frequency of the second zero (Hz).
[in] f_p1 Frequency of the first pole (Hz).
[in] f_p2 Frequency of the second pole (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 840 of file ctl_component_discrete.c.
References a1, a2, c, ctl_clear_2p2z(), float2ctrl, fs, and gain.
ctl_init_3p3z_complex_pair()
void ctl_init_3p3z_complex_pair (ctrl_3p3z_t * c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_z3, parameter_gt f_cpr, parameter_gt f_cpi, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate pole pair and one complex-conjugate zero pair.
Parameters
[out] c Pointer to the 3P3Z compensator instance.
[in] gain The desired overall DC gain.
[in] f_czr,f_czi Real and imaginary parts of the complex zero (Hz).
[in] f_z3 Frequency of the real zero (Hz).
[in] f_cpr,f_cpi Real and imaginary parts of the complex pole (Hz).
[in] f_p3 Frequency of the real pole (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 1006 of file ctl_component_discrete.c.
References a1, a2, b2, c, ctrl_1p1z_t::coef_a, ctrl_2p2z_t::coef_a, ctrl_1p1z_t::coef_b, ctrl_2p2z_t::coef_b, ctl_clear_3p3z(), ctl_init_1p1z(), float2ctrl, fs, gain, and i.
ctl_init_3p3z_complex_poles()
void ctl_init_3p3z_complex_poles (ctrl_3p3z_t * c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_z3, parameter_gt f_cpr, parameter_gt f_cpi, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate pole pair and one real pole.
Parameters
[out] c Pointer to the 3P3Z compensator instance.
[in] gain The desired overall DC gain.
[in] f_z1,f_z2,f_z3 Frequencies of the three real zeros (Hz).
[in] f_cpr,f_cpi Real and imaginary parts of the complex pole (Hz).
[in] f_p3 Frequency of the real pole (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 959 of file ctl_component_discrete.c.
References a1, a2, b2, c, ctrl_1p1z_t::coef_a, ctrl_2p2z_t::coef_a, ctrl_1p1z_t::coef_b, ctrl_2p2z_t::coef_b, ctl_clear_3p3z(), ctl_init_1p1z(), float2ctrl, fs, gain, and i.
ctl_init_3p3z_complex_zeros()
void ctl_init_3p3z_complex_zeros (ctrl_3p3z_t * c, parameter_gt gain, parameter_gt f_czr, parameter_gt f_czi, parameter_gt f_z3, parameter_gt f_p1, parameter_gt f_p2, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with one complex-conjugate zero pair and one real zero.
Parameters
[out] c Pointer to the 3P3Z compensator instance.
[in] gain The desired overall DC gain.
[in] f_czr,f_czi Real and imaginary parts of the complex zero (Hz).
[in] f_z3 Frequency of the real zero (Hz).
[in] f_p1,f_p2,f_p3 Frequencies of the three real poles (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 926 of file ctl_component_discrete.c.
References a1, a2, b2, c, ctrl_1p1z_t::coef_a, ctrl_2p2z_t::coef_a, ctrl_1p1z_t::coef_b, ctrl_2p2z_t::coef_b, ctl_clear_3p3z(), ctl_init_1p1z(), ctl_init_2p2z_complex_zeros(), float2ctrl, fs, gain, and i.
ctl_init_3p3z_real()
void ctl_init_3p3z_real (ctrl_3p3z_t * c, parameter_gt gain, parameter_gt f_z1, parameter_gt f_z2, parameter_gt f_z3, parameter_gt f_p1, parameter_gt f_p2, parameter_gt f_p3, parameter_gt fs)
Initializes a 3P3Z compensator with three real poles and three real zeros.
Parameters
[out] c Pointer to the 3P3Z compensator instance.
[in] gain The desired overall DC gain.
[in] f_z1,f_z2,f_z3 Frequencies of the three real zeros (Hz).
[in] f_p1,f_p2,f_p3 Frequencies of the three real poles (Hz).
[in] fs Sampling frequency (Hz).
Definition at line 893 of file ctl_component_discrete.c.
References a1, a2, b2, c, ctrl_1p1z_t::coef_a, ctrl_2p2z_t::coef_a, ctrl_1p1z_t::coef_b, ctrl_2p2z_t::coef_b, ctl_clear_3p3z(), ctl_init_1p1z(), ctl_init_2p2z_real(), float2ctrl, fs, gain, and i.
ctl_step_1p1z()
GMP_STATIC_INLINE ctrl_gt ctl_step_1p1z (ctrl_1p1z_t * c, ctrl_gt input)
Executes one step of the 1P1Z compensator.
Parameters
[in,out] c Pointer to the 1P1Z compensator instance.
[in] input The current input to the compensator, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 76 of file pole_zero.h.
References c, ctl_mul, and input.
ctl_step_2p2z()
GMP_STATIC_INLINE ctrl_gt ctl_step_2p2z (ctrl_2p2z_t * c, ctrl_gt input)
Executes one step of the 2P2Z compensator.
Parameters
[in,out] c Pointer to the 2P2Z compensator instance.
[in] input The current input to the compensator, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 163 of file pole_zero.h.
References c, ctl_mul, and input.
ctl_step_3p3z()
GMP_STATIC_INLINE ctrl_gt ctl_step_3p3z (ctrl_3p3z_t * c, ctrl_gt input)
Executes one step of the 3P3Z compensator.
Parameters
[in,out] c Pointer to the 3P3Z compensator instance.
[in] input The current input to the compensator, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 283 of file pole_zero.h.
References c, ctl_mul, and input.