GMP - CTL: Tracking PID Controller
Tracking PID Controller
Control Template Library Intrinsic » Discrete Components
A composite PID controller for smooth setpoint tracking.
Data Structures
struct ctl_tracking_discrete_pid_t
Data structure for the tracking PID controller.
Functions
void ctl_init_tracking_pid (ctl_tracking_discrete_pid_t *tp, parameter_gt kp, parameter_gt Ti, parameter_gt Td, ctrl_gt sat_max, ctrl_gt sat_min, parameter_gt slope_max, parameter_gt slope_min, uint32_t division, parameter_gt fs)
Initializes the tracking PID controller.
GMP_STATIC_INLINE void ctl_clear_tracking_pid (ctl_tracking_discrete_pid_t *tp)
Clears the internal states of the tracking PID controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_tracking_pid (ctl_tracking_discrete_pid_t *tp, ctrl_gt target, ctrl_gt fbk)
Executes one step of the tracking PID controller.
Detailed Description
A composite PID controller for smooth setpoint tracking.
This file implements a tracking PID controller. It is a higher-level control block that combines three intrinsic modules:
A Frequency Divider: To execute the controller at a lower rate than the main ISR.
A Slope Limiter: To generate a smooth trajectory (ramp) for the setpoint.
A Discrete PID: To calculate the control output based on the error between the trajectory and the feedback signal. This structure is ideal for reference tracking applications where smooth transitions and different control rates are required.
Function Documentation
ctl_clear_tracking_pid()
GMP_STATIC_INLINE void ctl_clear_tracking_pid (ctl_tracking_discrete_pid_t * tp)
Clears the internal states of the tracking PID controller.
Parameters
[out] tp Pointer to the tracking PID instance.
Definition at line 73 of file track_discrete_pid.h.
References ctl_clear_discrete_pid(), ctl_clear_divider(), ctl_clear_slope_limiter(), ctl_tracking_discrete_pid_t::div, ctl_tracking_discrete_pid_t::pid, and ctl_tracking_discrete_pid_t::traj.
ctl_init_tracking_pid()
void ctl_init_tracking_pid (ctl_tracking_discrete_pid_t * tp, parameter_gt kp, parameter_gt Ti, parameter_gt Td, ctrl_gt sat_max, ctrl_gt sat_min, parameter_gt slope_max, parameter_gt slope_min, uint32_t division, parameter_gt fs)
Initializes the tracking PID controller.
Parameters
[out] tp Pointer to the tracking PID instance.
[in] kp Proportional gain of the PID.
[in] Ti Integral time constant of the PID (in seconds).
[in] Td Derivative time constant of the PID (in seconds).
[in] sat_max Maximum output saturation limit for the PID.
[in] sat_min Minimum output saturation limit for the PID.
[in] slope_max Maximum positive rate of change for the setpoint (units/sec).
[in] slope_min Maximum negative rate of change for the setpoint (-units/sec).
[in] division The factor by which to divide the execution frequency.
[in] fs The main sampling frequency (Hz) at which this module's step function is called.
Definition at line 705 of file ctl_component_discrete.c.
References ctl_init_discrete_pid(), ctl_init_divider(), ctl_init_slope_limiter(), ctl_set_discrete_pid_limit(), ctl_tracking_discrete_pid_t::div, fs, ctl_tracking_discrete_pid_t::pid, and ctl_tracking_discrete_pid_t::traj.
ctl_step_tracking_pid()
GMP_STATIC_INLINE ctrl_gt ctl_step_tracking_pid (ctl_tracking_discrete_pid_t * tp, ctrl_gt target, ctrl_gt fbk)
Executes one step of the tracking PID controller.
This function should be called at the main system frequency (fs). It uses an internal divider to decide when to execute the core control logic. When the divider triggers, it updates the setpoint trajectory and calculates a new PID output. On other steps, it holds the last calculated PID output.
Parameters
[in,out] tp Pointer to the tracking PID instance.
[in] target The ultimate target value for the setpoint.
[in] fbk The feedback value from the system.
Returns
ctrl_gt The latest control output.
Definition at line 91 of file track_discrete_pid.h.
References ctl_get_discrete_pid_output(), ctl_step_discrete_pid(), ctl_step_divider(), ctl_step_slope_limiter(), ctl_tracking_discrete_pid_t::div, ctl_slope_limiter_t::out, ctl_tracking_discrete_pid_t::pid, and ctl_tracking_discrete_pid_t::traj.