GMP - CTL: ADC Bias Calibrator
ADC Bias Calibrator
GMP CTL interface » GMP CTL basic interface
A utility for calibrating the offset (bias) of an ADC channel.
Data Structures
struct adc_bias_calibrator_t
Data structure for the ADC bias calibrator.
Functions
void ctl_init_adc_calibrator (adc_bias_calibrator_t *obj, parameter_gt fc, parameter_gt Q, parameter_gt fs)
void ctl_enable_adc_calibrator (adc_bias_calibrator_t *obj)
Enables the ADC bias calibration process.
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_cmpt (adc_bias_calibrator_t *obj)
Checks if the ADC calibration period is complete.
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_enabled (adc_bias_calibrator_t *obj)
Checks if the ADC calibrator is currently enabled.
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_result_valid (adc_bias_calibrator_t *obj)
Checks if the calibration result is valid.
GMP_STATIC_INLINE void ctl_clear_adc_calibrator (adc_bias_calibrator_t *obj)
Resets the calibrator to prepare for a new calibration sequence.
GMP_STATIC_INLINE void ctl_step_adc_calibrator (adc_bias_calibrator_t *obj, ctrl_gt adc_value)
Executes one step of the calibration process. This should be called periodically (e.g., in an ISR).
GMP_STATIC_INLINE ctrl_gt ctl_get_adc_calibrator_result (adc_bias_calibrator_t *obj)
Gets the calculated ADC bias result from the filter.
Detailed Description
A utility for calibrating the offset (bias) of an ADC channel.
This module uses a low-pass filter to determine the DC bias from a series of ADC readings.
Function Documentation
ctl_clear_adc_calibrator()
GMP_STATIC_INLINE void ctl_clear_adc_calibrator (adc_bias_calibrator_t * obj)
Resets the calibrator to prepare for a new calibration sequence.
Parameters
obj Pointer to the ADC bias calibrator object.
Definition at line 473 of file adc_channel.h.
References adc_bias_calibrator_t::enable_filter, adc_bias_calibrator_t::filter_tick, adc_bias_calibrator_t::output_valid, and adc_bias_calibrator_t::raw.
ctl_enable_adc_calibrator()
void ctl_enable_adc_calibrator (adc_bias_calibrator_t * obj)
Enables the ADC bias calibration process.
Parameters
obj Pointer to the ADC bias calibrator object.
Definition at line 82 of file ctl_component_interface.c.
References ctl_clear_biquad_filter(), adc_bias_calibrator_t::enable_filter, adc_bias_calibrator_t::filter, adc_bias_calibrator_t::filter_tick, and adc_bias_calibrator_t::output_valid.
ctl_get_adc_calibrator_result()
GMP_STATIC_INLINE ctrl_gt ctl_get_adc_calibrator_result (adc_bias_calibrator_t * obj)
Gets the calculated ADC bias result from the filter.
Parameters
obj Pointer to the ADC bias calibrator object.
Returns
The calculated average bias value.
Definition at line 508 of file adc_channel.h.
References ctl_get_biquad_filter_output(), and adc_bias_calibrator_t::filter.
ctl_init_adc_calibrator()
void ctl_init_adc_calibrator (adc_bias_calibrator_t * obj, parameter_gt fc, parameter_gt Q, parameter_gt fs)
Definition at line 61 of file ctl_component_interface.c.
References ctl_init_biquad_lpf(), adc_bias_calibrator_t::enable_filter, adc_bias_calibrator_t::filter, adc_bias_calibrator_t::filter_period, adc_bias_calibrator_t::filter_tick, fs, adc_bias_calibrator_t::output_valid, and adc_bias_calibrator_t::raw.
ctl_is_adc_calibrator_cmpt()
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_cmpt (adc_bias_calibrator_t * obj)
Checks if the ADC calibration period is complete.
Parameters
obj Pointer to the ADC bias calibrator object.
Returns
1 if complete, 0 otherwise.
Definition at line 444 of file adc_channel.h.
References adc_bias_calibrator_t::filter_period, and adc_bias_calibrator_t::filter_tick.
ctl_is_adc_calibrator_enabled()
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_enabled (adc_bias_calibrator_t * obj)
Checks if the ADC calibrator is currently enabled.
Parameters
obj Pointer to the ADC bias calibrator object.
Returns
1 if enabled, 0 if disabled.
Definition at line 454 of file adc_channel.h.
References adc_bias_calibrator_t::enable_filter.
ctl_is_adc_calibrator_result_valid()
GMP_STATIC_INLINE fast_gt ctl_is_adc_calibrator_result_valid (adc_bias_calibrator_t * obj)
Checks if the calibration result is valid.
Parameters
obj Pointer to the ADC bias calibrator object.
Returns
1 if the result is valid, 0 otherwise.
Definition at line 464 of file adc_channel.h.
References adc_bias_calibrator_t::output_valid.
ctl_step_adc_calibrator()
GMP_STATIC_INLINE void ctl_step_adc_calibrator (adc_bias_calibrator_t * obj, ctrl_gt adc_value)
Executes one step of the calibration process. This should be called periodically (e.g., in an ISR).
Parameters
obj Pointer to the ADC bias calibrator object.
adc_value The current ADC value to be included in the calibration.
Definition at line 486 of file adc_channel.h.
References ctl_is_adc_calibrator_cmpt(), ctl_step_biquad_filter(), adc_bias_calibrator_t::enable_filter, adc_bias_calibrator_t::filter, adc_bias_calibrator_t::filter_tick, adc_bias_calibrator_t::output_valid, and adc_bias_calibrator_t::raw.