GMP - CTL: Single Phase SOGI-DC PLL API
Single Phase SOGI-DC PLL API
Digital Power Control Library » Digital Power Components » Single Phase PLL API
A Phase-Locked Loop with DC Offset Rejection for single-phase grid synchronization.
Data Structures
struct ctl_single_phase_dc_pll
Data structure for the Single-Phase SOGI-DC PLL controller.
Functions
void ctl_init_single_phase_dc_pll (ctl_single_phase_dc_pll *spll, parameter_gt loop_kp, parameter_gt loop_ki, parameter_gt k_sogi, parameter_gt k_dc, parameter_gt fc_uq, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase SOGI-DC PLL module.
GMP_STATIC_INLINE void ctl_clear_single_phase_dc_pll (ctl_single_phase_dc_pll *spll)
Clears the internal states of the PLL.
GMP_STATIC_INLINE void ctl_step_single_phase_dc_pll (ctl_single_phase_dc_pll *spll, ctrl_gt ac_input)
Executes one step of the Single-Phase SOGI-DC PLL algorithm.
Detailed Description
A Phase-Locked Loop with DC Offset Rejection for single-phase grid synchronization.
This implementation uses a SOGI-DC block to generate orthogonal signals. The DC rejection loop inside the SOGI-DC block estimates and subtracts the input DC offset, preventing low-frequency oscillations (50/60Hz) in the d-q frame outputs.
Function Documentation
ctl_clear_single_phase_dc_pll()
GMP_STATIC_INLINE void ctl_clear_single_phase_dc_pll (ctl_single_phase_dc_pll * spll)
Clears the internal states of the PLL.
Definition at line 216 of file spll.h.
References ctl_clear_discrete_sogi_dc(), ctl_clear_lowpass_filter(), ctl_clear_pid(), ctl_set_phasor_via_angle(), ctl_vector2_clear(), ctl_single_phase_dc_pll::filter_uq, float2ctrl, ctl_single_phase_dc_pll::frequency, ctl_single_phase_dc_pll::phasor, ctl_single_phase_dc_pll::sogi_dc, ctl_single_phase_dc_pll::spll_ctrl, ctl_single_phase_dc_pll::theta, ctl_single_phase_dc_pll::uab, ctl_single_phase_dc_pll::udq, ctl_single_phase_dc_pll::v_dc_est, and ctl_single_phase_dc_pll::v_mag.
ctl_init_single_phase_dc_pll()
void ctl_init_single_phase_dc_pll (ctl_single_phase_dc_pll * spll, parameter_gt loop_kp, parameter_gt loop_ki, parameter_gt k_sogi, parameter_gt k_dc, parameter_gt fc_uq, parameter_gt fg, parameter_gt fs)
Initializes the Single-Phase SOGI-DC PLL module.
Parameters
[out] spll Pointer to the Single-Phase PLL instance.
[in] loop_kp Proportional gain (Kp) for the PLL's PI loop filter.
[in] loop_ki Integral time constant (s) for the PLL's PI loop filter.
[in] k_sogi SOGI damping gain (typically 1.414).
[in] k_dc DC rejection gain (typically 0.5 - 1.0).
[in] fc_uq Cutoff frequency (Hz) for the q-axis low-pass filter.
[in] fg Nominal grid frequency (e.g., 50 or 60 Hz).
[in] fs Controller execution frequency (Hz).
Definition at line 60 of file ctl_dp_single_phase.c.
References ctl_clear_single_phase_dc_pll(), ctl_init_discrete_sogi_dc(), ctl_init_lp_filter(), ctl_init_pid(), ctl_single_phase_dc_pll::filter_uq, float2ctrl, ctl_single_phase_dc_pll::freq_sf, fs, ctl_single_phase_dc_pll::sogi_dc, and ctl_single_phase_dc_pll::spll_ctrl.
ctl_step_single_phase_dc_pll()
GMP_STATIC_INLINE void ctl_step_single_phase_dc_pll (ctl_single_phase_dc_pll * spll, ctrl_gt ac_input)
Executes one step of the Single-Phase SOGI-DC PLL algorithm.
Parameters
[in,out] spll Pointer to the Single-Phase PLL instance.
[in] ac_input The instantaneous value of the single-phase AC input signal.
Definition at line 238 of file spll.h.
References ctl_ct_park2(), ctl_get_discrete_sogi_dc_alpha(), ctl_get_discrete_sogi_dc_beta(), ctl_get_discrete_sogi_dc_offset(), ctl_get_lowpass_filter_result(), ctl_mul, ctl_set_phasor_via_angle(), ctl_step_discrete_sogi_dc(), ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctrl_mod_1, ctl_single_phase_dc_pll::filter_uq, float2ctrl, ctl_single_phase_dc_pll::freq_error, ctl_single_phase_dc_pll::freq_sf, ctl_single_phase_dc_pll::frequency, phase_alpha, phase_beta, phase_d, phase_q, ctl_single_phase_dc_pll::phasor, ctl_single_phase_dc_pll::sogi_dc, ctl_single_phase_dc_pll::spll_ctrl, ctl_single_phase_dc_pll::theta, ctl_single_phase_dc_pll::uab, ctl_single_phase_dc_pll::udq, ctl_single_phase_dc_pll::v_dc_est, and ctl_single_phase_dc_pll::v_mag.