GMP - CTL: ACM Sliding Mode Observer
ACM Sliding Mode Observer
Motor Control Library » Motor Controller Observer & Estimate
A sensorless module for estimating speed and flux angle of an ACM.
Data Structures
struct ctl_acm_smo_init_t
Initialization parameters for the ACM SMO module.
struct ctl_acm_smo_t
Main structure for the ACM SMO estimator.
Functions
void ctl_init_acm_smo (ctl_acm_smo_t *smo, const ctl_acm_smo_init_t *init)
Initializes the ACM SMO estimator module.
GMP_STATIC_INLINE void ctl_step_acm_smo (ctl_acm_smo_t *smo, ctrl_gt u_alpha, ctrl_gt u_beta, ctrl_gt i_alpha, ctrl_gt i_beta)
Executes one step of the ACM SMO estimation.
Detailed Description
A sensorless module for estimating speed and flux angle of an ACM.
This module provides a sensorless estimator for AC Induction Motors. It uses a full-order SMO to estimate both the stator currents and the rotor flux vector in the stationary alpha-beta frame. A sliding control law, based on the stator current error, generates a correction term. This correction term drives the observer model, and the estimated rotor flux vector is then processed by a Phase-Locked Loop (PLL) to extract the rotor flux angle, electrical speed, and mechanical speed.
The observer is based on the full-order discrete-time model of the ACM:
\[ \frac{d\mathbf{x}}{dt} = \mathbf{A}(\omega_r)\mathbf{x} + \mathbf{B}\mathbf{u} \]
Where the state vector is \(\mathbf{x} = [\mathbf{i}_s, \mathbf{\psi}_r]^T\). A sliding control law Z is applied to the current dynamics based on current error: \(\frac{d\hat{\mathbf{i}}_s}{dt} = ... - \mathbf{Z}\) The PLL then tracks the angle of the estimated rotor flux \(\hat{\mathbf{\psi}}_r\).
Function Documentation
ctl_init_acm_smo()
void ctl_init_acm_smo (ctl_acm_smo_t * smo, const ctl_acm_smo_init_t * init)
Initializes the ACM SMO estimator module.
Parameters
[out] smo Pointer to the SMO structure to initialize.
[in] init Pointer to the structure containing initialization parameters.
Definition at line 118 of file ctl_mc_observer.c.
References ctl_acm_smo_t::c1, ctl_acm_smo_t::c2, ctl_acm_smo_t::c3, ctl_acm_smo_t::c4, ctl_acm_smo_t::c5, ctl_init_lp_filter(), ctl_init_pid_Tmode(), CTL_PARAM_CONST_2PI, ctl_vector2_clear(), ctl_acm_smo_t::encif, ctl_acm_smo_t::filter_spd, float2ctrl, ctl_acm_smo_t::i_s_est, init(), ctl_acm_smo_t::k_slide, ctl_acm_smo_t::omega_e_est, ctl_acm_smo_t::pid_pll, ctl_acm_smo_t::pole_pairs, rotation_ift::position, ctl_acm_smo_t::psi_r_est, ctl_acm_smo_t::spdif, velocity_ift::speed, ctl_acm_smo_t::speed_pu_sf, ctl_acm_smo_t::theta_est, ctl_acm_smo_t::Ts, and ctl_acm_smo_t::z.
ctl_step_acm_smo()
GMP_STATIC_INLINE void ctl_step_acm_smo (ctl_acm_smo_t * smo, ctrl_gt u_alpha, ctrl_gt u_beta, ctrl_gt i_alpha, ctrl_gt i_beta)
Executes one step of the ACM SMO estimation.
Parameters
[out] smo Pointer to the SMO structure.
[in] u_alpha The commanded alpha-axis voltage.
[in] u_beta The commanded beta-axis voltage.
[in] i_alpha The measured alpha-axis current.
[in] i_beta The measured beta-axis current.
Definition at line 123 of file acm.smo.h.
References ctl_acm_smo_t::c1, ctl_acm_smo_t::c2, ctl_acm_smo_t::c3, ctl_acm_smo_t::c4, ctl_acm_smo_t::c5, CTL_CTRL_CONST_2_PI, ctl_mul, ctl_sat, ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctrl_mod_1, rotation_ift::elec_position, ctl_acm_smo_t::encif, ctl_acm_smo_t::filter_spd, ctl_acm_smo_t::i_s_est, ctl_acm_smo_t::k_slide, ctl_acm_smo_t::omega_e_est, ctl_acm_smo_t::pid_pll, ctl_acm_smo_t::pole_pairs, rotation_ift::position, ctl_acm_smo_t::psi_r_est, ctl_acm_smo_t::spdif, velocity_ift::speed, ctl_acm_smo_t::speed_pu_sf, ctl_acm_smo_t::theta_est, ctl_acm_smo_t::Ts, and ctl_acm_smo_t::z.