GMP - CTL: Fuzzy PID Controller
Fuzzy PID Controller
Control Template Library Intrinsic » Advance Components
A self-tuning PID controller using fuzzy logic look-up tables.
Data Structures
struct ctl_fuzzy_pid_t
Data structure for the Fuzzy PID controller.
Functions
void ctl_init_fuzzy_pid (ctl_fuzzy_pid_t *fp, parameter_gt base_kp, parameter_gt base_ti, parameter_gt base_td, ctrl_gt sat_max, ctrl_gt sat_min, parameter_gt e_q_factor, parameter_gt ec_q_factor, ctl_lut2d_t d_kp_lut, ctl_lut2d_t d_ki_lut, ctl_lut2d_t d_kd_lut, parameter_gt fs)
Initializes the Fuzzy PID controller.
GMP_STATIC_INLINE void ctl_clear_fuzzy_pid (ctl_fuzzy_pid_t *fp)
Clears the internal states of the Fuzzy PID controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_fuzzy_pid (ctl_fuzzy_pid_t *fp, ctrl_gt error)
Executes one step of the Fuzzy PID controller.
Detailed Description
A self-tuning PID controller using fuzzy logic look-up tables.
A self-tuning PID controller using fuzzy logic look-up tables. Őâ¸öÄŁżéÔÚ¶ţ˝×µÍÍ¨»·˝ÚŁ¨Ç·×čÄáŇ˛ĘĘÓĂŁ©·ÇłŁĘĘÓĂŁ¬µ±·Ö×ÓÉĎÓĐsĘ±ĎµÍł»áŐńµ´ˇŁ ĐčŇŞµ÷˝Úľ˛˛îżÉŇÔµ÷˝ÚÔöŇćŁ¬ĐčŇŞµ÷˝ÚerrorÔöŇćŁ¬ĐčŇŞµ÷˝ÚĎěÓ¦Ę±ĽäżÉŇÔµ÷˝Úerror diffµÄÔöŇć.
This file implements a fuzzy self-tuning PID controller. The controller uses two inputs: the error (E) and the change in error (EC). These inputs are used to look up tuning adjustments for the PID parameters (delta_Kp, delta_Ki, delta_Kd) from three separate 2D look-up tables (surfaces). These adjustments are then added to the base PID parameters, allowing the controller to adapt to changing system dynamics in real-time.
Function Documentation
ctl_clear_fuzzy_pid()
GMP_STATIC_INLINE void ctl_clear_fuzzy_pid (ctl_fuzzy_pid_t * fp)
Clears the internal states of the Fuzzy PID controller.
Parameters
[out] fp Pointer to the Fuzzy PID instance.
Definition at line 90 of file fuzzy_pid.h.
References ctl_clear_pid(), ctl_fuzzy_pid_t::last_error, and ctl_fuzzy_pid_t::pid.
ctl_init_fuzzy_pid()
void ctl_init_fuzzy_pid (ctl_fuzzy_pid_t * fp, parameter_gt base_kp, parameter_gt base_ti, parameter_gt base_td, ctrl_gt sat_max, ctrl_gt sat_min, parameter_gt e_q_factor, parameter_gt ec_q_factor, ctl_lut2d_t d_kp_lut, ctl_lut2d_t d_ki_lut, ctl_lut2d_t d_kd_lut, parameter_gt fs)
Initializes the Fuzzy PID controller.
Parameters
[out] fp Pointer to the Fuzzy PID instance.
[in] base_kp The base proportional gain.
[in] base_ti The base integral time constant (in seconds).
[in] base_td The base derivative time constant (in seconds).
[in] sat_max Maximum output saturation limit for the PID.
[in] sat_min Minimum output saturation limit for the PID.
[in] e_q_factor Quantization factor to scale the error before LUT lookup.
[in] ec_q_factor Quantization factor to scale the change-in-error before LUT lookup.
[in] d_kp_lut A fully initialized 2D LUT for delta_Kp.
[in] d_ki_lut A fully initialized 2D LUT for delta_Ki.
[in] d_kd_lut A fully initialized 2D LUT for delta_Kd.
[in] fs The sampling frequency (Hz).
Definition at line 20 of file ctl_component_advance.c.
References ctl_fuzzy_pid_t::base_kp, ctl_fuzzy_pid_t::base_td, ctl_fuzzy_pid_t::base_ti, ctl_clear_fuzzy_pid(), ctl_init_pid_Tmode(), ctl_fuzzy_pid_t::d_kd_lut, ctl_fuzzy_pid_t::d_ki_lut, ctl_fuzzy_pid_t::d_kp_lut, ctl_fuzzy_pid_t::e_q_factor, ctl_fuzzy_pid_t::ec_q_factor, ctl_fuzzy_pid_t::fs, fs, ctl_pid_t::integral_max, ctl_pid_t::integral_min, ctl_pid_t::out_max, ctl_pid_t::out_min, and ctl_fuzzy_pid_t::pid.
ctl_step_fuzzy_pid()
GMP_STATIC_INLINE ctrl_gt ctl_step_fuzzy_pid (ctl_fuzzy_pid_t * fp, ctrl_gt error)
Executes one step of the Fuzzy PID controller.
Parameters
[in,out] fp Pointer to the Fuzzy PID instance.
[in] error The current system error, e(n).
Returns
ctrl_gt The calculated control output.
Definition at line 102 of file fuzzy_pid.h.
References ctl_fuzzy_pid_t::base_kp, ctl_fuzzy_pid_t::base_td, ctl_fuzzy_pid_t::base_ti, ctl_mul, ctl_step_interpolate_lut2d(), ctl_step_pid_par(), ctrl2float, ctl_fuzzy_pid_t::d_kd_lut, ctl_fuzzy_pid_t::d_ki_lut, ctl_fuzzy_pid_t::d_kp_lut, ctl_fuzzy_pid_t::e_q_factor, ctl_fuzzy_pid_t::ec_q_factor, float2ctrl, ctl_fuzzy_pid_t::fs, ctl_pid_t::kd, ctl_pid_t::ki, ctl_pid_t::kp, ctl_fuzzy_pid_t::last_error, output, and ctl_fuzzy_pid_t::pid.