GMP - CTL: PMSM HFI Estimator
PMSM HFI Estimator
Motor Control Library » Motor Controller Observer & Estimate
A module for sensorless position and speed estimation using HFI.
Data Structures
struct ctl_hfi_init_t
Initialization parameters for the HFI estimator module.
struct pmsm_hfi_t
Holds the state and parameters for the HFI estimator.
Functions
void ctl_init_pmsm_hfi (pmsm_hfi_t *hfi, const ctl_hfi_init_t *init)
Initializes the HFI estimator module.
void ctl_clear_pmsm_hfi (pmsm_hfi_t *hfi)
Clears the internal states of the HFI estimator.
GMP_STATIC_INLINE ctrl_gt ctl_step_pmsm_hfi (pmsm_hfi_t *hfi, ctrl_gt iq)
Executes one step of the HFI position and speed estimation.
Detailed Description
A module for sensorless position and speed estimation using HFI.
Implements the signal injection, demodulation, filtering, and PLL required to track the rotor angle of a salient PMSM at low speeds.
Implements the signal injection, demodulation, filtering, and PLL required to track the rotor angle of a salient PMSM at low speeds.
This module implements an HFI-based position and speed estimator. It works by injecting a high-frequency voltage signal into the estimated d-axis and then demodulating the resulting q-axis current response. The demodulated signal, which is proportional to the rotor position error, is fed into a Phase-Locked Loop (PLL) to track the rotor's angle and speed. This method is particularly effective for low and zero-speed sensorless control. The core principle relies on the motor's saliency \((Ld != Lq)\). A high-frequency voltage, \(v_{dqh} = [V_h \cos(\omega_h t), 0]^T\), is injected. The resulting high-frequency current response contains information about the rotor position. The demodulated q-axis current is proportional to the position error:
\[ i_{q\_demod} \propto \sin(2(\theta_e - \hat{\theta}_e)) \]
Function Documentation
ctl_clear_pmsm_hfi()
void ctl_clear_pmsm_hfi (pmsm_hfi_t * hfi)
Clears the internal states of the HFI estimator.
Parameters
[out] hfi Pointer to the HFI structure.
ctl_init_pmsm_hfi()
void ctl_init_pmsm_hfi (pmsm_hfi_t * hfi, const ctl_hfi_init_t * init)
Initializes the HFI estimator module.
Parameters
[out] hfi Pointer to the HFI structure to initialize.
[in] init Pointer to the structure containing initialization parameters.
Definition at line 52 of file ctl_mc_observer.c.
References ctl_init_biquad_lpf(), ctl_init_pid_Tmode(), ctl_init_sine_generator(), CTL_PARAM_CONST_PI, ctl_set_pid_limit(), float2ctrl, pmsm_hfi_t::hfi_inj_amp, pmsm_hfi_t::hfi_sincos_gen, init(), pmsm_hfi_t::iq_demodulate, pmsm_hfi_t::iq_lp_filter, pmsm_hfi_t::pid_pll, pmsm_hfi_t::pole_pairs, pmsm_hfi_t::spd_sf, pmsm_hfi_t::theta_error, pmsm_hfi_t::theta_r_est, pmsm_hfi_t::ud_inj, and pmsm_hfi_t::wr_est.
ctl_step_pmsm_hfi()
GMP_STATIC_INLINE ctrl_gt ctl_step_pmsm_hfi (pmsm_hfi_t * hfi, ctrl_gt iq)
Executes one step of the HFI position and speed estimation.
This function performs the core HFI algorithm: it generates the injection signal, demodulates the feedback current, filters the result to get a position error, and uses a PLL to track the angle and speed.
Parameters
[out] hfi Pointer to the HFI structure.
[in] iq The measured q-axis current from the main FOC loop.
Returns
The calculated high-frequency injection voltage (ud_inj) to be added to the d-axis voltage command in the FOC controller.
Definition at line 134 of file pmsm.hfi.h.
References CTL_CTRL_CONST_1_OVER_2PI, ctl_get_sine_generator_cos(), ctl_get_sine_generator_sin(), ctl_mul, ctl_step_biquad_filter(), ctl_step_pid_par(), ctl_step_sine_generator(), ctrl_mod_1, rotation_ift::elec_position, pmsm_hfi_t::encif, pmsm_hfi_t::hfi_inj_amp, pmsm_hfi_t::hfi_sincos_gen, pmsm_hfi_t::iq_demodulate, pmsm_hfi_t::iq_lp_filter, pmsm_hfi_t::pid_pll, pmsm_hfi_t::pole_pairs, rotation_ift::position, pmsm_hfi_t::spd_sf, pmsm_hfi_t::spdif, velocity_ift::speed, pmsm_hfi_t::theta_error, pmsm_hfi_t::theta_r_est, pmsm_hfi_t::ud_inj, and pmsm_hfi_t::wr_est.