GMP - CTL: PMSM MTPA Controller
PMSM MTPA Controller
Motor Control Library » Motor Controller Suite
A module for controlling a PMSM using FOC with an MTPA strategy.
Data Structures
struct pmsm_mtpa_controller_t
Main structure for the PMSM MTPA Controller.
struct pmsm_mtpa_controller_init_t
Initialization parameters for the PMSM MTPA Controller.
Macros
#define MTR_CTRL_CURRENT_MEASUREMENT_PHASES ((3))
Configures the number of phase current sensors used for measurement.
#define MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES ((0))
Configures the number of phase voltage sensors used for measurement.
#define MTR_CTRL_FEEDFORWARD_STRATEGY (1)
Selects the feedforward strategy for the controller.
#define PMSM_CTRL_USING_CURRENT_DISTRIBUTOR
Enables the MTPA current distributor.
Functions
void ctl_init_pmsm_mtpa_bare_controller (pmsm_mtpa_controller_t *ctrl, pmsm_mtpa_controller_init_t *init)
Initializes the PMSM MTPA Controller.
void ctl_attach_pmsm_mtpa_bare_output (pmsm_mtpa_controller_t *ctrl, tri_pwm_ift *pwm_out)
Attaches the controller to a three-phase PWM output interface.
void ctl_attach_idq_distributor (pmsm_mtpa_controller_t *ctrl, ctl_current_distributor_t *distributor)
Attaches an MTPA current distributor module to the controller.
GMP_STATIC_INLINE void ctl_clear_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t *ctrl)
Resets all internal states and integrators of the PID controllers.
GMP_STATIC_INLINE void ctl_step_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t *ctrl)
Executes one step of the PMSM FOC control loop with MTPA.
GMP_STATIC_INLINE void ctl_enable_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t *ctrl)
Enables the entire PMSM controller.
GMP_STATIC_INLINE void ctl_disable_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t *ctrl)
Disables the entire PMSM controller.
GMP_STATIC_INLINE void ctl_enable_pmsm_mtpa_ctrl_output (pmsm_mtpa_controller_t *ctrl)
Enables PWM signal output.
GMP_STATIC_INLINE void ctl_disable_pmsm_mtpa_ctrl_output (pmsm_mtpa_controller_t *ctrl)
Disables PWM signal output.
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_valphabeta_mode (pmsm_mtpa_controller_t *ctrl)
Sets the controller to V_alpha_beta mode.
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_valphabeta (pmsm_mtpa_controller_t *ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target alpha and beta voltage components.
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_voltage_mode (pmsm_mtpa_controller_t *ctrl)
Sets the controller to Vdq (voltage) mode.
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_vdq_ff (pmsm_mtpa_controller_t *ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the d-q voltage feedforward (or reference) values.
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_current_mode (pmsm_mtpa_controller_t *ctrl)
Sets the controller to Idq (current) mode.
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_idq_ff (pmsm_mtpa_controller_t *ctrl, ctrl_gt id, ctrl_gt iq)
Sets the d-q current feedforward (or reference) values.
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_velocity_mode (pmsm_mtpa_controller_t *ctrl)
Sets the controller to velocity mode (with MTPA).
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_speed (pmsm_mtpa_controller_t *ctrl, ctrl_gt spd)
Sets the target speed for the velocity controller.
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_position_mode (pmsm_mtpa_controller_t *ctrl)
Sets the controller to position mode.
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_position (pmsm_mtpa_controller_t *ctrl, int32_t revolution, ctrl_gt pos)
Sets the target position for the position controller.
Detailed Description
A module for controlling a PMSM using FOC with an MTPA strategy.
This module extends the standard FOC controller by adding a current distributor that calculates the optimal Id and Iq references from the speed controller's output to achieve maximum torque per ampere.
This module builds upon the basic FOC controller by incorporating an MTPA current distributor. The speed controller's output (total current magnitude) is optimally distributed into d-axis and q-axis current references to maximize torque for a given current, which is particularly useful for Interior PMSMs (IPMSM).
The controller supports the same operating modes as the base controller but enhances the velocity control mode with the MTPA algorithm.
//tex: // The MTPA condition for an IPMSM is given by: // i_d = \frac{-\psi_{pm} + \sqrt{\psi_{pm}^2 + 4(L_d - L_q)^2 i_q^2}}{2(L_d - L_q)}
Macro Definition Documentation
MTR_CTRL_CURRENT_MEASUREMENT_PHASES
#define MTR_CTRL_CURRENT_MEASUREMENT_PHASES ((3))
Configures the number of phase current sensors used for measurement.
3: Uses 3 phase current sensors (default).
2: Uses 2 phase current sensors.
Definition at line 66 of file pmsm_ctrl_mtpa.h.
MTR_CTRL_FEEDFORWARD_STRATEGY
#define MTR_CTRL_FEEDFORWARD_STRATEGY (1)
Selects the feedforward strategy for the controller.
1: Decoupled mode. Feedforward terms are calculated automatically (default).
0: User mode. Feedforward values must be specified manually by the user.
Definition at line 87 of file pmsm_ctrl_mtpa.h.
MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES
#define MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES ((0))
Configures the number of phase voltage sensors used for measurement.
3: Uses 3 phase voltage sensors.
2: Uses 2 phase voltage sensors.
0: Disables voltage measurement (default).
Definition at line 77 of file pmsm_ctrl_mtpa.h.
PMSM_CTRL_USING_CURRENT_DISTRIBUTOR
#define PMSM_CTRL_USING_CURRENT_DISTRIBUTOR
Enables the MTPA current distributor.
When defined, the output of the speed controller is interpreted as a total current magnitude and is split into Id and Iq components by the MTPA algorithm.
Definition at line 96 of file pmsm_ctrl_mtpa.h.
Function Documentation
ctl_attach_idq_distributor()
void ctl_attach_idq_distributor (pmsm_mtpa_controller_t * ctrl, ctl_current_distributor_t * distributor)
Attaches an MTPA current distributor module to the controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] distributor Pointer to the initialized current distributor module.
ctl_attach_pmsm_mtpa_bare_output()
void ctl_attach_pmsm_mtpa_bare_output (pmsm_mtpa_controller_t * ctrl, tri_pwm_ift * pwm_out)
Attaches the controller to a three-phase PWM output interface.
Parameters
[out] ctrl Pointer to the controller structure.
[in] pwm_out Pointer to the PWM interface to attach.
Definition at line 105 of file ctl_mc_pmsm_ctrl_mtpa.c.
References pmsm_mtpa_controller_t::pwm_out.
ctl_clear_pmsm_mtpa_ctrl()
GMP_STATIC_INLINE void ctl_clear_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t * ctrl)
Resets all internal states and integrators of the PID controllers.
Parameters
[out] ctrl Pointer to the controller structure to clear.
Definition at line 226 of file pmsm_ctrl_mtpa.h.
References ctl_clear_discrete_pid(), ctl_clear_pid(), ctl_clear_tracking_continuous_pid(), ctl_clear_tracking_pid(), pmsm_mtpa_controller_t::current_ctrl, phase_d, phase_q, and pmsm_mtpa_controller_t::spd_ctrl.
ctl_disable_pmsm_mtpa_ctrl()
GMP_STATIC_INLINE void ctl_disable_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t * ctrl)
Disables the entire PMSM controller.
Definition at line 401 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_controller.
ctl_disable_pmsm_mtpa_ctrl_output()
GMP_STATIC_INLINE void ctl_disable_pmsm_mtpa_ctrl_output (pmsm_mtpa_controller_t * ctrl)
Disables PWM signal output.
Definition at line 413 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_output.
ctl_enable_pmsm_mtpa_ctrl()
GMP_STATIC_INLINE void ctl_enable_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t * ctrl)
Enables the entire PMSM controller.
Definition at line 395 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_controller.
ctl_enable_pmsm_mtpa_ctrl_output()
GMP_STATIC_INLINE void ctl_enable_pmsm_mtpa_ctrl_output (pmsm_mtpa_controller_t * ctrl)
Enables PWM signal output.
Definition at line 407 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_output.
ctl_init_pmsm_mtpa_bare_controller()
void ctl_init_pmsm_mtpa_bare_controller (pmsm_mtpa_controller_t * ctrl, pmsm_mtpa_controller_init_t * init)
Initializes the PMSM MTPA Controller.
Parameters
[out] ctrl Pointer to the controller structure to initialize.
[in] init Pointer to the structure containing initialization parameters.
Definition at line 10 of file ctl_mc_pmsm_ctrl_mtpa.c.
References ctl_disable_pmsm_mtpa_ctrl(), ctl_init_discrete_pid(), ctl_init_pid_Tmode(), ctl_init_tracking_continuous_pid(), ctl_init_tracking_pid(), ctl_pmsm_mtpa_ctrl_valphabeta_mode(), ctl_set_discrete_pid_limit(), ctl_set_pid_limit(), ctl_vector2_clear(), ctl_vector3_clear(), pmsm_mtpa_controller_t::current_ctrl, pmsm_mtpa_controller_t::iab0, pmsm_mtpa_controller_t::idq0, pmsm_mtpa_controller_t::idq_ff, pmsm_mtpa_controller_t::idq_set, init(), phase_d, phase_q, pmsm_mtpa_controller_t::pos_set, pmsm_mtpa_controller_t::revolution_set, pmsm_mtpa_controller_t::spd_ctrl, pmsm_mtpa_controller_t::speed_set, pmsm_mtpa_controller_t::uab0, pmsm_mtpa_controller_t::udq0, pmsm_mtpa_controller_t::vab0_set, pmsm_mtpa_controller_t::vdq_ff, and pmsm_mtpa_controller_t::vdq_set.
ctl_pmsm_mtpa_ctrl_current_mode()
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_current_mode (pmsm_mtpa_controller_t * ctrl)
Sets the controller to Idq (current) mode.
Definition at line 454 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, and pmsm_mtpa_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_mtpa_ctrl_position_mode()
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_position_mode (pmsm_mtpa_controller_t * ctrl)
Sets the controller to position mode.
Definition at line 487 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, and pmsm_mtpa_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_mtpa_ctrl_valphabeta_mode()
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_valphabeta_mode (pmsm_mtpa_controller_t * ctrl)
Sets the controller to V_alpha_beta mode.
Definition at line 419 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, and pmsm_mtpa_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_mtpa_ctrl_velocity_mode()
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_velocity_mode (pmsm_mtpa_controller_t * ctrl)
Sets the controller to velocity mode (with MTPA).
Definition at line 471 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, and pmsm_mtpa_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_mtpa_ctrl_voltage_mode()
GMP_STATIC_INLINE void ctl_pmsm_mtpa_ctrl_voltage_mode (pmsm_mtpa_controller_t * ctrl)
Sets the controller to Vdq (voltage) mode.
Definition at line 437 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, and pmsm_mtpa_controller_t::flag_enable_velocity_ctrl.
ctl_set_pmsm_mtpa_ctrl_idq_ff()
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_idq_ff (pmsm_mtpa_controller_t * ctrl, ctrl_gt id, ctrl_gt iq)
Sets the d-q current feedforward (or reference) values.
Definition at line 464 of file pmsm_ctrl_mtpa.h.
References vector2_gt::dat, pmsm_mtpa_controller_t::idq_ff, phase_d, and phase_q.
ctl_set_pmsm_mtpa_ctrl_position()
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_position (pmsm_mtpa_controller_t * ctrl, int32_t revolution, ctrl_gt pos)
Sets the target position for the position controller.
Definition at line 497 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::pos_set, and pmsm_mtpa_controller_t::revolution_set.
ctl_set_pmsm_mtpa_ctrl_speed()
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_speed (pmsm_mtpa_controller_t * ctrl, ctrl_gt spd)
Sets the target speed for the velocity controller.
Definition at line 481 of file pmsm_ctrl_mtpa.h.
References pmsm_mtpa_controller_t::speed_set.
ctl_set_pmsm_mtpa_ctrl_valphabeta()
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_valphabeta (pmsm_mtpa_controller_t * ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target alpha and beta voltage components.
Definition at line 429 of file pmsm_ctrl_mtpa.h.
References vector3_gt::dat, phase_0, phase_A, phase_B, and pmsm_mtpa_controller_t::vab0_set.
ctl_set_pmsm_mtpa_ctrl_vdq_ff()
GMP_STATIC_INLINE void ctl_set_pmsm_mtpa_ctrl_vdq_ff (pmsm_mtpa_controller_t * ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the d-q voltage feedforward (or reference) values.
Definition at line 447 of file pmsm_ctrl_mtpa.h.
References vector2_gt::dat, phase_d, phase_q, and pmsm_mtpa_controller_t::vdq_ff.
ctl_step_pmsm_mtpa_ctrl()
GMP_STATIC_INLINE void ctl_step_pmsm_mtpa_ctrl (pmsm_mtpa_controller_t * ctrl)
Executes one step of the PMSM FOC control loop with MTPA.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 243 of file pmsm_ctrl_mtpa.h.
References ctl_clear_pmsm_mtpa_ctrl(), ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_ipark(), ctl_ct_park(), ctl_ct_svpwm_calc(), ctl_get_distributor_id_ref(), ctl_get_distributor_iq_ref(), ctl_get_mtr_elec_theta(), ctl_get_mtr_velocity(), ctl_mul, ctl_set_phasor_via_angle(), ctl_set_pid_limit(), ctl_sqrt, ctl_step_current_distributor(), ctl_step_discrete_pid(), ctl_step_pid_ser(), ctl_step_tracking_continuous_pid(), ctl_step_tracking_pid(), ctl_vector3_clear(), pmsm_mtpa_controller_t::current_ctrl, vector2_gt::dat, vector3_gt::dat, pmsm_mtpa_controller_t::distributor, pmsm_mtpa_controller_t::flag_enable_controller, pmsm_mtpa_controller_t::flag_enable_current_ctrl, pmsm_mtpa_controller_t::flag_enable_modulation, pmsm_mtpa_controller_t::flag_enable_output, pmsm_mtpa_controller_t::flag_enable_position_ctrl, pmsm_mtpa_controller_t::flag_enable_velocity_ctrl, float2ctrl, pmsm_mtpa_controller_t::iab0, mtr_ift::iabc, pmsm_mtpa_controller_t::idq0, pmsm_mtpa_controller_t::idq_ff, pmsm_mtpa_controller_t::idq_set, pmsm_mtpa_controller_t::im_set, pmsm_mtpa_controller_t::isr_tick, pmsm_mtpa_controller_t::mtr_interface, phase_0, phase_A, phase_B, phase_C, phase_d, phase_q, pmsm_mtpa_controller_t::pwm_out, pmsm_mtpa_controller_t::spd_ctrl, pmsm_mtpa_controller_t::speed_set, pmsm_mtpa_controller_t::uab0, mtr_ift::uabc, pmsm_mtpa_controller_t::udq0, pmsm_mtpa_controller_t::vab0_set, tri_pwm_ift::value, pmsm_mtpa_controller_t::vdq_ff, and pmsm_mtpa_controller_t::vdq_set.