GMP - CTL: 3D Vector Math
3D Vector Math
Control Math Library » Linear Algebra
A collection of types and functions for 3D vector arithmetic.
Data Structures
struct vector3_gt
Data structure for representing a 3D vector.
Functions
GMP_STATIC_INLINE void ctl_vector3_clear (ctl_vector3_t *vec)
Clears a 3D vector, setting its components to zero.
GMP_STATIC_INLINE void ctl_vector3_set (ctl_vector3_t *vec, ctrl_gt v)
Sets all components of a 3D vector to a single scalar value.
GMP_STATIC_INLINE void ctl_vector3_copy (ctl_vector3_t *dup, ctl_vector3_t *vec)
Copies the contents of one 3D vector to another.
GMP_STATIC_INLINE void ctl_vector3_add (ctl_vector3_t *result, ctl_vector3_t *a, ctl_vector3_t *b)
Adds two 3D vectors.
GMP_STATIC_INLINE void ctl_vector3_sub (ctl_vector3_t *result, ctl_vector3_t *a, ctl_vector3_t *b)
Subtracts one 3D vector from another.
GMP_STATIC_INLINE void ctl_vector3_scale (ctl_vector3_t *result, ctl_vector3_t vec, ctrl_gt scalar)
Multiplies a 3D vector by a scalar value.
GMP_STATIC_INLINE ctrl_gt ctl_vector3_dot (ctl_vector3_t a, ctl_vector3_t b)
Calculates the dot product of two 3D vectors.
GMP_STATIC_INLINE void ctl_vector3_cross (ctl_vector3_t *result, ctl_vector3_t *a, ctl_vector3_t *b)
Calculates the cross product of two 3D vectors.
GMP_STATIC_INLINE ctrl_gt ctl_vector3_mag_sq (ctl_vector3_t *vec)
Calculates the squared magnitude (length) of a 3D vector. This is computationally cheaper than ctl_vector3_mag as it avoids a square root.
GMP_STATIC_INLINE ctrl_gt ctl_vector3_mag (ctl_vector3_t *vec)
Calculates the magnitude (length) of a 3D vector.
GMP_STATIC_INLINE void ctl_vector3_normalize (ctl_vector3_t *result, ctl_vector3_t *vec)
Normalizes a 3D vector to produce a unit vector (a vector with length 1).
Detailed Description
A collection of types and functions for 3D vector arithmetic.
Function Documentation
ctl_vector3_add()
GMP_STATIC_INLINE void ctl_vector3_add (ctl_vector3_t * result, ctl_vector3_t * a, ctl_vector3_t * b)
Adds two 3D vectors.
Parameters
a The first vector.
b The second vector.
[out] result The resulting vector (a + b).
Definition at line 84 of file vector3.h.
ctl_vector3_clear()
GMP_STATIC_INLINE void ctl_vector3_clear (ctl_vector3_t * vec)
Clears a 3D vector, setting its components to zero.
Parameters
[out] vec Pointer to the vector to be cleared.
Definition at line 47 of file vector3.h.
References vector3_gt::dat.
ctl_vector3_copy()
GMP_STATIC_INLINE void ctl_vector3_copy (ctl_vector3_t * dup, ctl_vector3_t * vec)
Copies the contents of one 3D vector to another.
Parameters
[out] dup Pointer to the destination vector.
[in] vec Pointer to the source vector.
Definition at line 71 of file vector3.h.
ctl_vector3_cross()
GMP_STATIC_INLINE void ctl_vector3_cross (ctl_vector3_t * result, ctl_vector3_t * a, ctl_vector3_t * b)
Calculates the cross product of two 3D vectors.
\[a \times b = \begin{pmatrix} a_y b_z - a_z b_y \\ a_z b_x - a_x b_z \\ a_x b_y - a_y b_x \end{pmatrix} \]
Parameters
a The first vector.
b The second vector.
result The resulting vector from the cross product.
Definition at line 140 of file vector3.h.
References ctl_mul.
ctl_vector3_dot()
GMP_STATIC_INLINE ctrl_gt ctl_vector3_dot (ctl_vector3_t a, ctl_vector3_t b)
Calculates the dot product of two 3D vectors.
\[a \cdot b = a_x b_x + a_y b_y + a_z b_z \]
Parameters
a The first vector.
b The second vector.
Returns
The dot product.
Definition at line 126 of file vector3.h.
References ctl_mul.
ctl_vector3_mag()
GMP_STATIC_INLINE ctrl_gt ctl_vector3_mag (ctl_vector3_t * vec)
Calculates the magnitude (length) of a 3D vector.
Parameters
vec The input vector.
Returns
The magnitude of the vector.
Definition at line 163 of file vector3.h.
References ctl_sqrt, and ctl_vector3_mag_sq().
ctl_vector3_mag_sq()
GMP_STATIC_INLINE ctrl_gt ctl_vector3_mag_sq (ctl_vector3_t * vec)
Calculates the squared magnitude (length) of a 3D vector. This is computationally cheaper than ctl_vector3_mag as it avoids a square root.
Parameters
vec The input vector.
Returns
The squared magnitude of the vector.
Definition at line 153 of file vector3.h.
References ctl_mul.
ctl_vector3_normalize()
GMP_STATIC_INLINE void ctl_vector3_normalize (ctl_vector3_t * result, ctl_vector3_t * vec)
Normalizes a 3D vector to produce a unit vector (a vector with length 1).
Parameters
vec The vector to be normalized.
[out] result The normalized (unit) vector. Returns a zero vector if the magnitude is zero.
Definition at line 173 of file vector3.h.
References ctl_div, ctl_vector3_clear(), ctl_vector3_mag(), and float2ctrl.
ctl_vector3_scale()
GMP_STATIC_INLINE void ctl_vector3_scale (ctl_vector3_t * result, ctl_vector3_t vec, ctrl_gt scalar)
Multiplies a 3D vector by a scalar value.
Parameters
vec The vector to be scaled.
scalar The scalar value.
[out] result The resulting scaled vector.
Definition at line 110 of file vector3.h.
References ctl_mul.
ctl_vector3_set()
GMP_STATIC_INLINE void ctl_vector3_set (ctl_vector3_t * vec, ctrl_gt v)
Sets all components of a 3D vector to a single scalar value.
Parameters
[out] vec Pointer to the vector to be set.
[in] v The scalar value to set all components to.
Definition at line 59 of file vector3.h.
ctl_vector3_sub()
GMP_STATIC_INLINE void ctl_vector3_sub (ctl_vector3_t * result, ctl_vector3_t * a, ctl_vector3_t * b)
Subtracts one 3D vector from another.
Parameters
a The minuend vector.
b The subtrahend vector.
[out] result The resulting vector (a - b).
Definition at line 97 of file vector3.h.