GMP - CTL: Tracking Continuous PID Controller
Tracking Continuous PID Controller
Control Template Library Intrinsic » Continuous Components
A composite PID controller for smooth setpoint tracking using a continuous-form PID.
Data Structures
struct ctl_tracking_continuous_pid_t
Data structure for the tracking continuous PID controller.
Functions
void ctl_init_tracking_continuous_pid (ctl_tracking_continuous_pid_t *tp, ctrl_gt kp, ctrl_gt ki, ctrl_gt kd, ctrl_gt sat_max, ctrl_gt sat_min, ctrl_gt slope_max, ctrl_gt slope_min, uint32_t division, parameter_gt fs)
Initializes the tracking continuous PID controller.
GMP_STATIC_INLINE void ctl_clear_tracking_continuous_pid (ctl_tracking_continuous_pid_t *tp)
Clears the internal states of the tracking continuous PID controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_tracking_continuous_pid (ctl_tracking_continuous_pid_t *tp, ctrl_gt target, ctrl_gt fbk)
Executes one step of the tracking continuous PID controller.
GMP_STATIC_INLINE ctrl_gt ctl_get_tracking_continuous_pid_output (ctl_tracking_continuous_pid_t *tp)
Gets the current output of the tracking PID controller.
Detailed Description
A composite PID controller for smooth setpoint tracking using a continuous-form PID.
This file implements a tracking PID controller based on the continuous-form PID implementation. It combines three intrinsic modules:
A Frequency Divider: To execute the controller at a lower rate.
A Slope Limiter: To generate a smooth trajectory (ramp) for the setpoint.
A Continuous-Form PID: To calculate the control output. This is ideal for setpoint tracking where smooth transitions are needed.
Function Documentation
ctl_clear_tracking_continuous_pid()
GMP_STATIC_INLINE void ctl_clear_tracking_continuous_pid (ctl_tracking_continuous_pid_t * tp)
Clears the internal states of the tracking continuous PID controller.
Parameters
[out] tp Pointer to the tracking PID instance.
Definition at line 81 of file track_pid.h.
References ctl_clear_divider(), ctl_clear_pid(), ctl_clear_slope_limiter(), ctl_tracking_continuous_pid_t::div, ctl_tracking_continuous_pid_t::pid, and ctl_tracking_continuous_pid_t::traj.
ctl_get_tracking_continuous_pid_output()
GMP_STATIC_INLINE ctrl_gt ctl_get_tracking_continuous_pid_output (ctl_tracking_continuous_pid_t * tp)
Gets the current output of the tracking PID controller.
Parameters
[in] tp Pointer to the tracking PID instance.
Returns
ctrl_gt The last calculated output value.
Definition at line 121 of file track_pid.h.
References ctl_pid_t::out, and ctl_tracking_continuous_pid_t::pid.
ctl_init_tracking_continuous_pid()
void ctl_init_tracking_continuous_pid (ctl_tracking_continuous_pid_t * tp, ctrl_gt kp, ctrl_gt ki, ctrl_gt kd, ctrl_gt sat_max, ctrl_gt sat_min, ctrl_gt slope_max, ctrl_gt slope_min, uint32_t division, parameter_gt fs)
Initializes the tracking continuous PID controller.
Parameters
[out] tp Pointer to the tracking PID instance.
[in] kp Proportional gain of the PID.
[in] Ti Integral time constant of the PID (in seconds).
[in] Td Derivative time constant of the PID (in seconds).
[in] sat_max Maximum output saturation limit for the PID.
[in] sat_min Minimum output saturation limit for the PID.
[in] slope_max Maximum positive rate of change for the setpoint (units/sec).
[in] slope_min Maximum negative rate of change for the setpoint (-units/sec).
[in] division The factor by which to divide the execution frequency.
[in] fs The main sampling frequency (Hz) at which this module's step function is called.
Definition at line 176 of file ctl_component_continuous.c.
References ctl_init_divider(), ctl_init_pid(), ctl_init_slope_limiter(), ctl_set_pid_limit(), ctl_tracking_continuous_pid_t::div, fs, ctl_tracking_continuous_pid_t::pid, and ctl_tracking_continuous_pid_t::traj.
ctl_step_tracking_continuous_pid()
GMP_STATIC_INLINE ctrl_gt ctl_step_tracking_continuous_pid (ctl_tracking_continuous_pid_t * tp, ctrl_gt target, ctrl_gt fbk)
Executes one step of the tracking continuous PID controller.
This function should be called at the main system frequency (fs). It uses an internal divider to decide when to execute the core control logic. When the divider triggers, it updates the setpoint trajectory and calculates a new PID output. On other steps, it holds the last calculated PID output.
Parameters
[in,out] tp Pointer to the tracking PID instance.
[in] target The ultimate target value for the setpoint.
[in] fbk The feedback value from the system.
Returns
ctrl_gt The latest control output.
Definition at line 99 of file track_pid.h.
References ctl_step_divider(), ctl_step_pid_ser(), ctl_step_slope_limiter(), ctl_tracking_continuous_pid_t::div, ctl_pid_t::out, ctl_slope_limiter_t::out, ctl_tracking_continuous_pid_t::pid, and ctl_tracking_continuous_pid_t::traj.