GMP - CTL: Basic Flux Weakening Controller
Basic Flux Weakening Controller
Flux weakening controller.
Data Structures
struct ctl_fw_ctrl_t
Flux Weakening Controller Structure.
Functions
void ctl_init_fw_ctrl (ctl_fw_ctrl_t *fw, ctrl_gt kp, ctrl_gt ki, ctrl_gt margin, parameter_gt fs)
Initializes the Flux Weakening Controller.
GMP_STATIC_INLINE void ctl_step_fw_ctrl (ctl_fw_ctrl_t *fw, ctl_vector2_t *vdq_out, ctrl_gt udc, ctrl_gt i_max)
Executes one step of Flux Weakening Control.
Detailed Description
Flux weakening controller.
Function Documentation
ctl_init_fw_ctrl()
void ctl_init_fw_ctrl (ctl_fw_ctrl_t * fw, ctrl_gt kp, ctrl_gt ki, ctrl_gt margin, parameter_gt fs)
Initializes the Flux Weakening Controller.
Parameters
[out] fw Pointer to the FW controller instance.
[in] kp Voltage loop Kp.
[in] ki Voltage loop Ki.
[in] margin Voltage reference margin (e.g., 0.95).
[in] fs Sampling frequency.
Definition at line 59 of file flux_weakening.h.
References ctl_init_pid(), ctl_set_pid_int_limit(), ctl_set_pid_limit(), ctl_vector2_clear(), ctl_fw_ctrl_t::flag_in_fw, fs, ctl_fw_ctrl_t::i_smax, ctl_fw_ctrl_t::id_ref_fw, ctl_fw_ctrl_t::iq_max_dynamic, ctl_fw_ctrl_t::v_ref_margin, ctl_fw_ctrl_t::vdq_curr, and ctl_fw_ctrl_t::volt_ctrl.
ctl_step_fw_ctrl()
GMP_STATIC_INLINE void ctl_step_fw_ctrl (ctl_fw_ctrl_t * fw, ctl_vector2_t * vdq_out, ctrl_gt udc, ctrl_gt i_max)
Executes one step of Flux Weakening Control.
Should be called BEFORE the Speed Loop and Current Loop.
Parameters
[in,out] fw Pointer to the FW controller.
[in] vdq_out The voltage output from the previous current loop cycle.
[in] udc The current DC bus voltage.
[in] i_max The maximum current capability (Inverter/Motor limit).
Definition at line 92 of file flux_weakening.h.
References ctl_mul, ctl_set_pid_int_limit(), ctl_set_pid_limit(), ctl_sqrt, ctl_step_pid_par(), ctl_vector2_copy(), ctl_fw_ctrl_t::flag_in_fw, float2ctrl, ctl_fw_ctrl_t::i_smax, ctl_fw_ctrl_t::id_ref_fw, ctl_fw_ctrl_t::iq_max_dynamic, phase_d, phase_q, udc, v_limit, ctl_fw_ctrl_t::v_ref_margin, ctl_fw_ctrl_t::vdq_curr, and ctl_fw_ctrl_t::volt_ctrl.