GMP - CTL: Three-Phase GFL Inverter Topology API (Header)
Three-Phase GFL Inverter Topology API (Header)
Digital Power Control Library
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Data Structures
struct inv_dq_hcm_t
DQ Harmonic Compensation Module (HCM).
struct inv_dq_hcm_init_t
Initialization parameters for the DQ Harmonic Compensation Module.
struct inv_neg_ctrl_t
Main data structure for the three-phase negative sequence controller.
struct inv_neg_ctrl_init_t
Initialization structure for auto-tuning the negative sequence controller.
struct gfl_inv_ctrl_t
Main data structure for the three-phase inverter controller.
struct gfl_inv_ctrl_init_t
Main data structure for the three-phase inverter controller.
struct gfl_pq_ctrl_t
P-Q Grid-Following Power Controller.
Macros
#define GFL_CURRENT_SAMPLE_PHASE_MODE (3)
Configures the current sampling method.
#define GFL_VOLTAGE_SAMPLE_PHASE_MODE (3)
Configures the voltage sampling method.
#define GFL_CAPACITOR_CURRENT_CALCULATE_MODE (3)
Configures the voltage sampling method.
Functions
void ctl_auto_tuning_gfl_inv (gfl_inv_ctrl_init_t *init)
Auto-tuning GFL inverter parameters.
void ctl_update_gfl_inv_coeff (gfl_inv_ctrl_t *inv, gfl_inv_ctrl_init_t *init)
update GFL inverter controller parameters by init structure.
void ctl_init_gfl_inv (gfl_inv_ctrl_t *inv, gfl_inv_ctrl_init_t *init)
Init GFL inverter parameters.
void ctl_attach_gfl_inv (gfl_inv_ctrl_t *inv, adc_ift *adc_idc, adc_ift *adc_udc, tri_adc_ift *adc_iabc, tri_adc_ift *adc_vabc)
Attach GFL inverter with input/output interface.
GMP_STATIC_INLINE void ctl_clear_dq_hcm (inv_dq_hcm_t *hcm)
Clears internal states of all resonators.
void ctl_init_dq_hcm (inv_dq_hcm_t *hcm, const inv_dq_hcm_init_t *init)
Initializes the HCM module.
void ctl_update_dq_hcm_freq (inv_dq_hcm_t *hcm, const inv_dq_hcm_init_t *init)
Updates the resonant parameters.
GMP_STATIC_INLINE void ctl_step_dq_hcm (inv_dq_hcm_t *hcm)
Executes one step of the Harmonic Compensation.
GMP_STATIC_INLINE void ctl_attach_dq_hcm (inv_dq_hcm_t *hcm, ctl_vector2_t *dq_meas, ctl_vector2_t *dq_set)
Attaches the HCM to data sources.
GMP_STATIC_INLINE void ctl_clear_neg_inv (inv_neg_ctrl_t *neg)
Clears all internal states of the negative sequence controller.
void ctl_auto_tuning_neg_inv (inv_neg_ctrl_init_t *neg_init, const gfl_inv_ctrl_init_t *gfl_init)
Auto-tuning Negative Sequence Controller parameters based on GFL system parameters.
void ctl_update_neg_inv_coeff (inv_neg_ctrl_t *neg, const inv_neg_ctrl_init_t *neg_init)
Update Negative Sequence Controller coefficients.
void ctl_init_neg_inv (inv_neg_ctrl_t *neg, const inv_neg_ctrl_init_t *neg_init)
Initialize Negative Sequence Controller.
GMP_STATIC_INLINE void ctl_step_neg_inv_ctrl (inv_neg_ctrl_t *neg)
Executes one step of the Negative Sequence Controller.
GMP_STATIC_INLINE void ctl_attach_neg_inv_to_gfl (inv_neg_ctrl_t *neg, gfl_inv_ctrl_t *gfl)
Attach the negative controller to a Grid-Following Inverter controller.
GMP_STATIC_INLINE void ctl_attach_neg_inv (inv_neg_ctrl_t *neg, ctl_vector2_t *iab, ctl_vector2_t *vab, ctl_vector2_t *phasor)
Attach external pointers to the negative controller.
GMP_STATIC_INLINE void ctl_enable_neg_current_inv (inv_neg_ctrl_t *neg)
GMP_STATIC_INLINE void ctl_enable_neg_voltage_inv (inv_neg_ctrl_t *neg)
GMP_STATIC_INLINE void ctl_disable_neg_inv (inv_neg_ctrl_t *neg)
GMP_STATIC_INLINE void ctl_clear_gfl_inv (gfl_inv_ctrl_t *inv)
Clear GFL inverter parameters, without PLL.
GMP_STATIC_INLINE void ctl_clear_gfl_inv_with_PLL (gfl_inv_ctrl_t *inv)
Auto-tuning GFL inverter parameters.
GMP_STATIC_INLINE void ctl_step_gfl_inv_ctrl (gfl_inv_ctrl_t *gfl)
Executes one step of the GFL three-phase inverter control algorithm.
GMP_STATIC_INLINE void ctl_set_gfl_inv_openloop_mode (gfl_inv_ctrl_t *inv)
Sets the controller to open-loop mode.
GMP_STATIC_INLINE void ctl_set_gfl_inv_voltage_openloop (gfl_inv_ctrl_t *inv, ctrl_gt vd, ctrl_gt vq)
Sets the open-loop output voltage in the d-q frame.
GMP_STATIC_INLINE void ctl_set_gfl_inv_current_mode (gfl_inv_ctrl_t *inv)
Sets the controller to current closed-loop mode.
GMP_STATIC_INLINE void ctl_set_gfl_inv_current (gfl_inv_ctrl_t *inv, ctrl_gt id, ctrl_gt iq)
Sets the target current in the d-q frame.
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_Pout (gfl_inv_ctrl_t *inv)
Calculates the output active power (P).
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_Qout (gfl_inv_ctrl_t *inv)
Calculates the output reactive power (Q).
GMP_STATIC_INLINE void ctl_set_gfl_inv_freerun (gfl_inv_ctrl_t *inv)
Sets the angle source to the internal ramp generator (freerun).
GMP_STATIC_INLINE void ctl_set_gfl_inv_grid_connect (gfl_inv_ctrl_t *inv)
Sets the angle source to the PLL (grid-tied).
GMP_STATIC_INLINE void ctl_enable_gfl_inv_decouple (gfl_inv_ctrl_t *inv)
Enable inverter decoupling.
GMP_STATIC_INLINE void ctl_enable_gfl_inv_active_damp (gfl_inv_ctrl_t *inv)
Enable inverter active damping.
GMP_STATIC_INLINE void ctl_enable_gfl_inv_lead_compensator (gfl_inv_ctrl_t *inv)
Enable inverter lead compensator.
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_pll_error (gfl_inv_ctrl_t *inv)
Get PLL error.
GMP_STATIC_INLINE void ctl_enable_gfl_inv_pll (gfl_inv_ctrl_t *inv)
Enable PLL module.
GMP_STATIC_INLINE void ctl_disable_gfl_inv_pll (gfl_inv_ctrl_t *inv)
Disable PLL module.
GMP_STATIC_INLINE fast_gt ctl_is_gfl_grid_connected (gfl_inv_ctrl_t *inv)
GFL preparing to connect to grid.
GMP_STATIC_INLINE void ctl_enable_gfl_inv (gfl_inv_ctrl_t *inv)
Enable GFL controller.
GMP_STATIC_INLINE void ctl_disable_gfl_inv (gfl_inv_ctrl_t *inv)
Disable GFL controller.
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_pll_theta (gfl_inv_ctrl_t *inv)
GMP_STATIC_INLINE void ctl_get_gfl_inv_pll_phasor (gfl_inv_ctrl_t *inv, vector2_gt *phasor)
void ctl_init_gfl_pq (gfl_pq_ctrl_t *pq, parameter_gt p_kp, parameter_gt p_ki, parameter_gt q_kp, parameter_gt q_ki, parameter_gt i_out_max, parameter_gt fs)
Initialize the PQ controller with parameters.
GMP_STATIC_INLINE void ctl_clear_gfl_pq (gfl_pq_ctrl_t *pq)
Reset the PQ controller (clear integrators).
void ctl_attach_gfl_pq (gfl_pq_ctrl_t *pq, ctl_vector2_t *vdq, ctl_vector2_t *idq)
Attach feedback pointers to the PQ controller.
void ctl_attach_gfl_pq_to_core (gfl_pq_ctrl_t *pq, gfl_inv_ctrl_t *core)
Attach feedback pointers to the PQ controller.
GMP_STATIC_INLINE void ctl_step_gfl_pq (gfl_pq_ctrl_t *pq)
Execute one step of the PQ control loop.
GMP_STATIC_INLINE void ctl_enable_gfl_pq_ctrl (gfl_pq_ctrl_t *pq)
Enable PQ controller.
GMP_STATIC_INLINE void ctl_disable_gfl_pq_ctrl (gfl_pq_ctrl_t *pq)
Disable PQ controller.
Detailed Description
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Macro Definition Documentation
GFL_CAPACITOR_CURRENT_CALCULATE_MODE
#define GFL_CAPACITOR_CURRENT_CALCULATE_MODE (3)
Configures the voltage sampling method.
4: TODO calculate Ic based on Uuvw and Iabc
3: Capacitor Voltage is measured, calculate Ic = C d/dt(Vc)
2: Sample inverter current Iuvw and grid current Iabc, calculate Ic = Iuvw - Iabc.
1: Sample Capacitor current directly.
Definition at line 68 of file three_phase_GFL.h.
GFL_CURRENT_SAMPLE_PHASE_MODE
#define GFL_CURRENT_SAMPLE_PHASE_MODE (3)
Configures the current sampling method.
3: Sample all three phase currents (Ia, Ib, Ic).
2: Sample two phase currents (Ia, Ib), and calculate the third.
Definition at line 47 of file three_phase_GFL.h.
GFL_VOLTAGE_SAMPLE_PHASE_MODE
#define GFL_VOLTAGE_SAMPLE_PHASE_MODE (3)
Configures the voltage sampling method.
3: Sample all three phase voltages (Va, Vb, Vc).
2: Sample two phase voltages (Va, Vb), and calculate the third.
1: Sample two line-to-line voltages (Vab, Vbc).
Definition at line 57 of file three_phase_GFL.h.
Function Documentation
ctl_attach_dq_hcm()
GMP_STATIC_INLINE void ctl_attach_dq_hcm (inv_dq_hcm_t * hcm, ctl_vector2_t * dq_meas, ctl_vector2_t * dq_set)
Attaches the HCM to data sources.
Parameters
hcm Pointer to HCM object.
dq_meas Pointer to the measured value (e.g., &gfl->idq).
dq_set Pointer to the setpoint (e.g., &zero_vector).
Definition at line 180 of file three_phase_additional.h.
References inv_dq_hcm_t::dq_meas, and inv_dq_hcm_t::dq_set.
ctl_attach_gfl_inv()
void ctl_attach_gfl_inv (gfl_inv_ctrl_t * inv, adc_ift * adc_idc, adc_ift * adc_udc, tri_adc_ift * adc_iabc, tri_adc_ift * adc_vabc)
Attach GFL inverter with input/output interface.
Parameters
[in,out] inv Pointer to the gfl_inv_ctrl_t structure.
[in] pwm_out Pointer to the tri-channel PWM interface structure.
[in] adc_udc Pointer to the udc ADC interface structure.
[in] adc_idc Pointer to the idc ADC interface structure.
[in] adc_iabc Pointer to the tri-channel ADC current interface structure.
[in] adc_vabc Pointer to the tri-channel ADC voltage interface structure.
[in,out] inv Pointer to the gfl_inv_ctrl_t structure.
[in] adc_udc Pointer to the udc ADC interface structure.
[in] adc_idc Pointer to the idc ADC interface structure.
[in] adc_iabc Pointer to the tri-channel ADC current interface structure.
[in] adc_vabc Pointer to the tri-channel ADC voltage interface structure.
Definition at line 373 of file ctl_dp_three_phase.c.
References gfl_inv_ctrl_t::adc_iabc, gfl_inv_ctrl_t::adc_idc, gfl_inv_ctrl_t::adc_udc, and gfl_inv_ctrl_t::adc_vabc.
ctl_attach_gfl_pq()
void ctl_attach_gfl_pq (gfl_pq_ctrl_t * pq, ctl_vector2_t * vdq, ctl_vector2_t * idq)
Attach feedback pointers to the PQ controller.
Parameters
[in,out] pq Pointer to the PQ controller instance.
[in] vdq Pointer to the inner loop's Vdq measurement.
[in] idq Pointer to the inner loop's Idq measurement.
Definition at line 403 of file ctl_dp_three_phase.c.
References gfl_pq_ctrl_t::idq_meas, and gfl_pq_ctrl_t::vdq_meas.
ctl_attach_gfl_pq_to_core()
void ctl_attach_gfl_pq_to_core (gfl_pq_ctrl_t * pq, gfl_inv_ctrl_t * core)
Attach feedback pointers to the PQ controller.
Parameters
[in,out] pq Pointer to the PQ controller instance.
[in] vdq Pointer to the inner loop's Vdq measurement.
[in] idq Pointer to the inner loop's Idq measurement.
Definition at line 415 of file ctl_dp_three_phase.c.
References gfl_inv_ctrl_t::idq, gfl_pq_ctrl_t::idq_meas, gfl_inv_ctrl_t::vdq, and gfl_pq_ctrl_t::vdq_meas.
ctl_attach_neg_inv()
GMP_STATIC_INLINE void ctl_attach_neg_inv (inv_neg_ctrl_t * neg, ctl_vector2_t * iab, ctl_vector2_t * vab, ctl_vector2_t * phasor)
Attach external pointers to the negative controller.
Definition at line 414 of file three_phase_additional.h.
References inv_neg_ctrl_t::iab, inv_neg_ctrl_t::phasor, and inv_neg_ctrl_t::vab.
ctl_attach_neg_inv_to_gfl()
GMP_STATIC_INLINE void ctl_attach_neg_inv_to_gfl (inv_neg_ctrl_t * neg, gfl_inv_ctrl_t * gfl)
Attach the negative controller to a Grid-Following Inverter controller.
Automatically maps the Alpha/Beta currents, voltages, and PLL phasor.
Parameters
[in,out] neg Pointer to the negative sequence controller.
[in] gfl Pointer to the main GFL inverter controller.
Definition at line 397 of file three_phase_additional.h.
References inv_neg_ctrl_t::iab, gfl_inv_ctrl_t::iab0, gfl_inv_ctrl_t::phasor, inv_neg_ctrl_t::phasor, inv_neg_ctrl_t::vab, and gfl_inv_ctrl_t::vab0.
ctl_auto_tuning_gfl_inv()
void ctl_auto_tuning_gfl_inv (gfl_inv_ctrl_init_t * init)
Auto-tuning GFL inverter parameters.
Parameters
[in,out] init Pointer to the gfl_inv_ctrl_init_t structure.
Definition at line 201 of file ctl_dp_three_phase.c.
References ctl_get_filter_iir1_phase_lag(), ctl_init_filter_iir1_lpf(), CTL_PARAM_CONST_2PI, and init().
ctl_auto_tuning_neg_inv()
void ctl_auto_tuning_neg_inv (inv_neg_ctrl_init_t * neg_init, const gfl_inv_ctrl_init_t * _gfl_init)
Auto-tuning Negative Sequence Controller parameters based on GFL system parameters.
Calculates reasonable bandwidths and filter settings derived from the main grid filter L/C and base values.
Parameters
[out] neg_init Pointer to the negative controller init structure to be filled.
[in] gfl_init Pointer to the source GFL system init structure (provides L, C, bases, etc.).
Auto-tuning Negative Sequence Controller parameters based on GFL system parameters.
Definition at line 433 of file ctl_dp_three_phase.c.
References CTL_PARAM_CONST_2PI, gfl_inv_ctrl_init_t::freq_base, inv_neg_ctrl_init_t::freq_base, gfl_inv_ctrl_init_t::fs, inv_neg_ctrl_init_t::fs, gfl_inv_ctrl_init_t::grid_filter_C, gfl_inv_ctrl_init_t::grid_filter_L, gfl_inv_ctrl_init_t::i_base, inv_neg_ctrl_init_t::ki_current, inv_neg_ctrl_init_t::ki_voltage, inv_neg_ctrl_init_t::kp_current, inv_neg_ctrl_init_t::kp_voltage, inv_neg_ctrl_init_t::limit_current_out, inv_neg_ctrl_init_t::limit_voltage_out, inv_neg_ctrl_init_t::seq_filter_fc, inv_neg_ctrl_init_t::seq_filter_q, and gfl_inv_ctrl_init_t::v_base.
ctl_clear_dq_hcm()
GMP_STATIC_INLINE void ctl_clear_dq_hcm (inv_dq_hcm_t * hcm)
Clears internal states of all resonators.
Definition at line 93 of file three_phase_additional.h.
References ctl_clear_qr_controller(), ctl_vector2_clear(), inv_dq_hcm_t::dq_out, inv_dq_hcm_t::qr_d_12th, inv_dq_hcm_t::qr_d_6th, inv_dq_hcm_t::qr_q_12th, and inv_dq_hcm_t::qr_q_6th.
ctl_clear_gfl_inv()
GMP_STATIC_INLINE void ctl_clear_gfl_inv (gfl_inv_ctrl_t * inv)
Clear GFL inverter parameters, without PLL.
Parameters
[in,out] inv Pointer to the gfl_inv_ctrl_t structure.
Definition at line 175 of file three_phase_GFL.h.
References ctl_clear_biquad_filter(), ctl_clear_filter_iir1(), ctl_clear_lead(), ctl_clear_pid(), ctl_vector2_clear(), ctl_vector3_clear(), ctl_ramp_generator_t::current, gfl_inv_ctrl_t::filter_damping, gfl_inv_ctrl_t::filter_iabc, gfl_inv_ctrl_t::filter_idc, gfl_inv_ctrl_t::filter_uabc, gfl_inv_ctrl_t::filter_udc, i, gfl_inv_ctrl_t::lead_compensator, phase_d, phase_q, gfl_inv_ctrl_t::pid_idq, gfl_inv_ctrl_t::rg, gfl_inv_ctrl_t::vab0_ff_external, gfl_inv_ctrl_t::vdq_ff_external, and gfl_inv_ctrl_t::vdq_last.
ctl_clear_gfl_inv_with_PLL()
GMP_STATIC_INLINE void ctl_clear_gfl_inv_with_PLL (gfl_inv_ctrl_t * inv)
Auto-tuning GFL inverter parameters.
Parameters
[in,out] inv Pointer to the gfl_inv_ctrl_t structure.
Definition at line 211 of file three_phase_GFL.h.
References ctl_clear_dsogi_pll(), ctl_clear_gfl_inv(), ctl_clear_pll_3ph(), gfl_inv_ctrl_t::flag_enable_system, and gfl_inv_ctrl_t::pll.
ctl_clear_gfl_pq()
GMP_STATIC_INLINE void ctl_clear_gfl_pq (gfl_pq_ctrl_t * pq)
Reset the PQ controller (clear integrators).
Parameters
[in,out] pq Pointer to the PQ controller instance.
Definition at line 684 of file three_phase_GFL.h.
References ctl_clear_pid(), gfl_pq_ctrl_t::idq_set_out, phase_d, phase_q, gfl_pq_ctrl_t::pid_p, and gfl_pq_ctrl_t::pid_q.
ctl_clear_neg_inv()
GMP_STATIC_INLINE void ctl_clear_neg_inv (inv_neg_ctrl_t * neg)
Clears all internal states of the negative sequence controller.
Parameters
[out] neg Pointer to the negative controller instance.
Definition at line 250 of file three_phase_additional.h.
References ctl_clear_biquad_filter(), ctl_clear_pid(), ctl_vector2_clear(), inv_neg_ctrl_t::filter_idqn, inv_neg_ctrl_t::filter_vdqn, inv_neg_ctrl_t::idqn, inv_neg_ctrl_t::idqn_raw, inv_neg_ctrl_t::idqn_ref_int, phase_d, phase_q, inv_neg_ctrl_t::pid_idqn, inv_neg_ctrl_t::pid_vdqn, inv_neg_ctrl_t::vab_out, inv_neg_ctrl_t::vdqn, inv_neg_ctrl_t::vdqn_out, and inv_neg_ctrl_t::vdqn_raw.
ctl_disable_gfl_inv()
GMP_STATIC_INLINE void ctl_disable_gfl_inv (gfl_inv_ctrl_t * inv)
Disable GFL controller.
Definition at line 597 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_system.
ctl_disable_gfl_inv_pll()
GMP_STATIC_INLINE void ctl_disable_gfl_inv_pll (gfl_inv_ctrl_t * inv)
Disable PLL module.
Definition at line 576 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_pll.
ctl_disable_gfl_pq_ctrl()
GMP_STATIC_INLINE void ctl_disable_gfl_pq_ctrl (gfl_pq_ctrl_t * pq)
Disable PQ controller.
Definition at line 790 of file three_phase_GFL.h.
References gfl_pq_ctrl_t::flag_enable.
ctl_disable_neg_inv()
GMP_STATIC_INLINE void ctl_disable_neg_inv (inv_neg_ctrl_t * neg)
Definition at line 434 of file three_phase_additional.h.
References inv_neg_ctrl_t::flag_enable_negative_current_ctrl, and inv_neg_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_enable_gfl_inv()
GMP_STATIC_INLINE void ctl_enable_gfl_inv (gfl_inv_ctrl_t * inv)
Enable GFL controller.
Definition at line 591 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_system.
ctl_enable_gfl_inv_active_damp()
GMP_STATIC_INLINE void ctl_enable_gfl_inv_active_damp (gfl_inv_ctrl_t * inv)
Enable inverter active damping.
Definition at line 548 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_active_damping.
ctl_enable_gfl_inv_decouple()
GMP_STATIC_INLINE void ctl_enable_gfl_inv_decouple (gfl_inv_ctrl_t * inv)
Enable inverter decoupling.
Definition at line 542 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_decouple.
ctl_enable_gfl_inv_lead_compensator()
GMP_STATIC_INLINE void ctl_enable_gfl_inv_lead_compensator (gfl_inv_ctrl_t * inv)
Enable inverter lead compensator.
Definition at line 554 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_active_damping.
ctl_enable_gfl_inv_pll()
GMP_STATIC_INLINE void ctl_enable_gfl_inv_pll (gfl_inv_ctrl_t * inv)
Enable PLL module.
Definition at line 570 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_pll.
ctl_enable_gfl_pq_ctrl()
GMP_STATIC_INLINE void ctl_enable_gfl_pq_ctrl (gfl_pq_ctrl_t * pq)
Enable PQ controller.
Definition at line 784 of file three_phase_GFL.h.
References gfl_pq_ctrl_t::flag_enable.
ctl_enable_neg_current_inv()
GMP_STATIC_INLINE void ctl_enable_neg_current_inv (inv_neg_ctrl_t * neg)
Definition at line 422 of file three_phase_additional.h.
References inv_neg_ctrl_t::flag_enable_negative_current_ctrl, and inv_neg_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_enable_neg_voltage_inv()
GMP_STATIC_INLINE void ctl_enable_neg_voltage_inv (inv_neg_ctrl_t * neg)
Definition at line 428 of file three_phase_additional.h.
References inv_neg_ctrl_t::flag_enable_negative_current_ctrl, and inv_neg_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_get_gfl_inv_pll_phasor()
GMP_STATIC_INLINE void ctl_get_gfl_inv_pll_phasor (gfl_inv_ctrl_t * inv, vector2_gt * phasor)
Definition at line 611 of file three_phase_GFL.h.
References ctl_vector2_copy(), srf_pll_t::phasor, and gfl_inv_ctrl_t::pll.
ctl_get_gfl_inv_pll_theta()
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_pll_theta (gfl_inv_ctrl_t * inv)
Definition at line 602 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::pll, and srf_pll_t::theta.
ctl_get_gfl_inv_Pout()
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_Pout (gfl_inv_ctrl_t * inv)
Calculates the output active power (P).
Definition at line 516 of file three_phase_GFL.h.
References ctl_add, ctl_mul, gfl_inv_ctrl_t::idq, phase_d, phase_q, and gfl_inv_ctrl_t::vdq.
ctl_get_gfl_inv_Qout()
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_inv_Qout (gfl_inv_ctrl_t * inv)
Calculates the output reactive power (Q).
Definition at line 523 of file three_phase_GFL.h.
References ctl_mul, ctl_sub, gfl_inv_ctrl_t::idq, phase_d, phase_q, and gfl_inv_ctrl_t::vdq.
ctl_get_gfl_pll_error()
GMP_STATIC_INLINE ctrl_gt ctl_get_gfl_pll_error (gfl_inv_ctrl_t * inv)
Get PLL error.
Definition at line 560 of file three_phase_GFL.h.
References srf_pll_t::e_error, and gfl_inv_ctrl_t::pll.
ctl_init_dq_hcm()
void ctl_init_dq_hcm (inv_dq_hcm_t * hcm, const inv_dq_hcm_init_t * init)
Initializes the HCM module.
Calculates QR coefficients using Frequency Pre-warping.
Definition at line 567 of file ctl_dp_three_phase.c.
References ctl_clear_dq_hcm(), ctl_update_dq_hcm_freq(), inv_dq_hcm_t::flag_enable_12th, inv_dq_hcm_t::flag_enable_6th, and init().
ctl_init_gfl_inv()
void ctl_init_gfl_inv (gfl_inv_ctrl_t * inv, gfl_inv_ctrl_init_t * init)
Init GFL inverter parameters.
Parameters
[out] inv Pointer to the gfl_inv_ctrl_t structure.
[in] init Pointer to the gfl_inv_ctrl_init_t structure.
Definition at line 357 of file ctl_dp_three_phase.c.
References ctl_clear_gfl_inv_with_PLL(), ctl_update_gfl_inv_coeff(), and init().
ctl_init_gfl_pq()
void ctl_init_gfl_pq (gfl_pq_ctrl_t * pq, parameter_gt p_kp, parameter_gt p_ki, parameter_gt q_kp, parameter_gt q_ki, parameter_gt i_out_max, parameter_gt fs)
Initialize the PQ controller with parameters.
Parameters
[out] pq Pointer to the PQ controller instance.
[in] init Initialization parameters.
Definition at line 388 of file ctl_dp_three_phase.c.
References ctl_init_pid(), gfl_pq_ctrl_t::flag_enable, float2ctrl, fs, gfl_pq_ctrl_t::max_i2_mag, gfl_pq_ctrl_t::pid_p, and gfl_pq_ctrl_t::pid_q.
ctl_init_neg_inv()
void ctl_init_neg_inv (inv_neg_ctrl_t * neg, const inv_neg_ctrl_init_t * neg_init)
Initialize Negative Sequence Controller.
Parameters
[out] neg Pointer to the negative controller object.
[in] neg_init Pointer to the negative controller init structure.
Definition at line 546 of file ctl_dp_three_phase.c.
References ctl_clear_neg_inv(), ctl_update_neg_inv_coeff(), ctl_vector2_clear(), inv_neg_ctrl_t::flag_enable_negative_current_ctrl, inv_neg_ctrl_t::flag_enable_negative_voltage_ctrl, inv_neg_ctrl_t::idqn_set, and inv_neg_ctrl_t::vdqn_set.
ctl_is_gfl_grid_connected()
GMP_STATIC_INLINE fast_gt ctl_is_gfl_grid_connected (gfl_inv_ctrl_t * inv)
GFL preparing to connect to grid.
Definition at line 582 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_offgrid.
ctl_set_gfl_inv_current()
GMP_STATIC_INLINE void ctl_set_gfl_inv_current (gfl_inv_ctrl_t * inv, ctrl_gt id, ctrl_gt iq)
Sets the target current in the d-q frame.
Definition at line 505 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::idq_set, phase_d, and phase_q.
ctl_set_gfl_inv_current_mode()
GMP_STATIC_INLINE void ctl_set_gfl_inv_current_mode (gfl_inv_ctrl_t * inv)
Sets the controller to current closed-loop mode.
Definition at line 493 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_active_damping, gfl_inv_ctrl_t::flag_enable_current_ctrl, gfl_inv_ctrl_t::flag_enable_decouple, gfl_inv_ctrl_t::flag_enable_lead_compensator, gfl_inv_ctrl_t::flag_enable_offgrid, gfl_inv_ctrl_t::flag_enable_pll, and gfl_inv_ctrl_t::flag_enable_system.
ctl_set_gfl_inv_freerun()
GMP_STATIC_INLINE void ctl_set_gfl_inv_freerun (gfl_inv_ctrl_t * inv)
Sets the angle source to the internal ramp generator (freerun).
Definition at line 530 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_offgrid.
ctl_set_gfl_inv_grid_connect()
GMP_STATIC_INLINE void ctl_set_gfl_inv_grid_connect (gfl_inv_ctrl_t * inv)
Sets the angle source to the PLL (grid-tied).
Definition at line 536 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_offgrid.
ctl_set_gfl_inv_openloop_mode()
GMP_STATIC_INLINE void ctl_set_gfl_inv_openloop_mode (gfl_inv_ctrl_t * inv)
Sets the controller to open-loop mode.
Definition at line 474 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::flag_enable_active_damping, gfl_inv_ctrl_t::flag_enable_current_ctrl, gfl_inv_ctrl_t::flag_enable_decouple, gfl_inv_ctrl_t::flag_enable_lead_compensator, gfl_inv_ctrl_t::flag_enable_offgrid, gfl_inv_ctrl_t::flag_enable_pll, and gfl_inv_ctrl_t::flag_enable_system.
ctl_set_gfl_inv_voltage_openloop()
GMP_STATIC_INLINE void ctl_set_gfl_inv_voltage_openloop (gfl_inv_ctrl_t * inv, ctrl_gt vd, ctrl_gt vq)
Sets the open-loop output voltage in the d-q frame.
Definition at line 486 of file three_phase_GFL.h.
References phase_d, phase_q, and gfl_inv_ctrl_t::vdq_out.
ctl_step_dq_hcm()
GMP_STATIC_INLINE void ctl_step_dq_hcm (inv_dq_hcm_t * hcm)
Executes one step of the Harmonic Compensation.
Parameters
hcm Pointer to HCM object.
Definition at line 142 of file three_phase_additional.h.
References ctl_step_qr_controller(), ctl_step_saturation(), inv_dq_hcm_t::dq_meas, inv_dq_hcm_t::dq_out, inv_dq_hcm_t::dq_set, inv_dq_hcm_t::flag_enable_12th, inv_dq_hcm_t::flag_enable_6th, phase_d, phase_q, inv_dq_hcm_t::qr_d_12th, inv_dq_hcm_t::qr_d_6th, inv_dq_hcm_t::qr_q_12th, inv_dq_hcm_t::qr_q_6th, inv_dq_hcm_t::sat_d, and inv_dq_hcm_t::sat_q.
ctl_step_gfl_inv_ctrl()
GMP_STATIC_INLINE void ctl_step_gfl_inv_ctrl (gfl_inv_ctrl_t * gfl)
Executes one step of the GFL three-phase inverter control algorithm.
Parameters
[out] ctrl Pointer to the inv_ctrl_t structure.
Definition at line 299 of file three_phase_GFL.h.
References gfl_inv_ctrl_t::adc_iabc, gfl_inv_ctrl_t::adc_idc, gfl_inv_ctrl_t::adc_udc, gfl_inv_ctrl_t::adc_vabc, gfl_inv_ctrl_t::angle, gfl_inv_ctrl_t::coef_ff_damping, gfl_inv_ctrl_t::coef_ff_decouple, ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_clarke_from_line(), ctl_ct_ipark2(), ctl_ct_park2(), ctl_set_phasor_via_angle(), ctl_step_biquad_filter(), ctl_step_dsogi_pll(), ctl_step_filter_iir1(), ctl_step_lead(), ctl_step_pid_ser(), ctl_step_pll_3ph(), ctl_step_ramp_generator(), ctl_vector2_copy(), vector2_gt::dat, gfl_inv_ctrl_t::filter_damping, gfl_inv_ctrl_t::filter_iabc, gfl_inv_ctrl_t::filter_idc, gfl_inv_ctrl_t::filter_uabc, gfl_inv_ctrl_t::filter_udc, gfl_inv_ctrl_t::flag_enable_active_damping, gfl_inv_ctrl_t::flag_enable_current_ctrl, gfl_inv_ctrl_t::flag_enable_decouple, gfl_inv_ctrl_t::flag_enable_external_phasor, gfl_inv_ctrl_t::flag_enable_lead_compensator, gfl_inv_ctrl_t::flag_enable_offgrid, gfl_inv_ctrl_t::flag_enable_pll, gfl_inv_ctrl_t::flag_enable_system, gfl_inv_ctrl_t::iab0, gfl_inv_ctrl_t::iabc, gfl_inv_ctrl_t::idq, gfl_inv_ctrl_t::idq_set, gfl_inv_ctrl_t::isr_tick, gfl_inv_ctrl_t::lead_compensator, phase_0, phase_A, phase_alpha, phase_B, phase_beta, phase_C, phase_d, phase_q, phase_UAB, phase_UBC, gfl_inv_ctrl_t::phasor, srf_pll_t::phasor, gfl_inv_ctrl_t::phasor_ext, gfl_inv_ctrl_t::pid_idq, gfl_inv_ctrl_t::pll, gfl_inv_ctrl_t::rg, srf_pll_t::theta, gfl_inv_ctrl_t::vab0, gfl_inv_ctrl_t::vab0_ff_external, gfl_inv_ctrl_t::vab0_out, gfl_inv_ctrl_t::vab_pos, gfl_inv_ctrl_t::vabc, gfl_inv_ctrl_t::vdq, gfl_inv_ctrl_t::vdq_ff_damping, gfl_inv_ctrl_t::vdq_ff_decouple, gfl_inv_ctrl_t::vdq_last, gfl_inv_ctrl_t::vdq_out, and gfl_inv_ctrl_t::vdq_out_comp.
ctl_step_gfl_pq()
GMP_STATIC_INLINE void ctl_step_gfl_pq (gfl_pq_ctrl_t * pq)
Execute one step of the PQ control loop.
Parameters
[in,out] pq Pointer to the PQ controller instance.
Note
This should run at a slower rate than the current loop (e.g., 1kHz - 5kHz).
Definition at line 714 of file three_phase_GFL.h.
References ctl_div, ctl_mul, ctl_sqrt, ctl_step_pid_ser(), gfl_pq_ctrl_t::flag_enable, gfl_pq_ctrl_t::idq_meas, gfl_pq_ctrl_t::idq_set_out, gfl_pq_ctrl_t::max_i2_mag, phase_d, phase_q, gfl_pq_ctrl_t::pid_p, gfl_pq_ctrl_t::pid_q, gfl_pq_ctrl_t::pq_meas, gfl_pq_ctrl_t::pq_set, and gfl_pq_ctrl_t::vdq_meas.
ctl_step_neg_inv_ctrl()
GMP_STATIC_INLINE void ctl_step_neg_inv_ctrl (inv_neg_ctrl_t * neg)
Executes one step of the Negative Sequence Controller.
Must be called after measurement sampling and PLL, but before PWM generation.
Parameters
[in,out] neg Pointer to the negative controller instance.
Definition at line 328 of file three_phase_additional.h.
References ctl_ct_ipark2_neg(), ctl_ct_park2_neg(), ctl_step_biquad_filter(), ctl_step_pid_ser(), ctl_vector2_clear(), inv_neg_ctrl_t::filter_idqn, inv_neg_ctrl_t::filter_vdqn, inv_neg_ctrl_t::flag_enable_negative_current_ctrl, inv_neg_ctrl_t::flag_enable_negative_voltage_ctrl, inv_neg_ctrl_t::iab, inv_neg_ctrl_t::idqn, inv_neg_ctrl_t::idqn_raw, inv_neg_ctrl_t::idqn_ref_int, inv_neg_ctrl_t::idqn_set, phase_d, phase_q, inv_neg_ctrl_t::phasor, inv_neg_ctrl_t::pid_idqn, inv_neg_ctrl_t::pid_vdqn, inv_neg_ctrl_t::vab, inv_neg_ctrl_t::vab_out, inv_neg_ctrl_t::vdqn, inv_neg_ctrl_t::vdqn_out, inv_neg_ctrl_t::vdqn_raw, and inv_neg_ctrl_t::vdqn_set.
ctl_update_dq_hcm_freq()
void ctl_update_dq_hcm_freq (inv_dq_hcm_t * hcm, const inv_dq_hcm_init_t * init)
Updates the resonant parameters.
Parameters
hcm Pointer to HCM object.
new_freq_base New fundamental frequency (Hz).
init Original init structure (to retrieve Kr and BW settings).
Definition at line 581 of file ctl_dp_three_phase.c.
References ctl_init_qr_controller_prewarped(), ctl_init_saturation(), init(), inv_dq_hcm_t::qr_d_12th, inv_dq_hcm_t::qr_d_6th, inv_dq_hcm_t::qr_q_12th, inv_dq_hcm_t::qr_q_6th, inv_dq_hcm_t::sat_d, and inv_dq_hcm_t::sat_q.
ctl_update_gfl_inv_coeff()
void ctl_update_gfl_inv_coeff (gfl_inv_ctrl_t * inv, gfl_inv_ctrl_init_t * init)
update GFL inverter controller parameters by init structure.
Parameters
[out] inv Pointer to the gfl_inv_ctrl_t structure.
[in] init Pointer to the gfl_inv_ctrl_init_t structure.
Definition at line 293 of file ctl_dp_three_phase.c.
References gfl_inv_ctrl_t::coef_ff_damping, gfl_inv_ctrl_t::coef_ff_decouple, ctl_init_biquad_bpf(), ctl_init_dsogi_pll(), ctl_init_filter_iir1_lpf(), ctl_init_lead_form3(), ctl_init_pid(), ctl_init_ramp_generator_via_freq(), ctl_init_srf_pll_auto_tune(), CTL_PARAM_CONST_2PI, gfl_inv_ctrl_t::filter_damping, gfl_inv_ctrl_t::filter_iabc, gfl_inv_ctrl_t::filter_uabc, gfl_inv_ctrl_t::flag_enable_active_damping, float2ctrl, i, init(), gfl_inv_ctrl_t::lead_compensator, phase_d, phase_q, gfl_inv_ctrl_t::pid_idq, gfl_inv_ctrl_t::pll, and gfl_inv_ctrl_t::rg.
ctl_update_neg_inv_coeff()
void ctl_update_neg_inv_coeff (inv_neg_ctrl_t * neg, const inv_neg_ctrl_init_t * neg_init)
Update Negative Sequence Controller coefficients.
Calculates Kp, Ki and initializes filters/PIDs based on the init structure.
Parameters
[out] neg Pointer to the negative controller object.
[in] neg_init Pointer to the negative controller init structure.
Definition at line 508 of file ctl_dp_three_phase.c.
References ctl_init_biquad_notch(), ctl_init_pid(), ctl_set_pid_limit(), inv_neg_ctrl_t::filter_idqn, inv_neg_ctrl_t::filter_vdqn, inv_neg_ctrl_init_t::freq_base, inv_neg_ctrl_init_t::fs, i, inv_neg_ctrl_init_t::ki_current, inv_neg_ctrl_init_t::ki_voltage, inv_neg_ctrl_init_t::kp_current, inv_neg_ctrl_init_t::kp_voltage, inv_neg_ctrl_init_t::limit_current_out, inv_neg_ctrl_init_t::limit_voltage_out, phase_d, phase_q, inv_neg_ctrl_t::pid_idqn, inv_neg_ctrl_t::pid_vdqn, and inv_neg_ctrl_init_t::seq_filter_q.