GMP - CTL: Look-Up Tables (LUT)
Look-Up Tables (LUT)
Control Template Library Intrinsic » Advance Components
A library for 1D and 2D data searching and interpolation.
Data Structures
struct ctl_lut1d_t
Data structure for a 1D Look-Up Table.
struct ctl_lut2d_t
Data structure for a 2D LUT with non-uniformly spaced axes.
struct ctl_uniform_lut2d_t
Data structure for a 2D LUT with uniformly spaced axes.
Functions
void ctl_init_lut1d (ctl_lut1d_t *lut, const ctrl_gt *axis, uint32_t size)
Initializes a 1D Look-Up Table.
GMP_STATIC_INLINE int32_t ctl_search_lut1d_index (const ctl_lut1d_t *lut, ctrl_gt target)
Performs a binary search to find the index of the lower bound for a target value.
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_lut1d (const ctl_lut1d_t *lut, const ctrl_gt *values, ctrl_gt target)
Performs 1D linear interpolation.
void ctl_init_lut2d (ctl_lut2d_t *lut, const ctrl_gt *axis1, uint32_t size1, const ctrl_gt *axis2, uint32_t size2, const ctrl_gt **surface)
Initializes a 2D Look-Up Table.
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_lut2d (const ctl_lut2d_t *lut, ctrl_gt target1, ctrl_gt target2)
Performs 2D bilinear interpolation on a non-uniform grid.
void ctl_init_uniform_lut2d (ctl_uniform_lut2d_t *lut, ctrl_gt x_min, ctrl_gt x_max, uint32_t x_size, ctrl_gt y_min, ctrl_gt y_max, uint32_t y_size, const ctrl_gt **surface)
Initializes a 2D LUT with a uniform grid.
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_uniform_lut2d (const ctl_uniform_lut2d_t *lut, ctrl_gt x, ctrl_gt y)
Performs 2D bilinear interpolation on a uniform grid.
Detailed Description
A library for 1D and 2D data searching and interpolation.
This module implements algorithms for searching and interpolating values from pre-defined tables. It includes a 1D LUT with binary search and linear interpolation, a 2D LUT for non-uniform grids, and a 2D LUT for uniform grids, both using bilinear interpolation. These are essential for efficiently implementing complex, nonlinear functions in embedded systems.
Function Documentation
ctl_init_lut1d()
void ctl_init_lut1d (ctl_lut1d_t * lut, const ctrl_gt * axis, uint32_t size)
Initializes a 1D Look-Up Table.
Parameters
[out] lut Pointer to the 1D LUT instance.
[in] axis Pointer to the array of axis data.
[in] size The number of elements in the axis array.
Definition at line 62 of file ctl_component_advance.c.
References axis, ctl_lut1d_t::axis, and ctl_lut1d_t::size.
ctl_init_lut2d()
void ctl_init_lut2d (ctl_lut2d_t * lut, const ctrl_gt * axis1, uint32_t size1, const ctrl_gt * axis2, uint32_t size2, const ctrl_gt ** surface)
Initializes a 2D Look-Up Table.
Parameters
[out] lut Pointer to the 2D LUT instance.
[in] axis1 Pointer to the array for the 1st axis.
[in] size1 Number of elements in the 1st axis.
[in] axis2 Pointer to the array for the 2nd axis.
[in] size2 Number of elements in the 2nd axis.
[in] surface Pointer to the 2D array (size1 x size2) of surface data.
Definition at line 68 of file ctl_component_advance.c.
References ctl_init_lut1d(), ctl_lut2d_t::dim1_axis, ctl_lut2d_t::dim2_axis, ctl_lut2d_t::surface, and surface.
ctl_init_uniform_lut2d()
void ctl_init_uniform_lut2d (ctl_uniform_lut2d_t * lut, ctrl_gt x_min, ctrl_gt x_max, uint32_t x_size, ctrl_gt y_min, ctrl_gt y_max, uint32_t y_size, const ctrl_gt ** surface)
Initializes a 2D LUT with a uniform grid.
Parameters
[out] lut Pointer to the uniform 2D LUT instance.
[in] x_min Minimum value of the x-axis.
[in] x_max Maximum value of the x-axis.
[in] x_size Number of points on the x-axis.
[in] y_min Minimum value of the y-axis.
[in] y_max Maximum value of the y-axis.
[in] y_size Number of points on the y-axis.
[in] surface Pointer to the 2D array (x_size x y_size) of surface data.
Definition at line 76 of file ctl_component_advance.c.
References ctl_uniform_lut2d_t::surface, surface, ctl_uniform_lut2d_t::x_min, ctl_uniform_lut2d_t::x_size, ctl_uniform_lut2d_t::x_step_inv, ctl_uniform_lut2d_t::y_min, ctl_uniform_lut2d_t::y_size, and ctl_uniform_lut2d_t::y_step_inv.
ctl_search_lut1d_index()
GMP_STATIC_INLINE int32_t ctl_search_lut1d_index (const ctl_lut1d_t * lut, ctrl_gt target)
Performs a binary search to find the index of the lower bound for a target value.
Parameters
[in] lut Pointer to the 1D LUT instance.
[in] target The value to search for in the axis.
Returns
int32_t The index of the grid point immediately to the left of (or equal to) the target. Returns -1 if the target is below the first element. Returns (size-2) if the target is at or above the last element.
Definition at line 65 of file surf_search.h.
References axis, ctl_lut1d_t::axis, and ctl_lut1d_t::size.
ctl_step_interpolate_lut1d()
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_lut1d (const ctl_lut1d_t * lut, const ctrl_gt * values, ctrl_gt target)
Performs 1D linear interpolation.
Parameters
[in] lut Pointer to the 1D LUT instance containing the x-axis data.
[in] values Pointer to the array of y-axis values corresponding to the x-axis.
[in] target The x-value at which to interpolate.
Returns
ctrl_gt The interpolated y-value.
Definition at line 102 of file surf_search.h.
References ctl_lut1d_t::axis, ctl_div, ctl_mul, ctl_search_lut1d_index(), ctl_lut1d_t::size, x1, and y1.
ctl_step_interpolate_lut2d()
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_lut2d (const ctl_lut2d_t * lut, ctrl_gt target1, ctrl_gt target2)
Performs 2D bilinear interpolation on a non-uniform grid.
Parameters
[in] lut Pointer to the 2D LUT instance.
[in] target1 The target value on the 1st axis.
[in] target2 The target value on the 2nd axis.
Returns
ctrl_gt The interpolated surface value.
Definition at line 159 of file surf_search.h.
References ctl_lut1d_t::axis, ctl_div, ctl_mul, ctl_search_lut1d_index(), ctl_lut2d_t::dim1_axis, ctl_lut2d_t::dim2_axis, ctl_lut1d_t::size, and ctl_lut2d_t::surface.
ctl_step_interpolate_uniform_lut2d()
GMP_STATIC_INLINE ctrl_gt ctl_step_interpolate_uniform_lut2d (const ctl_uniform_lut2d_t * lut, ctrl_gt x, ctrl_gt y)
Performs 2D bilinear interpolation on a uniform grid.
Parameters
[in] lut Pointer to the uniform 2D LUT instance.
[in] x The target value on the x-axis.
[in] y The target value on the y-axis.
Returns
ctrl_gt The interpolated surface value.
Definition at line 230 of file surf_search.h.
References ctl_mul, ctl_sat, ctl_uniform_lut2d_t::surface, ctl_uniform_lut2d_t::x_min, ctl_uniform_lut2d_t::x_size, ctl_uniform_lut2d_t::x_step_inv, ctl_uniform_lut2d_t::y_min, ctl_uniform_lut2d_t::y_size, and ctl_uniform_lut2d_t::y_step_inv.