GMP - CTL: Fuzzy Logic Controller
Fuzzy Logic Controller
Control Template Library Intrinsic » Advance Components
A complete FLC implementation based on a 2D look-up table.
Data Structures
struct flc_controller_t
Data structure for the Fuzzy Logic Controller instance.
Functions
GMP_STATIC_INLINE void ctl_init_flc (flc_controller_t *flc, ctrl_gt x_min, ctrl_gt x_max, uint32_t x_size, ctrl_gt y_min, ctrl_gt y_max, uint32_t y_size, const ctrl_gt **surface, ctrl_gt gain_err, ctrl_gt gain_err_diff, ctrl_gt gain_output)
Initializes the Fuzzy Logic Controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_flc (const flc_controller_t *flc, ctrl_gt error, ctrl_gt error_rate)
Executes one step of the Fuzzy Logic Controller.
Variables
ctrl_gt fuzzy_matrix [21][21]
Extern declaration for the 21x21 fuzzy control surface matrix.
ctrl_gt fuzzy_matrix_segment1 [21]
Extern declaration for the first dimension's axis points.
ctrl_gt fuzzy_matrix_segment2 [21]
Extern declaration for the second dimension's axis points.
Detailed Description
A complete FLC implementation based on a 2D look-up table.
This module integrates a pre-generated fuzzy control surface (from fuzzy_2d.c) with a 2D uniform grid interpolation algorithm (from surf_search.h) to create a complete FLC. It includes scaling factors (gains) for inputs and output, which is essential for tuning the controller's performance in a real-world application.
Function Documentation
ctl_init_flc()
GMP_STATIC_INLINE void ctl_init_flc (flc_controller_t * flc, ctrl_gt x_min, ctrl_gt x_max, uint32_t x_size, ctrl_gt y_min, ctrl_gt y_max, uint32_t y_size, const ctrl_gt ** surface, ctrl_gt gain_err, ctrl_gt gain_err_diff, ctrl_gt gain_output)
Initializes the Fuzzy Logic Controller.
Parameters
[out] flc Pointer to the FLC instance to initialize.
[in] x_min Minimum value of the error (x-axis).
[in] x_max Maximum value of the error (x-axis).
[in] x_size Number of points of the error on the x-axis.
[in] y_min Minimum value of the error rate (y-axis).
[in] y_max Maximum value of the error rate (y-axis).
[in] y_size Number of points of the error rate on the y-axis.
[in] surface Pointer to the 2D array (x_size x y_size), (error, error rate) of surface data.
[in] gain_err The gain for the 'Error' input.
[in] gain_err_diff The gain for the 'Error Rate' input.
[in] gain_output The gain for the final control output.
This function configures the internal look-up table object with the data from fuzzy_2d.c and sets the scaling factors. It must be called once before using flc_run().
Definition at line 95 of file flc.h.
References ctl_init_saturation(), ctl_init_uniform_lut2d(), float2ctrl, flc_controller_t::gce, flc_controller_t::ge, flc_controller_t::gu, flc_controller_t::lut, flc_controller_t::sat_ce, flc_controller_t::sat_e, flc_controller_t::sat_u, and surface.
ctl_step_flc()
GMP_STATIC_INLINE ctrl_gt ctl_step_flc (const flc_controller_t * flc, ctrl_gt error, ctrl_gt error_rate)
Executes one step of the Fuzzy Logic Controller.
Parameters
[in] flc Pointer to the initialized FLC instance.
[in] error The current system error (e).
[in] error_rate The current system error rate (ec).
Returns
ctrl_gt The calculated control output.
Definition at line 128 of file flc.h.
References ctl_mul, ctl_step_interpolate_uniform_lut2d(), ctl_step_saturation(), flc_controller_t::gce, flc_controller_t::ge, flc_controller_t::gu, flc_controller_t::lut, flc_controller_t::out, flc_controller_t::sat_ce, flc_controller_t::sat_e, and flc_controller_t::sat_u.
Variable Documentation
fuzzy_matrix
ctrl_gt fuzzy_matrix[21][21] extern
Extern declaration for the 21x21 fuzzy control surface matrix.
This data should be defined in fuzzy_2d.c.
Definition at line 53 of file get_fuzzy_matrix.m.
fuzzy_matrix_segment1
ctrl_gt fuzzy_matrix_segment1[21] extern
Extern declaration for the first dimension's axis points.
fuzzy_matrix_segment2
ctrl_gt fuzzy_matrix_segment2[21] extern
Extern declaration for the second dimension's axis points.