GMP - CTL: CTL Framework Dispatcher
CTL Framework Dispatcher
CMP CTL Framework Core
The core scheduler for the control loop execution.
Functions
GMP_STATIC_INLINE void gmp_base_ctl_step (void)
The main kernel step function for the GMP CTL module.
Detailed Description
The core scheduler for the control loop execution.
Function Documentation
gmp_base_ctl_step()
GMP_STATIC_INLINE void gmp_base_ctl_step (void)
The main kernel step function for the GMP CTL module.
This function is the primary entry point intended to be invoked by the user in the main control ISR. It conditionally compiles the appropriate dispatch logic based on the selected framework.
Definition at line 106 of file ctl_dispatch.h.
References ctl_dispatch(), ctl_input_callback(), ctl_nano_handle, and ctl_output_callback().