GMP - CTL: SOGI-based Quadrature Signal Generator with DC Rejection
SOGI-based Quadrature Signal Generator with DC Rejection
Control Template Library Intrinsic » Discrete Components » SOGI-based Quadrature Signal Generator
Implements a SOGI with an additional loop to reject DC offset.
Data Structures
struct discrete_sogi_dc_t
Functions
void ctl_init_discrete_sogi_dc (discrete_sogi_dc_t *sogi_dc, parameter_gt k_damp, parameter_gt k_dc, parameter_gt fn, parameter_gt fs)
Initializes the SOGI-DC module.
GMP_STATIC_INLINE void ctl_clear_discrete_sogi_dc (discrete_sogi_dc_t *sogi_dc)
Clears the internal states of the SOGI-DC module.
GMP_STATIC_INLINE void ctl_step_discrete_sogi_dc (discrete_sogi_dc_t *sogi_dc, ctrl_gt u)
Executes one step of the SOGI-DC calculation.
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_alpha (discrete_sogi_dc_t *sogi_dc)
Gets the latest direct (alpha) output (DC-free).
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_beta (discrete_sogi_dc_t *sogi_dc)
Gets the latest quadrature (beta) output (DC-free).
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_offset (discrete_sogi_dc_t *sogi_dc)
Gets the estimated DC offset.
Detailed Description
Implements a SOGI with an additional loop to reject DC offset.
This module extends the standard SOGI by adding a DC estimation loop. Ideally, the alpha channel of a standard SOGI rejects DC (gain=0 at 0Hz). However, any DC offset in the input passes through to the beta channel (integrator), causing low-frequency oscillation in the DQ frame (50/60Hz ripple).
This module estimates the DC component and subtracts it from the input before feeding it to the SOGI core, ensuring pure AC signals for alpha and beta outputs.
generally,
\[ k_{dc} \approx 0.5 ~ 1.0 \]
Transfer Functions (Simplified structural view):
Direct Output (Alpha) D(s):
\[ \frac{D(s)}{R(s)} = \frac{k \omega_0 s^2}{s^3 + (k + k_{dc})\omega_0 s^2 + \omega_0^2 s + k_{dc}\omega_0^3} \]
Quadrature Output (Beta) Q(s):
\[ \frac{Q(s)}{R(s)} = \frac{k \omega_0^2 s}{s^3 + (k + k_{dc})\omega_0 s^2 + \omega_0^2 s + k_{dc}\omega_0^3} \]
DC Estimation Output DC(s):
\[ \frac{DC(s)}{R(s)} = \frac{k_{dc} \omega_0 (s^2 + \omega_0^2)}{s^3 + (k + k_{dc})\omega_0 s^2 + \omega_0^2 s + k_{dc}\omega_0^3} \]
where \(k_{dc} \) is the DC rejection gain.
Function Documentation
ctl_clear_discrete_sogi_dc()
GMP_STATIC_INLINE void ctl_clear_discrete_sogi_dc (discrete_sogi_dc_t * sogi_dc)
Clears the internal states of the SOGI-DC module.
Definition at line 224 of file discrete_sogi.h.
References discrete_sogi_dc_t::core, ctl_clear_discrete_sogi(), discrete_sogi_dc_t::input_prev, and discrete_sogi_dc_t::v_dc_est.
ctl_get_discrete_sogi_dc_alpha()
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_alpha (discrete_sogi_dc_t * sogi_dc)
Gets the latest direct (alpha) output (DC-free).
Definition at line 273 of file discrete_sogi.h.
References discrete_sogi_dc_t::core, and ctl_get_discrete_sogi_ds().
ctl_get_discrete_sogi_dc_beta()
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_beta (discrete_sogi_dc_t * sogi_dc)
Gets the latest quadrature (beta) output (DC-free).
Definition at line 281 of file discrete_sogi.h.
References discrete_sogi_dc_t::core, and ctl_get_discrete_sogi_qs().
ctl_get_discrete_sogi_dc_offset()
GMP_STATIC_INLINE ctrl_gt ctl_get_discrete_sogi_dc_offset (discrete_sogi_dc_t * sogi_dc)
Gets the estimated DC offset.
Definition at line 289 of file discrete_sogi.h.
References discrete_sogi_dc_t::v_dc_est.
ctl_init_discrete_sogi_dc()
void ctl_init_discrete_sogi_dc (discrete_sogi_dc_t * sogi_dc, parameter_gt k_damp, parameter_gt k_dc, parameter_gt fn, parameter_gt fs)
Initializes the SOGI-DC module.
Parameters
[out] sogi_dc Pointer to the SOGI-DC instance.
[in] k_damp SOGI damping coefficient (typically 1.414).
[in] k_dc DC rejection gain (typically 0.5 to 1.0). Lower is slower but more stable.
[in] fn Center frequency in Hz.
[in] fs Sampling frequency in Hz.
Definition at line 1445 of file ctl_component_discrete.c.
References discrete_sogi_dc_t::core, ctl_clear_discrete_sogi_dc(), ctl_init_discrete_sogi(), CTL_PARAM_CONST_2PI, discrete_sogi_dc_t::dc_integ_gain, float2ctrl, and fs.
ctl_step_discrete_sogi_dc()
GMP_STATIC_INLINE void ctl_step_discrete_sogi_dc (discrete_sogi_dc_t * sogi_dc, ctrl_gt u)
Executes one step of the SOGI-DC calculation.
Update DC estimate based on previous error.
Subtract DC from current Input.
Step standard SOGI.
Parameters
[in,out] sogi_dc Pointer to the instance.
[in] u The current raw input sample (containing AC + DC).
Definition at line 243 of file discrete_sogi.h.
References discrete_sogi_dc_t::core, ctl_get_discrete_sogi_ds(), ctl_mul, ctl_step_discrete_sogi(), discrete_sogi_dc_t::dc_integ_gain, discrete_sogi_dc_t::input_prev, and discrete_sogi_dc_t::v_dc_est.