GMP - CTL: Slope Frequency Generator
Slope Frequency Generator
Motor Control Library » Motor Controller Components
A module that generates a frequency signal with a controlled slope.
Data Structures
struct ctl_slope_f_controller
Data structure for the Slope Frequency Controller.
struct ctl_slope_f_pu_controller
Data structure for the Slope Frequency Controller (Per-Unit Version).
Functions
void ctl_init_const_slope_f_controller (ctl_slope_f_controller *ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_slope_f (ctl_slope_f_controller *ctrl)
Executes one step of the slope frequency controller.
GMP_STATIC_INLINE void ctl_clear_slope_f (ctl_slope_f_controller *ctrl)
Resets the internal state of the frequency slope limiter.
void ctl_set_slope_f_freq (ctl_slope_f_controller *ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the slope generator.
void ctl_init_const_slope_f_pu_controller (ctl_slope_f_pu_controller *ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt rated_krpm, parameter_gt pole_pairs, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller (PU).
GMP_STATIC_INLINE ctrl_gt ctl_step_slope_f_pu (ctl_slope_f_pu_controller *ctrl)
Executes one step of the slope frequency controller (PU).
GMP_STATIC_INLINE void ctl_clear_slope_f_pu (ctl_slope_f_pu_controller *ctrl)
Resets the internal state of the frequency slope limiter.
GMP_STATIC_INLINE void ctl_set_slope_f_pu_freq (ctl_slope_f_pu_controller *ctrl, parameter_gt target_freq_hz, parameter_gt rated_krpm, parameter_gt pole_pairs)
Sets the target frequency (Converting Hz input to PU).
Detailed Description
A module that generates a frequency signal with a controlled slope.
This module changes the output frequency from its current value to a target value gradually, following a defined slope (rate of change).
Function Documentation
ctl_clear_slope_f()
GMP_STATIC_INLINE void ctl_clear_slope_f (ctl_slope_f_controller * ctrl)
Resets the internal state of the frequency slope limiter.
Parameters
[in,out] ctrl Pointer to the ctl_slope_f_controller object.
Definition at line 148 of file vf_generator.h.
References ctl_clear_slope_limiter(), and ctl_slope_f_controller::freq_slope.
ctl_clear_slope_f_pu()
GMP_STATIC_INLINE void ctl_clear_slope_f_pu (ctl_slope_f_pu_controller * ctrl)
Resets the internal state of the frequency slope limiter.
Parameters
[in,out] ctrl Pointer to the ctl_slope_f_controller object.
Definition at line 233 of file vf_generator.h.
References ctl_clear_slope_limiter(), and ctl_slope_f_pu_controller::freq_slope.
ctl_init_const_slope_f_controller()
void ctl_init_const_slope_f_controller (ctl_slope_f_controller * ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller.
Parameters
[out] ctrl Pointer to the ctl_slope_f_controller object.
[in] frequency The initial target frequency in Hz.
[in] freq_slope The maximum rate of frequency change in Hz/s.
[in] isr_freq The frequency of the interrupt service routine (ISR) in Hz.
Definition at line 150 of file ctl_mc_basic.c.
References ctl_init_ramp_generator_via_freq(), ctl_init_slope_limiter(), rotation_ift::elec_position, ctl_slope_f_controller::enc, float2ctrl, ctl_slope_f_controller::freq_slope, rotation_ift::position, ctl_slope_f_controller::rg, and ctl_slope_f_controller::target_frequency.
ctl_init_const_slope_f_pu_controller()
void ctl_init_const_slope_f_pu_controller (ctl_slope_f_pu_controller * ctrl, parameter_gt frequency, parameter_gt freq_slope, parameter_gt rated_krpm, parameter_gt pole_pairs, parameter_gt isr_freq)
Initializes the Constant Slope Frequency Controller (PU).
Parameters
[out] ctrl Pointer to the ctl_slope_f_pu_controller object.
[in] frequency The initial target frequency in Hz.
[in] freq_slope The maximum rate of frequency change in Hz/s.
[in] rated_krpm The motor rated speed in krpm (Base value source).
[in] pole_pairs The motor pole pairs (Base value source).
[in] isr_freq The frequency of the interrupt service routine (ISR) in Hz.
Definition at line 193 of file ctl_mc_basic.c.
References ctl_init_ramp_generator_via_freq(), ctl_init_slope_limiter(), ctl_slope_f_pu_controller::current_freq_pu, rotation_ift::elec_position, ctl_slope_f_pu_controller::enc, float2ctrl, ctl_slope_f_pu_controller::freq_slope, ctl_slope_limiter_t::out, rotation_ift::position, ctl_slope_f_pu_controller::ratio_freq_pu_to_step, ctl_slope_f_pu_controller::rg, and ctl_slope_f_pu_controller::target_freq_pu.
ctl_set_slope_f_freq()
void ctl_set_slope_f_freq (ctl_slope_f_controller * ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the slope generator.
Parameters
[in,out] ctrl Pointer to the ctl_slope_f_controller object.
[in] target_freq The new target frequency in Hz.
[in] isr_freq The frequency of the interrupt service routine (ISR) in Hz.
Definition at line 173 of file ctl_mc_basic.c.
References float2ctrl, and ctl_slope_f_controller::target_frequency.
ctl_set_slope_f_pu_freq()
GMP_STATIC_INLINE void ctl_set_slope_f_pu_freq (ctl_slope_f_pu_controller * ctrl, parameter_gt target_freq_hz, parameter_gt rated_krpm, parameter_gt pole_pairs)
Sets the target frequency (Converting Hz input to PU).
Parameters
ctrl Controller instance.
target_freq_hz Target frequency in Hz.
rated_krpm Motor rated speed (Base).
pole_pairs Motor pole pairs (Base).
Definition at line 245 of file vf_generator.h.
References float2ctrl, and ctl_slope_f_pu_controller::target_freq_pu.
ctl_step_slope_f()
GMP_STATIC_INLINE ctrl_gt ctl_step_slope_f (ctl_slope_f_controller * ctrl)
Executes one step of the slope frequency controller.
This function updates the current frequency based on the slope, and then generates the next electrical angle.
Parameters
[in,out] ctrl Pointer to the ctl_slope_f_controller object.
Returns
ctrl_gt The new electrical position (angle).
Definition at line 129 of file vf_generator.h.
References ctl_set_ramp_generator_slope(), ctl_step_ramp_generator(), ctl_step_slope_limiter(), ctl_slope_f_controller::current_freq, rotation_ift::elec_position, ctl_slope_f_controller::enc, ctl_slope_f_controller::freq_slope, rotation_ift::position, ctl_slope_f_controller::rg, and ctl_slope_f_controller::target_frequency.
ctl_step_slope_f_pu()
GMP_STATIC_INLINE ctrl_gt ctl_step_slope_f_pu (ctl_slope_f_pu_controller * ctrl)
Executes one step of the slope frequency controller (PU).
Parameters
[in,out] ctrl Pointer to the ctl_slope_f_pu_controller object.
Returns
ctrl_gt The new electrical position (angle).
Definition at line 208 of file vf_generator.h.
References ctl_mul, ctl_set_ramp_generator_slope(), ctl_step_ramp_generator(), ctl_step_slope_limiter(), ctl_slope_f_pu_controller::current_freq_pu, rotation_ift::elec_position, ctl_slope_f_pu_controller::enc, ctl_slope_f_pu_controller::freq_slope, rotation_ift::position, ctl_slope_f_pu_controller::ratio_freq_pu_to_step, ctl_slope_f_pu_controller::rg, and ctl_slope_f_pu_controller::target_freq_pu.