GMP - CTL: Three-Phase Inverter Topology API
Three-Phase Inverter Topology API
Digital Power Control Library » Digital Power Topology Presets
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Data Structures
struct inv_ctrl_t
Main data structure for the three-phase inverter controller.
struct three_phase_inv_init_t
Initialization parameters for the three-phase inverter controller.
struct gfm_droop_ctrl_t
Grid-Forming Droop Controller (Outer Loop).
struct gfm_droop_init_t
Initialization parameters for GFM Droop Controller.
Macros
#define CURRENT_SAMPLE_PHASE_MODE (3)
Configures the current sampling method.
#define VOLTAGE_SAMPLE_PHASE_MODE (1)
Configures the voltage sampling method.
#define _FILE_THREE_PHASE_GFM_
Functions
void ctl_upgrade_three_phase_inv (inv_ctrl_t *inv, three_phase_inv_init_t *init)
void ctl_init_three_phase_inv (inv_ctrl_t *inv, three_phase_inv_init_t *init)
void ctl_attach_three_phase_inv (inv_ctrl_t *inv, tri_pwm_ift *pwm_out, adc_ift *adc_udc, adc_ift *adc_idc, tri_adc_ift *adc_iabc, tri_adc_ift *adc_vabc, tri_adc_ift *adc_iuvw, tri_adc_ift *adc_vuvw)
GMP_STATIC_INLINE void ctl_step_inv_ctrl (inv_ctrl_t *ctrl)
Executes one step of the three-phase inverter control algorithm.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_openloop_mode (inv_ctrl_t *inv)
Sets the controller to open-loop mode.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage_openloop (inv_ctrl_t *inv, ctrl_gt vd, ctrl_gt vq)
Sets the open-loop output voltage in the d-q frame.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current_mode (inv_ctrl_t *inv)
Sets the controller to current closed-loop mode.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current (inv_ctrl_t *inv, ctrl_gt id, ctrl_gt iq)
Sets the target current in the d-q frame.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current_via_pf (inv_ctrl_t *inv, ctrl_gt is, ctrl_gt pf)
Sets the target current via magnitude and power factor.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage_mode (inv_ctrl_t *inv)
Sets the controller to voltage closed-loop mode.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage (inv_ctrl_t *inv, ctrl_gt vd)
Sets the target voltage in the d-q frame (vq is assumed to be 0).
GMP_STATIC_INLINE void ctl_set_three_phase_inv_rg_frequency (inv_ctrl_t *inv, ctrl_gt freq_pu)
Sets the frequency of the ramp generator in per-unit.
GMP_STATIC_INLINE void ctl_set_three_phase_inv_droop_mode (inv_ctrl_t *inv)
Sets the controller to droop control mode.
GMP_STATIC_INLINE void ctl_set_droop_reference_voltage (inv_ctrl_t *inv, ctrl_gt vref)
Sets the reference voltage for droop control.
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_inv_Pout (inv_ctrl_t *inv)
Calculates the output active power (P).
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_inv_Qout (inv_ctrl_t *inv)
Calculates the output reactive power (Q).
GMP_STATIC_INLINE void ctl_set_three_phase_inv_freerun (inv_ctrl_t *inv)
Sets the angle source to the internal ramp generator (freerun).
GMP_STATIC_INLINE void ctl_set_three_phase_inv_pll (inv_ctrl_t *inv)
Sets the angle source to the PLL (grid-tied).
GMP_STATIC_INLINE void ctl_enable_three_phase_harm_ctrl (inv_ctrl_t *inv)
Enables the harmonic compensation controllers.
GMP_STATIC_INLINE void ctl_disable_three_phase_harm_ctrl (inv_ctrl_t *inv)
Disables the harmonic compensation controllers.
GMP_STATIC_INLINE void ctl_enable_three_phase_negative_current_ctrl (inv_ctrl_t *inv)
Enables negative-sequence current control only.
GMP_STATIC_INLINE void ctl_enable_three_phase_negative_voltage_ctrl (inv_ctrl_t *inv)
Enables cascaded negative-sequence voltage and current control.
GMP_STATIC_INLINE void ctl_disable_three_phase_negative_ctrl (inv_ctrl_t *inv)
Disables all negative-sequence control.
GMP_STATIC_INLINE void ctl_enable_three_phase_inverter (inv_ctrl_t *inv)
Enables the main system controller.
GMP_STATIC_INLINE void ctl_disable_three_phase_inverter (inv_ctrl_t *inv)
Disables the main system controller, setting PWM to 50%.
GMP_STATIC_INLINE void ctl_enable_three_phase_feedforward (inv_ctrl_t *inv)
Enables the inductor decoupling feed-forward term.
GMP_STATIC_INLINE void ctl_disable_three_phase_feedforward (inv_ctrl_t *inv)
Disables the inductor decoupling feed-forward term.
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_pll_error (inv_ctrl_t *inv)
Gets the current error from the PLL.
GMP_STATIC_INLINE ctrl_gt ctl_is_three_phase_inverter_mode (inv_ctrl_t *inv)
Judge if the converter is inverter mode.ctl_is_three_phase_inverter_mode.
GMP_STATIC_INLINE fast_gt ctl_is_three_phase_inverter_freerun_mode (inv_ctrl_t *inv)
Checks if the controller is in freerun mode.
GMP_STATIC_INLINE void ctl_clear_three_phase_inv (inv_ctrl_t *inv)
Clears all runtime states of the inverter controller.
GMP_STATIC_INLINE void ctl_clear_gfm_droop_ctrl (gfm_droop_ctrl_t *gfm)
void ctl_auto_tuning_gfm_droop_ctrl (gfm_droop_init_t *gfm_init, gfl_inv_ctrl_init_t *gfl)
void ctl_init_gfm_droop (gfm_droop_ctrl_t *gfm, const gfm_droop_init_t *init)
GMP_STATIC_INLINE void ctl_step_gfm_droop (gfm_droop_ctrl_t *gfm)
Executes one step of the GFM Droop Controller.
GMP_STATIC_INLINE fast_gt ctl_if_gfm_voltage_ready (gfm_droop_ctrl_t *gfm)
Checks if the GFM Voltage is ready to engage (Pre-sync check).
void ctl_attach_gfm_droop_with_gfl_core (gfm_droop_ctrl_t *gfm, gfl_inv_ctrl_t *gfl)
Detailed Description
Defines the data structures, control flags, and function interfaces for a comprehensive three-phase inverter, including harmonic compensation, droop control, and multiple operating modes.
Macro Definition Documentation
_FILE_THREE_PHASE_GFM_
#define _FILE_THREE_PHASE_GFM_
Definition at line 23 of file three_phase_GFM.h.
CURRENT_SAMPLE_PHASE_MODE
#define CURRENT_SAMPLE_PHASE_MODE (3)
Configures the current sampling method.
3: Sample all three phase currents (Ia, Ib, Ic).
2: Sample two phase currents (Ia, Ib), and calculate the third.
Definition at line 46 of file three_phase_dc_ac.h.
VOLTAGE_SAMPLE_PHASE_MODE
#define VOLTAGE_SAMPLE_PHASE_MODE (1)
Configures the voltage sampling method.
3: Sample all three phase voltages (Va, Vb, Vc).
2: Sample two phase voltages (Va, Vb), and calculate the third.
1: Sample two line-to-line voltages (Vab, Vbc).
Definition at line 56 of file three_phase_dc_ac.h.
Function Documentation
ctl_attach_gfm_droop_with_gfl_core()
void ctl_attach_gfm_droop_with_gfl_core (gfm_droop_ctrl_t * gfm, gfl_inv_ctrl_t * gfl)
Definition at line 405 of file three_phase_GFM.h.
References gfl_inv_ctrl_t::idq, gfm_droop_ctrl_t::idq_meas, gfl_inv_ctrl_t::phasor_ext, gfm_droop_ctrl_t::phasor_out, gfl_inv_ctrl_t::pll, gfm_droop_ctrl_t::pll_angle, srf_pll_t::theta, gfl_inv_ctrl_t::vdq, and gfm_droop_ctrl_t::vdq_meas.
ctl_attach_three_phase_inv()
void ctl_attach_three_phase_inv (inv_ctrl_t * inv, tri_pwm_ift * pwm_out, adc_ift * adc_udc, adc_ift * adc_idc, tri_adc_ift * adc_iabc, tri_adc_ift * adc_vabc, tri_adc_ift * adc_iuvw, tri_adc_ift * adc_vuvw)
Definition at line 82 of file ctl_dp_topology_inv.c.
References inv_ctrl_t::adc_iabc, inv_ctrl_t::adc_idc, inv_ctrl_t::adc_iuvw, inv_ctrl_t::adc_udc, inv_ctrl_t::adc_vabc, inv_ctrl_t::adc_vuvw, inv_ctrl_t::pwm_out, and pwm_out.
ctl_auto_tuning_gfm_droop_ctrl()
void ctl_auto_tuning_gfm_droop_ctrl (gfm_droop_init_t * gfm_init, gfl_inv_ctrl_init_t * gfl)
Definition at line 149 of file three_phase_GFM.h.
References gfm_droop_init_t::cf_capacitance, CTL_PARAM_CONST_2PI, gfm_droop_init_t::current_limit, gfm_droop_init_t::droop_p_percent, gfm_droop_init_t::droop_q_percent, gfm_droop_init_t::freq_base, gfm_droop_init_t::fs, gfl_init, gfm_droop_init_t::i_base, gfm_droop_init_t::lv_virtual, gfm_droop_init_t::power_lpf_fc, gfm_droop_init_t::rv_virtual, gfm_droop_init_t::s_base, gfm_droop_init_t::v_base, and gfm_droop_init_t::voltage_loop_bw.
ctl_clear_gfm_droop_ctrl()
GMP_STATIC_INLINE void ctl_clear_gfm_droop_ctrl (gfm_droop_ctrl_t * gfm)
Definition at line 106 of file three_phase_GFM.h.
References ctl_clear_filter_iir1(), ctl_clear_pid(), ctl_vector2_clear(), gfm_droop_ctrl_t::lpf_pq, phase_d, phase_q, gfm_droop_ctrl_t::pid_vdq, gfm_droop_ctrl_t::pq_avg, gfm_droop_ctrl_t::pq_inst, and gfm_droop_ctrl_t::theta_out.
ctl_clear_three_phase_inv()
GMP_STATIC_INLINE void ctl_clear_three_phase_inv (inv_ctrl_t * inv)
Clears all runtime states of the inverter controller.
Definition at line 648 of file three_phase_dc_ac.h.
References ctl_clear_lowpass_filter(), ctl_clear_pid(), ctl_clear_qr_controller(), ctl_vector2_clear(), inv_ctrl_t::current_ctrl, inv_ctrl_t::harm_qr_5, inv_ctrl_t::harm_qr_7, i, inv_ctrl_t::idq_ff, inv_ctrl_t::lpf_iabc, inv_ctrl_t::lpf_idc, inv_ctrl_t::lpf_udc, inv_ctrl_t::lpf_vabc, inv_ctrl_t::neg_current_ctrl, inv_ctrl_t::neg_voltage_ctrl, phase_d, phase_q, inv_ctrl_t::voltage_ctrl, inv_ctrl_t::zero_pid, inv_ctrl_t::zero_qr_3, and inv_ctrl_t::zero_qr_9.
ctl_disable_three_phase_feedforward()
GMP_STATIC_INLINE void ctl_disable_three_phase_feedforward (inv_ctrl_t * inv)
Disables the inductor decoupling feed-forward term.
Definition at line 621 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_decouple_lf.
ctl_disable_three_phase_harm_ctrl()
GMP_STATIC_INLINE void ctl_disable_three_phase_harm_ctrl (inv_ctrl_t * inv)
Disables the harmonic compensation controllers.
Definition at line 576 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_harm_ctrl.
ctl_disable_three_phase_inverter()
GMP_STATIC_INLINE void ctl_disable_three_phase_inverter (inv_ctrl_t * inv)
Disables the main system controller, setting PWM to 50%.
Definition at line 609 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_system.
ctl_disable_three_phase_negative_ctrl()
GMP_STATIC_INLINE void ctl_disable_three_phase_negative_ctrl (inv_ctrl_t * inv)
Disables all negative-sequence control.
Definition at line 596 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_negative_current_ctrl, and inv_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_enable_three_phase_feedforward()
GMP_STATIC_INLINE void ctl_enable_three_phase_feedforward (inv_ctrl_t * inv)
Enables the inductor decoupling feed-forward term.
Definition at line 615 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_decouple_lf.
ctl_enable_three_phase_harm_ctrl()
GMP_STATIC_INLINE void ctl_enable_three_phase_harm_ctrl (inv_ctrl_t * inv)
Enables the harmonic compensation controllers.
Definition at line 570 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_harm_ctrl.
ctl_enable_three_phase_inverter()
GMP_STATIC_INLINE void ctl_enable_three_phase_inverter (inv_ctrl_t * inv)
Enables the main system controller.
Definition at line 603 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_system.
ctl_enable_three_phase_negative_current_ctrl()
GMP_STATIC_INLINE void ctl_enable_three_phase_negative_current_ctrl (inv_ctrl_t * inv)
Enables negative-sequence current control only.
Definition at line 582 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_negative_current_ctrl, and inv_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_enable_three_phase_negative_voltage_ctrl()
GMP_STATIC_INLINE void ctl_enable_three_phase_negative_voltage_ctrl (inv_ctrl_t * inv)
Enables cascaded negative-sequence voltage and current control.
Definition at line 589 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_negative_current_ctrl, and inv_ctrl_t::flag_enable_negative_voltage_ctrl.
ctl_get_three_phase_inv_Pout()
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_inv_Pout (inv_ctrl_t * inv)
Calculates the output active power (P).
Definition at line 544 of file three_phase_dc_ac.h.
References ctl_add, ctl_mul, inv_ctrl_t::idq, phase_d, phase_q, and inv_ctrl_t::vdq.
ctl_get_three_phase_inv_Qout()
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_inv_Qout (inv_ctrl_t * inv)
Calculates the output reactive power (Q).
Definition at line 551 of file three_phase_dc_ac.h.
References ctl_mul, ctl_sub, inv_ctrl_t::idq, phase_d, phase_q, and inv_ctrl_t::vdq.
ctl_get_three_phase_pll_error()
GMP_STATIC_INLINE ctrl_gt ctl_get_three_phase_pll_error (inv_ctrl_t * inv)
Gets the current error from the PLL.
Definition at line 627 of file three_phase_dc_ac.h.
References srf_pll_t::e_error, and inv_ctrl_t::pll.
ctl_if_gfm_voltage_ready()
GMP_STATIC_INLINE fast_gt ctl_if_gfm_voltage_ready (gfm_droop_ctrl_t * gfm)
Checks if the GFM Voltage is ready to engage (Pre-sync check).
Returns
1 if voltage magnitude is within tolerance of V_nom, 0 otherwise.
Definition at line 385 of file three_phase_GFM.h.
References ctl_abs, ctl_mul, ctl_sqrt, phase_d, phase_q, gfm_droop_ctrl_t::v_nom, and gfm_droop_ctrl_t::vdq_meas.
ctl_init_gfm_droop()
void ctl_init_gfm_droop (gfm_droop_ctrl_t * gfm, const gfm_droop_init_t * init)
Definition at line 195 of file three_phase_GFM.h.
References gfm_droop_ctrl_t::coef_droop, gfm_droop_ctrl_t::coef_vdq_ff, gfm_droop_ctrl_t::coef_vir_ind, gfm_droop_ctrl_t::coef_vir_res, ctl_clear_gfm_droop_ctrl(), ctl_init_filter_iir1_lpf(), ctl_init_pid(), ctl_init_saturation(), CTL_PARAM_CONST_2PI, gfm_droop_ctrl_t::f_nom, gfm_droop_ctrl_t::flag_enable_droop, gfm_droop_ctrl_t::flag_enable_system, gfm_droop_ctrl_t::flag_enable_virtual_imp, gfm_droop_ctrl_t::flag_enable_voltage_ff, gfm_droop_ctrl_t::flag_enable_voltage_loop, init(), gfm_droop_ctrl_t::lpf_pq, gfm_droop_ctrl_t::omega_nom, phase_d, phase_q, gfm_droop_ctrl_t::pid_vdq, gfm_droop_ctrl_t::pq_set, gfm_droop_ctrl_t::sat_id, gfm_droop_ctrl_t::sat_iq, gfm_droop_ctrl_t::Ts, and gfm_droop_ctrl_t::v_nom.
ctl_init_three_phase_inv()
void ctl_init_three_phase_inv (inv_ctrl_t * inv, three_phase_inv_init_t * init)
Definition at line 98 of file ctl_dp_topology_inv.c.
References ctl_clear_three_phase_inv(), ctl_upgrade_three_phase_inv(), init(), and inv_ctrl_t::isr_tick.
ctl_is_three_phase_inverter_freerun_mode()
GMP_STATIC_INLINE fast_gt ctl_is_three_phase_inverter_freerun_mode (inv_ctrl_t * inv)
Checks if the controller is in freerun mode.
Definition at line 642 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_freerun.
ctl_is_three_phase_inverter_mode()
GMP_STATIC_INLINE ctrl_gt ctl_is_three_phase_inverter_mode (inv_ctrl_t * inv)
Judge if the converter is inverter mode.ctl_is_three_phase_inverter_mode.
Definition at line 635 of file three_phase_dc_ac.h.
ctl_set_droop_reference_voltage()
GMP_STATIC_INLINE void ctl_set_droop_reference_voltage (inv_ctrl_t * inv, ctrl_gt vref)
Sets the reference voltage for droop control.
Definition at line 534 of file three_phase_dc_ac.h.
References inv_ctrl_t::v_droop_ref.
ctl_set_three_phase_inv_current()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current (inv_ctrl_t * inv, ctrl_gt id, ctrl_gt iq)
Sets the target current in the d-q frame.
Definition at line 477 of file three_phase_dc_ac.h.
References inv_ctrl_t::idq_set, phase_d, and phase_q.
ctl_set_three_phase_inv_current_mode()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current_mode (inv_ctrl_t * inv)
Sets the controller to current closed-loop mode.
Definition at line 462 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_current_ctrl, inv_ctrl_t::flag_enable_decouple_lf, inv_ctrl_t::flag_enable_droop, inv_ctrl_t::flag_enable_freerun, inv_ctrl_t::flag_enable_harm_ctrl, inv_ctrl_t::flag_enable_negative_current_ctrl, inv_ctrl_t::flag_enable_negative_voltage_ctrl, inv_ctrl_t::flag_enable_pll, inv_ctrl_t::flag_enable_system, and inv_ctrl_t::flag_enable_voltage_ctrl.
ctl_set_three_phase_inv_current_via_pf()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_current_via_pf (inv_ctrl_t * inv, ctrl_gt is, ctrl_gt pf)
Sets the target current via magnitude and power factor.
Definition at line 484 of file three_phase_dc_ac.h.
References ctl_mul, ctl_sqrt, ctl_sub, float2ctrl, inv_ctrl_t::idq_set, phase_d, and phase_q.
ctl_set_three_phase_inv_droop_mode()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_droop_mode (inv_ctrl_t * inv)
Sets the controller to droop control mode.
Definition at line 519 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_current_ctrl, inv_ctrl_t::flag_enable_decouple_lf, inv_ctrl_t::flag_enable_droop, inv_ctrl_t::flag_enable_freerun, inv_ctrl_t::flag_enable_harm_ctrl, inv_ctrl_t::flag_enable_negative_current_ctrl, inv_ctrl_t::flag_enable_negative_voltage_ctrl, inv_ctrl_t::flag_enable_pll, inv_ctrl_t::flag_enable_system, and inv_ctrl_t::flag_enable_voltage_ctrl.
ctl_set_three_phase_inv_freerun()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_freerun (inv_ctrl_t * inv)
Sets the angle source to the internal ramp generator (freerun).
Definition at line 558 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_freerun.
ctl_set_three_phase_inv_openloop_mode()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_openloop_mode (inv_ctrl_t * inv)
Sets the controller to open-loop mode.
Definition at line 440 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_current_ctrl, inv_ctrl_t::flag_enable_decouple_lf, inv_ctrl_t::flag_enable_droop, inv_ctrl_t::flag_enable_freerun, inv_ctrl_t::flag_enable_harm_ctrl, inv_ctrl_t::flag_enable_negative_current_ctrl, inv_ctrl_t::flag_enable_negative_voltage_ctrl, inv_ctrl_t::flag_enable_pll, inv_ctrl_t::flag_enable_system, and inv_ctrl_t::flag_enable_voltage_ctrl.
ctl_set_three_phase_inv_pll()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_pll (inv_ctrl_t * inv)
Sets the angle source to the PLL (grid-tied).
Definition at line 564 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_freerun.
ctl_set_three_phase_inv_rg_frequency()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_rg_frequency (inv_ctrl_t * inv, ctrl_gt freq_pu)
Sets the frequency of the ramp generator in per-unit.
Definition at line 513 of file three_phase_dc_ac.h.
References inv_ctrl_t::rg_freq_pu.
ctl_set_three_phase_inv_voltage()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage (inv_ctrl_t * inv, ctrl_gt vd)
Sets the target voltage in the d-q frame (vq is assumed to be 0).
Definition at line 506 of file three_phase_dc_ac.h.
References phase_d, phase_q, and inv_ctrl_t::vdq_set.
ctl_set_three_phase_inv_voltage_mode()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage_mode (inv_ctrl_t * inv)
Sets the controller to voltage closed-loop mode.
Definition at line 491 of file three_phase_dc_ac.h.
References inv_ctrl_t::flag_enable_current_ctrl, inv_ctrl_t::flag_enable_decouple_lf, inv_ctrl_t::flag_enable_droop, inv_ctrl_t::flag_enable_freerun, inv_ctrl_t::flag_enable_harm_ctrl, inv_ctrl_t::flag_enable_negative_current_ctrl, inv_ctrl_t::flag_enable_negative_voltage_ctrl, inv_ctrl_t::flag_enable_pll, inv_ctrl_t::flag_enable_system, and inv_ctrl_t::flag_enable_voltage_ctrl.
ctl_set_three_phase_inv_voltage_openloop()
GMP_STATIC_INLINE void ctl_set_three_phase_inv_voltage_openloop (inv_ctrl_t * inv, ctrl_gt vd, ctrl_gt vq)
Sets the open-loop output voltage in the d-q frame.
Definition at line 455 of file three_phase_dc_ac.h.
References phase_d, phase_q, and inv_ctrl_t::vdq_pos_out.
ctl_step_gfm_droop()
GMP_STATIC_INLINE void ctl_step_gfm_droop (gfm_droop_ctrl_t * gfm)
Executes one step of the GFM Droop Controller.
Definition at line 256 of file three_phase_GFM.h.
References gfm_droop_ctrl_t::coef_droop, gfm_droop_ctrl_t::coef_vdq_ff, gfm_droop_ctrl_t::coef_vir_ind, gfm_droop_ctrl_t::coef_vir_res, ctl_mul, CTL_PARAM_CONST_2PI, ctl_set_phasor_via_angle(), ctl_step_filter_iir1(), ctl_step_pid_ser(), ctl_step_saturation(), gfm_droop_ctrl_t::droop_freq_ref, gfm_droop_ctrl_t::droop_v_mag_ref, gfm_droop_ctrl_t::f_nom, gfm_droop_ctrl_t::flag_enable_droop, gfm_droop_ctrl_t::flag_enable_system, gfm_droop_ctrl_t::flag_enable_virtual_imp, gfm_droop_ctrl_t::flag_enable_voltage_ff, gfm_droop_ctrl_t::flag_enable_voltage_loop, gfm_droop_ctrl_t::idq_meas, gfm_droop_ctrl_t::idq_ref_out, gfm_droop_ctrl_t::lpf_pq, phase_d, phase_q, gfm_droop_ctrl_t::phasor_out, gfm_droop_ctrl_t::pid_vdq, gfm_droop_ctrl_t::pll_angle, gfm_droop_ctrl_t::pq_avg, gfm_droop_ctrl_t::pq_inst, gfm_droop_ctrl_t::pq_set, gfm_droop_ctrl_t::sat_id, gfm_droop_ctrl_t::sat_iq, gfm_droop_ctrl_t::theta_out, gfm_droop_ctrl_t::Ts, gfm_droop_ctrl_t::v_nom, gfm_droop_ctrl_t::vdq_ff_decouple, gfm_droop_ctrl_t::vdq_meas, gfm_droop_ctrl_t::vdq_vir_imp, and gfm_droop_ctrl_t::vdq_virt_ref.
ctl_step_inv_ctrl()
GMP_STATIC_INLINE void ctl_step_inv_ctrl (inv_ctrl_t * ctrl)
Executes one step of the three-phase inverter control algorithm.
Parameters
[out] ctrl Pointer to the inv_ctrl_t structure.
Definition at line 242 of file three_phase_dc_ac.h.
References inv_ctrl_t::abc_out, inv_ctrl_t::adc_iabc, inv_ctrl_t::adc_idc, inv_ctrl_t::adc_iuvw, inv_ctrl_t::adc_udc, inv_ctrl_t::adc_vabc, inv_ctrl_t::adc_vuvw, inv_ctrl_t::angle, ctl_add, ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_clarke_from_line(), ctl_ct_iclarke2(), ctl_ct_ipark2(), ctl_ct_ipark2_neg(), ctl_ct_park2(), ctl_ct_park2_neg(), ctl_div2, ctl_mul, ctl_set_phasor_via_angle(), ctl_set_ramp_generator_slope(), ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctl_step_pll_3ph(), ctl_step_qr_controller(), ctl_step_ramp_generator(), ctl_step_saturation(), ctl_vector2_clear(), ctl_vector2_copy(), ctl_vector3_set(), inv_ctrl_t::current_ctrl, vector3_gt::dat, inv_ctrl_t::flag_enable_current_ctrl, inv_ctrl_t::flag_enable_decouple_lf, inv_ctrl_t::flag_enable_droop, inv_ctrl_t::flag_enable_freerun, inv_ctrl_t::flag_enable_harm_ctrl, inv_ctrl_t::flag_enable_negative_current_ctrl, inv_ctrl_t::flag_enable_negative_voltage_ctrl, inv_ctrl_t::flag_enable_pll, inv_ctrl_t::flag_enable_system, inv_ctrl_t::flag_enable_voltage_ctrl, inv_ctrl_t::flag_enable_zero_current_ctrl, float2ctrl, srf_pll_t::freq_pu, inv_ctrl_t::harm_qr_5, inv_ctrl_t::harm_qr_7, i, inv_ctrl_t::iab0, inv_ctrl_t::iabc, inv_ctrl_t::idq, inv_ctrl_t::idq_droop_sat, inv_ctrl_t::idq_droop_set, inv_ctrl_t::idq_ff, inv_ctrl_t::idq_neg, inv_ctrl_t::idq_net_set, inv_ctrl_t::idq_set, inv_ctrl_t::isr_tick, inv_ctrl_t::kp_droop, inv_ctrl_t::kq_droop, inv_ctrl_t::lpf_iabc, inv_ctrl_t::lpf_idc, inv_ctrl_t::lpf_udc, inv_ctrl_t::lpf_vabc, inv_ctrl_t::neg_current_ctrl, inv_ctrl_t::neg_voltage_ctrl, inv_ctrl_t::omega_L, phase_0, phase_A, phase_alpha, phase_B, phase_beta, phase_C, phase_d, phase_q, inv_ctrl_t::phasor, srf_pll_t::phasor, inv_ctrl_t::pll, inv_ctrl_t::pwm_out, inv_ctrl_t::rg, inv_ctrl_t::rg_freq_pu, inv_ctrl_t::rg_slope_default, srf_pll_t::theta, inv_ctrl_t::v0_set, inv_ctrl_t::v_droop_ref, inv_ctrl_t::vab0, inv_ctrl_t::vab_harm, inv_ctrl_t::vab_neg, inv_ctrl_t::vab_out, inv_ctrl_t::vab_pos, inv_ctrl_t::vabc, tri_pwm_ift::value, inv_ctrl_t::vdq, inv_ctrl_t::vdq_neg, inv_ctrl_t::vdq_neg_out, inv_ctrl_t::vdq_pos_out, inv_ctrl_t::vdq_set, inv_ctrl_t::voltage_ctrl, inv_ctrl_t::zero_pid, inv_ctrl_t::zero_qr_3, and inv_ctrl_t::zero_qr_9.
ctl_upgrade_three_phase_inv()
void ctl_upgrade_three_phase_inv (inv_ctrl_t * inv, three_phase_inv_init_t * init)
Definition at line 23 of file ctl_dp_topology_inv.c.
References ctl_init_lp_filter(), ctl_init_pid_Tmode(), ctl_init_qr_controller(), ctl_init_ramp_generator_via_freq(), ctl_init_saturation(), ctl_init_sfr_pll(), CTL_PARAM_CONST_2PI, inv_ctrl_t::current_ctrl, float2ctrl, inv_ctrl_t::harm_qr_5, inv_ctrl_t::harm_qr_7, i, inv_ctrl_t::idq_droop_sat, init(), inv_ctrl_t::kp_droop, inv_ctrl_t::kq_droop, inv_ctrl_t::lpf_iabc, inv_ctrl_t::lpf_idc, inv_ctrl_t::lpf_udc, inv_ctrl_t::lpf_vabc, inv_ctrl_t::neg_current_ctrl, inv_ctrl_t::neg_voltage_ctrl, inv_ctrl_t::omega_L, phase_d, phase_q, inv_ctrl_t::pll, inv_ctrl_t::rg, inv_ctrl_t::rg_freq_pu, inv_ctrl_t::rg_slope_default, ctl_ramp_generator_t::slope, inv_ctrl_t::voltage_ctrl, inv_ctrl_t::zero_pid, inv_ctrl_t::zero_qr_3, and inv_ctrl_t::zero_qr_9.