GMP - CTL: Discrete Filter Library
Discrete Filter Library
Control Template Library Intrinsic » Discrete Components
A collection of common discrete filters for signal processing.
Data Structures
struct ctl_low_pass_filter_t
A first-order infinite impulse response (IIR) low-pass filter.
struct ctl_filter_IIR1_t
A first-order infinite impulse response (IIR) general filter.
Functions
void ctl_init_lp_filter (ctl_low_pass_filter_t *lpf, parameter_gt fs, parameter_gt fc)
Initializes a first-order low-pass filter object.
GMP_STATIC_INLINE ctrl_gt ctl_helper_lp_filter (parameter_gt fs, parameter_gt fc)
Helper function to calculate the filter coefficient 'a'.
GMP_STATIC_INLINE parameter_gt ctl_helper_get_lp_filter_lag_phase (parameter_gt fc, parameter_gt finput)
Calculates the approximate phase lag introduced by the filter at a given frequency.
GMP_STATIC_INLINE ctrl_gt ctl_step_lowpass_filter (ctl_low_pass_filter_t *lpf, ctrl_gt input)
Executes one step of the low-pass filter calculation.
GMP_STATIC_INLINE void ctl_clear_lowpass_filter (ctl_low_pass_filter_t *lpf)
Clears the internal state of the low-pass filter.
GMP_STATIC_INLINE ctrl_gt ctl_get_lowpass_filter_result (ctl_low_pass_filter_t *lpf)
Gets the last calculated output from the filter.
GMP_STATIC_INLINE ctrl_gt ctl_step_filter_iir1 (ctl_filter_IIR1_t *obj, ctrl_gt input)
Executes one step of the 1st-order IIR filter.
GMP_STATIC_INLINE void ctl_clear_filter_iir1 (ctl_filter_IIR1_t *obj)
Clears all internal states of the 1st-order IIR filter.
void ctl_init_filter_iir1_lpf (ctl_filter_IIR1_t *obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order Low-Pass Filter (LPF).
void ctl_init_filter_iir1_hpf (ctl_filter_IIR1_t *obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order High-Pass Filter (HPF).
void ctl_init_filter_iir1_apf (ctl_filter_IIR1_t *obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order All-Pass Filter.
parameter_gt ctl_get_filter_iir1_phase_lag (ctl_filter_IIR1_t *obj, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 1st-order filter at a specific frequency.
parameter_gt ctl_get_filter_iir1_gain (ctl_filter_IIR1_t *obj, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 1st-order filter at a specific frequency.
Detailed Description
A collection of common discrete filters for signal processing.
This file contains implementations for several standard discrete filters used in digital control and signal processing. It includes a generic first-order and second-order IIR filter, along with various initializers. It also includes a generic FIR filter module.
Function Documentation
ctl_clear_filter_iir1()
GMP_STATIC_INLINE void ctl_clear_filter_iir1 (ctl_filter_IIR1_t * obj)
Clears all internal states of the 1st-order IIR filter.
Parameters
[out] obj Pointer to the IIR filter instance.
Definition at line 166 of file discrete_filter.h.
References ctl_filter_IIR1_t::out, ctl_filter_IIR1_t::x1, and ctl_filter_IIR1_t::y1.
ctl_clear_lowpass_filter()
GMP_STATIC_INLINE void ctl_clear_lowpass_filter (ctl_low_pass_filter_t * lpf)
Clears the internal state of the low-pass filter.
Resets the stored previous output to 0.
Parameters
[out] lpf Pointer to the low-pass filter instance.
Definition at line 112 of file discrete_filter.h.
References ctl_low_pass_filter_t::out.
ctl_get_filter_iir1_gain()
parameter_gt ctl_get_filter_iir1_gain (ctl_filter_IIR1_t * obj, parameter_gt fs, parameter_gt f)
Calculates the linear gain of the 1st-order filter at a specific frequency.
Parameters
[in] obj Pointer to the IIR filter instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the gain (Hz).
Returns
parameter_gt The linear gain (magnitude).
Definition at line 74 of file ctl_component_discrete.c.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, CTL_PARAM_CONST_PI, float2ctrl, and fs.
ctl_get_filter_iir1_phase_lag()
parameter_gt ctl_get_filter_iir1_phase_lag (ctl_filter_IIR1_t * obj, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the 1st-order filter at a specific frequency.
Parameters
[in] obj Pointer to the IIR filter instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the phase lag (Hz).
Returns
parameter_gt The phase lag in radians. A positive value indicates lag.
Definition at line 57 of file ctl_component_discrete.c.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, CTL_PARAM_CONST_PI, and fs.
ctl_get_lowpass_filter_result()
GMP_STATIC_INLINE ctrl_gt ctl_get_lowpass_filter_result (ctl_low_pass_filter_t * lpf)
Gets the last calculated output from the filter.
Parameters
[in] lpf Pointer to the low-pass filter instance.
Returns
ctrl_gt The last output value.
Definition at line 122 of file discrete_filter.h.
References ctl_low_pass_filter_t::out.
ctl_helper_get_lp_filter_lag_phase()
GMP_STATIC_INLINE parameter_gt ctl_helper_get_lp_filter_lag_phase (parameter_gt fc, parameter_gt finput)
Calculates the approximate phase lag introduced by the filter at a given frequency.
Parameters
fc Filter cutoff frequency (Hz).
finput Input signal frequency (Hz).
Returns
parameter_gt The phase lag in radians.
Definition at line 89 of file discrete_filter.h.
ctl_helper_lp_filter()
GMP_STATIC_INLINE ctrl_gt ctl_helper_lp_filter (parameter_gt fs, parameter_gt fc)
Helper function to calculate the filter coefficient 'a'.
This calculates the approximate coefficient using \(a \approx \omega_c T_s = 2\pi f_c / f_s \).
Parameters
fs Sample frequency (Hz).
fc Cutoff frequency (Hz).
Returns
ctrl_gt The calculated filter coefficient.
Definition at line 78 of file discrete_filter.h.
References CTL_PARAM_CONST_2PI, float2ctrl, and fs.
ctl_init_filter_iir1_apf()
void ctl_init_filter_iir1_apf (ctl_filter_IIR1_t * obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order All-Pass Filter.
Based on the Tustin transformation of H(s) = (s - wc) / (s + wc).
Parameters
[out] obj Pointer to the IIR filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Center frequency (Hz).
Definition at line 47 of file ctl_component_discrete.c.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, ctl_clear_filter_iir1(), CTL_PARAM_CONST_PI, and fs.
ctl_init_filter_iir1_hpf()
void ctl_init_filter_iir1_hpf (ctl_filter_IIR1_t * obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order High-Pass Filter (HPF).
Based on the Tustin transformation of H(s) = s / (s + wc).
Parameters
[out] obj Pointer to the IIR filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Cutoff frequency (Hz).
Definition at line 37 of file ctl_component_discrete.c.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, ctl_clear_filter_iir1(), CTL_PARAM_CONST_PI, and fs.
ctl_init_filter_iir1_lpf()
void ctl_init_filter_iir1_lpf (ctl_filter_IIR1_t * obj, parameter_gt fs, parameter_gt fc)
Initializes the filter as a 1st-order Low-Pass Filter (LPF).
Based on the Tustin (trapezoidal) transformation of H(s) = wc / (s + wc).
Parameters
[out] obj Pointer to the IIR filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Cutoff frequency (Hz).
Definition at line 27 of file ctl_component_discrete.c.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, ctl_clear_filter_iir1(), CTL_PARAM_CONST_PI, and fs.
ctl_init_lp_filter()
void ctl_init_lp_filter (ctl_low_pass_filter_t * lpf, parameter_gt fs, parameter_gt fc)
Initializes a first-order low-pass filter object.
Parameters
[out] lpf Pointer to the low-pass filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Cutoff frequency (Hz).
Definition at line 21 of file ctl_component_discrete.c.
References ctl_low_pass_filter_t::a, ctl_helper_lp_filter(), fs, and ctl_low_pass_filter_t::out.
ctl_step_filter_iir1()
GMP_STATIC_INLINE ctrl_gt ctl_step_filter_iir1 (ctl_filter_IIR1_t * obj, ctrl_gt input)
Executes one step of the 1st-order IIR filter.
Parameters
[in,out] obj Pointer to the IIR filter instance.
[in] input The current input sample, x[n].
Returns
ctrl_gt The calculated output sample, y[n].
Definition at line 154 of file discrete_filter.h.
References ctl_filter_IIR1_t::a1, ctl_filter_IIR1_t::b0, ctl_filter_IIR1_t::b1, input, ctl_filter_IIR1_t::out, ctl_filter_IIR1_t::x1, and ctl_filter_IIR1_t::y1.
ctl_step_lowpass_filter()
GMP_STATIC_INLINE ctrl_gt ctl_step_lowpass_filter (ctl_low_pass_filter_t * lpf, ctrl_gt input)
Executes one step of the low-pass filter calculation.
Parameters
[in,out] lpf Pointer to the low-pass filter instance.
[in] input The current input sample, x[n].
Returns
ctrl_gt The calculated output sample, y[n].
Definition at line 100 of file discrete_filter.h.
References ctl_low_pass_filter_t::a, CTL_CTRL_CONST_1, ctl_mul, input, and ctl_low_pass_filter_t::out.