GMP - CTL: Single Phase PFC API
Single Phase PFC API
Digital Power Control Library » Digital Power Topology Presets
Controller for single-phase Power Factor Correction.
Data Structures
struct spfc_t
Data structure for the single-phase PFC controller.
Functions
void ctl_init_spfc_ctrl (spfc_t *pfc, parameter_gt voltage_kp, parameter_gt voltage_Ti, parameter_gt voltage_Td, parameter_gt current_kp, parameter_gt current_Ti, parameter_gt current_Td, parameter_gt fs)
Initializes the single-phase PFC controller.
void ctl_attach_spfc_input (spfc_t *pfc, adc_ift *rect_u, adc_ift *rect_i, adc_ift *dc_u)
Attaches the PFC controller to the physical ADC input interfaces.
GMP_STATIC_INLINE void ctl_clear_pfc_ctrl (spfc_t *pfc)
Clears the internal states of the PFC PID controllers.
GMP_STATIC_INLINE ctrl_gt ctl_step_spfc_ctrl (spfc_t *pfc)
Executes one step of the single-phase PFC control logic.
GMP_STATIC_INLINE void ctl_set_spfc_voltage (spfc_t *pfc, ctrl_gt voltage_set)
Sets the target DC bus voltage.
GMP_STATIC_INLINE void ctl_enable_spfc_ctrl (spfc_t *pfc)
Enables the PFC controller.
GMP_STATIC_INLINE void ctl_disable_spfc_ctrl (spfc_t *pfc)
Disables the PFC controller.
Detailed Description
Controller for single-phase Power Factor Correction.
This file provides a dual-loop controller for a single-phase boost-type PFC converter. The control strategy aims to maintain a stable DC bus voltage while forcing the input AC current to be sinusoidal and in phase with the input voltage, thus achieving a high power factor.
The controller consists of:
An outer voltage loop that regulates the DC bus voltage. Its output sets the amplitude for the current reference.
An inner current loop that shapes the inductor current to follow a rectified sinusoidal reference, which is synchronized with the input voltage.
Function Documentation
ctl_attach_spfc_input()
void ctl_attach_spfc_input (spfc_t * pfc, adc_ift * rect_u, adc_ift * rect_i, adc_ift * dc_u)
Attaches the PFC controller to the physical ADC input interfaces.
Parameters
[out] pfc Pointer to the PFC controller instance.
[in] rect_u Pointer to the ADC interface for the rectified grid voltage.
[in] rect_i Pointer to the ADC interface for the inductor current.
[in] dc_u Pointer to the ADC interface for the DC bus voltage.
ctl_clear_pfc_ctrl()
GMP_STATIC_INLINE void ctl_clear_pfc_ctrl (spfc_t * pfc)
Clears the internal states of the PFC PID controllers.
Parameters
[in,out] pfc Pointer to the PFC controller instance.
Definition at line 94 of file spfc.h.
References ctl_clear_pid(), spfc_t::current_ctrl, and spfc_t::voltage_ctrl.
ctl_disable_spfc_ctrl()
GMP_STATIC_INLINE void ctl_disable_spfc_ctrl (spfc_t * pfc)
Disables the PFC controller.
Parameters
[in,out] pfc Pointer to the PFC controller instance.
Definition at line 154 of file spfc.h.
References spfc_t::flag_enable.
ctl_enable_spfc_ctrl()
GMP_STATIC_INLINE void ctl_enable_spfc_ctrl (spfc_t * pfc)
Enables the PFC controller.
Parameters
[in,out] pfc Pointer to the PFC controller instance.
Definition at line 145 of file spfc.h.
References spfc_t::flag_enable.
ctl_init_spfc_ctrl()
void ctl_init_spfc_ctrl (spfc_t * pfc, parameter_gt voltage_kp, parameter_gt voltage_Ti, parameter_gt voltage_Td, parameter_gt current_kp, parameter_gt current_Ti, parameter_gt current_Td, parameter_gt fs)
Initializes the single-phase PFC controller.
Parameters
[out] pfc Pointer to the PFC controller instance.
[in] voltage_kp Proportional gain for the voltage PID controller.
[in] voltage_Ti Integral time constant for the voltage PID controller.
[in] voltage_Td Derivative time constant for the voltage PID controller.
[in] current_kp Proportional gain for the current PID controller.
[in] current_Ti Integral time constant for the current PID controller.
[in] current_Td Derivative time constant for the current PID controller.
[in] fs Controller execution frequency in Hz.
Definition at line 104 of file ctl_dp_single_phase.c.
References ctl_init_pid_Tmode(), spfc_t::current_ctrl, fs, and spfc_t::voltage_ctrl.
ctl_set_spfc_voltage()
GMP_STATIC_INLINE void ctl_set_spfc_voltage (spfc_t * pfc, ctrl_gt voltage_set)
Sets the target DC bus voltage.
Parameters
[in,out] pfc Pointer to the PFC controller instance.
[in] voltage_set The desired DC bus voltage.
Definition at line 136 of file spfc.h.
References spfc_t::voltage_set.
ctl_step_spfc_ctrl()
GMP_STATIC_INLINE ctrl_gt ctl_step_spfc_ctrl (spfc_t * pfc)
Executes one step of the single-phase PFC control logic.
Parameters
[in,out] pfc Handle of the PFC controller.
Returns
The calculated PWM duty cycle for the Boost converter.
Definition at line 105 of file spfc.h.
References spfc_t::adc_dc_u, spfc_t::adc_rect_i, spfc_t::adc_rect_u, spfc_t::boost_modulation, ctl_mul, ctl_step_pid_ser(), spfc_t::current_ctrl, spfc_t::current_ref, spfc_t::current_set, spfc_t::flag_enable, spfc_t::voltage_ctrl, and spfc_t::voltage_set.