GMP - CTL: Constant V/F Profile Generator
Constant V/F Profile Generator
Motor Control Library » Motor Controller Components
A module to generate a constant Volts/Hertz (V/F) profile.
Data Structures
struct ctl_const_vf_controller
Data structure for the Constant V/F Controller.
Functions
void ctl_init_const_vf_controller (ctl_const_vf_controller *ctrl, parameter_gt isr_freq, parameter_gt frequency, parameter_gt freq_slope, ctrl_gt voltage_bound, ctrl_gt voltage_over_frequency, ctrl_gt voltage_bias)
Initializes the Constant V/F Controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_const_vf (ctl_const_vf_controller *ctrl)
Executes one step of the constant V/F controller.
void ctl_set_const_vf_target_freq (ctl_const_vf_controller *ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the V/F controller.
Detailed Description
A module to generate a constant Volts/Hertz (V/F) profile.
This module is used for open-loop speed control of an AC motor. It generates a variable frequency to control speed and a variable voltage that maintains a constant V/F ratio, which helps in keeping the motor's magnetic flux constant.
Function Documentation
ctl_init_const_vf_controller()
void ctl_init_const_vf_controller (ctl_const_vf_controller * ctrl, parameter_gt isr_freq, parameter_gt frequency, parameter_gt freq_slope, ctrl_gt voltage_bound, ctrl_gt voltage_over_frequency, ctrl_gt voltage_bias)
Initializes the Constant V/F Controller.
Parameters
[out] ctrl Pointer to the ctl_const_vf_controller object.
[in] isr_freq The frequency of the interrupt service routine (ISR) in Hz.
[in] frequency The initial target frequency in Hz.
[in] freq_slope The maximum rate of frequency change in Hz/s.
[in] voltage_bound The maximum output voltage magnitude (p.u.).
[in] voltage_over_frequency The V/F ratio constant (p.u./Hz).
[in] voltage_bias The voltage boost at low frequencies (p.u.).
ctl_set_const_vf_target_freq()
void ctl_set_const_vf_target_freq (ctl_const_vf_controller * ctrl, parameter_gt target_freq, parameter_gt isr_freq)
Sets a new target frequency for the V/F controller.
Parameters
[in,out] ctrl Pointer to the ctl_const_vf_controller object.
[in] target_freq The new target frequency in Hz.
[in] isr_freq The frequency of the interrupt service routine (ISR) in Hz.
Definition at line 280 of file ctl_mc_basic.c.
References float2ctrl, and ctl_const_vf_controller::target_frequency.
ctl_step_const_vf()
GMP_STATIC_INLINE ctrl_gt ctl_step_const_vf (ctl_const_vf_controller * ctrl)
Executes one step of the constant V/F controller.
This function calculates the next frequency and the corresponding voltage magnitude based on the V/F profile. It then generates the next electrical angle.
Parameters
[in,out] ctrl Pointer to the ctl_const_vf_controller object.
Returns
ctrl_gt The calculated target voltage amplitude (p.u.).
Definition at line 339 of file vf_generator.h.
References ctl_mul, ctl_set_ramp_generator_slope(), ctl_step_ramp_generator(), ctl_step_saturation(), ctl_step_slope_limiter(), ctl_const_vf_controller::current_freq, rotation_ift::elec_position, ctl_const_vf_controller::enc, ctl_const_vf_controller::freq_deadband, ctl_const_vf_controller::freq_slope, rotation_ift::position, ctl_const_vf_controller::rg, ctl_const_vf_controller::target_frequency, ctl_const_vf_controller::target_voltage, ctl_const_vf_controller::v_bias, ctl_const_vf_controller::v_over_f, and ctl_const_vf_controller::volt_sat.