GMP - CTL: Buck Controller API
Buck Controller API
Digital Power Control Library » Digital Power Topology Presets
Functions and data structures for Buck converter control.
Data Structures
struct buck_ctrl_t
Core data structure for the Buck controller.
Macros
#define CTL_BUCK_CTRL_OUTPUT_WITHOUT_UIN
Functions
void ctl_init_buck_ctrl (buck_ctrl_t *buck, parameter_gt v_kp, parameter_gt v_Ti, parameter_gt v_Td, parameter_gt i_kp, parameter_gt i_Ti, parameter_gt i_Td, parameter_gt uin_min, parameter_gt uin_max, parameter_gt fc, parameter_gt fs)
Initializes the Buck controller with specified PID and filter parameters.
void ctl_attach_buck_ctrl_input (buck_ctrl_t *buck, adc_ift *uo, adc_ift *il, adc_ift *uin)
Attaches the controller to the physical ADC input interfaces.
GMP_STATIC_INLINE void ctl_clear_buck_ctrl (buck_ctrl_t *buck)
Clears the internal states and integral terms of the PID controllers.
GMP_STATIC_INLINE ctrl_gt ctl_step_buck_ctrl (buck_ctrl_t *buck)
Executes one step of the Buck control logic.
GMP_STATIC_INLINE void ctl_buck_ctrl_openloop_mode (buck_ctrl_t *buck)
Switches the controller to open-loop Voltage mode.
GMP_STATIC_INLINE void ctl_set_buck_ctrl_voltage_openloop (buck_ctrl_t *buck, ctrl_gt vo)
Sets the target intermediate voltage command in open-loop mode.
GMP_STATIC_INLINE void ctl_buck_ctrl_current_mode (buck_ctrl_t *buck)
Switches the controller to closed-loop Current mode.
GMP_STATIC_INLINE void ctl_set_buck_ctrl_current (buck_ctrl_t *buck, ctrl_gt il)
Sets the target inductor current in Current mode.
GMP_STATIC_INLINE void ctl_buck_ctrl_voltage_mode (buck_ctrl_t *buck)
Switches the controller to closed-loop Voltage mode.
GMP_STATIC_INLINE void ctl_set_buck_ctrl_voltage (buck_ctrl_t *buck, ctrl_gt uo)
Sets the target output voltage in Voltage mode.
GMP_STATIC_INLINE void ctl_enable_buck_ctrl (buck_ctrl_t *buck)
Enables the entire Buck controller system.
GMP_STATIC_INLINE void ctl_disable_buck_ctrl (buck_ctrl_t *buck)
Disables the entire Buck controller system.
GMP_STATIC_INLINE ctrl_gt ctl_get_buck_ctrl_modulation (buck_ctrl_t *buck)
Gets the last calculated PWM duty cycle.
Detailed Description
Functions and data structures for Buck converter control.
Contains all configurations, data structures, and functions for the Buck controller.
Buck Controller Usage Guide
This module implements a standard dual-loop (voltage and current) controller for a DC-DC Buck converter.
1. Initialization
Call ctl_init_buck_ctrl to configure the PID parameters for both the outer voltage loop and the inner current loop.
Call ctl_attach_buck_ctrl_input to link the controller to the ADC interfaces for sensing input/output voltages and inductor current.
2. Mode Selection
The controller supports several operating modes:
Voltage Mode: Closed-loop voltage control. Use ctl_buck_ctrl_voltage_mode to enter and ctl_set_buck_ctrl_voltage to set the target output voltage.
Current Mode: Closed-loop current control (voltage loop is bypassed). Use ctl_buck_ctrl_current_mode to enter and ctl_set_buck_ctrl_current to set the target inductor current.
Open Loop Mode: Directly control the output voltage command. Use ctl_buck_ctrl_openloop_mode to enter and ctl_set_buck_ctrl_voltage_openloop to set the voltage command.
3. Execution
Call ctl_step_buck_ctrl periodically in a timer ISR to execute one step of the control logic.
Call ctl_get_buck_ctrl_modulation to retrieve the calculated PWM duty cycle and apply it to your PWM peripheral.
4. Control
Use ctl_enable_buck_ctrl and ctl_disable_buck_ctrl for master control.
Use ctl_clear_buck_ctrl to reset PID integrators before enabling.
Macro Definition Documentation
CTL_BUCK_CTRL_OUTPUT_WITHOUT_UIN
#define CTL_BUCK_CTRL_OUTPUT_WITHOUT_UIN
Definition at line 67 of file buck.h.
Function Documentation
ctl_attach_buck_ctrl_input()
void ctl_attach_buck_ctrl_input (buck_ctrl_t * buck, adc_ift * uo, adc_ift * il, adc_ift * uin)
Attaches the controller to the physical ADC input interfaces.
Parameters
[out] buck Pointer to the Buck controller instance.
[in] uo Pointer to the ADC interface for the output capacitor voltage.
[in] il Pointer to the ADC interface for the inductor current.
[in] uin Pointer to the ADC interface for the input voltage.
Definition at line 45 of file ctl_dp_basic.c.
References buck_ctrl_t::adc_il, buck_ctrl_t::adc_ui, buck_ctrl_t::adc_uo, il, and uin.
ctl_buck_ctrl_current_mode()
GMP_STATIC_INLINE void ctl_buck_ctrl_current_mode (buck_ctrl_t * buck)
Switches the controller to closed-loop Current mode.
The outer voltage loop is disabled, and the inner current loop directly tracks the user-specified current setpoint.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 239 of file buck.h.
References buck_ctrl_t::flag_enable_current_ctrl, and buck_ctrl_t::flag_enable_voltage_ctrl.
ctl_buck_ctrl_openloop_mode()
GMP_STATIC_INLINE void ctl_buck_ctrl_openloop_mode (buck_ctrl_t * buck)
Switches the controller to open-loop Voltage mode.
Both PID loops are disabled. The output is determined directly by the value set with ctl_set_buck_ctrl_voltage_openloop.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 217 of file buck.h.
References buck_ctrl_t::flag_enable_current_ctrl, and buck_ctrl_t::flag_enable_voltage_ctrl.
ctl_buck_ctrl_voltage_mode()
GMP_STATIC_INLINE void ctl_buck_ctrl_voltage_mode (buck_ctrl_t * buck)
Switches the controller to closed-loop Voltage mode.
Both the inner current loop and outer voltage loop are enabled.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 261 of file buck.h.
References buck_ctrl_t::flag_enable_current_ctrl, and buck_ctrl_t::flag_enable_voltage_ctrl.
ctl_clear_buck_ctrl()
GMP_STATIC_INLINE void ctl_clear_buck_ctrl (buck_ctrl_t * buck)
Clears the internal states and integral terms of the PID controllers.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 154 of file buck.h.
References ctl_clear_pid(), buck_ctrl_t::current_ff, buck_ctrl_t::current_pid, buck_ctrl_t::voltage_ff, and buck_ctrl_t::voltage_pid.
ctl_disable_buck_ctrl()
GMP_STATIC_INLINE void ctl_disable_buck_ctrl (buck_ctrl_t * buck)
Disables the entire Buck controller system.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 291 of file buck.h.
References buck_ctrl_t::flag_enable_system.
ctl_enable_buck_ctrl()
GMP_STATIC_INLINE void ctl_enable_buck_ctrl (buck_ctrl_t * buck)
Enables the entire Buck controller system.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Definition at line 282 of file buck.h.
References buck_ctrl_t::flag_enable_system.
ctl_get_buck_ctrl_modulation()
GMP_STATIC_INLINE ctrl_gt ctl_get_buck_ctrl_modulation (buck_ctrl_t * buck)
Gets the last calculated PWM duty cycle.
Parameters
[in] buck Pointer to the Buck controller instance.
Returns
The last calculated PWM duty cycle (per-unit).
Definition at line 301 of file buck.h.
References buck_ctrl_t::pwm_out_pu.
ctl_init_buck_ctrl()
void ctl_init_buck_ctrl (buck_ctrl_t * buck, parameter_gt v_kp, parameter_gt v_Ti, parameter_gt v_Td, parameter_gt i_kp, parameter_gt i_Ti, parameter_gt i_Td, parameter_gt uin_min, parameter_gt uin_max, parameter_gt fc, parameter_gt fs)
Initializes the Buck controller with specified PID and filter parameters.
Parameters
[out] buck Pointer to the Buck controller instance to be initialized.
[in] v_kp Proportional gain for the voltage PID controller.
[in] v_Ti Integral time constant for the voltage PID controller.
[in] v_Td Derivative time constant for the voltage PID controller.
[in] i_kp Proportional gain for the current PID controller.
[in] i_Ti Integral time constant for the current PID controller.
[in] i_Td Derivative time constant for the current PID controller.
[in] uin_min Minimum input voltage for saturation, to prevent division by zero.
[in] uin_max Maximum input voltage for saturation.
[in] fc Cutoff frequency for the low-pass filters on sensor inputs.
[in] fs Controller execution frequency in Hz.
Definition at line 22 of file ctl_dp_basic.c.
References ctl_clear_buck_ctrl(), ctl_disable_buck_ctrl(), ctl_init_lp_filter(), ctl_init_pid_Tmode(), ctl_init_saturation(), buck_ctrl_t::current_pid, fs, buck_ctrl_t::lpf_il, buck_ctrl_t::lpf_ui, buck_ctrl_t::lpf_uo, buck_ctrl_t::modulation_saturation, and buck_ctrl_t::voltage_pid.
ctl_set_buck_ctrl_current()
GMP_STATIC_INLINE void ctl_set_buck_ctrl_current (buck_ctrl_t * buck, ctrl_gt il)
Sets the target inductor current in Current mode.
Parameters
[in,out] buck Pointer to the Buck controller instance.
[in] il The target inductor current.
Definition at line 251 of file buck.h.
References buck_ctrl_t::current_set, and il.
ctl_set_buck_ctrl_voltage()
GMP_STATIC_INLINE void ctl_set_buck_ctrl_voltage (buck_ctrl_t * buck, ctrl_gt uo)
Sets the target output voltage in Voltage mode.
Parameters
[in,out] buck Pointer to the Buck controller instance.
[in] uo The target output voltage.
Definition at line 273 of file buck.h.
References buck_ctrl_t::voltage_set.
ctl_set_buck_ctrl_voltage_openloop()
GMP_STATIC_INLINE void ctl_set_buck_ctrl_voltage_openloop (buck_ctrl_t * buck, ctrl_gt vo)
Sets the target intermediate voltage command in open-loop mode.
Parameters
[in,out] buck Pointer to the Buck controller instance.
[in] vo The desired intermediate voltage command.
Definition at line 229 of file buck.h.
References buck_ctrl_t::voltage_out.
ctl_step_buck_ctrl()
GMP_STATIC_INLINE ctrl_gt ctl_step_buck_ctrl (buck_ctrl_t * buck)
Executes one step of the Buck control logic.
This function performs the cascaded voltage and current control loop calculations. It should be called periodically at the frequency specified during initialization.
Parameters
[in,out] buck Pointer to the Buck controller instance.
Returns
The calculated PWM duty cycle (per-unit).
Definition at line 170 of file buck.h.
References buck_ctrl_t::adc_il, buck_ctrl_t::adc_ui, buck_ctrl_t::adc_uo, ctl_div, ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctl_step_saturation(), buck_ctrl_t::current_ff, buck_ctrl_t::current_pid, buck_ctrl_t::current_set, buck_ctrl_t::flag_enable_current_ctrl, buck_ctrl_t::flag_enable_system, buck_ctrl_t::flag_enable_voltage_ctrl, float2ctrl, buck_ctrl_t::lpf_il, buck_ctrl_t::lpf_ui, buck_ctrl_t::lpf_uo, buck_ctrl_t::modulation_saturation, ctl_low_pass_filter_t::out, buck_ctrl_t::pwm_out_pu, buck_ctrl_t::ui_sat, buck_ctrl_t::voltage_ff, buck_ctrl_t::voltage_out, buck_ctrl_t::voltage_pid, and buck_ctrl_t::voltage_set.