GMP - CTL: Speed Calculator
Speed Calculator
Motor Control Library » Motor Controller Components » Encoder Interface
Calculates motor speed by differentiating position over time.
Data Structures
struct spd_calculator_t
Data structure for the speed calculator.
Functions
void ctl_init_spd_calculator (spd_calculator_t *sc, rotation_ift *pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, parameter_gt speed_filter_fc)
Initializes the speed calculator.
void ctl_init_spd_calculator_elecpos (spd_calculator_t *sc, rotation_ift *pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, uint16_t pole_pairs, parameter_gt speed_filter_fc)
Initializes the speed calculator.
GMP_STATIC_INLINE void ctl_step_spd_calc (spd_calculator_t *sc)
Executes one step of the speed calculation.
Detailed Description
Calculates motor speed by differentiating position over time.
Function Documentation
ctl_init_spd_calculator()
void ctl_init_spd_calculator (spd_calculator_t * sc, rotation_ift * pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, parameter_gt speed_filter_fc)
Initializes the speed calculator.
Parameters
[out] sc Pointer to the speed calculator structure.
[in] pos_encif Pointer to the source position encoder interface.
[in] control_law_freq Frequency of the main control loop in Hz.
[in] speed_calc_div Division factor for the speed calculation frequency (relative to control_law_freq).
[in] rated_speed_rpm The rated speed of the motor in RPM, used as the base for per-unit speed.
[in] pole_pairs Number of motor pole pairs.
[in] speed_filter_fc Cutoff frequency for the speed low-pass filter in Hz.
Definition at line 69 of file ctl_mc_basic.c.
References ctl_init_divider(), ctl_init_lp_filter(), spd_calculator_t::div, spd_calculator_t::encif, float2ctrl, spd_calculator_t::old_position, spd_calculator_t::pos_encif, spd_calculator_t::scale_factor, spd_calculator_t::spd_filter, and velocity_ift::speed.
ctl_init_spd_calculator_elecpos()
void ctl_init_spd_calculator_elecpos (spd_calculator_t * sc, rotation_ift * pos_encif, parameter_gt control_law_freq, uint32_t speed_calc_div, parameter_gt rated_speed_rpm, uint16_t pole_pairs, parameter_gt speed_filter_fc)
Initializes the speed calculator.
Parameters
[out] sc Pointer to the speed calculator structure.
[in] pos_encif Pointer to the source position encoder interface, if pos = elec_pos.
[in] control_law_freq Frequency of the main control loop in Hz.
[in] speed_calc_div Division factor for the speed calculation frequency (relative to control_law_freq).
[in] rated_speed_rpm The rated speed of the motor in RPM, used as the base for per-unit speed.
[in] pole_pairs Number of motor pole pairs.
[in] speed_filter_fc Cutoff frequency for the speed low-pass filter in Hz.
Definition at line 100 of file ctl_mc_basic.c.
References ctl_init_divider(), ctl_init_lp_filter(), spd_calculator_t::div, spd_calculator_t::encif, float2ctrl, spd_calculator_t::old_position, spd_calculator_t::pos_encif, spd_calculator_t::scale_factor, spd_calculator_t::spd_filter, and velocity_ift::speed.
ctl_step_spd_calc()
GMP_STATIC_INLINE void ctl_step_spd_calc (spd_calculator_t * sc)
Executes one step of the speed calculation.
This function should be called periodically. It calculates the speed based on the change in position since the last call, filters it, and updates the output. The internal divider determines the actual execution rate.
Parameters
[in,out] sc Pointer to the speed calculator structure.
Definition at line 293 of file encoder.h.
References CTL_CTRL_CONST_1, CTL_CTRL_CONST_1_OVER_2, ctl_get_encoder_position(), ctl_mul, ctl_step_divider(), ctl_step_lowpass_filter(), spd_calculator_t::div, spd_calculator_t::encif, spd_calculator_t::old_position, spd_calculator_t::pos_encif, spd_calculator_t::scale_factor, spd_calculator_t::spd_filter, and velocity_ift::speed.