GMP - CTL: MPPT(Maximum Power Point Tracking) API
MPPT(Maximum Power Point Tracking) API
Digital Power Control Library » Digital Power Components
Maximum Power Point Tracking algorithm.
Data Structures
struct mppt_inc_algo_t
Data structure for the Incremental Conductance (INC) MPPT algorithm.
struct mppt_PnO_algo_t
Data structure for the Perturb and Observe (P&O) MPPT algorithm.
Macros
#define CTL_MPPT_PNO_EPSILON (float2ctrl(-0.000001))
A small epsilon value to create a dead-zone around zero for power change.
Functions
void ctl_init_mppt_inc_algo (mppt_inc_algo_t *_mppt, adc_ift *u_in, adc_ift *i_in, parameter_gt voltage_0, parameter_gt voltage_step, parameter_gt max_voltage, parameter_gt min_voltage)
Initializes the Incremental Conductance MPPT algorithm module.
GMP_STATIC_INLINE void ctl_clear_mppt_inc_algo (mppt_inc_algo_t *_mppt)
Clears the internal states of the INC MPPT algorithm.
GMP_STATIC_INLINE ctrl_gt ctl_step_mppt_inc_algo (mppt_inc_algo_t *_mppt_obj)
Executes one step of the Incremental Conductance MPPT algorithm.
GMP_STATIC_INLINE void ctl_enable_mppt_inc_algo (mppt_inc_algo_t *_mppt_obj)
Enables the MPPT algorithm.
GMP_STATIC_INLINE void ctl_disable_mppt_inc_algo (mppt_inc_algo_t *_mppt_obj)
Disables the MPPT algorithm.
void ctl_init_mppt_PnO_algo (mppt_PnO_algo_t *_mppt_obj, parameter_gt voltage_0, parameter_gt searching_range_max, parameter_gt searching_range_min, parameter_gt searching_step_max, parameter_gt searching_step_min, parameter_gt attenuation_time, parameter_gt freq_mppt, parameter_gt freq_ctrl)
Initializes the P&O MPPT algorithm module.
GMP_STATIC_INLINE ctrl_gt ctl_step_mppt_PnO_algo (mppt_PnO_algo_t *mppt, ctrl_gt current_voltage, ctrl_gt current_current)
Executes one step of the P&O MPPT algorithm.
GMP_STATIC_INLINE void ctl_clear_mppt_PnO_algo (mppt_PnO_algo_t *mppt)
Clears the internal states of the MPPT algorithm.
GMP_STATIC_INLINE void ctl_enable_mppt_PnO_algo (mppt_PnO_algo_t *mppt)
Enables the MPPT algorithm.
GMP_STATIC_INLINE void ctl_disable_mppt_PnO_algo (mppt_PnO_algo_t *mppt)
Disables the MPPT algorithm.
GMP_STATIC_INLINE void ctl_enable_adaptive_step_size (mppt_PnO_algo_t *mppt)
Enables the adaptive step size feature.
GMP_STATIC_INLINE void ctl_disable_adaptive_step_size (mppt_PnO_algo_t *mppt)
Disables the adaptive step size feature, using a fixed step size.
Detailed Description
Maximum Power Point Tracking algorithm.
Contains algorithms for Maximum Power Point Tracking.
Macro Definition Documentation
CTL_MPPT_PNO_EPSILON
#define CTL_MPPT_PNO_EPSILON (float2ctrl(-0.000001))
A small epsilon value to create a dead-zone around zero for power change.
This helps prevent the algorithm from reacting to negligible power fluctuations caused by noise or floating-point inaccuracies.
Definition at line 35 of file PnO_algorithm.h.
Function Documentation
ctl_clear_mppt_inc_algo()
GMP_STATIC_INLINE void ctl_clear_mppt_inc_algo (mppt_inc_algo_t * _mppt)
Clears the internal states of the INC MPPT algorithm.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 86 of file INC_algorithm.h.
References mppt_inc_algo_t::current_power, mppt_inc_algo_t::last_current, and mppt_inc_algo_t::last_voltage.
ctl_clear_mppt_PnO_algo()
GMP_STATIC_INLINE void ctl_clear_mppt_PnO_algo (mppt_PnO_algo_t * mppt)
Clears the internal states of the MPPT algorithm.
Resets power history, filters, and sets the step size back to maximum.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 196 of file PnO_algorithm.h.
References ctl_clear_divider(), ctl_clear_lowpass_filter(), mppt_PnO_algo_t::current_power, mppt_PnO_algo_t::delta_power, mppt_PnO_algo_t::delta_voltage, mppt_PnO_algo_t::divider, mppt_PnO_algo_t::last_power, mppt_PnO_algo_t::last_voltage, mppt_PnO_algo_t::mppt_record, mppt_PnO_algo_t::power_filter, mppt_PnO_algo_t::searching_step_max, and mppt_PnO_algo_t::voltage_increment.
ctl_disable_adaptive_step_size()
GMP_STATIC_INLINE void ctl_disable_adaptive_step_size (mppt_PnO_algo_t * mppt)
Disables the adaptive step size feature, using a fixed step size.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 245 of file PnO_algorithm.h.
References mppt_PnO_algo_t::flag_enable_adaptive_step_size.
ctl_disable_mppt_inc_algo()
GMP_STATIC_INLINE void ctl_disable_mppt_inc_algo (mppt_inc_algo_t * _mppt_obj)
Disables the MPPT algorithm.
Parameters
[in,out] _mppt_obj Pointer to the MPPT algorithm instance.
Definition at line 171 of file INC_algorithm.h.
References mppt_inc_algo_t::flag_enable_mppt.
ctl_disable_mppt_PnO_algo()
GMP_STATIC_INLINE void ctl_disable_mppt_PnO_algo (mppt_PnO_algo_t * mppt)
Disables the MPPT algorithm.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 225 of file PnO_algorithm.h.
References mppt_PnO_algo_t::flag_enable_mppt.
ctl_enable_adaptive_step_size()
GMP_STATIC_INLINE void ctl_enable_adaptive_step_size (mppt_PnO_algo_t * mppt)
Enables the adaptive step size feature.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 235 of file PnO_algorithm.h.
References mppt_PnO_algo_t::flag_enable_adaptive_step_size.
ctl_enable_mppt_inc_algo()
GMP_STATIC_INLINE void ctl_enable_mppt_inc_algo (mppt_inc_algo_t * _mppt_obj)
Enables the MPPT algorithm.
Parameters
[in,out] _mppt_obj Pointer to the MPPT algorithm instance.
Definition at line 162 of file INC_algorithm.h.
References mppt_inc_algo_t::flag_enable_mppt.
ctl_enable_mppt_PnO_algo()
GMP_STATIC_INLINE void ctl_enable_mppt_PnO_algo (mppt_PnO_algo_t * mppt)
Enables the MPPT algorithm.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
Definition at line 215 of file PnO_algorithm.h.
References mppt_PnO_algo_t::flag_enable_mppt.
ctl_init_mppt_inc_algo()
void ctl_init_mppt_inc_algo (mppt_inc_algo_t * _mppt, adc_ift * u_in, adc_ift * i_in, parameter_gt voltage_0, parameter_gt voltage_step, parameter_gt max_voltage, parameter_gt min_voltage)
Initializes the Incremental Conductance MPPT algorithm module.
Parameters
[out] _mppt Pointer to the MPPT algorithm instance.
[in] u_in Pointer to the voltage ADC interface.
[in] i_in Pointer to the current ADC interface.
[in] voltage_0 The initial voltage reference output by the algorithm.
[in] voltage_step The fixed perturbation step size.
[in] max_voltage The absolute maximum voltage limit.
[in] min_voltage The absolute minimum voltage limit.
Definition at line 56 of file ctl_dp_mppt.c.
References mppt_inc_algo_t::adc_i, mppt_inc_algo_t::adc_u, ctl_clear_mppt_inc_algo(), ctl_disable_mppt_inc_algo(), mppt_inc_algo_t::current_power, mppt_inc_algo_t::flag_enable_mppt, mppt_inc_algo_t::last_current, mppt_inc_algo_t::last_voltage, mppt_inc_algo_t::max_voltage_limit, mppt_inc_algo_t::min_voltage_limit, mppt_inc_algo_t::v_ref, and mppt_inc_algo_t::voltage_increment.
ctl_init_mppt_PnO_algo()
void ctl_init_mppt_PnO_algo (mppt_PnO_algo_t * _mppt_obj, parameter_gt voltage_0, parameter_gt searching_range_max, parameter_gt searching_range_min, parameter_gt searching_step_max, parameter_gt searching_step_min, parameter_gt attenuation_time, parameter_gt freq_mppt, parameter_gt freq_ctrl)
Initializes the P&O MPPT algorithm module.
Parameters
[out] _mppt_obj Pointer to the MPPT algorithm instance.
[in] voltage_0 The initial voltage reference output by the algorithm.
[in] searching_range_max The absolute maximum voltage limit.
[in] searching_range_min The absolute minimum voltage limit.
[in] searching_step_max The maximum perturbation step size, used for fast tracking.
[in] searching_step_min The minimum perturbation step size, used for steady-state fine-tuning.
[in] attenuation_time Time constant for the convergence of the adaptive step size.
[in] freq_mppt The desired execution frequency of the MPPT algorithm (e.g., 50 Hz).
[in] freq_ctrl The frequency of the main control ISR that calls this function.
Definition at line 21 of file ctl_dp_mppt.c.
References ctl_clear_mppt_PnO_algo(), ctl_disable_mppt_PnO_algo(), ctl_enable_adaptive_step_size(), ctl_helper_lp_filter(), ctl_init_divider(), ctl_init_lp_filter(), mppt_PnO_algo_t::divider, mppt_PnO_algo_t::inc_attenuation, mppt_PnO_algo_t::max_voltage_limit, mppt_PnO_algo_t::min_voltage_limit, mppt_PnO_algo_t::power_filter, mppt_PnO_algo_t::searching_step_max, mppt_PnO_algo_t::searching_step_min, and mppt_PnO_algo_t::v_ref.
ctl_step_mppt_inc_algo()
GMP_STATIC_INLINE ctrl_gt ctl_step_mppt_inc_algo (mppt_inc_algo_t * _mppt_obj)
Executes one step of the Incremental Conductance MPPT algorithm.
This function should be called periodically. It calculates the incremental and instantaneous conductance to determine the direction of voltage change needed to track the maximum power point.
Parameters
[in,out] _mppt_obj Pointer to the MPPT algorithm instance.
Returns
The updated voltage reference (v_ref) to be used by the power converter.
Definition at line 101 of file INC_algorithm.h.
References mppt_inc_algo_t::adc_i, mppt_inc_algo_t::adc_u, ctl_div, ctl_mul, ctl_sat, mppt_inc_algo_t::flag_enable_mppt, mppt_inc_algo_t::last_current, mppt_inc_algo_t::last_voltage, mppt_inc_algo_t::max_voltage_limit, mppt_inc_algo_t::min_voltage_limit, mppt_inc_algo_t::v_ref, and mppt_inc_algo_t::voltage_increment.
ctl_step_mppt_PnO_algo()
GMP_STATIC_INLINE ctrl_gt ctl_step_mppt_PnO_algo (mppt_PnO_algo_t * mppt, ctrl_gt current_voltage, ctrl_gt current_current)
Executes one step of the P&O MPPT algorithm.
This function should be called periodically. It calculates the current power, compares it with the previous power, and adjusts the output voltage reference (v_ref) accordingly to track the maximum power point.
Parameters
[in,out] mppt Pointer to the MPPT algorithm instance.
[in] current_voltage The current measured voltage from the solar panel.
[in] current_current The current measured current from the solar panel.
Returns
The updated voltage reference (v_ref) to be used by the power converter.
Definition at line 108 of file PnO_algorithm.h.
References CTL_CTRL_CONST_1, CTL_MPPT_PNO_EPSILON, ctl_mul, ctl_sat, ctl_step_divider(), ctl_step_lowpass_filter(), mppt_PnO_algo_t::current_power, mppt_PnO_algo_t::delta_power, mppt_PnO_algo_t::delta_voltage, mppt_PnO_algo_t::divider, mppt_PnO_algo_t::flag_enable_adaptive_step_size, mppt_PnO_algo_t::flag_enable_mppt, mppt_PnO_algo_t::inc_attenuation, mppt_PnO_algo_t::last_power, mppt_PnO_algo_t::last_voltage, mppt_PnO_algo_t::max_voltage_limit, mppt_PnO_algo_t::min_voltage_limit, mppt_PnO_algo_t::mppt_record, mppt_PnO_algo_t::power_filter, mppt_PnO_algo_t::searching_step_max, mppt_PnO_algo_t::searching_step_min, mppt_PnO_algo_t::v_ref, and mppt_PnO_algo_t::voltage_increment.