GMP - CTL: Functions
Functions
Motor Control Library » Motor Controller Suite » Sensored ACM FOC Controller
API functions for controlling and configuring the ACM controller.
Functions
void ctl_init_acm_sensored_bare_controller (acm_sensored_bare_controller_t *ctrl, acm_sensored_bare_controller_init_t *init)
Initializes the sensored ACM controller.
void ctl_attach_acm_sensored_bare_output (acm_sensored_bare_controller_t *ctrl, tri_pwm_ift *pwm_out)
Attaches the PWM output interface to the controller.
void ctl_attach_acm_sensored_bare_rotor_postion (acm_sensored_bare_controller_t *ctrl, rotation_ift *rotor_enc)
Attaches the rotor position encoder interface to the controller.
GMP_STATIC_INLINE void ctl_clear_acm_sensored_ctrl (acm_sensored_bare_controller_t *ctrl)
Resets the internal states of the PID controllers.
GMP_STATIC_INLINE void ctl_step_acm_sensored_ctrl (acm_sensored_bare_controller_t *ctrl)
Executes one step of the sensored ACM control algorithm. This function should be called periodically in the main control ISR.
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl (acm_sensored_bare_controller_t *ctrl)
Enables the entire controller.
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl (acm_sensored_bare_controller_t *ctrl)
Disables the entire controller.
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl_output (acm_sensored_bare_controller_t *ctrl)
Enables the PWM output.
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl_output (acm_sensored_bare_controller_t *ctrl)
Disables the PWM output.
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl_flux_est (acm_sensored_bare_controller_t *ctrl)
Enables the flux estimator.
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl_flux_est (acm_sensored_bare_controller_t *ctrl)
Disables the flux estimator.
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_valphabeta_mode (acm_sensored_bare_controller_t *ctrl)
Sets the controller to Valpha-Vbeta open-loop mode.
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_valphabeta (acm_sensored_bare_controller_t *ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target Valpha and Vbeta voltages.
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_voltage_mode (acm_sensored_bare_controller_t *ctrl)
Sets the controller to Vd-Vq open-loop voltage mode.
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_vdq_ff (acm_sensored_bare_controller_t *ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the feedforward/reference Vd and Vq voltages.
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_current_mode (acm_sensored_bare_controller_t *ctrl)
Sets the controller to Id-Iq closed-loop current mode.
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_idq_ff (acm_sensored_bare_controller_t *ctrl, ctrl_gt id, ctrl_gt iq)
Sets the feedforward/reference Id and Iq currents.
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_velocity_mode (acm_sensored_bare_controller_t *ctrl)
Sets the controller to closed-loop velocity mode.
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_speed (acm_sensored_bare_controller_t *ctrl, ctrl_gt spd)
Sets the target speed reference.
Detailed Description
API functions for controlling and configuring the ACM controller.
Function Documentation
ctl_acm_sensored_ctrl_current_mode()
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_current_mode (acm_sensored_bare_controller_t * ctrl)
Sets the controller to Id-Iq closed-loop current mode.
Definition at line 468 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_current_ctrl, acm_sensored_bare_controller_t::flag_enable_modulation, acm_sensored_bare_controller_t::flag_enable_output, and acm_sensored_bare_controller_t::flag_enable_velocity_ctrl.
ctl_acm_sensored_ctrl_valphabeta_mode()
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_valphabeta_mode (acm_sensored_bare_controller_t * ctrl)
Sets the controller to Valpha-Vbeta open-loop mode.
Definition at line 434 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_current_ctrl, acm_sensored_bare_controller_t::flag_enable_modulation, acm_sensored_bare_controller_t::flag_enable_output, and acm_sensored_bare_controller_t::flag_enable_velocity_ctrl.
ctl_acm_sensored_ctrl_velocity_mode()
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_velocity_mode (acm_sensored_bare_controller_t * ctrl)
Sets the controller to closed-loop velocity mode.
Definition at line 484 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_current_ctrl, acm_sensored_bare_controller_t::flag_enable_modulation, acm_sensored_bare_controller_t::flag_enable_output, and acm_sensored_bare_controller_t::flag_enable_velocity_ctrl.
ctl_acm_sensored_ctrl_voltage_mode()
GMP_STATIC_INLINE void ctl_acm_sensored_ctrl_voltage_mode (acm_sensored_bare_controller_t * ctrl)
Sets the controller to Vd-Vq open-loop voltage mode.
Definition at line 452 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_current_ctrl, acm_sensored_bare_controller_t::flag_enable_modulation, acm_sensored_bare_controller_t::flag_enable_output, and acm_sensored_bare_controller_t::flag_enable_velocity_ctrl.
ctl_attach_acm_sensored_bare_output()
void ctl_attach_acm_sensored_bare_output (acm_sensored_bare_controller_t * ctrl, tri_pwm_ift * pwm_out)
Attaches the PWM output interface to the controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] pwm_out Pointer to the PWM interface.
Definition at line 158 of file ctl_mc_acm_sensored_ctrl.c.
References acm_sensored_bare_controller_t::pwm_out.
ctl_attach_acm_sensored_bare_rotor_postion()
void ctl_attach_acm_sensored_bare_rotor_postion (acm_sensored_bare_controller_t * ctrl, rotation_ift * rotor_enc)
Attaches the rotor position encoder interface to the controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] rotor_enc Pointer to the rotor position encoder interface.
Definition at line 168 of file ctl_mc_acm_sensored_ctrl.c.
References acm_sensored_bare_controller_t::rotor_pos.
ctl_clear_acm_sensored_ctrl()
GMP_STATIC_INLINE void ctl_clear_acm_sensored_ctrl (acm_sensored_bare_controller_t * ctrl)
Resets the internal states of the PID controllers.
Parameters
[in,out] ctrl Pointer to the controller structure.
Definition at line 267 of file acm_sensored_ctrl.h.
References ctl_clear_discrete_pid(), ctl_clear_pid(), ctl_clear_tracking_continuous_pid(), ctl_clear_tracking_pid(), acm_sensored_bare_controller_t::current_ctrl, phase_d, phase_q, and acm_sensored_bare_controller_t::spd_ctrl.
ctl_disable_acm_sensored_ctrl()
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl (acm_sensored_bare_controller_t * ctrl)
Disables the entire controller.
Definition at line 406 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_controller.
ctl_disable_acm_sensored_ctrl_flux_est()
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl_flux_est (acm_sensored_bare_controller_t * ctrl)
Disables the flux estimator.
Definition at line 426 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_flux_est.
ctl_disable_acm_sensored_ctrl_output()
GMP_STATIC_INLINE void ctl_disable_acm_sensored_ctrl_output (acm_sensored_bare_controller_t * ctrl)
Disables the PWM output.
Definition at line 416 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_output.
ctl_enable_acm_sensored_ctrl()
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl (acm_sensored_bare_controller_t * ctrl)
Enables the entire controller.
Definition at line 401 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_controller.
ctl_enable_acm_sensored_ctrl_flux_est()
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl_flux_est (acm_sensored_bare_controller_t * ctrl)
Enables the flux estimator.
Definition at line 421 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_flux_est.
ctl_enable_acm_sensored_ctrl_output()
GMP_STATIC_INLINE void ctl_enable_acm_sensored_ctrl_output (acm_sensored_bare_controller_t * ctrl)
Enables the PWM output.
Definition at line 411 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::flag_enable_output.
ctl_init_acm_sensored_bare_controller()
void ctl_init_acm_sensored_bare_controller (acm_sensored_bare_controller_t * ctrl, acm_sensored_bare_controller_init_t * init)
Initializes the sensored ACM controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] init Pointer to the initialization parameters.
Definition at line 8 of file ctl_mc_acm_sensored_ctrl.c.
References ctl_acm_sensored_ctrl_valphabeta_mode(), ctl_attach_mtr_position(), ctl_attach_mtr_velocity(), ctl_disable_acm_sensored_ctrl(), ctl_enable_acm_sensored_ctrl_flux_est(), ctl_init_const_slope_f_controller(), ctl_init_discrete_pid(), ctl_init_im_spd_calc(), ctl_init_pid_Tmode(), ctl_init_spd_calculator(), ctl_init_tracking_continuous_pid(), ctl_init_tracking_pid(), ctl_set_discrete_pid_limit(), ctl_set_pid_limit(), ctl_vector2_clear(), ctl_vector3_clear(), acm_sensored_bare_controller_t::current_ctrl, ctl_slope_f_controller::enc, spd_calculator_t::encif, float2ctrl, acm_sensored_bare_controller_t::flux_calc, acm_sensored_bare_controller_t::iab0, acm_sensored_bare_controller_t::idq0, acm_sensored_bare_controller_t::idq_ff, acm_sensored_bare_controller_t::idq_set, init(), acm_sensored_bare_controller_t::mtr_interface, phase_d, phase_q, acm_sensored_bare_controller_t::rg, acm_sensored_bare_controller_t::rotor_pos, acm_sensored_bare_controller_t::spd_ctrl, acm_sensored_bare_controller_t::spd_enc, acm_sensored_bare_controller_t::speed_pu_rg_sf, acm_sensored_bare_controller_t::speed_set, acm_sensored_bare_controller_t::uab0, acm_sensored_bare_controller_t::udq0, acm_sensored_bare_controller_t::vab0_set, acm_sensored_bare_controller_t::vdq_ff, and acm_sensored_bare_controller_t::vdq_set.
ctl_set_acm_sensored_ctrl_idq_ff()
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_idq_ff (acm_sensored_bare_controller_t * ctrl, ctrl_gt id, ctrl_gt iq)
Sets the feedforward/reference Id and Iq currents.
Definition at line 477 of file acm_sensored_ctrl.h.
References vector2_gt::dat, acm_sensored_bare_controller_t::idq_ff, phase_d, and phase_q.
ctl_set_acm_sensored_ctrl_speed()
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_speed (acm_sensored_bare_controller_t * ctrl, ctrl_gt spd)
Sets the target speed reference.
Definition at line 493 of file acm_sensored_ctrl.h.
References acm_sensored_bare_controller_t::speed_set.
ctl_set_acm_sensored_ctrl_valphabeta()
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_valphabeta (acm_sensored_bare_controller_t * ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target Valpha and Vbeta voltages.
Definition at line 443 of file acm_sensored_ctrl.h.
References vector3_gt::dat, phase_0, phase_alpha, phase_beta, and acm_sensored_bare_controller_t::vab0_set.
ctl_set_acm_sensored_ctrl_vdq_ff()
GMP_STATIC_INLINE void ctl_set_acm_sensored_ctrl_vdq_ff (acm_sensored_bare_controller_t * ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the feedforward/reference Vd and Vq voltages.
Definition at line 461 of file acm_sensored_ctrl.h.
References vector2_gt::dat, phase_d, phase_q, and acm_sensored_bare_controller_t::vdq_ff.
ctl_step_acm_sensored_ctrl()
GMP_STATIC_INLINE void ctl_step_acm_sensored_ctrl (acm_sensored_bare_controller_t * ctrl)
Executes one step of the sensored ACM control algorithm. This function should be called periodically in the main control ISR.
Parameters
[in,out] ctrl Pointer to the controller structure.
Definition at line 285 of file acm_sensored_ctrl.h.
References ctl_clear_acm_sensored_ctrl(), ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_ipark(), ctl_ct_park(), ctl_ct_svpwm_calc(), ctl_get_mtr_elec_theta(), ctl_get_mtr_velocity(), ctl_mul, ctl_set_phasor_via_angle(), ctl_step_discrete_pid(), ctl_step_im_spd_calc(), ctl_step_pid_ser(), ctl_step_slope_f(), ctl_step_spd_calc(), ctl_step_tracking_continuous_pid(), ctl_step_tracking_pid(), ctl_vector2_copy(), ctl_vector3_clear(), ctl_vector3_set(), acm_sensored_bare_controller_t::current_ctrl, vector2_gt::dat, vector3_gt::dat, acm_sensored_bare_controller_t::flag_enable_controller, acm_sensored_bare_controller_t::flag_enable_current_ctrl, acm_sensored_bare_controller_t::flag_enable_flux_est, acm_sensored_bare_controller_t::flag_enable_modulation, acm_sensored_bare_controller_t::flag_enable_output, acm_sensored_bare_controller_t::flag_enable_velocity_ctrl, float2ctrl, acm_sensored_bare_controller_t::flux_calc, acm_sensored_bare_controller_t::iab0, mtr_ift::iabc, acm_sensored_bare_controller_t::idq0, acm_sensored_bare_controller_t::idq_ff, acm_sensored_bare_controller_t::idq_set, acm_sensored_bare_controller_t::isr_tick, acm_sensored_bare_controller_t::mtr_interface, ctl_im_spd_calc_t::omega_s, phase_0, phase_d, phase_q, acm_sensored_bare_controller_t::pwm_out, acm_sensored_bare_controller_t::rg, acm_sensored_bare_controller_t::spd_ctrl, acm_sensored_bare_controller_t::spd_enc, acm_sensored_bare_controller_t::speed_pu_rg_sf, acm_sensored_bare_controller_t::speed_set, ctl_slope_f_controller::target_frequency, acm_sensored_bare_controller_t::vab0_set, tri_pwm_ift::value, acm_sensored_bare_controller_t::vdq_ff, and acm_sensored_bare_controller_t::vdq_set.