GMP - CTL: Direct Form Controllers
Direct Form Controllers
Control Template Library Intrinsic » Discrete Components
A library of standard direct form IIR filter implementations.
Data Structures
struct ctl_df11_t
Data structure for the DF11 controller.
struct ctl_df22_t
Data structure for the DF22 controller.
struct ctl_df13_t
Data structure for the DF13 controller.
struct ctl_df23_t
Data structure for the DF23 controller.
Functions
GMP_STATIC_INLINE void ctl_clear_df11 (ctl_df11_t *df)
Clears the internal state variables of the DF11 controller.
void ctl_init_df11 (ctl_df11_t *df, parameter_gt b0, parameter_gt b1, parameter_gt a1)
Initializes the DF11 controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_df11 (ctl_df11_t *df, ctrl_gt input)
Executes one step of the DF11 controller.
parameter_gt ctl_get_df11_gain (ctl_df11_t *df, parameter_gt fs, parameter_gt f)
Calculate DF11 gain at specified frequency f.
parameter_gt ctl_get_df11_phase_lag (ctl_df11_t *df, parameter_gt fs, parameter_gt f)
Calculate DF11 phase lag at specified frequency f.
GMP_STATIC_INLINE void ctl_clear_df22 (ctl_df22_t *df)
Clears the internal state variables of the DF22 controller.
void ctl_init_df22 (ctl_df22_t *df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt a1, parameter_gt a2)
Initializes the DF22 controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_df22 (ctl_df22_t *df, ctrl_gt input)
Executes one step of the DF22 controller.
parameter_gt ctl_get_df22_gain (ctl_df22_t *df, parameter_gt fs, parameter_gt f)
Calculate DF22 gain at specified frequency f.
parameter_gt ctl_get_df22_phase_lag (ctl_df22_t *df, parameter_gt fs, parameter_gt f)
Calculate DF22 phase lag at specified frequency f.
GMP_STATIC_INLINE void ctl_clear_df13 (ctl_df13_t *df)
Clears the internal state variables of the DF13 controller.
void ctl_init_df13 (ctl_df13_t *df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt b3, parameter_gt a1, parameter_gt a2, parameter_gt a3)
Initializes the DF13 controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_df13 (ctl_df13_t *df, ctrl_gt input)
Executes one step of the DF13 controller.
parameter_gt ctl_get_df13_gain (ctl_df13_t *df, parameter_gt fs, parameter_gt f)
Calculate DF13 gain at specified frequency f.
parameter_gt ctl_get_df13_phase_lag (ctl_df13_t *df, parameter_gt fs, parameter_gt f)
Calculate DF13 phase lag at specified frequency f.
GMP_STATIC_INLINE void ctl_clear_df23 (ctl_df23_t *df)
Clears the internal state variables of the DF23 controller.
void ctl_init_df23 (ctl_df23_t *df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt b3, parameter_gt a1, parameter_gt a2, parameter_gt a3)
Initializes the DF23 controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_df23 (ctl_df23_t *df, ctrl_gt input)
Executes one step of the DF23 controller.
parameter_gt ctl_get_df23_gain (ctl_df23_t *df, parameter_gt fs, parameter_gt f)
Calculate DF23 gain at specified frequency f.
parameter_gt ctl_get_df23_phase_lag (ctl_df23_t *df, parameter_gt fs, parameter_gt f)
Calculate DF23 phase lag at specified frequency f.
Detailed Description
A library of standard direct form IIR filter implementations.
This module contains implementations for various standard Direct Form IIR filter structures, commonly used in digital control systems. This module includes DF11, DF22, DF13 and DF23 structures. reference TI DF controller
Function Documentation
ctl_clear_df11()
GMP_STATIC_INLINE void ctl_clear_df11 (ctl_df11_t * df)
Clears the internal state variables of the DF11 controller.
Parameters
[out] df Pointer to the DF11 controller instance.
Definition at line 62 of file direct_form.h.
References ctl_df11_t::d1, ctl_df11_t::d2, and ctl_df11_t::output.
ctl_clear_df13()
GMP_STATIC_INLINE void ctl_clear_df13 (ctl_df13_t * df)
Clears the internal state variables of the DF13 controller.
Parameters
[out] df Pointer to the DF13 controller instance.
Definition at line 229 of file direct_form.h.
References ctl_df13_t::d1, ctl_df13_t::d2, ctl_df13_t::d3, ctl_df13_t::d5, ctl_df13_t::d6, ctl_df13_t::d7, and ctl_df13_t::output.
ctl_clear_df22()
GMP_STATIC_INLINE void ctl_clear_df22 (ctl_df22_t * df)
Clears the internal state variables of the DF22 controller.
Parameters
[out] df Pointer to the DF22 controller instance.
Definition at line 145 of file direct_form.h.
References ctl_df22_t::output, ctl_df22_t::x1d, and ctl_df22_t::x2d.
ctl_clear_df23()
GMP_STATIC_INLINE void ctl_clear_df23 (ctl_df23_t * df)
Clears the internal state variables of the DF23 controller.
Parameters
[out] df Pointer to the DF23 controller instance.
Definition at line 324 of file direct_form.h.
References ctl_df23_t::d1, ctl_df23_t::d2, ctl_df23_t::d3, and ctl_df23_t::output.
ctl_get_df11_gain()
parameter_gt ctl_get_df11_gain (ctl_df11_t * df, parameter_gt fs, parameter_gt f)
Calculate DF11 gain at specified frequency f.
Parameters
[in] df Pointer to the DF11 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 349 of file ctl_component_discrete.c.
References ctl_df11_t::a1, ctl_df11_t::b0, ctl_df11_t::b1, CTL_PARAM_CONST_PI, and fs.
ctl_get_df11_phase_lag()
parameter_gt ctl_get_df11_phase_lag (ctl_df11_t * df, parameter_gt fs, parameter_gt f)
Calculate DF11 phase lag at specified frequency f.
Parameters
[in] df Pointer to the DF11 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 366 of file ctl_component_discrete.c.
References ctl_df11_t::a1, ctl_df11_t::b0, ctl_df11_t::b1, CTL_PARAM_CONST_PI, and fs.
ctl_get_df13_gain()
parameter_gt ctl_get_df13_gain (ctl_df13_t * df, parameter_gt fs, parameter_gt f)
Calculate DF13 gain at specified frequency f.
Parameters
[in] df Pointer to the DF13 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 446 of file ctl_component_discrete.c.
References ctl_df13_t::a1, ctl_df13_t::a2, ctl_df13_t::a3, ctl_df13_t::b0, ctl_df13_t::b1, ctl_df13_t::b2, ctl_df13_t::b3, CTL_PARAM_CONST_PI, and fs.
ctl_get_df13_phase_lag()
parameter_gt ctl_get_df13_phase_lag (ctl_df13_t * df, parameter_gt fs, parameter_gt f)
Calculate DF13 phase lag at specified frequency f.
Parameters
[in] df Pointer to the DF13 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 464 of file ctl_component_discrete.c.
References ctl_df13_t::a1, ctl_df13_t::a2, ctl_df13_t::a3, ctl_df13_t::b0, ctl_df13_t::b1, ctl_df13_t::b2, ctl_df13_t::b3, CTL_PARAM_CONST_PI, and fs.
ctl_get_df22_gain()
parameter_gt ctl_get_df22_gain (ctl_df22_t * df, parameter_gt fs, parameter_gt f)
Calculate DF22 gain at specified frequency f.
Parameters
[in] df Pointer to the DF22 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 396 of file ctl_component_discrete.c.
References ctl_df22_t::a1, ctl_df22_t::a2, ctl_df22_t::b0, ctl_df22_t::b1, ctl_df22_t::b2, CTL_PARAM_CONST_PI, and fs.
ctl_get_df22_phase_lag()
parameter_gt ctl_get_df22_phase_lag (ctl_df22_t * df, parameter_gt fs, parameter_gt f)
Calculate DF22 phase lag at specified frequency f.
Parameters
[in] df Pointer to the DF22 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 413 of file ctl_component_discrete.c.
References ctl_df22_t::a1, ctl_df22_t::a2, ctl_df22_t::b0, ctl_df22_t::b1, ctl_df22_t::b2, CTL_PARAM_CONST_PI, and fs.
ctl_get_df23_gain()
parameter_gt ctl_get_df23_gain (ctl_df23_t * df, parameter_gt fs, parameter_gt f)
Calculate DF23 gain at specified frequency f.
Parameters
[in] df Pointer to the DF23 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 498 of file ctl_component_discrete.c.
References ctl_df23_t::a1, ctl_df23_t::a2, ctl_df23_t::a3, ctl_df23_t::b0, ctl_df23_t::b1, ctl_df23_t::b2, ctl_df23_t::b3, CTL_PARAM_CONST_PI, and fs.
ctl_get_df23_phase_lag()
parameter_gt ctl_get_df23_phase_lag (ctl_df23_t * df, parameter_gt fs, parameter_gt f)
Calculate DF23 phase lag at specified frequency f.
Parameters
[in] df Pointer to the DF23 controller instance.
[in] fs controller sample frequency, unit Hz.
[in] f target frequency, unit Hz.
Definition at line 517 of file ctl_component_discrete.c.
References ctl_df23_t::a1, ctl_df23_t::a2, ctl_df23_t::a3, ctl_df23_t::b0, ctl_df23_t::b1, ctl_df23_t::b2, ctl_df23_t::b3, CTL_PARAM_CONST_PI, and fs.
ctl_init_df11()
void ctl_init_df11 (ctl_df11_t * df, parameter_gt b0, parameter_gt b1, parameter_gt a1)
Initializes the DF11 controller.
Parameters
[out] df Pointer to the DF11 controller instance.
[in] b0 Numerator coefficient b0.
[in] b1 Numerator coefficient b1.
[in] a1 Denominator coefficient a1 (from 1 + a1*z^-1).
Definition at line 341 of file ctl_component_discrete.c.
References a1, ctl_df11_t::a1, b0, ctl_df11_t::b0, b1, ctl_df11_t::b1, ctl_clear_df11(), and float2ctrl.
ctl_init_df13()
void ctl_init_df13 (ctl_df13_t * df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt b3, parameter_gt a1, parameter_gt a2, parameter_gt a3)
Initializes the DF13 controller.
Parameters
[out] df Pointer to the DF13 controller instance.
[in] b0,b1,b2,b3 Numerator coefficients.
[in] a1,a2,a3 Denominator coefficients.
Definition at line 433 of file ctl_component_discrete.c.
References a1, ctl_df13_t::a1, a2, ctl_df13_t::a2, ctl_df13_t::a3, b0, ctl_df13_t::b0, b1, ctl_df13_t::b1, b2, ctl_df13_t::b2, ctl_df13_t::b3, ctl_clear_df13(), and float2ctrl.
ctl_init_df22()
void ctl_init_df22 (ctl_df22_t * df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt a1, parameter_gt a2)
Initializes the DF22 controller.
Parameters
[out] df Pointer to the DF22 controller instance.
[in] b0,b1,b2 Numerator coefficients.
[in] a1,a2 Denominator coefficients.
Definition at line 386 of file ctl_component_discrete.c.
References a1, ctl_df22_t::a1, a2, ctl_df22_t::a2, b0, ctl_df22_t::b0, b1, ctl_df22_t::b1, b2, ctl_df22_t::b2, ctl_clear_df22(), and float2ctrl.
ctl_init_df23()
void ctl_init_df23 (ctl_df23_t * df, parameter_gt b0, parameter_gt b1, parameter_gt b2, parameter_gt b3, parameter_gt a1, parameter_gt a2, parameter_gt a3)
Initializes the DF23 controller.
Parameters
[out] df Pointer to the DF23 controller instance.
[in] b0,b1,b2,b3 Numerator coefficients.
[in] a1,a2,a3 Denominator coefficients.
Definition at line 485 of file ctl_component_discrete.c.
References a1, ctl_df23_t::a1, a2, ctl_df23_t::a2, ctl_df23_t::a3, b0, ctl_df23_t::b0, b1, ctl_df23_t::b1, b2, ctl_df23_t::b2, ctl_df23_t::b3, ctl_clear_df23(), and float2ctrl.
ctl_step_df11()
GMP_STATIC_INLINE ctrl_gt ctl_step_df11 (ctl_df11_t * df, ctrl_gt input)
Executes one step of the DF11 controller.
Parameters
[in,out] df Pointer to the DF11 controller instance.
[in] input The current input error signal, e(k).
Returns
ctrl_gt The calculated output, u(k).
Definition at line 84 of file direct_form.h.
References ctl_df11_t::a1, ctl_df11_t::b0, ctl_df11_t::b1, ctl_mul, ctl_df11_t::d1, ctl_df11_t::d2, input, and ctl_df11_t::output.
ctl_step_df13()
GMP_STATIC_INLINE ctrl_gt ctl_step_df13 (ctl_df13_t * df, ctrl_gt input)
Executes one step of the DF13 controller.
Parameters
[in,out] df Pointer to the DF13 controller instance.
[in] input The current input error signal, e(k).
Returns
ctrl_gt The calculated output, u(k).
Definition at line 255 of file direct_form.h.
References ctl_df13_t::a1, ctl_df13_t::a2, ctl_df13_t::a3, ctl_df13_t::b0, ctl_df13_t::b1, ctl_df13_t::b2, ctl_df13_t::b3, ctl_mul, ctl_df13_t::d1, ctl_df13_t::d2, ctl_df13_t::d3, ctl_df13_t::d5, ctl_df13_t::d6, ctl_df13_t::d7, input, and ctl_df13_t::output.
ctl_step_df22()
GMP_STATIC_INLINE ctrl_gt ctl_step_df22 (ctl_df22_t * df, ctrl_gt input)
Executes one step of the DF22 controller.
Parameters
[in,out] df Pointer to the DF22 controller instance.
[in] input The current input error signal, e(k).
Returns
ctrl_gt The calculated output, u(k).
Definition at line 166 of file direct_form.h.
References ctl_df22_t::a1, ctl_df22_t::a2, ctl_df22_t::b0, ctl_df22_t::b1, ctl_df22_t::b2, ctl_mul, input, ctl_df22_t::output, ctl_df22_t::x1d, and ctl_df22_t::x2d.
ctl_step_df23()
GMP_STATIC_INLINE ctrl_gt ctl_step_df23 (ctl_df23_t * df, ctrl_gt input)
Executes one step of the DF23 controller.
Parameters
[in,out] df Pointer to the DF23 controller instance.
[in] input The current input error signal, e(k).
Returns
ctrl_gt The calculated output, u(k).
Definition at line 347 of file direct_form.h.
References ctl_df23_t::a1, ctl_df23_t::a2, ctl_df23_t::a3, ctl_df23_t::b0, ctl_df23_t::b1, ctl_df23_t::b2, ctl_df23_t::b3, ctl_mul, ctl_df23_t::d1, ctl_df23_t::d2, ctl_df23_t::d3, input, and ctl_df23_t::output.