GMP - CTL: 3x3 Matrix Math
3x3 Matrix Math
Control Math Library » Linear Algebra
A collection of types and functions for 3x3 matrix arithmetic.
Data Structures
struct ctl_matrix3_t
Data structure for representing a 3x3 matrix. The elements are stored in row-major order: | dat[0] dat[1] dat[2] | | dat[3] dat[4] dat[5] | | dat[6] dat[7] dat[8] |.
Functions
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_get (const ctl_matrix3_t *mat, int row, int col)
Gets an element from the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix3_set (ctl_matrix3_t *mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix3_clear (ctl_matrix3_t *matrix)
Clears a 3x3 matrix, setting all its elements to zero.
GMP_STATIC_INLINE void ctl_matrix3_set_identity (ctl_matrix3_t *matrix)
Sets a 3x3 matrix to the identity matrix.
GMP_STATIC_INLINE void ctl_matrix3_copy (ctl_matrix3_t *dup, const ctl_matrix3_t *src)
Copies the contents of one 3x3 matrix to another.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_add (ctl_matrix3_t a, ctl_matrix3_t b)
Adds two 3x3 matrices.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_sub (ctl_matrix3_t a, ctl_matrix3_t b)
Subtracts one 3x3 matrix from another.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_scale (ctl_matrix3_t mat, ctrl_gt scalar)
Multiplies a 3x3 matrix by a scalar value.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_mul (ctl_matrix3_t a, ctl_matrix3_t b)
Multiplies two 3x3 matrices.
GMP_STATIC_INLINE ctl_vector3_t ctl_matrix3_mul_vector (ctl_matrix3_t mat, ctl_vector3_t vec)
Multiplies a 3x3 matrix by a 3D column vector.
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_det (ctl_matrix3_t mat)
Calculates the determinant of a 3x3 matrix.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_inv (ctl_matrix3_t mat)
Calculates the inverse of a 3x3 matrix.
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_trans (ctl_matrix3_t mat)
Transposes a 3x3 matrix.
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_trace (ctl_matrix3_t mat)
Calculates the trace of a 3x3 matrix (sum of diagonal elements).
Detailed Description
A collection of types and functions for 3x3 matrix arithmetic.
Function Documentation
ctl_matrix3_add()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_add (ctl_matrix3_t a, ctl_matrix3_t b)
Adds two 3x3 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a + b).
Definition at line 121 of file matrix3.h.
References ctl_matrix3_t::dat, and i.
ctl_matrix3_clear()
GMP_STATIC_INLINE void ctl_matrix3_clear (ctl_matrix3_t * matrix)
Clears a 3x3 matrix, setting all its elements to zero.
Parameters
[out] matrix Pointer to the matrix to be cleared.
Definition at line 78 of file matrix3.h.
References i, and matrix.
ctl_matrix3_copy()
GMP_STATIC_INLINE void ctl_matrix3_copy (ctl_matrix3_t * dup, const ctl_matrix3_t * src)
Copies the contents of one 3x3 matrix to another.
Parameters
[out] dup Pointer to the destination matrix.
[in] src Pointer to the source matrix.
Definition at line 105 of file matrix3.h.
References ctl_matrix3_t::dat, and i.
ctl_matrix3_det()
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_det (ctl_matrix3_t mat)
Calculates the determinant of a 3x3 matrix.
Parameters
mat The input matrix.
Returns
The determinant of the matrix.
Definition at line 210 of file matrix3.h.
References ctl_matrix3_t::dat.
ctl_matrix3_get()
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_get (const ctl_matrix3_t * mat, int row, int col)
Gets an element from the matrix at the specified row and column.
Parameters
[in] mat Pointer to the matrix.
[in] row The row index (0, 1, or 2).
[in] col The column index (0, 1, or 2).
Returns
The value of the element at (row, col).
Definition at line 57 of file matrix3.h.
References ctl_matrix3_t::dat.
ctl_matrix3_inv()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_inv (ctl_matrix3_t mat)
Calculates the inverse of a 3x3 matrix.
Parameters
mat The matrix to be inverted.
Returns
The inverse of the matrix. Returns a zero matrix if the determinant is zero.
Definition at line 222 of file matrix3.h.
References ctl_matrix3_clear(), ctl_matrix3_det(), and ctl_matrix3_t::dat.
ctl_matrix3_mul()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_mul (ctl_matrix3_t a, ctl_matrix3_t b)
Multiplies two 3x3 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a * b).
Definition at line 175 of file matrix3.h.
References ctl_matrix3_t::dat.
ctl_matrix3_mul_vector()
GMP_STATIC_INLINE ctl_vector3_t ctl_matrix3_mul_vector (ctl_matrix3_t mat, ctl_vector3_t vec)
Multiplies a 3x3 matrix by a 3D column vector.
Parameters
mat The matrix.
vec The vector.
Returns
The resulting transformed vector (mat * vec).
Definition at line 196 of file matrix3.h.
References ctl_matrix3_t::dat.
ctl_matrix3_scale()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_scale (ctl_matrix3_t mat, ctrl_gt scalar)
Multiplies a 3x3 matrix by a scalar value.
Parameters
mat The matrix to be scaled.
scalar The scalar value.
Returns
The resulting scaled matrix.
Definition at line 157 of file matrix3.h.
References ctl_matrix3_t::dat, and i.
ctl_matrix3_set()
GMP_STATIC_INLINE void ctl_matrix3_set (ctl_matrix3_t * mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
Parameters
[out] mat Pointer to the matrix.
[in] row The row index (0, 1, or 2).
[in] col The column index (0, 1, or 2).
[in] value The new value for the element.
Definition at line 69 of file matrix3.h.
References ctl_matrix3_t::dat, and value().
ctl_matrix3_set_identity()
GMP_STATIC_INLINE void ctl_matrix3_set_identity (ctl_matrix3_t * matrix)
Sets a 3x3 matrix to the identity matrix.
Parameters
[out] matrix Pointer to the matrix to be set.
Definition at line 92 of file matrix3.h.
References ctl_matrix3_clear(), and matrix.
ctl_matrix3_sub()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_sub (ctl_matrix3_t a, ctl_matrix3_t b)
Subtracts one 3x3 matrix from another.
Parameters
a The minuend matrix.
b The subtrahend matrix.
Returns
The resulting matrix (a - b).
Definition at line 139 of file matrix3.h.
References ctl_matrix3_t::dat, and i.
ctl_matrix3_trace()
GMP_STATIC_INLINE ctrl_gt ctl_matrix3_trace (ctl_matrix3_t mat)
Calculates the trace of a 3x3 matrix (sum of diagonal elements).
Parameters
mat The input matrix.
Returns
The trace of the matrix.
Definition at line 273 of file matrix3.h.
References ctl_matrix3_t::dat.
ctl_matrix3_trans()
GMP_STATIC_INLINE ctl_matrix3_t ctl_matrix3_trans (ctl_matrix3_t mat)
Transposes a 3x3 matrix.
Parameters
mat The matrix to be transposed.
Returns
The transposed matrix.
Definition at line 253 of file matrix3.h.
References ctl_matrix3_t::dat.