GMP - CTL: 2x2 Matrix Math
2x2 Matrix Math
Control Math Library » Linear Algebra
A collection of types and functions for 2x2 matrix arithmetic.
Data Structures
struct ctl_matrix2_t
Data structure for representing a 2x2 matrix. The elements are stored in row-major order: | dat[0] dat[1] | | dat[2] dat[3] |.
Functions
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_get (const ctl_matrix2_t *mat, int row, int col)
Gets an element from the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix2_set (ctl_matrix2_t *mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix2_clear (ctl_matrix2_t *matrix)
Clears a 2x2 matrix, setting all its elements to zero.
GMP_STATIC_INLINE void ctl_matrix2_set_identity (ctl_matrix2_t *matrix)
Sets a 2x2 matrix to the identity matrix.
GMP_STATIC_INLINE void ctl_matrix2_copy (ctl_matrix2_t *dup, ctl_matrix2_t *src)
Copies the contents of one 2x2 matrix to another.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_add (ctl_matrix2_t a, ctl_matrix2_t b)
Adds two 2x2 matrices.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_sub (ctl_matrix2_t a, ctl_matrix2_t b)
Subtracts one 2x2 matrix from another.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_scale (ctl_matrix2_t mat, ctrl_gt scalar)
Multiplies a 2x2 matrix by a scalar value.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_mul (ctl_matrix2_t a, ctl_matrix2_t b)
Multiplies two 2x2 matrices.
GMP_STATIC_INLINE ctl_vector2_t ctl_matrix2_mul_vector (ctl_matrix2_t mat, ctl_vector2_t vec)
Multiplies a 2x2 matrix by a 2D column vector.
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_det (ctl_matrix2_t mat)
Calculates the determinant of a 2x2 matrix.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_inv (ctl_matrix2_t mat)
Calculates the inverse of a 2x2 matrix.
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_trans (ctl_matrix2_t mat)
Transposes a 2x2 matrix.
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_trace (ctl_matrix2_t mat)
Calculates the trace of a 2x2 matrix (sum of diagonal elements).
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_congruent (ctl_matrix2_t a, ctl_matrix2_t p)
Performs a congruent transformation on matrix A with matrix P.
GMP_STATIC_INLINE void ctl_matrix2_eigenvalues_complex (ctl_matrix2_t mat, ctl_complex_t *eigenvalue1, ctl_complex_t *eigenvalue2)
Calculates the eigenvalues of a 2x2 matrix.
GMP_STATIC_INLINE void ctl_matrix2_eigenvectors_real (ctl_matrix2_t mat, ctl_vector2_t eigenvalues, ctl_vector2_t *eigenvector1, ctl_vector2_t *eigenvector2)
Calculates the real eigenvectors of a 2x2 matrix for given real eigenvalues.
Detailed Description
A collection of types and functions for 2x2 matrix arithmetic.
Function Documentation
ctl_matrix2_add()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_add (ctl_matrix2_t a, ctl_matrix2_t b)
Adds two 2x2 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a + b).
Definition at line 115 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_clear()
GMP_STATIC_INLINE void ctl_matrix2_clear (ctl_matrix2_t * matrix)
Clears a 2x2 matrix, setting all its elements to zero.
Parameters
[out] matrix Pointer to the matrix to be cleared.
Definition at line 76 of file matrix2.h.
References matrix.
ctl_matrix2_congruent()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_congruent (ctl_matrix2_t a, ctl_matrix2_t p)
Performs a congruent transformation on matrix A with matrix P.
This calculates the result of \(P^T A P \).
Parameters
a The matrix to be transformed.
p The transformation matrix.
Returns
The resulting matrix from the congruent transformation.
Definition at line 258 of file matrix2.h.
References ctl_matrix2_mul(), and ctl_matrix2_trans().
ctl_matrix2_copy()
GMP_STATIC_INLINE void ctl_matrix2_copy (ctl_matrix2_t * dup, ctl_matrix2_t * src)
Copies the contents of one 2x2 matrix to another.
Parameters
[out] dup Pointer to the destination matrix.
[in] src Pointer to the source matrix.
Definition at line 101 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_det()
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_det (ctl_matrix2_t mat)
Calculates the determinant of a 2x2 matrix.
\[det(M) = ad - bc \]
Parameters
mat The input matrix.
Returns
The determinant of the matrix.
Definition at line 195 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_eigenvalues_complex()
GMP_STATIC_INLINE void ctl_matrix2_eigenvalues_complex (ctl_matrix2_t mat, ctl_complex_t * eigenvalue1, ctl_complex_t * eigenvalue2)
Calculates the eigenvalues of a 2x2 matrix.
It solves the characteristic equation: \(\lambda^2 - \text{trace}(A)\lambda + \text{det}(A) = 0 \). The eigenvalues can be real or a complex conjugate pair.
Parameters
[in] mat The input matrix.
[out] eigenvalue1 Pointer to the first complex number to store an eigenvalue.
[out] eigenvalue2 Pointer to the second complex number to store an eigenvalue.
Definition at line 275 of file matrix2.h.
References ctl_matrix2_det(), ctl_matrix2_trace(), ctl_sqrt, ctl_complex_t::imag, and ctl_complex_t::real.
ctl_matrix2_eigenvectors_real()
GMP_STATIC_INLINE void ctl_matrix2_eigenvectors_real (ctl_matrix2_t mat, ctl_vector2_t eigenvalues, ctl_vector2_t * eigenvector1, ctl_vector2_t * eigenvector2)
Calculates the real eigenvectors of a 2x2 matrix for given real eigenvalues.
Parameters
[in] mat The input matrix.
[in] eigenvalues A 2D vector containing the two real eigenvalues.
[out] eigenvector1 Pointer to a 2D vector to store the first eigenvector.
[out] eigenvector2 Pointer to a 2D vector to store the second eigenvector.
Definition at line 310 of file matrix2.h.
References c, ctl_vector2_normalize(), and ctl_matrix2_t::dat.
ctl_matrix2_get()
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_get (const ctl_matrix2_t * mat, int row, int col)
Gets an element from the matrix at the specified row and column.
Parameters
[in] mat Pointer to the matrix.
[in] row The row index (0 or 1).
[in] col The column index (0 or 1).
Returns
The value of the element at (row, col).
Definition at line 55 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_inv()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_inv (ctl_matrix2_t mat)
Calculates the inverse of a 2x2 matrix.
Parameters
mat The matrix to be inverted.
Returns
The inverse of the matrix. Returns a zero matrix if the determinant is zero.
Definition at line 205 of file matrix2.h.
References ctl_matrix2_clear(), ctl_matrix2_det(), and ctl_matrix2_t::dat.
ctl_matrix2_mul()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_mul (ctl_matrix2_t a, ctl_matrix2_t b)
Multiplies two 2x2 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a * b).
Definition at line 163 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_mul_vector()
GMP_STATIC_INLINE ctl_vector2_t ctl_matrix2_mul_vector (ctl_matrix2_t mat, ctl_vector2_t vec)
Multiplies a 2x2 matrix by a 2D column vector.
Parameters
mat The matrix.
vec The vector.
Returns
The resulting transformed vector (mat * vec).
Definition at line 179 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_scale()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_scale (ctl_matrix2_t mat, ctrl_gt scalar)
Multiplies a 2x2 matrix by a scalar value.
Parameters
mat The matrix to be scaled.
scalar The scalar value.
Returns
The resulting scaled matrix.
Definition at line 147 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_set()
GMP_STATIC_INLINE void ctl_matrix2_set (ctl_matrix2_t * mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
Parameters
[out] mat Pointer to the matrix.
[in] row The row index (0 or 1).
[in] col The column index (0 or 1).
[in] value The new value for the element.
Definition at line 67 of file matrix2.h.
References ctl_matrix2_t::dat, and value().
ctl_matrix2_set_identity()
GMP_STATIC_INLINE void ctl_matrix2_set_identity (ctl_matrix2_t * matrix)
Sets a 2x2 matrix to the identity matrix.
Parameters
[out] matrix Pointer to the matrix to be set.
Definition at line 88 of file matrix2.h.
References matrix.
ctl_matrix2_sub()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_sub (ctl_matrix2_t a, ctl_matrix2_t b)
Subtracts one 2x2 matrix from another.
Parameters
a The minuend matrix.
b The subtrahend matrix.
Returns
The resulting matrix (a - b).
Definition at line 131 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_trace()
GMP_STATIC_INLINE ctrl_gt ctl_matrix2_trace (ctl_matrix2_t mat)
Calculates the trace of a 2x2 matrix (sum of diagonal elements).
Parameters
mat The input matrix.
Returns
The trace of the matrix.
Definition at line 244 of file matrix2.h.
References ctl_matrix2_t::dat.
ctl_matrix2_trans()
GMP_STATIC_INLINE ctl_matrix2_t ctl_matrix2_trans (ctl_matrix2_t mat)
Transposes a 2x2 matrix.
Parameters
mat The matrix to be transposed.
Returns
The transposed matrix.
Definition at line 229 of file matrix2.h.
References ctl_matrix2_t::dat.