GMP - CTL: Dual PI FOC Current Controller
Dual PI FOC Current Controller
Motor Control Library » Motor Controller Components
The core current regulation loop for an FOC motor controller.
Data Structures
struct mtr_current_ctrl_t
Main structure for the FOC current controller.
struct mtr_current_init_t
Macros
#define MC_CURRENT_SAMPLE_PHASE_MODE (3)
#define MC_CURRENT_OUTPUT_LIMIT_BY_SQRT (0)
Functions
GMP_STATIC_INLINE void ctl_clear_mtr_current_ctrl (mtr_current_ctrl_t *mc)
Initializes the current controller structure to safe defaults.
void ctl_auto_tuning_mtr_current_ctrl (mtr_current_init_t *init)
Auto-tuning motor driver parameters.
void ctl_init_mtr_current_ctrl (mtr_current_ctrl_t *mc, mtr_current_init_t *init)
Sets up the parameters for the d-q axis PI controllers.
GMP_STATIC_INLINE void ctl_step_current_controller (mtr_current_ctrl_t *mc)
Executes one step of the FOC current control loop.
GMP_STATIC_INLINE void ctl_enable_mtr_current_ctrl (mtr_current_ctrl_t *mc)
Enables the PI controller action.
GMP_STATIC_INLINE void ctl_set_mtr_current_ctrl_ref (mtr_current_ctrl_t *mc, ctrl_gt id_ref, ctrl_gt iq_ref)
Sets the d-q axis current reference (target).
GMP_STATIC_INLINE void ctl_set_mtr_current_ctrl_vdq_ref (mtr_current_ctrl_t *mc, ctrl_gt vd_ff, ctrl_gt vq_ff)
Sets the d-q axis voltage reference terms.
GMP_STATIC_INLINE void ctl_disable_mtr_current_ctrl (mtr_current_ctrl_t *mc)
Disables the PI controller action.
GMP_STATIC_INLINE void ctl_attach_mtr_current_ctrl_port (mtr_current_ctrl_t *mc, tri_adc_ift *_iabc, adc_ift *_udc, rotation_ift *_pos_if, velocity_ift *_vec_if)
GMP_STATIC_INLINE void ctl_attach_mtr_current_ctrl_phasor (mtr_current_ctrl_t *mc, ctl_vector2_t *_phasor)
Detailed Description
The core current regulation loop for an FOC motor controller.
This module forms the core of an FOC system. It takes three-phase current measurements, a rotor angle, and d-q axis current references, then performs the necessary coordinate transformations (Clarke, Park) and PI control to generate the required d-q axis voltages. These voltages are then transformed back to the stationary frame (Inverse Park) to be used by a PWM modulator. The controller implements the PMSM voltage equations in the d-q frame:
\[ v_d = R_s i_d + L_d \frac{di_d}{dt} - \omega_e L_q i_q \]
\[ v_q = R_s i_q + L_q \frac{di_q}{dt} + \omega_e L_d i_d + \omega_e \psi_f \]
The PI controllers regulate i_d and i_q to their reference values.
Macro Definition Documentation
MC_CURRENT_OUTPUT_LIMIT_BY_SQRT
#define MC_CURRENT_OUTPUT_LIMIT_BY_SQRT (0)
Definition at line 55 of file motor_current_ctrl.h.
MC_CURRENT_SAMPLE_PHASE_MODE
#define MC_CURRENT_SAMPLE_PHASE_MODE (3)
Definition at line 51 of file motor_current_ctrl.h.
Function Documentation
ctl_attach_mtr_current_ctrl_phasor()
GMP_STATIC_INLINE void ctl_attach_mtr_current_ctrl_phasor (mtr_current_ctrl_t * mc, ctl_vector2_t * _phasor)
Definition at line 463 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::phasor_input.
ctl_attach_mtr_current_ctrl_port()
GMP_STATIC_INLINE void ctl_attach_mtr_current_ctrl_port (mtr_current_ctrl_t * mc, tri_adc_ift * _iabc, adc_ift * _udc, rotation_ift * _pos_if, velocity_ift * _vec_if)
Definition at line 454 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::adc_iuvw, mtr_current_ctrl_t::adc_udc, mtr_current_ctrl_t::pos_if, and mtr_current_ctrl_t::spd_if.
ctl_auto_tuning_mtr_current_ctrl()
void ctl_auto_tuning_mtr_current_ctrl (mtr_current_init_t * init)
Auto-tuning motor driver parameters.
Parameters
[in,out] init Pointer to the mtr_current_init_t structure.
Definition at line 9 of file ctl_mc_current_loop.c.
References ctl_get_filter_iir1_phase_lag(), ctl_init_filter_iir1_lpf(), CTL_PARAM_CONST_2PI, and init().
ctl_clear_mtr_current_ctrl()
GMP_STATIC_INLINE void ctl_clear_mtr_current_ctrl (mtr_current_ctrl_t * mc)
Initializes the current controller structure to safe defaults.
Parameters
[out] mc Pointer to the current controller structure.
Definition at line 145 of file motor_current_ctrl.h.
References ctl_clear_filter_iir1(), ctl_clear_lead(), ctl_clear_pid(), ctl_vector2_clear(), ctl_vector3_clear(), mtr_current_ctrl_t::filter_iuvw, mtr_current_ctrl_t::filter_udc, mtr_current_ctrl_t::iab0, mtr_current_ctrl_t::idq0, mtr_current_ctrl_t::idq_ctrl, mtr_current_ctrl_t::isr_tick, mtr_current_ctrl_t::iuvw, mtr_current_ctrl_t::lead_compensator, phase_d, phase_q, phase_U, phase_V, phase_W, mtr_current_ctrl_t::udc, mtr_current_ctrl_t::vab0, mtr_current_ctrl_t::vdq0, mtr_current_ctrl_t::vdq_ctrl_out, mtr_current_ctrl_t::vdq_decouple, mtr_current_ctrl_t::vdq_ff, mtr_current_ctrl_t::vdq_out, mtr_current_ctrl_t::vdq_out_bus_compensator, and mtr_current_ctrl_t::vdq_out_sat.
ctl_disable_mtr_current_ctrl()
GMP_STATIC_INLINE void ctl_disable_mtr_current_ctrl (mtr_current_ctrl_t * mc)
Disables the PI controller action.
When disabled, the controller output will be zero, but feedforward terms will still be applied.
Parameters
[out] cc Pointer to the current controller structure.
Definition at line 449 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::flag_enable_current_ctrl.
ctl_enable_mtr_current_ctrl()
GMP_STATIC_INLINE void ctl_enable_mtr_current_ctrl (mtr_current_ctrl_t * mc)
Enables the PI controller action.
Parameters
[out] cc Pointer to the current controller structure.
Definition at line 415 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::flag_enable_current_ctrl.
ctl_init_mtr_current_ctrl()
void ctl_init_mtr_current_ctrl (mtr_current_ctrl_t * mc, mtr_current_init_t * init)
Sets up the parameters for the d-q axis PI controllers.
Parameters
[out] mc Pointer to the current controller structure.
[in] init initialize object for Motor controller.
Definition at line 50 of file ctl_mc_current_loop.c.
References mtr_current_ctrl_t::coef_ff_decouple, ctl_clear_mtr_current_ctrl(), ctl_init_filter_iir1_lpf(), ctl_init_lead_form3(), ctl_init_pid(), CTL_PARAM_CONST_PI, ctl_set_pid_int_limit(), ctl_set_pid_limit(), mtr_current_ctrl_t::filter_iuvw, mtr_current_ctrl_t::filter_udc, mtr_current_ctrl_t::flag_enable_bus_compensation, mtr_current_ctrl_t::flag_enable_current_ctrl, mtr_current_ctrl_t::flag_enable_decouple, mtr_current_ctrl_t::flag_enable_lead_compensator, mtr_current_ctrl_t::flag_enable_theta_calc, mtr_current_ctrl_t::flag_enable_vdq_feedforward, i, mtr_current_ctrl_t::idq_ctrl, init(), mtr_current_ctrl_t::lead_compensator, mtr_current_ctrl_t::max_dcbus_voltage, mtr_current_ctrl_t::max_vs_mag, phase_d, and phase_q.
ctl_set_mtr_current_ctrl_ref()
GMP_STATIC_INLINE void ctl_set_mtr_current_ctrl_ref (mtr_current_ctrl_t * mc, ctrl_gt id_ref, ctrl_gt iq_ref)
Sets the d-q axis current reference (target).
Parameters
[out] cc Pointer to the current controller structure.
[in] id_ref The target d-axis current.
[in] iq_ref The target q-axis current.
Definition at line 426 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::idq_ref.
ctl_set_mtr_current_ctrl_vdq_ref()
GMP_STATIC_INLINE void ctl_set_mtr_current_ctrl_vdq_ref (mtr_current_ctrl_t * mc, ctrl_gt vd_ff, ctrl_gt vq_ff)
Sets the d-q axis voltage reference terms.
Parameters
[out] cc Pointer to the current controller structure.
[in] vd_ff The d-axis voltage feed forward term.
[in] vq_ff The q-axis voltage feed forward term.
Definition at line 438 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::vdq_ref.
ctl_step_current_controller()
GMP_STATIC_INLINE void ctl_step_current_controller (mtr_current_ctrl_t * mc)
Executes one step of the FOC current control loop.
Parameters
[out] mc Pointer to the current controller structure.
[in] theta The current electrical angle of the rotor (0.0 to 1.0).
Definition at line 234 of file motor_current_ctrl.h.
References mtr_current_ctrl_t::adc_iuvw, mtr_current_ctrl_t::adc_udc, mtr_current_ctrl_t::coef_ff_decouple, ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_ipark(), ctl_ct_park(), ctl_mul, ctl_pid_clamping_correction_using_real_output(), ctl_sat, ctl_set_phasor_via_angle(), ctl_sqrt, ctl_step_filter_iir1(), ctl_step_lead(), ctl_step_pid_ser(), ctl_vector2_add(), ctl_vector2_copy(), rotation_ift::elec_position, mtr_current_ctrl_t::filter_iuvw, mtr_current_ctrl_t::filter_udc, mtr_current_ctrl_t::flag_enable_bus_compensation, mtr_current_ctrl_t::flag_enable_current_ctrl, mtr_current_ctrl_t::flag_enable_decouple, mtr_current_ctrl_t::flag_enable_lead_compensator, mtr_current_ctrl_t::flag_enable_theta_calc, mtr_current_ctrl_t::flag_enable_vdq_feedforward, float2ctrl, mtr_current_ctrl_t::iab0, mtr_current_ctrl_t::idq0, mtr_current_ctrl_t::idq_ctrl, mtr_current_ctrl_t::idq_ref, mtr_current_ctrl_t::isr_tick, mtr_current_ctrl_t::iuvw, mtr_current_ctrl_t::lead_compensator, mtr_current_ctrl_t::max_dcbus_voltage, mtr_current_ctrl_t::max_vq_mag, mtr_current_ctrl_t::max_vs_mag, phase_0, phase_A, phase_B, phase_C, phase_d, phase_q, phase_U, phase_V, phase_W, mtr_current_ctrl_t::phasor, mtr_current_ctrl_t::phasor_input, mtr_current_ctrl_t::pos_if, mtr_current_ctrl_t::spd_if, velocity_ift::speed, mtr_current_ctrl_t::udc, mtr_current_ctrl_t::vab0, mtr_current_ctrl_t::vdq0, mtr_current_ctrl_t::vdq_ctrl_out, mtr_current_ctrl_t::vdq_decouple, mtr_current_ctrl_t::vdq_ff, mtr_current_ctrl_t::vdq_out, mtr_current_ctrl_t::vdq_out_bus_compensator, mtr_current_ctrl_t::vdq_out_sat, and mtr_current_ctrl_t::vdq_ref.