GMP - CTL: Three Phase Phase-Locked Loop (PLL) API
Three Phase Phase-Locked Loop (PLL) API
Digital Power Control Library » Digital Power Components
A standard three-phase SRF-PLL for grid synchronization.
Data Structures
struct srf_pll_t
Data structure for the three-phase PLL controller.
struct ddsrf_pll_t
Data structure for the Decoupled Double Synchronous Reference Frame (DDSRF) PLL.
struct dsogi_pll_t
Data structure for the DSOGI-PLL controller.
Macros
#define CTL_DDSRF_USE_DOUBLE_ANGLE_FORMULA (0)
Functions
void ctl_init_sfr_pll (srf_pll_t *pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_ki, parameter_gt pid_kd, parameter_gt f_ctrl)
Initializes the three-phase PLL controller.
void ctl_init_dsogi_pll (dsogi_pll_t *dsogi, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt v_mag, parameter_gt bw_pll, parameter_gt k_sogi)
Initializes the DSOGI-PLL controller.
void ctl_init_sfr_pll_T (srf_pll_t *pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_Ti, parameter_gt pid_Td, parameter_gt f_ctrl)
Initializes the three-phase PLL controller.
void ctl_init_srf_pll_auto_tune (srf_pll_t *pll, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt voltage_mag, parameter_gt bandwidth_hz, parameter_gt damping_factor)
Initializes the SRF-PLL by automatically calculating the PI parameters based on the desired bandwidth and damping ratio.
GMP_STATIC_INLINE void ctl_clear_pll_3ph (srf_pll_t *pll)
Clears the internal states of the three-phase PLL controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_pll_3ph (srf_pll_t *pll, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the three-phase PLL algorithm.
void ctl_init_ddsrf_pll (ddsrf_pll_t *pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_ki, parameter_gt f_ctrl, parameter_gt decoupling_fc)
Initialize the DDSRF-PLL.
void ctl_init_ddsrf_pll_auto_tune (ddsrf_pll_t *pll, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt voltage_mag, parameter_gt bandwidth_hz)
Auto-tune and initialize the DDSRF-PLL.
GMP_STATIC_INLINE void ctl_clear_ddsrf_pll (ddsrf_pll_t *pll)
Clears internal states.
GMP_STATIC_INLINE ctrl_gt ctl_step_ddsrf_pll (ddsrf_pll_t *pll, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the DDSRF-PLL algorithm.
GMP_STATIC_INLINE void ctl_clear_dsogi_pll (dsogi_pll_t *dsogi)
Clears the internal states of the DSOGI-PLL controller.
GMP_STATIC_INLINE ctrl_gt ctl_step_dsogi_pll (dsogi_pll_t *dsogi, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the DSOGI-PLL algorithm.
Detailed Description
A standard three-phase SRF-PLL for grid synchronization.
Macro Definition Documentation
CTL_DDSRF_USE_DOUBLE_ANGLE_FORMULA
#define CTL_DDSRF_USE_DOUBLE_ANGLE_FORMULA (0)
Definition at line 169 of file pll.h.
Function Documentation
ctl_clear_ddsrf_pll()
GMP_STATIC_INLINE void ctl_clear_ddsrf_pll (ddsrf_pll_t * pll)
Clears internal states.
Definition at line 246 of file pll.h.
References ctl_clear_filter_iir1(), ctl_clear_pid(), ctl_set_phasor_via_angle(), ctl_vector2_clear(), ddsrf_pll_t::e_alpha, ddsrf_pll_t::e_beta, ddsrf_pll_t::e_error, float2ctrl, ddsrf_pll_t::freq_pu, ddsrf_pll_t::lpf_neg_d, ddsrf_pll_t::lpf_neg_q, ddsrf_pll_t::lpf_pos_d, ddsrf_pll_t::lpf_pos_q, ddsrf_pll_t::phasor, ddsrf_pll_t::pid_pll, ddsrf_pll_t::theta, ddsrf_pll_t::v_neg_dc, ddsrf_pll_t::v_neg_mag, ddsrf_pll_t::v_neg_raw, ddsrf_pll_t::v_pos_dc, ddsrf_pll_t::v_pos_mag, and ddsrf_pll_t::v_pos_raw.
ctl_clear_dsogi_pll()
GMP_STATIC_INLINE void ctl_clear_dsogi_pll (dsogi_pll_t * dsogi)
Clears the internal states of the DSOGI-PLL controller.
Parameters
[out] dsogi Pointer to the dsogi_pll_t structure.
Definition at line 436 of file pll.h.
References ctl_clear_discrete_sogi(), ctl_clear_pll_3ph(), ctl_vector2_clear(), dsogi_pll_t::sogi_alpha, dsogi_pll_t::sogi_beta, dsogi_pll_t::srf_pll, and dsogi_pll_t::v_pos_seq.
ctl_clear_pll_3ph()
GMP_STATIC_INLINE void ctl_clear_pll_3ph (srf_pll_t * pll)
Clears the internal states of the three-phase PLL controller.
Parameters
[out] pll Pointer to the srf_pll_t structure.
Definition at line 110 of file pll.h.
References ctl_clear_pid(), ctl_set_phasor_via_angle(), ctl_vector2_clear(), srf_pll_t::e_ab, srf_pll_t::e_error, float2ctrl, srf_pll_t::freq_pu, srf_pll_t::phasor, srf_pll_t::pid_pll, and srf_pll_t::theta.
ctl_init_ddsrf_pll()
void ctl_init_ddsrf_pll (ddsrf_pll_t * pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_ki, parameter_gt f_ctrl, parameter_gt decoupling_fc)
Initialize the DDSRF-PLL.
Definition at line 102 of file ctl_dp_three_phase.c.
References ctl_clear_ddsrf_pll(), ctl_init_filter_iir1_lpf(), ctl_init_pid(), float2ctrl, ddsrf_pll_t::freq_sf, ddsrf_pll_t::lpf_neg_d, ddsrf_pll_t::lpf_neg_q, ddsrf_pll_t::lpf_pos_d, ddsrf_pll_t::lpf_pos_q, and ddsrf_pll_t::pid_pll.
ctl_init_ddsrf_pll_auto_tune()
void ctl_init_ddsrf_pll_auto_tune (ddsrf_pll_t * pll, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt voltage_mag, parameter_gt bandwidth_hz)
Auto-tune and initialize the DDSRF-PLL.
Bandwidth usually 20-30Hz. Decoupling FC usually f_base/sqrt(2).
Definition at line 125 of file ctl_dp_three_phase.c.
References ctl_init_ddsrf_pll(), and CTL_PARAM_CONST_2PI.
ctl_init_dsogi_pll()
void ctl_init_dsogi_pll (dsogi_pll_t * dsogi, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt v_mag, parameter_gt bw_pll, parameter_gt k_sogi)
Initializes the DSOGI-PLL controller.
Parameters
[out] dsogi Pointer to the dsogi_pll_t structure.
[in] f_base Nominal grid frequency (e.g., 50.0).
[in] f_ctrl Control loop frequency (e.g., 10000.0).
[in] v_mag Nominal voltage magnitude (usually 1.0 for per-unit).
[in] bw_pll Desired PLL bandwidth in Hz (e.g., 20.0).
[in] k_sogi SOGI damping factor (typically 1.414 or 1.0).
Definition at line 158 of file ctl_dp_three_phase.c.
References ctl_init_discrete_sogi(), ctl_init_srf_pll_auto_tune(), ctl_vector2_clear(), dsogi_pll_t::sogi_alpha, dsogi_pll_t::sogi_beta, dsogi_pll_t::srf_pll, and dsogi_pll_t::v_pos_seq.
ctl_init_sfr_pll()
void ctl_init_sfr_pll (srf_pll_t * pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_ki, parameter_gt pid_kd, parameter_gt f_ctrl)
Initializes the three-phase PLL controller.
Parameters
[out] pll Pointer to the srf_pll_t structure to be initialized.
[in] f_base The nominal grid frequency (e.g., 50 or 60 Hz), used as the per-unit base.
[in] pid_kp Proportional gain for the phase-locking PI controller.
[in] pid_ki Integral gain for the phase-locking PI controller (in seconds).
[in] pid_kd Derivative time constant (typically 0 for a PI controller).
[in] f_ctrl The controller's execution frequency (sampling frequency) in Hz.
Definition at line 47 of file ctl_dp_three_phase.c.
References ctl_clear_pll_3ph(), ctl_init_pid(), float2ctrl, srf_pll_t::freq_sf, and srf_pll_t::pid_pll.
ctl_init_sfr_pll_T()
void ctl_init_sfr_pll_T (srf_pll_t * pll, parameter_gt f_base, parameter_gt pid_kp, parameter_gt pid_Ti, parameter_gt pid_Td, parameter_gt f_ctrl)
Initializes the three-phase PLL controller.
Parameters
[out] pll Pointer to the srf_pll_t structure to be initialized.
[in] f_base The nominal grid frequency (e.g., 50 or 60 Hz), used as the per-unit base.
[in] pid_kp Proportional gain for the phase-locking PI controller.
[in] pid_Ti Integral time constant for the phase-locking PI controller (in seconds).
[in] pid_Td Derivative time constant (typically 0 for a PI controller).
[in] f_ctrl The controller's execution frequency (sampling frequency) in Hz.
Definition at line 22 of file ctl_dp_three_phase.c.
References ctl_clear_pll_3ph(), ctl_init_pid_Tmode(), float2ctrl, srf_pll_t::freq_sf, and srf_pll_t::pid_pll.
ctl_init_srf_pll_auto_tune()
void ctl_init_srf_pll_auto_tune (srf_pll_t * pll, parameter_gt f_base, parameter_gt f_ctrl, parameter_gt voltage_mag, parameter_gt bandwidth_hz, parameter_gt damping_factor)
Initializes the SRF-PLL by automatically calculating the PI parameters based on the desired bandwidth and damping ratio.
Parameters
[out] pll Pointer to the PLL structure to be initialized.
[in] f_base The nominal grid frequency in Hz (e.g., 50.0 or 60.0).
[in] f_ctrl The control loop execution frequency (sampling frequency) in Hz (e.g., 10000.0).
[in] voltage_mag The magnitude of the input voltage vector (sqrt(alpha^2 + beta^2)). Set this to 1.0 if the input voltages are already normalized (per-unit).
[in] bandwidth_hz The desired bandwidth of the PLL in Hz. Recommended range: 10.0 ~ 30.0 Hz.
[in] damping_factor The damping ratio (zeta). Recommended value: 0.707.
Initializes the SRF-PLL by automatically calculating the PI parameters based on the desired bandwidth and damping ratio.
Parameters
[out] pll PLL 对象指针
[in] f_base 电网基准频率 (e.g., 50.0)
[in] f_ctrl 控制循环频率/采样频率 (e.g., 10000.0)
[in] voltage_mag 输入的电压矢量模长 (sqrt(alpha^2 + beta^2))。如果输入已经标幺化，则填 1.0。
[in] bandwidth_hz 期望的 PLL 带宽 (Hz)。推荐值: 10.0 ~ 30.0 Hz
[in] damping_factor 阻尼比。推荐值: 0.707
Definition at line 70 of file ctl_dp_three_phase.c.
References ctl_init_sfr_pll(), and CTL_PARAM_CONST_2PI.
ctl_step_ddsrf_pll()
GMP_STATIC_INLINE ctrl_gt ctl_step_ddsrf_pll (ddsrf_pll_t * pll, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the DDSRF-PLL algorithm.
Parameters
[in,out] pll Pointer to the DDSRF-PLL structure.
[in] alpha Measured alpha-axis voltage.
[in] beta Measured beta-axis voltage.
Returns
Estimated grid angle (theta) in p.u.
Definition at line 283 of file pll.h.
References alpha, cos_theta, ctl_ct_park2(), ctl_ct_park2_neg(), ctl_mul, ctl_mul2, ctl_set_phasor_via_angle(), ctl_step_filter_iir1(), ctl_step_pid_par(), ctrl_mod_1, ddsrf_pll_t::e_alpha, ddsrf_pll_t::e_beta, ddsrf_pll_t::e_error, float2ctrl, ddsrf_pll_t::freq_pu, ddsrf_pll_t::freq_sf, ddsrf_pll_t::lpf_neg_d, ddsrf_pll_t::lpf_neg_q, ddsrf_pll_t::lpf_pos_d, ddsrf_pll_t::lpf_pos_q, ctl_pid_t::out, phase_alpha, phase_beta, phase_d, phase_q, ddsrf_pll_t::phasor, ddsrf_pll_t::phasor_2w, phasor_cos, phasor_sin, ddsrf_pll_t::pid_pll, sin_theta, ddsrf_pll_t::theta, ddsrf_pll_t::v_neg_dc, ddsrf_pll_t::v_neg_mag, ddsrf_pll_t::v_neg_raw, ddsrf_pll_t::v_pos_dc, ddsrf_pll_t::v_pos_mag, and ddsrf_pll_t::v_pos_raw.
ctl_step_dsogi_pll()
GMP_STATIC_INLINE ctrl_gt ctl_step_dsogi_pll (dsogi_pll_t * dsogi, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the DSOGI-PLL algorithm.
Filters input voltages using SOGI (Band-Pass & Quadrature generation).
Calculates Positive Sequence Components (PNSC).
Feeds the clean positive sequence into the SRF-PLL.
Parameters
[in,out] dsogi Pointer to the dsogi_pll_t structure.
[in] alpha Raw measured alpha-axis voltage.
[in] beta Raw measured beta-axis voltage.
Returns
The estimated grid angle (theta) in per-unit format.
Definition at line 456 of file pll.h.
References alpha, ctl_div2, ctl_get_discrete_sogi_ds(), ctl_get_discrete_sogi_qs(), ctl_step_discrete_sogi(), ctl_step_pll_3ph(), vector2_gt::dat, phase_alpha, phase_beta, dsogi_pll_t::sogi_alpha, dsogi_pll_t::sogi_beta, dsogi_pll_t::srf_pll, and dsogi_pll_t::v_pos_seq.
ctl_step_pll_3ph()
GMP_STATIC_INLINE ctrl_gt ctl_step_pll_3ph (srf_pll_t * pll, ctrl_gt alpha, ctrl_gt beta)
Executes one step of the three-phase PLL algorithm.
This function performs a Park transform on the input alpha-beta voltages using the estimated angle, calculates the q-axis error, updates the PI controller, and integrates the frequency to get the new angle.
Parameters
[out] pll Pointer to the srf_pll_t structure.
[in] alpha The measured alpha-axis voltage.
[in] beta The measured beta-axis voltage.
Returns
The newly estimated grid angle (theta) in per-unit format.
Definition at line 139 of file pll.h.
References alpha, ctl_ct_park2(), ctl_mul, ctl_set_phasor_via_angle(), ctl_step_pid_par(), ctrl_mod_1, vector2_gt::dat, srf_pll_t::e_ab, srf_pll_t::e_error, float2ctrl, srf_pll_t::freq_pu, srf_pll_t::freq_sf, ctl_pid_t::out, phase_alpha, phase_beta, phase_d, phase_q, srf_pll_t::phasor, srf_pll_t::pid_pll, srf_pll_t::theta, and srf_pll_t::v_mag.