GMP - CTL: Discrete Filter Library
Discrete Filter Library
Control Template Library Intrinsic » Discrete Components
A collection of common discrete filters for signal processing.
Data Structures
struct ctl_biquad_filter_t
A second-order infinite impulse response (IIR) general filter.
Typedefs
typedef ctl_biquad_filter_t ctl_filter_IIR2_t
Alias for ctl_biquad_filter_t for backward compatibility.
Functions
GMP_STATIC_INLINE ctrl_gt ctl_step_biquad_filter (ctl_biquad_filter_t *obj, ctrl_gt input)
Executes one step of the 2nd-order IIR filter.
GMP_STATIC_INLINE void ctl_clear_biquad_filter (ctl_biquad_filter_t *obj)
Clears all internal states of the 2nd-order IIR filter.
GMP_STATIC_INLINE ctrl_gt ctl_get_biquad_filter_output (ctl_biquad_filter_t *obj)
Gets the last calculated output from the IIR filter.
void ctl_init_biquad_lpf (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Low-Pass Filter (LPF).
void ctl_init_biquad_hpf (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a High-Pass Filter (HPF).
void ctl_init_biquad_bpf (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Band-Pass Filter (BPF).
void ctl_init_biquad_notch (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Notch Filter.
void ctl_init_biquad_allpass (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as an All-Pass Filter.
void ctl_init_biquad_peaking_eq (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a Peaking EQ Filter.
void ctl_init_biquad_lowshelf (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a Low-Shelf Filter.
void ctl_init_biquad_highshelf (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a High-Shelf Filter.
parameter_gt ctl_get_biquad_phase_lag (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the biquad filter at a specific frequency.
parameter_gt ctl_get_biquad_gain (ctl_biquad_filter_t *obj, parameter_gt fs, parameter_gt f)
Calculates the linear gain (magnitude) of the biquad filter at a specific frequency.
Detailed Description
A collection of common discrete filters for signal processing.
This file contains implementations for a standard second-order IIR filter (Biquad) and a set of helper functions to initialize it as various common filter types (Low-pass, High-pass, Band-pass, Notch, etc.). The coefficient calculations are based on the Audio EQ Cookbook formulas, derived from the Bilinear Transform with frequency pre-warping.
Typedef Documentation
ctl_filter_IIR2_t
typedef ctl_biquad_filter_t ctl_filter_IIR2_t
Alias for ctl_biquad_filter_t for backward compatibility.
Definition at line 74 of file biquad_filter.h.
Function Documentation
ctl_clear_biquad_filter()
GMP_STATIC_INLINE void ctl_clear_biquad_filter (ctl_biquad_filter_t * obj)
Clears all internal states of the 2nd-order IIR filter.
Parameters
[out] obj Pointer to the biquad filter instance.
Definition at line 102 of file biquad_filter.h.
References ctl_biquad_filter_t::out, ctl_biquad_filter_t::x, and ctl_biquad_filter_t::y.
ctl_get_biquad_filter_output()
GMP_STATIC_INLINE ctrl_gt ctl_get_biquad_filter_output (ctl_biquad_filter_t * obj)
Gets the last calculated output from the IIR filter.
Parameters
[in] obj Pointer to the biquad filter instance.
Returns
ctrl_gt The last output value.
Definition at line 116 of file biquad_filter.h.
References ctl_biquad_filter_t::out.
ctl_get_biquad_gain()
parameter_gt ctl_get_biquad_gain (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt f)
Calculates the linear gain (magnitude) of the biquad filter at a specific frequency.
This function evaluates the filter's magnitude response |H(e^(j¦ŘT))| at the given frequency f. To convert the result to decibels (dB), use the formula: Gain_dB = 20 * log10(linear_gain). Key Steps:
Calculate the normalized angular frequency: ¦ŘT = 2*pi*f / fs.
Evaluate the complex numerator N(¦Ř) and denominator D(¦Ř).
Calculate the magnitude of the numerator: |N(¦Ř)| = sqrt(real(N)^2 + imag(N)^2).
Calculate the magnitude of the denominator: |D(¦Ř)| = sqrt(real(D)^2 + imag(D)^2).
The total gain is |N(¦Ř)| / |D(¦Ř)|.
Parameters
[in] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the gain (Hz).
Returns
parameter_gt The linear gain (magnitude).
Definition at line 274 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, ctl_biquad_filter_t::b, CTL_PARAM_CONST_PI, and fs.
ctl_get_biquad_phase_lag()
parameter_gt ctl_get_biquad_phase_lag (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt f)
Calculates the phase lag of the biquad filter at a specific frequency.
This function evaluates the filter's complex frequency response H(e^(j¦ŘT)) at the given frequency f. Key Steps:
Calculate the normalized angular frequency: ¦ŘT = 2*pi*f / fs.
Evaluate the complex numerator N(¦Ř) = b0 + b1*e^(-j¦ŘT) + b2*e^(-j2¦ŘT).
Evaluate the complex denominator D(¦Ř) = 1 + a1*e^(-j¦ŘT) + a2*e^(-j2¦ŘT).
Calculate the phase of the numerator and denominator using atan2.
The total phase is phase(N) - phase(D).
The phase lag is the negative of the total phase.
Parameters
[in] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] f The frequency at which to calculate the phase lag (Hz).
Returns
parameter_gt The phase lag in radians. A positive value indicates lag.
Definition at line 242 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, ctl_biquad_filter_t::b, CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_allpass()
void ctl_init_biquad_allpass (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as an All-Pass Filter.
S-Domain Transfer Function:
\[ H(s) = \frac{s^2 - \frac{\omega_0}{Q}s + \omega_0^2}{s^2 + \frac{\omega_0}{Q}s + \omega_0^2} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Center frequency where phase shift is -180 degrees (Hz).
[in] Q Quality factor. Controls how quickly the phase changes around fc.
Definition at line 166 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_bpf()
void ctl_init_biquad_bpf (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Band-Pass Filter (BPF).
S-Domain Transfer Function:
\[ H(s) = \frac{\frac{\omega_0}{Q} s}{s^2 + \frac{\omega_0}{Q}s + \omega_0^2} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Center frequency (Hz).
[in] Q Quality factor. Higher Q means a narrower bandwidth.
Definition at line 132 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_highshelf()
void ctl_init_biquad_highshelf (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a High-Shelf Filter.
The High Self filter is the opposite of the Low Self filter, as it is used to enhance or attenuate all frequencies above a specified "inflection point frequency". S-Domain Transfer Function:
\[ H(s) = A \cdot \frac{s^2 + \frac{\sqrt{A}}{Q}\omega_0 s + \omega_0^2}{s^2 + \frac{1}{\sqrt{A}Q}\omega_0 s + \omega_0^2} \]
where
\[ A = 10^{gain_db} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Corner frequency (Hz).
[in] Q Quality factor (shelf slope).
[in] gain_db The desired gain or cut for the high frequencies in dB.
Definition at line 222 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_hpf()
void ctl_init_biquad_hpf (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a High-Pass Filter (HPF).
S-Domain Transfer Function:
\[ H(s) = \frac{s^2}{s^2 + \frac{\omega_0}{Q}s + \omega_0^2} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Cutoff frequency (Hz).
[in] Q Quality factor.
Definition at line 115 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_lowshelf()
void ctl_init_biquad_lowshelf (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a Low-Shelf Filter.
The Low Self filter is used to enhance or attenuate all frequencies below the specified "inflection point frequency", and its frequency response curve is like a shelf. S-Domain Transfer Function:
\[ H(s) = A \cdot \frac{s^2 + \frac{\omega_0}{\sqrt{A}}s + \omega_0^2}{s^2 + \sqrt{A}\omega_0 s + \omega_0^2} \]
where
\[ A = 10^{gain_db} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Corner frequency (Hz).
[in] Q Quality factor (shelf slope).
[in] gain_db The desired gain or cut for the low frequencies in dB.
Definition at line 202 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_lpf()
void ctl_init_biquad_lpf (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Low-Pass Filter (LPF).
Characteristics: Passes frequencies below the cutoff frequency fc and attenuates frequencies above it. S-Domain Transfer Function:
\[ H(s) = \frac{\omega_0^2}{s^2 + \frac{\omega_0}{Q}s + \omega_0^2} \]
Implementation Steps:
Calculate the normalized angular frequency omega.
Calculate intermediate variables alpha and cos_w0.
Calculate the denominator coefficient a0_inv for normalization.
Calculate the final a and b coefficients for the difference equation.
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Cutoff frequency (Hz).
[in] Q Quality factor. Controls the resonance peak at the cutoff frequency. A value of 0.707 gives a Butterworth response.
Definition at line 98 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_notch()
void ctl_init_biquad_notch (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q)
Initializes the biquad filter as a Notch Filter.
S-Domain Transfer Function:
\[ H(s) = \frac{s^2 + omega_0^2}{s^2 + \frac{\omega_0}{Q}s + \omega_0^2} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Center frequency to notch out (Hz).
[in] Q Quality factor. Higher Q means a narrower notch.
Definition at line 149 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_init_biquad_peaking_eq()
void ctl_init_biquad_peaking_eq (ctl_biquad_filter_t * obj, parameter_gt fs, parameter_gt fc, parameter_gt Q, parameter_gt gain_db)
Initializes the biquad filter as a Peaking EQ Filter.
Peaking EQ is the most common type of equalization (EQ) used to enhance or attenuate a frequency band centered around a certain central frequency, with a frequency response curve that is bell shaped or peak shaped. S-Domain Transfer Function:
\[ H(s) = \frac{s^2 + \frac{A}{Q}s + \omega_0^2}{s^2 + \frac{1}{AQ}s + \omega_0^2} \]
where
\[ A = 10^{gain_db} \]
Parameters
[out] obj Pointer to the biquad filter instance.
[in] fs Sampling frequency (Hz).
[in] fc Center frequency (Hz).
[in] Q Quality factor.
[in] gain_db The desired gain or cut in decibels (dB). Positive for boost, negative for cut.
Definition at line 183 of file ctl_component_discrete.c.
References ctl_biquad_filter_t::a, alpha, ctl_biquad_filter_t::b, ctl_clear_biquad_filter(), CTL_PARAM_CONST_PI, and fs.
ctl_step_biquad_filter()
GMP_STATIC_INLINE ctrl_gt ctl_step_biquad_filter (ctl_biquad_filter_t * obj, ctrl_gt input)
Executes one step of the 2nd-order IIR filter.
Parameters
[in,out] obj Pointer to the biquad filter instance.
[in] input The current input sample, x[n].
Returns
ctrl_gt The calculated output sample, y[n].
Definition at line 82 of file biquad_filter.h.
References ctl_biquad_filter_t::a, ctl_biquad_filter_t::b, ctl_mul, input, ctl_biquad_filter_t::out, ctl_biquad_filter_t::x, and ctl_biquad_filter_t::y.