GMP - CTL: FCS-MPC Current & Flux Controller for ACM
FCS-MPC Current & Flux Controller for ACM
Motor Control Library » Motor Controller Components
A model-predictive controller for fast torque and flux response in ACMs.
Data Structures
struct ctl_acm_mpc_init_t
Initialization parameters for the ACM MPC module.
struct ctl_acm_mpc_controller_t
Main structure for the ACM MPC controller.
Functions
void ctl_init_acm_mpc (ctl_acm_mpc_controller_t *mpc, const ctl_acm_mpc_init_t *init)
Initializes the ACM MPC module with motor and system parameters.
GMP_STATIC_INLINE void ctl_set_acm_mpc_flux_ref (ctl_acm_mpc_controller_t *mpc, ctrl_gt flux_ref)
Sets the reference magnitude for the rotor flux.
GMP_STATIC_INLINE void ctl_step_acm_mpc (ctl_acm_mpc_controller_t *mpc, ctl_vector2_t *idq_ref, ctl_vector2_t *is_ab_fbk, ctrl_gt omega_r, ctrl_gt _udc)
Executes one step of the ACM FCS-MPC algorithm.
GMP_STATIC_INLINE uint8_t ctl_get_acm_mpc_optimal_vector_index (const ctl_acm_mpc_controller_t *mpc)
Gets the index of the optimal voltage vector calculated by the MPC.
Variables
ctl_vector2_t MPC_VOLTAGE_VECTORS_NORMALIZED_ACM [8]
Table of the 8 standard voltage vectors in the alpha-beta frame.
Detailed Description
A model-predictive controller for fast torque and flux response in ACMs.
This module provides an advanced model-based controller for AC Induction Motors. It uses a discrete-time model of the ACM to predict the future state (stator currents and rotor flux) for each of the 8 possible inverter voltage vectors. It then selects the vector that minimizes a cost function, which penalizes both the current tracking error and any deviation from the desired rotor flux magnitude. This provides very fast torque and flux response. The controller uses a discretized ACM model to predict the next state:
\[ \mathbf{x}(k+1) = \mathbf{A}_d(\omega_r) \mathbf{x}(k) + \mathbf{B}_d \mathbf{u}(k) \]
where the state vector is \(\mathbf{x} = [\mathbf{i}_s, \mathbf{\psi}_r]^T\). A cost function is evaluated for each possible voltage vector \mathbf{u}_j:
\[ J_j = || \mathbf{i}_{s,ref}(k+1) - \mathbf{i}_{s,pred,j}(k+1) ||^2 + \lambda (\psi_{r,ref}^2 - ||\mathbf{\psi}_{r,pred,j}(k+1)||^2)^2 \]
The voltage vector \(\mathbf{u}_j\) that minimizes J is selected and applied.
Function Documentation
ctl_get_acm_mpc_optimal_vector_index()
GMP_STATIC_INLINE uint8_t ctl_get_acm_mpc_optimal_vector_index (const ctl_acm_mpc_controller_t * mpc)
Gets the index of the optimal voltage vector calculated by the MPC.
Parameters
[in] mpc Pointer to the MPC structure.
Returns
The index (0-7) of the optimal voltage vector.
Definition at line 208 of file acm_mpc.h.
References ctl_acm_mpc_controller_t::optimal_vector_index.
ctl_init_acm_mpc()
void ctl_init_acm_mpc (ctl_acm_mpc_controller_t * mpc, const ctl_acm_mpc_init_t * init)
Initializes the ACM MPC module with motor and system parameters.
Parameters
[out] mpc Pointer to the MPC structure.
[in] init Pointer to the initialization parameters structure.
Definition at line 171 of file ctl_mc_observer.c.
References ctl_acm_mpc_controller_t::c_is_pr, ctl_acm_mpc_controller_t::c_is_pr_w, ctl_acm_mpc_controller_t::c_is_u, ctl_acm_mpc_controller_t::c_iss, ctl_acm_mpc_controller_t::c_pr_is, ctl_acm_mpc_controller_t::c_pr_pr, ctl_vector2_clear(), float2ctrl, ctl_acm_mpc_controller_t::flux_ref_sq, init(), ctl_acm_mpc_controller_t::lambda_flux, ctl_acm_mpc_controller_t::optimal_vector_index, ctl_acm_mpc_controller_t::pole_pairs, ctl_acm_mpc_controller_t::psi_r_est, and ctl_acm_mpc_controller_t::Ts.
ctl_set_acm_mpc_flux_ref()
GMP_STATIC_INLINE void ctl_set_acm_mpc_flux_ref (ctl_acm_mpc_controller_t * mpc, ctrl_gt flux_ref)
Sets the reference magnitude for the rotor flux.
Parameters
[out] mpc Pointer to the MPC structure.
[in] flux_ref The desired rotor flux magnitude in Webers (Wb).
Definition at line 116 of file acm_mpc.h.
References ctl_acm_mpc_controller_t::flux_ref_sq.
ctl_step_acm_mpc()
GMP_STATIC_INLINE void ctl_step_acm_mpc (ctl_acm_mpc_controller_t * mpc, ctl_vector2_t * idq_ref, ctl_vector2_t * is_ab_fbk, ctrl_gt omega_r, ctrl_gt _udc)
Executes one step of the ACM FCS-MPC algorithm.
Parameters
[out] mpc Pointer to the MPC structure.
[in] idq_ref The reference d-q stator current vector.
[in] is_ab_fbk The feedback alpha-beta stator current vector.
[in] omega_r The current rotor mechanical speed (rad/s).
[in] udc The measured DC bus voltage (V).
Definition at line 129 of file acm_mpc.h.
References ctl_acm_mpc_controller_t::c_is_pr, ctl_acm_mpc_controller_t::c_is_pr_w, ctl_acm_mpc_controller_t::c_is_u, ctl_acm_mpc_controller_t::c_iss, ctl_acm_mpc_controller_t::c_pr_is, ctl_acm_mpc_controller_t::c_pr_pr, ctl_ct_ipark2(), ctl_mul, ctl_vector2_add(), ctl_vector2_mag_sq(), ctl_vector2_normalize(), ctl_vector2_scale(), ctl_vector2_sub(), ctl_acm_mpc_controller_t::flux_ref_sq, i, ctl_acm_mpc_controller_t::lambda_flux, MPC_VOLTAGE_VECTORS_NORMALIZED_ACM, ctl_acm_mpc_controller_t::optimal_vector_index, ctl_acm_mpc_controller_t::pole_pairs, ctl_acm_mpc_controller_t::psi_r_est, and ctl_acm_mpc_controller_t::Ts.
Variable Documentation
MPC_VOLTAGE_VECTORS_NORMALIZED_ACM
ctl_vector2_t MPC_VOLTAGE_VECTORS_NORMALIZED_ACM[8]
Table of the 8 standard voltage vectors in the alpha-beta frame.
The values are normalized and must be scaled by (2/3 * Udc).
Definition at line 51 of file acm_mpc.h.