GMP - CTL: Voltage Sag/Swell Detector
Voltage Sag/Swell Detector
Control Template Library Intrinsic » Protection Components
A module for detecting voltage sag and swell power quality events.
Data Structures
struct ctl_voltage_event_detector_t
Data structure for the voltage sag/swell detector.
Enumerations
enum ctl_voltage_event_status_t { VOLTAGE_EVENT_OK = 0 , VOLTAGE_EVENT_SAG = 1 , VOLTAGE_EVENT_SWELL = 2 }
Enumeration for the detected fault status.
Functions
void ctl_init_voltage_event_detector (ctl_voltage_event_detector_t *ved, parameter_gt sag_threshold, parameter_gt swell_threshold, parameter_gt sag_delay_ms, parameter_gt swell_delay_ms, parameter_gt nominal_freq, parameter_gt fs)
Initializes the voltage sag/swell detector.
GMP_STATIC_INLINE void ctl_clear_voltage_event_detector (ctl_voltage_event_detector_t *ved)
Clears the internal states and latched faults of the detector.
GMP_STATIC_INLINE ctl_voltage_event_status_t ctl_step_voltage_event_detector (ctl_voltage_event_detector_t *ved, ctrl_gt input)
Executes one step of the voltage event detection logic.
Detailed Description
A module for detecting voltage sag and swell power quality events.
This module monitors a sinusoidal input voltage to detect power quality events such as sags (undervoltage) and swells (overvoltage). It uses a Second-Order Generalized Integrator (SOGI) to extract the fundamental amplitude of the signal. A fault is flagged if the amplitude remains outside the configured thresholds for a specified duration.
Enumeration Type Documentation
ctl_voltage_event_status_t
enum ctl_voltage_event_status_t
Enumeration for the detected fault status.
Enumerator
VOLTAGE_EVENT_OK
No fault detected.
VOLTAGE_EVENT_SAG
A voltage sag event is active.
VOLTAGE_EVENT_SWELL
A voltage swell event is active.
Definition at line 41 of file sag_swell.h.
Function Documentation
ctl_clear_voltage_event_detector()
GMP_STATIC_INLINE void ctl_clear_voltage_event_detector (ctl_voltage_event_detector_t * ved)
Clears the internal states and latched faults of the detector.
Parameters
[out] ved Pointer to the voltage event detector instance.
Definition at line 88 of file sag_swell.h.
References ctl_voltage_event_detector_t::amplitude, ctl_clear_discrete_sogi(), ctl_voltage_event_detector_t::fault_status, ctl_voltage_event_detector_t::sag_counter, ctl_voltage_event_detector_t::sogi, ctl_voltage_event_detector_t::swell_counter, and VOLTAGE_EVENT_OK.
ctl_init_voltage_event_detector()
void ctl_init_voltage_event_detector (ctl_voltage_event_detector_t * ved, parameter_gt sag_threshold, parameter_gt swell_threshold, parameter_gt sag_delay_ms, parameter_gt swell_delay_ms, parameter_gt nominal_freq, parameter_gt fs)
Initializes the voltage sag/swell detector.
Parameters
[out] ved Pointer to the voltage event detector instance.
[in] sag_threshold The sag voltage threshold.
[in] swell_threshold The swell voltage threshold.
[in] sag_delay_ms The required duration of a sag event in milliseconds to trigger a fault.
[in] swell_delay_ms The required duration of a swell event in milliseconds to trigger a fault.
[in] nominal_freq The nominal frequency of the input signal in Hz.
[in] fs The sampling frequency in Hz.
Definition at line 21 of file ctl_component_protection.c.
References ctl_clear_voltage_event_detector(), ctl_init_discrete_sogi(), float2ctrl, fs, ctl_voltage_event_detector_t::sag_delay_samples, ctl_voltage_event_detector_t::sag_threshold, ctl_voltage_event_detector_t::sogi, ctl_voltage_event_detector_t::swell_delay_samples, and ctl_voltage_event_detector_t::swell_threshold.
ctl_step_voltage_event_detector()
GMP_STATIC_INLINE ctl_voltage_event_status_t ctl_step_voltage_event_detector (ctl_voltage_event_detector_t * ved, ctrl_gt input)
Executes one step of the voltage event detection logic.
Parameters
[in,out] ved Pointer to the voltage event detector instance.
[in] input The instantaneous input voltage sample.
Returns
ctl_voltage_event_status_t The current fault status.
Definition at line 103 of file sag_swell.h.
References ctl_voltage_event_detector_t::amplitude, ctl_get_discrete_sogi_ds(), ctl_get_discrete_sogi_qs(), ctl_mul, ctl_sqrt, ctl_step_discrete_sogi(), ctl_voltage_event_detector_t::fault_status, input, ctl_voltage_event_detector_t::sag_counter, ctl_voltage_event_detector_t::sag_delay_samples, ctl_voltage_event_detector_t::sag_threshold, ctl_voltage_event_detector_t::sogi, ctl_voltage_event_detector_t::swell_counter, ctl_voltage_event_detector_t::swell_delay_samples, ctl_voltage_event_detector_t::swell_threshold, VOLTAGE_EVENT_OK, VOLTAGE_EVENT_SAG, and VOLTAGE_EVENT_SWELL.