GMP - CTL: PMSM SMO Estimator
PMSM SMO Estimator
Motor Control Library » Motor Controller Observer & Estimate
A module for sensorless position and speed estimation using SMO.
Data Structures
struct ctl_smo_init_t
Initialization parameters for the SMO estimator module.
struct pmsm_smo_t
Holds the state and parameters for the SMO estimator.
Functions
void ctl_auto_tuning_pmsm_smo (ctl_smo_init_t *init, const mtr_current_init_t *ker_init)
Auto-calculates SMO parameters based on motor physics.
void ctl_init_pmsm_smo (pmsm_smo_t *smo, const ctl_smo_init_t *init)
Initializes the SMO estimator module.
GMP_STATIC_INLINE void ctl_clear_pmsm_smo (pmsm_smo_t *smo)
Clears the internal states of the SMO estimator.
GMP_STATIC_INLINE ctrl_gt ctl_step_pmsm_smo (pmsm_smo_t *smo, ctrl_gt u_alpha, ctrl_gt u_beta, ctrl_gt i_alpha, ctrl_gt i_beta)
Executes one step of the SMO position and speed estimation.
Detailed Description
A module for sensorless position and speed estimation using SMO.
Implements the observer model, sliding control law, filtering, and PLL required to track the rotor angle of a PMSM.
Implements the observer model, sliding control law, filtering, and PLL required to track the rotor angle of a PMSM.
This module implements an SMO to estimate the rotor position and speed of a Permanent Magnet Synchronous Motor. It uses the motor's voltage and current measurements to drive an observer model. A sliding control law generates a correction term (z) that, when filtered, represents the motor's back-EMF. A Phase-Locked Loop (PLL) then tracks the back-EMF signal to extract the rotor angle and speed.
The SMO is based on the PMSM voltage model in the stationary \(\alpha-\beta\) frame. The observer estimates the stator currents:
\[ \frac{d\hat{i}_{\alpha\beta}}{dt} = \frac{1}{L_s}(v_{\alpha\beta} - R_s\hat{i}_{\alpha\beta} - z_{\alpha\beta}) \]
The sliding control law, z, forces the estimated current to track the measured current:
\[ z_{\alpha\beta} = k_{slide} \cdot \text{sign}(\hat{i}_{\alpha\beta} - i_{\alpha\beta}) \]
When in the sliding mode, the filtered value of z is equal to the back-EMF:
\[ E_{\alpha\beta} \approx \bar{z}_{\alpha\beta} \]
Function Documentation
ctl_auto_tuning_pmsm_smo()
void ctl_auto_tuning_pmsm_smo (ctl_smo_init_t * init, const mtr_current_init_t * ker_init)
Auto-calculates SMO parameters based on motor physics.
Parameters
[out] init The SMO initialization structure to be filled.
[in] ker_init The motor physical parameters (Resistance, Inductance, etc.).
Definition at line 314 of file ctl_mc_observer.c.
References CTL_PARAM_CONST_2PI, float2ctrl, mtr_current_init_t::fs, mtr_current_init_t::i_base, init(), mtr_current_init_t::mtr_Ld, mtr_current_init_t::mtr_Lq, mtr_current_init_t::mtr_Rs, mtr_current_init_t::pole_pairs, mtr_current_init_t::spd_base, and mtr_current_init_t::v_base.
ctl_clear_pmsm_smo()
GMP_STATIC_INLINE void ctl_clear_pmsm_smo (pmsm_smo_t * smo)
Clears the internal states of the SMO estimator.
Parameters
[out] smo Pointer to the SMO structure.
Definition at line 142 of file pmsm.smo.h.
References ctl_clear_lowpass_filter(), ctl_clear_pid(), ctl_set_phasor_via_angle(), ctl_vector2_clear(), pmsm_smo_t::e_est, pmsm_smo_t::filter_e, pmsm_smo_t::filter_spd, pmsm_smo_t::i_est, phase_alpha, phase_beta, pmsm_smo_t::phasor, pmsm_smo_t::pid_pll, pmsm_smo_t::theta_est, pmsm_smo_t::wr_est, and pmsm_smo_t::z.
ctl_init_pmsm_smo()
void ctl_init_pmsm_smo (pmsm_smo_t * smo, const ctl_smo_init_t * init)
Initializes the SMO estimator module.
Parameters
[out] smo Pointer to the SMO structure to initialize.
[in] init Pointer to the structure containing initialization parameters.
Definition at line 273 of file ctl_mc_observer.c.
References ctl_init_lp_filter(), ctl_init_pid_Tmode(), CTL_PARAM_CONST_PI, ctl_set_phasor_via_angle(), ctl_set_pid_limit(), ctl_vector2_clear(), pmsm_smo_t::e_est, pmsm_smo_t::filter_e, pmsm_smo_t::filter_spd, float2ctrl, pmsm_smo_t::i_est, init(), pmsm_smo_t::k1, pmsm_smo_t::k2, pmsm_smo_t::k3, pmsm_smo_t::k_slide, pmsm_smo_t::phasor, pmsm_smo_t::pid_pll, pmsm_smo_t::spd_sf, pmsm_smo_t::theta_compensate, pmsm_smo_t::theta_est, pmsm_smo_t::wr_est, and pmsm_smo_t::z.
ctl_step_pmsm_smo()
GMP_STATIC_INLINE ctrl_gt ctl_step_pmsm_smo (pmsm_smo_t * smo, ctrl_gt u_alpha, ctrl_gt u_beta, ctrl_gt i_alpha, ctrl_gt i_beta)
Executes one step of the SMO position and speed estimation.
Parameters
[out] smo Pointer to the SMO structure.
[in] u_alpha The measured/commanded alpha-axis voltage.
[in] u_beta The measured/commanded beta-axis voltage.
[in] i_alpha The measured alpha-axis current.
[in] i_beta The measured beta-axis current.
Returns
The final estimated electrical angle with phase compensation (p.u.).
Definition at line 168 of file pmsm.smo.h.
References ctl_atan2, CTL_CTRL_CONST_1, CTL_CTRL_CONST_1_OVER_2PI, ctl_mul, ctl_sat, ctl_set_phasor_via_angle(), ctl_step_lowpass_filter(), ctl_step_pid_par(), ctrl_mod_1, pmsm_smo_t::e_est, rotation_ift::elec_position, pmsm_smo_t::encif, pmsm_smo_t::filter_e, pmsm_smo_t::filter_spd, float2ctrl, pmsm_smo_t::i_est, pmsm_smo_t::k1, pmsm_smo_t::k2, pmsm_smo_t::k3, pmsm_smo_t::k_slide, pmsm_smo_t::phasor, pmsm_smo_t::pid_pll, pmsm_smo_t::spd_sf, pmsm_smo_t::spdif, velocity_ift::speed, pmsm_smo_t::theta_compensate, pmsm_smo_t::theta_est, pmsm_smo_t::wr_est, and pmsm_smo_t::z.