GMP - CTL: FCS-MPC Current Controller
FCS-MPC Current Controller
Motor Control Library » Motor Controller Components
A model-predictive current controller for fast dynamic response.
Data Structures
struct ctl_mpc_init_t
Initialization parameters for the MPC module.
struct ctl_mpc_controller_t
Main structure for the MPC controller.
Functions
void ctl_init_mpc (ctl_mpc_controller_t *mpc, const ctl_mpc_init_t *init)
Initializes the MPC module with motor and system parameters.
GMP_STATIC_INLINE void ctl_step_mpc (ctl_mpc_controller_t *mpc, ctl_vector2_t *idq_ref, ctl_vector2_t *idq_fbk, ctl_vector2_t *phasor, ctrl_gt omega_e, ctrl_gt _udc)
Executes one step of the FCS-MPC algorithm.
GMP_STATIC_INLINE uint8_t ctl_get_mpc_optimal_vector_index (const ctl_mpc_controller_t *mpc)
Gets the index of the optimal voltage vector calculated by the MPC.
Variables
ctl_vector2_t MPC_VOLTAGE_VECTORS_NORMALIZED [8]
Table of the 8 standard voltage vectors in the alpha-beta frame.
Detailed Description
A model-predictive current controller for fast dynamic response.
This module provides an advanced model-based current controller. Instead of traditional PI loops, it uses a discrete-time model of the PMSM to predict the current response for each of the 8 possible inverter voltage vectors. It then selects the vector that minimizes a cost function, typically the squared error between the predicted current and the reference current. This approach offers very fast dynamic response and handles multivariable control and constraints intuitively. The controller uses the discretized PMSM voltage equations to predict the current at the next time step k+1:
\[ \mathbf{i}(k+1) = \mathbf{A}(\omega_e) \mathbf{i}(k) + \mathbf{B} \mathbf{u}(k) + \mathbf{E}(\omega_e) \]
A cost function is then evaluated for each possible voltage vector \(\mathbf{u}_j\):
\[ J_j = || \mathbf{i}_{ref}(k+1) - \mathbf{i}_{pred, j}(k+1) ||^2 \]
The voltage vector \(\mathbf{u}_j\) that minimizes J is selected and applied.
Function Documentation
ctl_get_mpc_optimal_vector_index()
GMP_STATIC_INLINE uint8_t ctl_get_mpc_optimal_vector_index (const ctl_mpc_controller_t * mpc)
Gets the index of the optimal voltage vector calculated by the MPC.
Parameters
[in] mpc Pointer to the MPC structure.
Returns
The index (0-7) of the optimal voltage vector.
Definition at line 174 of file pmsm_mpc.h.
References ctl_mpc_controller_t::optimal_vector_index.
ctl_init_mpc()
void ctl_init_mpc (ctl_mpc_controller_t * mpc, const ctl_mpc_init_t * init)
Initializes the MPC module with motor and system parameters.
This function pre-calculates the discrete-time system matrices based on the provided motor parameters to optimize the real-time step function.
Parameters
[out] mpc Pointer to the MPC structure.
[in] init Pointer to the initialization parameters structure.
Definition at line 337 of file ctl_mc_current_loop.c.
References ctl_mpc_controller_t::A_const, ctl_mpc_controller_t::B, ctl_matrix2_set(), init(), ctl_mpc_controller_t::Ld, ctl_mpc_controller_t::Lq, ctl_mpc_controller_t::optimal_vector_index, ctl_mpc_controller_t::psi_f, and ctl_mpc_controller_t::Ts.
ctl_step_mpc()
GMP_STATIC_INLINE void ctl_step_mpc (ctl_mpc_controller_t * mpc, ctl_vector2_t * idq_ref, ctl_vector2_t * idq_fbk, ctl_vector2_t * phasor, ctrl_gt omega_e, ctrl_gt _udc)
Executes one step of the FCS-MPC algorithm.
Parameters
[out] mpc Pointer to the MPC structure.
[in] idq_ref The reference d-q current vector [id_ref, iq_ref]^T.
[in] idq_fbk The feedback d-q current vector from the Park transform.
[in] phasor The current rotor angle phasor {sin(theta), cos(theta)}.
[in] omega_e The current electrical speed (rad/s).
[in] udc The measured DC bus voltage (V).
Definition at line 113 of file pmsm_mpc.h.
References ctl_mpc_controller_t::A_const, ctl_mpc_controller_t::B, ctl_ct_park2(), ctl_matrix2_mul_vector(), ctl_matrix2_set(), ctl_vector2_add(), ctl_vector2_mag_sq(), ctl_vector2_scale(), ctl_vector2_sub(), i, ctl_mpc_controller_t::Ld, ctl_mpc_controller_t::Lq, MPC_VOLTAGE_VECTORS_NORMALIZED, ctl_mpc_controller_t::optimal_vector_index, ctl_mpc_controller_t::psi_f, and ctl_mpc_controller_t::Ts.
Variable Documentation
MPC_VOLTAGE_VECTORS_NORMALIZED
ctl_vector2_t MPC_VOLTAGE_VECTORS_NORMALIZED[8] extern
Table of the 8 standard voltage vectors in the alpha-beta frame.
The values are normalized and must be scaled by (2/3 * Udc). V0 and V7 are zero vectors.
Definition at line 326 of file ctl_mc_current_loop.c.