GMP - CTL: Dead-beat Predictive Current Controller
Dead-beat Predictive Current Controller
Motor Control Library » Motor Controller Components
A model-based current controller for fast dynamic response.
Data Structures
struct ctl_dpcc_init_t
Initialization parameters for the DPCC module.
struct ctl_dpcc_controller_t
Main structure for the DPCC controller.
Functions
GMP_STATIC_INLINE void ctl_clear_dpcc (ctl_dpcc_controller_t *dpcc)
Clears the internal state variables of the DPCC module.
void ctl_init_dpcc (ctl_dpcc_controller_t *dpcc, const ctl_dpcc_init_t *init)
Initializes the DPCC module with motor and system parameters.
GMP_STATIC_INLINE void ctl_step_dpcc (ctl_dpcc_controller_t *dpcc, const ctl_vector2_t *idq_ref, const ctl_vector2_t *idq_fbk, ctrl_gt omega_e)
Executes one step of the Dead-beat Predictive Current Control algorithm.
GMP_STATIC_INLINE ctrl_gt ctl_get_dpcc_ud (const ctl_dpcc_controller_t *dpcc)
Gets the calculated d-axis output voltage.
GMP_STATIC_INLINE ctrl_gt ctl_get_dpcc_uq (const ctl_dpcc_controller_t *dpcc)
Gets the calculated q-axis output voltage.
Detailed Description
A model-based current controller for fast dynamic response.
This module provides a model-based current controller that aims to eliminate current error in a single control step (dead-beat). It uses the discrete-time model of the PMSM to predict the current at the next time step based on the previously applied voltage. It then calculates the required voltage for the current step to make the predicted current match the reference current at the next step. This approach can offer faster dynamic response than traditional PI controllers.
The controller is based on the discretized PMSM voltage equations:
\[ i_d(k+1) = i_d(k)+\frac{T_s}{L_d}\left[u_d(k)-R_si_d (k)+ \omega_e L_qi_q(k)\right] \]
\[ i_q(k+1) = i_q(k)+\frac{T_s}{L_q}\left[ u_q(k)-R_si_q (k)- \omega_e (L_di_d(k)+\Psi_f)\right] \]
By setting \(i_d(k+1)\) and \(i_q(k+1)\) to their reference values, we can solve for the required voltage \(u_d(k)\) and \(u_q(k)\). To compensate for the one-step digital delay, a prediction step is used.
Function Documentation
ctl_clear_dpcc()
GMP_STATIC_INLINE void ctl_clear_dpcc (ctl_dpcc_controller_t * dpcc)
Clears the internal state variables of the DPCC module.
Parameters
[out] dpcc Pointer to the DPCC structure.
Definition at line 97 of file PMSM_DPCC.h.
References ctl_vector2_clear(), ctl_dpcc_controller_t::idq_predicted, ctl_dpcc_controller_t::udq_last, and ctl_dpcc_controller_t::udq_out.
ctl_get_dpcc_ud()
GMP_STATIC_INLINE ctrl_gt ctl_get_dpcc_ud (const ctl_dpcc_controller_t * dpcc)
Gets the calculated d-axis output voltage.
Parameters
[in] dpcc Pointer to the DPCC structure.
Returns
The calculated d-axis voltage reference.
Definition at line 157 of file PMSM_DPCC.h.
References ctl_dpcc_controller_t::udq_out.
ctl_get_dpcc_uq()
GMP_STATIC_INLINE ctrl_gt ctl_get_dpcc_uq (const ctl_dpcc_controller_t * dpcc)
Gets the calculated q-axis output voltage.
Parameters
[in] dpcc Pointer to the DPCC structure.
Returns
The calculated q-axis voltage reference.
Definition at line 167 of file PMSM_DPCC.h.
References ctl_dpcc_controller_t::udq_out.
ctl_init_dpcc()
void ctl_init_dpcc (ctl_dpcc_controller_t * dpcc, const ctl_dpcc_init_t * init)
Initializes the DPCC module with motor and system parameters.
This function pre-calculates all necessary coefficients from the motor parameters to optimize the real-time step function.
Parameters
[out] dpcc Pointer to the DPCC structure.
[in] init Pointer to the initialization parameters structure.
Definition at line 114 of file ctl_mc_current_loop.c.
References ctl_clear_dpcc(), float2ctrl, init(), ctl_dpcc_controller_t::ld, ctl_dpcc_controller_t::ld_over_ts, ctl_dpcc_controller_t::lq, ctl_dpcc_controller_t::lq_over_ts, ctl_dpcc_controller_t::psi_f, ctl_dpcc_controller_t::rs, ctl_dpcc_controller_t::ts_over_ld, and ctl_dpcc_controller_t::ts_over_lq.
ctl_step_dpcc()
GMP_STATIC_INLINE void ctl_step_dpcc (ctl_dpcc_controller_t * dpcc, const ctl_vector2_t * idq_ref, const ctl_vector2_t * idq_fbk, ctrl_gt omega_e)
Executes one step of the Dead-beat Predictive Current Control algorithm.
Parameters
[out] dpcc Pointer to the DPCC structure.
[in] idq_ref The reference d-q current vector [id_ref, iq_ref]^T.
[in] idq_fbk The feedback d-q current vector from the Park transform.
[in] omega_e The current electrical speed (rad/s).
Definition at line 121 of file PMSM_DPCC.h.
References ctl_mul, ctl_vector2_copy(), ctl_dpcc_controller_t::idq_predicted, ctl_dpcc_controller_t::ld, ctl_dpcc_controller_t::ld_over_ts, ctl_dpcc_controller_t::lq, ctl_dpcc_controller_t::lq_over_ts, ctl_dpcc_controller_t::psi_f, ctl_dpcc_controller_t::rs, ctl_dpcc_controller_t::ts_over_ld, ctl_dpcc_controller_t::ts_over_lq, ctl_dpcc_controller_t::udq_last, and ctl_dpcc_controller_t::udq_out.