GMP - CTL: Direct Torque Controller (DTC)
Direct Torque Controller (DTC)
Motor Control Library » Motor Controller Components
A high-performance controller based on direct flux and torque regulation.
Data Structures
struct ctl_dtc_init_t
Initialization parameters for the DTC module.
struct ctl_dtc_controller_t
Main structure for the DTC controller.
Functions
void ctl_init_dtc (ctl_dtc_controller_t *dtc, const ctl_dtc_init_t *init)
Initializes the DTC controller.
GMP_STATIC_INLINE void ctl_set_dtc_references (ctl_dtc_controller_t *dtc, ctrl_gt flux_ref, ctrl_gt torque_ref)
Sets the reference (target) values for the flux and torque controllers.
GMP_STATIC_INLINE void ctl_step_dtc (ctl_dtc_controller_t *dtc, ctrl_gt i_alpha, ctrl_gt i_beta, ctrl_gt _udc)
Executes one step of the Direct Torque Control algorithm.
GMP_STATIC_INLINE uint8_t ctl_get_dtc_vector_index (const ctl_dtc_controller_t *dtc)
Gets the selected voltage vector index.
Variables
uint8_t DTC_SWITCH_TABLE [6][4]
The optimal voltage vector switching table for a 2-level DTC scheme.
ctrl_gt V_ALPHA_BETA_TABLE [8][2]
Table to convert voltage vector index (0-7) to alpha-beta voltages.
Detailed Description
A high-performance controller based on direct flux and torque regulation.
This module provides a complete DTC controller. Unlike FOC, DTC does not use inner current loops or a PWM modulator. Instead, it estimates the stator flux and electromagnetic torque and uses two hysteresis controllers to keep them within desired bands. Based on the outputs of the hysteresis controllers and the current sector of the stator flux vector, an optimal voltage vector is selected from a switching table and applied directly to the motor for the entire control period. The controller is based on the following estimations:
Stator Flux Estimation (Voltage Model):
\[ \vec{\psi_s} = \int (\vec{v_s} - R_s \vec{i_s}) dt \]
Electromagnetic Torque Estimation:
\[ T_e = \frac{3}{2} p (\psi_{s\alpha} i_{s\beta} - \psi_{s\beta} i_{s\alpha}) \]
Function Documentation
ctl_get_dtc_vector_index()
GMP_STATIC_INLINE uint8_t ctl_get_dtc_vector_index (const ctl_dtc_controller_t * dtc)
Gets the selected voltage vector index.
Parameters
[in] dtc Pointer to the DTC structure.
Returns
The index of the selected voltage vector (0-7).
Definition at line 169 of file dtc.h.
References ctl_dtc_controller_t::voltage_vector_index.
ctl_init_dtc()
void ctl_init_dtc (ctl_dtc_controller_t * dtc, const ctl_dtc_init_t * init)
Initializes the DTC controller.
Parameters
[out] dtc Pointer to the DTC structure.
[in] init Pointer to the initialization parameters structure.
Definition at line 189 of file ctl_mc_current_loop.c.
References ctl_init_hysteresis_controller(), ctl_vector2_clear(), ctl_dtc_controller_t::flux_hcc, ctl_dtc_controller_t::flux_mag_est, ctl_dtc_controller_t::flux_sector, init(), ctl_dtc_controller_t::pole_pairs, ctl_dtc_controller_t::rs, ctl_dtc_controller_t::stator_flux, ctl_dtc_controller_t::torque_est, ctl_dtc_controller_t::torque_hcc, ctl_dtc_controller_t::ts, and ctl_dtc_controller_t::voltage_vector_index.
ctl_set_dtc_references()
GMP_STATIC_INLINE void ctl_set_dtc_references (ctl_dtc_controller_t * dtc, ctrl_gt flux_ref, ctrl_gt torque_ref)
Sets the reference (target) values for the flux and torque controllers.
Parameters
[out] dtc Pointer to the DTC structure.
[in] flux_ref The target stator flux magnitude (Wb).
[in] torque_ref The target electromagnetic torque (Nm).
Definition at line 119 of file dtc.h.
References ctl_set_hysteresis_target(), ctl_dtc_controller_t::flux_hcc, and ctl_dtc_controller_t::torque_hcc.
ctl_step_dtc()
GMP_STATIC_INLINE void ctl_step_dtc (ctl_dtc_controller_t * dtc, ctrl_gt i_alpha, ctrl_gt i_beta, ctrl_gt _udc)
Executes one step of the Direct Torque Control algorithm.
Parameters
[out] dtc Pointer to the DTC structure.
[in] i_alpha The measured alpha-axis current.
[in] i_beta The measured beta-axis current.
[in] udc The measured DC bus voltage.
Definition at line 132 of file dtc.h.
References ctl_atan2, CTL_CTRL_CONST_PI, ctl_mul, ctl_sqrt, ctl_step_hysteresis_controller(), DTC_SWITCH_TABLE, ctl_dtc_controller_t::flux_hcc, ctl_dtc_controller_t::flux_mag_est, ctl_dtc_controller_t::flux_sector, ctl_dtc_controller_t::pole_pairs, ctl_dtc_controller_t::rs, ctl_dtc_controller_t::stator_flux, ctl_dtc_controller_t::torque_est, ctl_dtc_controller_t::torque_hcc, ctl_dtc_controller_t::ts, V_ALPHA_BETA_TABLE, and ctl_dtc_controller_t::voltage_vector_index.
Variable Documentation
DTC_SWITCH_TABLE
uint8_t DTC_SWITCH_TABLE[6][4] extern
The optimal voltage vector switching table for a 2-level DTC scheme.
Rows correspond to the flux vector sector (1-6). Columns correspond to the combined hysteresis outputs [Flux, Torque]: [0,0]->[Dec,Dec], [0,1]->[Dec,Inc], [1,0]->[Inc,Dec], [1,1]->[Inc,Inc]
Definition at line 167 of file ctl_mc_current_loop.c.
V_ALPHA_BETA_TABLE
ctrl_gt V_ALPHA_BETA_TABLE[8][2] extern
Table to convert voltage vector index (0-7) to alpha-beta voltages.
Assumes Vdc is the DC bus voltage. The values are scaled by 2/3.
Definition at line 178 of file ctl_mc_current_loop.c.