GMP - CTL: Protection Strategy API
Protection Strategy API
Digital Power Control Library » Digital Power Components
Functions and data structures for standard VIP (Voltage, Current, Power) protection.
Data Structures
struct std_vip_protection_t
Data structure for the standard VIP "brick-wall" protection module.
struct std_foldback_protection_t
Data structure for a foldback current protection module.
Functions
void ctl_init_vip_protection (std_vip_protection_t *obj, parameter_gt power_f_cut, parameter_gt voltage_f_cut, parameter_gt current_f_cut, parameter_gt v_max, parameter_gt v_base, parameter_gt i_max, parameter_gt i_base, parameter_gt p_max, parameter_gt fs)
Initializes the VIP protection module.
void ctl_attach_vip_protection (std_vip_protection_t *obj, adc_ift *uo, adc_ift *io)
Attaches the protection module to the physical ADC input interfaces.
GMP_STATIC_INLINE void ctl_clear_vip_protection_error (std_vip_protection_t *obj)
Clears a latched error flag.
GMP_STATIC_INLINE fast_gt ctl_step_vip_protection (std_vip_protection_t *obj)
Executes one step of the VIP protection logic.
void ctl_init_foldback_protection (std_foldback_protection_t *obj, parameter_gt voltage_f_cut, parameter_gt current_f_cut, parameter_gt v_rated, parameter_gt i_max, parameter_gt i_short, parameter_gt fs)
Initializes the foldback protection module.
void ctl_attach_foldback_protection (std_foldback_protection_t *obj, adc_ift *uo, adc_ift *io)
Attaches the foldback protection module to the physical ADC input interfaces.
GMP_STATIC_INLINE void ctl_clear_foldback_state (std_foldback_protection_t *obj)
Clears the overcurrent state flag.
GMP_STATIC_INLINE fast_gt ctl_step_foldback_protection (std_foldback_protection_t *obj)
Executes one step of the foldback protection logic.
ctrl_gt ctl_get_foldback_protection_current_limit (std_foldback_protection_t *obj)
this function will get foldback protect current limit result.
Detailed Description
Functions and data structures for standard VIP (Voltage, Current, Power) protection.
Contains standard protection modules for power converters.
This file implements a standard "brick-wall" protection scheme against over-voltage, over-current, and over-power conditions.
Function Documentation
ctl_attach_foldback_protection()
void ctl_attach_foldback_protection (std_foldback_protection_t * obj, adc_ift * uo, adc_ift * io)
Attaches the foldback protection module to the physical ADC input interfaces.
Parameters
[out] obj Pointer to the foldback protection instance.
[in] uo Pointer to the ADC interface for the output voltage.
[in] io Pointer to the ADC interface for the output current.
Definition at line 143 of file ctl_dp_basic.c.
References std_foldback_protection_t::adc_io, and std_foldback_protection_t::adc_uo.
ctl_attach_vip_protection()
void ctl_attach_vip_protection (std_vip_protection_t * obj, adc_ift * uo, adc_ift * io)
Attaches the protection module to the physical ADC input interfaces.
Parameters
[out] obj Pointer to the VIP protection instance.
[in] uo Pointer to the ADC interface for the output voltage.
[in] io Pointer to the ADC interface for the output current.
Definition at line 95 of file ctl_dp_basic.c.
References std_vip_protection_t::adc_io, and std_vip_protection_t::adc_uo.
ctl_clear_foldback_state()
GMP_STATIC_INLINE void ctl_clear_foldback_state (std_foldback_protection_t * obj)
Clears the overcurrent state flag.
Call this function to acknowledge and reset the overcurrent flag.
Parameters
[out] obj Pointer to the foldback protection instance.
Definition at line 199 of file protectoion_strategy.h.
References std_foldback_protection_t::flag_overcurrent.
ctl_clear_vip_protection_error()
GMP_STATIC_INLINE void ctl_clear_vip_protection_error (std_vip_protection_t * obj)
Clears a latched error flag.
This function must be called to reset the protection module after a fault has occurred.
Parameters
[out] obj Pointer to the VIP protection instance.
Definition at line 96 of file protectoion_strategy.h.
References std_vip_protection_t::flag_error.
ctl_get_foldback_protection_current_limit()
ctrl_gt ctl_get_foldback_protection_current_limit (std_foldback_protection_t * obj)
this function will get foldback protect current limit result.
Definition at line 255 of file protectoion_strategy.h.
References std_foldback_protection_t::current_limit_output.
ctl_init_foldback_protection()
void ctl_init_foldback_protection (std_foldback_protection_t * obj, parameter_gt voltage_f_cut, parameter_gt current_f_cut, parameter_gt v_rated, parameter_gt i_max, parameter_gt i_short, parameter_gt fs)
Initializes the foldback protection module.
Parameters
[out] obj Pointer to the foldback protection instance.
[in] voltage_f_cut Cutoff frequency for the voltage measurement filter.
[in] current_f_cut Cutoff frequency for the current measurement filter.
[in] v_rated The rated output voltage. Foldback begins when the voltage drops below this level.
[in] i_max The maximum current limit under normal operation (at v_rated).
[in] i_short The desired current limit during a full short-circuit (at v_out = 0).
[in] fs Sampling frequency of the controller.
Definition at line 116 of file ctl_dp_basic.c.
References ctl_div, ctl_init_lp_filter(), std_foldback_protection_t::current_filter, std_foldback_protection_t::current_limit_output, std_foldback_protection_t::current_max, std_foldback_protection_t::current_short_circuit, fs, std_foldback_protection_t::slope, std_foldback_protection_t::voltage_filter, and std_foldback_protection_t::voltage_rated.
ctl_init_vip_protection()
void ctl_init_vip_protection (std_vip_protection_t * obj, parameter_gt power_f_cut, parameter_gt voltage_f_cut, parameter_gt current_f_cut, parameter_gt v_max, parameter_gt v_base, parameter_gt i_max, parameter_gt i_base, parameter_gt p_max, parameter_gt fs)
Initializes the VIP protection module.
Parameters
[out] obj Pointer to the VIP protection instance.
[in] power_f_cut Cutoff frequency for the power measurement filter.
[in] voltage_f_cut Cutoff frequency for the voltage measurement filter.
[in] current_f_cut Cutoff frequency for the current measurement filter.
[in] v_max Maximum voltage limit.
[in] v_base Base voltage for per-unit conversion (if applicable).
[in] i_max Maximum current limit.
[in] i_base Base current for per-unit conversion (if applicable).
[in] p_max Maximum power limit.
[in] fs Sampling frequency of the controller.
Definition at line 101 of file ctl_dp_basic.c.
References ctl_init_lp_filter(), std_vip_protection_t::current_filter, std_vip_protection_t::current_max, float2ctrl, fs, std_vip_protection_t::power_filter, std_vip_protection_t::power_max, std_vip_protection_t::voltage_filter, and std_vip_protection_t::voltage_max.
ctl_step_foldback_protection()
GMP_STATIC_INLINE fast_gt ctl_step_foldback_protection (std_foldback_protection_t * obj)
Executes one step of the foldback protection logic.
This function filters the inputs and calculates the dynamic current limit based on the measured output voltage. It also sets a flag if the measured current exceeds this limit.
Parameters
[in,out] obj Pointer to the foldback protection instance.
Returns
The calculated dynamic current limit for the current control loop.
Definition at line 211 of file protectoion_strategy.h.
References std_foldback_protection_t::adc_io, std_foldback_protection_t::adc_uo, ctl_mul, ctl_step_lowpass_filter(), std_foldback_protection_t::current_filter, std_foldback_protection_t::current_limit_output, std_foldback_protection_t::current_max, std_foldback_protection_t::current_short_circuit, std_foldback_protection_t::flag_overcurrent, std_foldback_protection_t::iout, std_foldback_protection_t::slope, std_foldback_protection_t::uout, std_foldback_protection_t::voltage_filter, and std_foldback_protection_t::voltage_rated.
ctl_step_vip_protection()
GMP_STATIC_INLINE fast_gt ctl_step_vip_protection (std_vip_protection_t * obj)
Executes one step of the VIP protection logic.
This function filters the inputs, calculates power, and checks against the limits. If a limit is exceeded, it sets a persistent error flag.
Parameters
[in,out] obj Pointer to the VIP protection instance.
Returns
The current state of the error flag (0 for no error, 1 for error).
Definition at line 108 of file protectoion_strategy.h.
References std_vip_protection_t::adc_io, std_vip_protection_t::adc_uo, ctl_mul, ctl_step_lowpass_filter(), std_vip_protection_t::current_filter, std_vip_protection_t::current_max, std_vip_protection_t::flag_error, std_vip_protection_t::iout, std_vip_protection_t::pout, std_vip_protection_t::power_filter, std_vip_protection_t::power_max, std_vip_protection_t::uout, std_vip_protection_t::voltage_filter, and std_vip_protection_t::voltage_max.