GMP - CTL: 4D Vector Math
4D Vector Math
Control Math Library » Linear Algebra
A collection of types and functions for 4D vector arithmetic.
Data Structures
struct vector4_gt
Data structure for representing a 4D vector.
Functions
GMP_STATIC_INLINE void ctl_vector4_clear (ctl_vector4_t *vec)
Clears a 4D vector, setting its components to zero.
GMP_STATIC_INLINE void ctl_vector4_set (ctl_vector4_t *vec, ctrl_gt v)
Sets all components of a 4D vector to a single scalar value.
GMP_STATIC_INLINE void ctl_vector4_copy (ctl_vector4_t *dup, ctl_vector4_t *vec)
Copies the contents of one 4D vector to another.
GMP_STATIC_INLINE void ctl_vector4_add (ctl_vector4_t *result, ctl_vector4_t *a, ctl_vector4_t *b)
Adds two 4D vectors.
GMP_STATIC_INLINE void ctl_vector4_sub (ctl_vector4_t *result, ctl_vector4_t *a, ctl_vector4_t *b)
Subtracts one 4D vector from another.
GMP_STATIC_INLINE void ctl_vector4_scale (ctl_vector4_t *result, ctl_vector4_t *vec, ctrl_gt scalar)
Multiplies a 4D vector by a scalar value.
GMP_STATIC_INLINE ctrl_gt ctl_vector4_dot (ctl_vector4_t *a, ctl_vector4_t *b)
Calculates the dot product of two 4D vectors.
GMP_STATIC_INLINE ctrl_gt ctl_vector4_mag_sq (ctl_vector4_t *vec)
Calculates the squared magnitude (length) of a 4D vector. This is computationally cheaper than ctl_vector4_mag as it avoids a square root.
GMP_STATIC_INLINE ctrl_gt ctl_vector4_mag (ctl_vector4_t *vec)
Calculates the magnitude (length) of a 4D vector.
GMP_STATIC_INLINE void ctl_vector4_normalize (ctl_vector4_t *result, ctl_vector4_t *vec)
Normalizes a 4D vector to produce a unit vector (a vector with length 1).
Detailed Description
A collection of types and functions for 4D vector arithmetic.
Function Documentation
ctl_vector4_add()
GMP_STATIC_INLINE void ctl_vector4_add (ctl_vector4_t * result, ctl_vector4_t * a, ctl_vector4_t * b)
Adds two 4D vectors.
Parameters
a The first vector.
b The second vector.
[out] result The resulting vector (a + b).
Definition at line 89 of file vector4.h.
ctl_vector4_clear()
GMP_STATIC_INLINE void ctl_vector4_clear (ctl_vector4_t * vec)
Clears a 4D vector, setting its components to zero.
Parameters
[out] vec Pointer to the vector to be cleared.
Definition at line 49 of file vector4.h.
References vector4_gt::dat.
ctl_vector4_copy()
GMP_STATIC_INLINE void ctl_vector4_copy (ctl_vector4_t * dup, ctl_vector4_t * vec)
Copies the contents of one 4D vector to another.
Parameters
[out] dup Pointer to the destination vector.
[in] vec Pointer to the source vector.
Definition at line 75 of file vector4.h.
ctl_vector4_dot()
GMP_STATIC_INLINE ctrl_gt ctl_vector4_dot (ctl_vector4_t * a, ctl_vector4_t * b)
Calculates the dot product of two 4D vectors.
\[a \cdot b = a_x b_x + a_y b_y + a_z b_z + a_w b_w \]
Parameters
a The first vector.
b The second vector.
Returns
The dot product.
Definition at line 134 of file vector4.h.
References ctl_mul.
ctl_vector4_mag()
GMP_STATIC_INLINE ctrl_gt ctl_vector4_mag (ctl_vector4_t * vec)
Calculates the magnitude (length) of a 4D vector.
Parameters
vec The input vector.
Returns
The magnitude of the vector.
Definition at line 157 of file vector4.h.
References ctl_sqrt, and ctl_vector4_mag_sq().
ctl_vector4_mag_sq()
GMP_STATIC_INLINE ctrl_gt ctl_vector4_mag_sq (ctl_vector4_t * vec)
Calculates the squared magnitude (length) of a 4D vector. This is computationally cheaper than ctl_vector4_mag as it avoids a square root.
Parameters
vec The input vector.
Returns
The squared magnitude of the vector.
Definition at line 146 of file vector4.h.
References ctl_mul.
ctl_vector4_normalize()
GMP_STATIC_INLINE void ctl_vector4_normalize (ctl_vector4_t * result, ctl_vector4_t * vec)
Normalizes a 4D vector to produce a unit vector (a vector with length 1).
Parameters
vec The vector to be normalized.
[out] result The normalized (unit) vector. Returns a zero vector if the magnitude is zero.
Definition at line 167 of file vector4.h.
References ctl_div, ctl_vector4_clear(), ctl_vector4_mag(), and float2ctrl.
ctl_vector4_scale()
GMP_STATIC_INLINE void ctl_vector4_scale (ctl_vector4_t * result, ctl_vector4_t * vec, ctrl_gt scalar)
Multiplies a 4D vector by a scalar value.
Parameters
vec The vector to be scaled.
scalar The scalar value.
[out] result The resulting scaled vector.
Definition at line 117 of file vector4.h.
References ctl_mul.
ctl_vector4_set()
GMP_STATIC_INLINE void ctl_vector4_set (ctl_vector4_t * vec, ctrl_gt v)
Sets all components of a 4D vector to a single scalar value.
Parameters
[out] vec Pointer to the vector to be set.
[in] v The scalar value to set all components to.
Definition at line 62 of file vector4.h.
ctl_vector4_sub()
GMP_STATIC_INLINE void ctl_vector4_sub (ctl_vector4_t * result, ctl_vector4_t * a, ctl_vector4_t * b)
Subtracts one 4D vector from another.
Parameters
a The minuend vector.
b The subtrahend vector.
[out] result The resulting vector (a - b).
Definition at line 103 of file vector4.h.