GMP - CTL: PMSM HFI Controller
PMSM HFI Controller
Motor Control Library » Motor Controller Suite
A module for controlling a PMSM using Field-Oriented Control.
Data Structures
struct pmsm_hfi_controller_t
Main structure for the PMSM Bare Controller.
struct pmsm_hfi_controller_init_t
Initialization parameters for the PMSM Bare Controller.
Macros
#define MTR_CTRL_CURRENT_MEASUREMENT_PHASES ((3))
Configures the number of phase current sensors used for measurement.
#define MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES ((3))
Configures the number of phase voltage sensors used for measurement.
#define MTR_CTRL_FEEDFORWARD_STRATEGY (1)
Selects the feedforward strategy for the controller.
Functions
void ctl_init_pmsm_hfi_controller (pmsm_hfi_controller_t *ctrl, pmsm_hfi_controller_init_t *init)
Initializes the PMSM HFI Controller.
void ctl_attach_pmsm_hfi_output (pmsm_hfi_controller_t *ctrl, tri_pwm_ift *pwm_out)
Attaches the controller to a three-phase PWM output interface.
GMP_STATIC_INLINE void ctl_clear_pmsm_hfi_ctrl (pmsm_hfi_controller_t *ctrl)
Resets all internal states and integrators of the PID controllers.
GMP_STATIC_INLINE void ctl_step_pmsm_hfi_ctrl (pmsm_hfi_controller_t *ctrl)
Executes one step of the PMSM FOC HFI control loop.
GMP_STATIC_INLINE void ctl_enable_pmsm_hfi_ctrl (pmsm_hfi_controller_t *ctrl)
Enables the entire PMSM controller.
GMP_STATIC_INLINE void ctl_disable_pmsm_hfi_ctrl (pmsm_hfi_controller_t *ctrl)
Disables the entire PMSM controller.
GMP_STATIC_INLINE void ctl_enable_pmsm_hfi_ctrl_output (pmsm_hfi_controller_t *ctrl)
Enables PWM signal output.
GMP_STATIC_INLINE void ctl_disable_pmsm_hfi_ctrl_output (pmsm_hfi_controller_t *ctrl)
Disables PWM signal output.
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_valphabeta_mode (pmsm_hfi_controller_t *ctrl)
Sets the controller to V_alpha_beta mode.
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_valphabeta (pmsm_hfi_controller_t *ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target alpha and beta voltage components.
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_voltage_mode (pmsm_hfi_controller_t *ctrl)
Sets the controller to Vdq (voltage) mode.
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_vdq_ff (pmsm_hfi_controller_t *ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the d-q voltage feedforward (or reference) values.
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_current_mode (pmsm_hfi_controller_t *ctrl)
Sets the controller to Idq (current) mode.
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_idq_ff (pmsm_hfi_controller_t *ctrl, ctrl_gt id, ctrl_gt iq)
Sets the d-q current feedforward (or reference) values.
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_velocity_mode (pmsm_hfi_controller_t *ctrl)
Sets the controller to velocity mode.
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_speed (pmsm_hfi_controller_t *ctrl, ctrl_gt spd)
Sets the target speed for the velocity controller.
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_position_mode (pmsm_hfi_controller_t *ctrl)
Sets the controller to position mode.
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_position (pmsm_hfi_controller_t *ctrl, int32_t revolution, ctrl_gt pos)
Sets the target position for the position controller.
Detailed Description
A module for controlling a PMSM using Field-Oriented Control.
This module contains the data structures and functions to implement a full FOC controller with cascaded control loops for position, velocity, and current.
This module contains the data structures and functions to implement a full FOC controller with cascaded control loops for position, velocity, and current. This file defines the data structures, functions, and control logic for a generic Permanent Magnet Synchronous Motor (PMSM) controller. It supports various control modes, including voltage, current, velocity, and position control. The implementation can be configured for discrete or continuous PID controllers and supports different hardware setups for current and voltage measurement.
Usage involves these steps:
Attach hardware interfaces (ADC, PWM, encoders) using the provided functions.
Initialize the controller structure with motor and control parameters via ctl_init_pmsm_hfi_hfi_controller.
Select an operating mode (e.g., ctl_pmsm_hfi_ctrl_velocity_mode).
Provide a setpoint for the chosen mode (e.g., ctl_set_pmsm_hfi_ctrl_speed).
Call ctl_step_pmsm_hfi_ctrl periodically within a main control ISR.
Enable the controller and its output using the enable/disable functions.
Macro Definition Documentation
MTR_CTRL_CURRENT_MEASUREMENT_PHASES
#define MTR_CTRL_CURRENT_MEASUREMENT_PHASES ((3))
Configures the number of phase current sensors used for measurement.
3: Uses 3 phase current sensors (default).
2: Uses 2 phase current sensors.
Definition at line 66 of file pmsm_ctrl_hfi.h.
MTR_CTRL_FEEDFORWARD_STRATEGY
#define MTR_CTRL_FEEDFORWARD_STRATEGY (1)
Selects the feedforward strategy for the controller.
1: Decoupled mode. Feedforward terms are calculated automatically. This is only active when the velocity controller is enabled (default).
0: User mode. Feedforward values must be specified manually by the user.
Definition at line 88 of file pmsm_ctrl_hfi.h.
MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES
#define MTR_CTRL_VOLTAGE_MEASUREMENT_PHASES ((3))
Configures the number of phase voltage sensors used for measurement.
3: Uses 3 phase voltage sensors (default).
2: Uses 2 phase voltage sensors.
0: Disables voltage measurement.
Definition at line 77 of file pmsm_ctrl_hfi.h.
Function Documentation
ctl_attach_pmsm_hfi_output()
void ctl_attach_pmsm_hfi_output (pmsm_hfi_controller_t * ctrl, tri_pwm_ift * pwm_out)
Attaches the controller to a three-phase PWM output interface.
Parameters
[out] ctrl Pointer to the controller structure.
[in] pwm_out Pointer to the PWM interface to attach.
Definition at line 105 of file ctl_mc_pmsm_ctrl_hfi.c.
References pmsm_hfi_controller_t::pwm_out.
ctl_clear_pmsm_hfi_ctrl()
GMP_STATIC_INLINE void ctl_clear_pmsm_hfi_ctrl (pmsm_hfi_controller_t * ctrl)
Resets all internal states and integrators of the PID controllers.
This function should be called before enabling the controller to prevent unexpected behavior from stale data.
Parameters
[out] ctrl Pointer to the controller structure to clear.
Definition at line 206 of file pmsm_ctrl_hfi.h.
References ctl_clear_discrete_pid(), ctl_clear_pid(), ctl_clear_tracking_continuous_pid(), ctl_clear_tracking_pid(), pmsm_hfi_controller_t::current_ctrl, phase_d, phase_q, and pmsm_hfi_controller_t::spd_ctrl.
ctl_disable_pmsm_hfi_ctrl()
GMP_STATIC_INLINE void ctl_disable_pmsm_hfi_ctrl (pmsm_hfi_controller_t * ctrl)
Disables the entire PMSM controller.
Definition at line 377 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_controller.
ctl_disable_pmsm_hfi_ctrl_output()
GMP_STATIC_INLINE void ctl_disable_pmsm_hfi_ctrl_output (pmsm_hfi_controller_t * ctrl)
Disables PWM signal output.
Definition at line 389 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_output.
ctl_enable_pmsm_hfi_ctrl()
GMP_STATIC_INLINE void ctl_enable_pmsm_hfi_ctrl (pmsm_hfi_controller_t * ctrl)
Enables the entire PMSM controller.
Definition at line 371 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_controller.
ctl_enable_pmsm_hfi_ctrl_output()
GMP_STATIC_INLINE void ctl_enable_pmsm_hfi_ctrl_output (pmsm_hfi_controller_t * ctrl)
Enables PWM signal output.
Definition at line 383 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_output.
ctl_init_pmsm_hfi_controller()
void ctl_init_pmsm_hfi_controller (pmsm_hfi_controller_t * ctrl, pmsm_hfi_controller_init_t * init)
Initializes the PMSM HFI Controller.
Parameters
[out] ctrl Pointer to the controller structure to initialize.
[in] init Pointer to the structure containing initialization parameters.
Definition at line 10 of file ctl_mc_pmsm_ctrl_hfi.c.
References ctl_disable_pmsm_hfi_ctrl(), ctl_init_discrete_pid(), ctl_init_pid_Tmode(), ctl_init_tracking_continuous_pid(), ctl_init_tracking_pid(), ctl_pmsm_hfi_ctrl_valphabeta_mode(), ctl_set_discrete_pid_limit(), ctl_set_pid_limit(), ctl_vector2_clear(), ctl_vector3_clear(), pmsm_hfi_controller_t::current_ctrl, pmsm_hfi_controller_t::iab0, pmsm_hfi_controller_t::idq0, pmsm_hfi_controller_t::idq_ff, pmsm_hfi_controller_t::idq_set, init(), phase_d, phase_q, pmsm_hfi_controller_t::pos_set, pmsm_hfi_controller_t::revolution_set, pmsm_hfi_controller_t::spd_ctrl, pmsm_hfi_controller_t::speed_set, pmsm_hfi_controller_t::uab0, pmsm_hfi_controller_t::udq0, pmsm_hfi_controller_t::vab0_set, pmsm_hfi_controller_t::vdq_ff, and pmsm_hfi_controller_t::vdq_set.
ctl_pmsm_hfi_ctrl_current_mode()
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_current_mode (pmsm_hfi_controller_t * ctrl)
Sets the controller to Idq (current) mode.
Activates the current control loop. The user provides d-q current setpoints. The velocity loop is bypassed.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 470 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, and pmsm_hfi_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_hfi_ctrl_position_mode()
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_position_mode (pmsm_hfi_controller_t * ctrl)
Sets the controller to position mode.
Activates all control loops: position, velocity, and current.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 530 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, and pmsm_hfi_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_hfi_ctrl_valphabeta_mode()
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_valphabeta_mode (pmsm_hfi_controller_t * ctrl)
Sets the controller to V_alpha_beta mode.
In this mode, the controller bypasses all control loops and directly applies the user-specified alpha-beta voltages to the SVPWM stage.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 404 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, and pmsm_hfi_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_hfi_ctrl_velocity_mode()
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_velocity_mode (pmsm_hfi_controller_t * ctrl)
Sets the controller to velocity mode.
Activates the cascaded velocity and current control loops.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 502 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, and pmsm_hfi_controller_t::flag_enable_velocity_ctrl.
ctl_pmsm_hfi_ctrl_voltage_mode()
GMP_STATIC_INLINE void ctl_pmsm_hfi_ctrl_voltage_mode (pmsm_hfi_controller_t * ctrl)
Sets the controller to Vdq (voltage) mode.
In this mode, the user provides d-q voltage setpoints which are fed to the inverse Park transform. Current and velocity loops are bypassed.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 437 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, and pmsm_hfi_controller_t::flag_enable_velocity_ctrl.
ctl_set_pmsm_hfi_ctrl_idq_ff()
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_idq_ff (pmsm_hfi_controller_t * ctrl, ctrl_gt id, ctrl_gt iq)
Sets the d-q current feedforward (or reference) values.
In Idq mode, these values are the primary setpoints. In velocity mode, they act as feedforward terms.
Parameters
[out] ctrl Pointer to the controller structure.
[in] id The target d-axis current.
[in] iq The target q-axis current.
Definition at line 487 of file pmsm_ctrl_hfi.h.
References vector2_gt::dat, pmsm_hfi_controller_t::idq_ff, phase_d, and phase_q.
ctl_set_pmsm_hfi_ctrl_position()
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_position (pmsm_hfi_controller_t * ctrl, int32_t revolution, ctrl_gt pos)
Sets the target position for the position controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] revolution The target number of full revolutions.
[in] pos The fractional target position within the revolution (0.0 to 1.0).
Definition at line 545 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::pos_set, and pmsm_hfi_controller_t::revolution_set.
ctl_set_pmsm_hfi_ctrl_speed()
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_speed (pmsm_hfi_controller_t * ctrl, ctrl_gt spd)
Sets the target speed for the velocity controller.
Parameters
[out] ctrl Pointer to the controller structure.
[in] spd The target speed in per-unit format.
Definition at line 516 of file pmsm_ctrl_hfi.h.
References pmsm_hfi_controller_t::speed_set.
ctl_set_pmsm_hfi_ctrl_valphabeta()
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_valphabeta (pmsm_hfi_controller_t * ctrl, ctrl_gt valpha, ctrl_gt vbeta)
Sets the target alpha and beta voltage components.
This function is only effective in V_alpha_beta mode.
Parameters
[out] ctrl Pointer to the controller structure.
[in] valpha The target alpha-axis voltage.
[in] vbeta The target beta-axis voltage.
Definition at line 420 of file pmsm_ctrl_hfi.h.
References vector3_gt::dat, phase_0, phase_A, phase_B, and pmsm_hfi_controller_t::vab0_set.
ctl_set_pmsm_hfi_ctrl_vdq_ff()
GMP_STATIC_INLINE void ctl_set_pmsm_hfi_ctrl_vdq_ff (pmsm_hfi_controller_t * ctrl, ctrl_gt vd, ctrl_gt vq)
Sets the d-q voltage feedforward (or reference) values.
In Vdq mode, these values are the primary setpoints. In other modes, they act as feedforward terms.
Parameters
[out] ctrl Pointer to the controller structure.
[in] vd The target d-axis voltage.
[in] vq The target q-axis voltage.
Definition at line 454 of file pmsm_ctrl_hfi.h.
References vector2_gt::dat, phase_d, phase_q, and pmsm_hfi_controller_t::vdq_ff.
ctl_step_pmsm_hfi_ctrl()
GMP_STATIC_INLINE void ctl_step_pmsm_hfi_ctrl (pmsm_hfi_controller_t * ctrl)
Executes one step of the PMSM FOC HFI control loop.
This function should be called at a fixed frequency, typically within a timer-based ISR. It performs Clarke and Park transforms, executes the cascaded control loops (current, velocity, position), and calculates the required PWM duty cycles via SVPWM.
Parameters
[out] ctrl Pointer to the controller structure.
Definition at line 227 of file pmsm_ctrl_hfi.h.
References ctl_clear_pmsm_hfi_ctrl(), ctl_ct_clarke(), ctl_ct_clarke_2ph(), ctl_ct_ipark(), ctl_ct_park(), ctl_ct_svpwm_calc(), ctl_get_mtr_elec_theta(), ctl_get_mtr_velocity(), ctl_mul, ctl_set_phasor_via_angle(), ctl_set_pid_limit(), ctl_sqrt, ctl_step_discrete_pid(), ctl_step_pid_ser(), ctl_step_tracking_continuous_pid(), ctl_step_tracking_pid(), ctl_vector3_clear(), pmsm_hfi_controller_t::current_ctrl, vector2_gt::dat, vector3_gt::dat, pmsm_hfi_controller_t::flag_enable_controller, pmsm_hfi_controller_t::flag_enable_current_ctrl, pmsm_hfi_controller_t::flag_enable_modulation, pmsm_hfi_controller_t::flag_enable_output, pmsm_hfi_controller_t::flag_enable_position_ctrl, pmsm_hfi_controller_t::flag_enable_velocity_ctrl, float2ctrl, pmsm_hfi_controller_t::iab0, mtr_ift::iabc, pmsm_hfi_controller_t::idq0, pmsm_hfi_controller_t::idq_ff, pmsm_hfi_controller_t::idq_set, pmsm_hfi_controller_t::isr_tick, pmsm_hfi_controller_t::mtr_interface, phase_0, phase_A, phase_B, phase_C, phase_d, phase_q, pmsm_hfi_controller_t::pwm_out, pmsm_hfi_controller_t::spd_ctrl, pmsm_hfi_controller_t::speed_set, pmsm_hfi_controller_t::uab0, mtr_ift::uabc, pmsm_hfi_controller_t::udq0, pmsm_hfi_controller_t::vab0_set, tri_pwm_ift::value, pmsm_hfi_controller_t::vdq_ff, and pmsm_hfi_controller_t::vdq_set.