GMP - CTL: 4x4 Matrix Math
4x4 Matrix Math
Control Math Library » Linear Algebra
A collection of types and functions for 4x4 matrix arithmetic.
Data Structures
struct ctl_matrix4_t
Data structure for representing a 4x4 matrix. The elements are stored in row-major order.
Functions
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_get (const ctl_matrix4_t *mat, int row, int col)
Gets an element from the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix4_set (ctl_matrix4_t *mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
GMP_STATIC_INLINE void ctl_matrix4_clear (ctl_matrix4_t *matrix)
Clears a 4x4 matrix, setting all its elements to zero.
GMP_STATIC_INLINE void ctl_matrix4_set_identity (ctl_matrix4_t *matrix)
Sets a 4x4 matrix to the identity matrix.
GMP_STATIC_INLINE void ctl_matrix4_copy (ctl_matrix4_t *dup, const ctl_matrix4_t *src)
Copies the contents of one 4x4 matrix to another.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_add (ctl_matrix4_t a, ctl_matrix4_t b)
Adds two 4x4 matrices.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_sub (ctl_matrix4_t a, ctl_matrix4_t b)
Subtracts one 4x4 matrix from another.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_scale (ctl_matrix4_t mat, ctrl_gt scalar)
Multiplies a 4x4 matrix by a scalar value.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_mul (ctl_matrix4_t a, ctl_matrix4_t b)
Multiplies two 4x4 matrices.
GMP_STATIC_INLINE ctl_vector4_t ctl_matrix4_mul_vector (ctl_matrix4_t mat, ctl_vector4_t vec)
Multiplies a 4x4 matrix by a 4D column vector.
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_det (ctl_matrix4_t mat)
Calculates the determinant of a 4x4 matrix.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_inv (ctl_matrix4_t mat)
Calculates the inverse of a 4x4 matrix.
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_trans (ctl_matrix4_t mat)
Transposes a 4x4 matrix.
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_trace (ctl_matrix4_t mat)
Calculates the trace of a 4x4 matrix (sum of diagonal elements).
Detailed Description
A collection of types and functions for 4x4 matrix arithmetic.
Function Documentation
ctl_matrix4_add()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_add (ctl_matrix4_t a, ctl_matrix4_t b)
Adds two 4x4 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a + b).
Definition at line 116 of file matrix4.h.
References ctl_matrix4_t::dat, and i.
ctl_matrix4_clear()
GMP_STATIC_INLINE void ctl_matrix4_clear (ctl_matrix4_t * matrix)
Clears a 4x4 matrix, setting all its elements to zero.
Parameters
[out] matrix Pointer to the matrix to be cleared.
Definition at line 74 of file matrix4.h.
References i, and matrix.
ctl_matrix4_copy()
GMP_STATIC_INLINE void ctl_matrix4_copy (ctl_matrix4_t * dup, const ctl_matrix4_t * src)
Copies the contents of one 4x4 matrix to another.
Parameters
[out] dup Pointer to the destination matrix.
[in] src Pointer to the source matrix.
Definition at line 100 of file matrix4.h.
References ctl_matrix4_t::dat, and i.
ctl_matrix4_det()
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_det (ctl_matrix4_t mat)
Calculates the determinant of a 4x4 matrix.
Parameters
mat The input matrix.
Returns
The determinant of the matrix.
Definition at line 218 of file matrix4.h.
References ctl_matrix4_t::dat.
ctl_matrix4_get()
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_get (const ctl_matrix4_t * mat, int row, int col)
Gets an element from the matrix at the specified row and column.
Parameters
[in] mat Pointer to the matrix.
[in] row The row index (0-3).
[in] col The column index (0-3).
Returns
The value of the element at (row, col).
Definition at line 53 of file matrix4.h.
References ctl_matrix4_t::dat.
ctl_matrix4_inv()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_inv (ctl_matrix4_t mat)
Calculates the inverse of a 4x4 matrix.
Parameters
mat The matrix to be inverted.
Returns
The inverse of the matrix. Returns a zero matrix if the determinant is zero.
Definition at line 241 of file matrix4.h.
References ctl_matrix4_clear(), ctl_matrix4_det(), and ctl_matrix4_t::dat.
ctl_matrix4_mul()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_mul (ctl_matrix4_t a, ctl_matrix4_t b)
Multiplies two 4x4 matrices.
Parameters
a The first matrix.
b The second matrix.
Returns
The resulting matrix (a * b).
Definition at line 170 of file matrix4.h.
References ctl_matrix4_get(), ctl_matrix4_set(), and i.
ctl_matrix4_mul_vector()
GMP_STATIC_INLINE ctl_vector4_t ctl_matrix4_mul_vector (ctl_matrix4_t mat, ctl_vector4_t vec)
Multiplies a 4x4 matrix by a 4D column vector.
Parameters
mat The matrix.
vec The vector.
Returns
The resulting transformed vector (mat * vec).
Definition at line 196 of file matrix4.h.
References ctl_matrix4_get(), and i.
ctl_matrix4_scale()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_scale (ctl_matrix4_t mat, ctrl_gt scalar)
Multiplies a 4x4 matrix by a scalar value.
Parameters
mat The matrix to be scaled.
scalar The scalar value.
Returns
The resulting scaled matrix.
Definition at line 152 of file matrix4.h.
References ctl_matrix4_t::dat, and i.
ctl_matrix4_set()
GMP_STATIC_INLINE void ctl_matrix4_set (ctl_matrix4_t * mat, int row, int col, ctrl_gt value)
Sets an element in the matrix at the specified row and column.
Parameters
[out] mat Pointer to the matrix.
[in] row The row index (0-3).
[in] col The column index (0-3).
[in] value The new value for the element.
Definition at line 65 of file matrix4.h.
References ctl_matrix4_t::dat, and value().
ctl_matrix4_set_identity()
GMP_STATIC_INLINE void ctl_matrix4_set_identity (ctl_matrix4_t * matrix)
Sets a 4x4 matrix to the identity matrix.
Parameters
[out] matrix Pointer to the matrix to be set.
Definition at line 86 of file matrix4.h.
References ctl_matrix4_clear(), and matrix.
ctl_matrix4_sub()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_sub (ctl_matrix4_t a, ctl_matrix4_t b)
Subtracts one 4x4 matrix from another.
Parameters
a The minuend matrix.
b The subtrahend matrix.
Returns
The resulting matrix (a - b).
Definition at line 134 of file matrix4.h.
References ctl_matrix4_t::dat, and i.
ctl_matrix4_trace()
GMP_STATIC_INLINE ctrl_gt ctl_matrix4_trace (ctl_matrix4_t mat)
Calculates the trace of a 4x4 matrix (sum of diagonal elements).
Parameters
mat The input matrix.
Returns
The trace of the matrix.
Definition at line 347 of file matrix4.h.
References ctl_matrix4_t::dat.
ctl_matrix4_trans()
GMP_STATIC_INLINE ctl_matrix4_t ctl_matrix4_trans (ctl_matrix4_t mat)
Transposes a 4x4 matrix.
Parameters
mat The matrix to be transposed.
Returns
The transposed matrix.
Definition at line 327 of file matrix4.h.
References ctl_matrix4_get(), ctl_matrix4_set(), and i.