GMP - CTL: Basic Velocity and Position Controller
Basic Velocity and Position Controller
A simple velocity and position loop.
Data Structures
struct ctl_vel_pos_controller_t
Typedefs
typedef ctl_vel_pos_controller_t vel_pos_ctrl_t
Functions
GMP_STATIC_INLINE void ctl_clear_vel_pos_ctrl (ctl_vel_pos_controller_t *ctrl)
Initializes the velocity and position controller structure to safe defaults.
void ctl_init_vel_pos_ctrl (ctl_vel_pos_controller_t *ctrl, parameter_gt vel_kp, parameter_gt pos_kp, parameter_gt vel_ki, parameter_gt pos_ki, parameter_gt speed_limit, parameter_gt speed_slope_limit, parameter_gt cur_limit, uint32_t vel_division, uint32_t pos_division, parameter_gt fs)
Initializes the velocity and position controller structure to safe defaults.
GMP_STATIC_INLINE void ctl_step_vel_pos_ctrl (ctl_vel_pos_controller_t *ctrl)
Executes one step of the velocity and position control loop.
GMP_STATIC_INLINE ctrl_gt ctl_get_vel_pos_cmd (ctl_vel_pos_controller_t *ctrl)
GMP_STATIC_INLINE void ctl_enable_velocity_ctrl (ctl_vel_pos_controller_t *ctrl)
GMP_STATIC_INLINE void ctl_enable_position_ctrl (ctl_vel_pos_controller_t *ctrl)
GMP_STATIC_INLINE void ctl_set_target_velocity (ctl_vel_pos_controller_t *ctrl, ctrl_gt spd)
GMP_STATIC_INLINE void ctl_attach_vel_pos_ctrl (ctl_vel_pos_controller_t *ctrl, rotation_ift *pos_if, velocity_ift *spd_if)
Detailed Description
A simple velocity and position loop.
This module provides a simple and effective position controller. It takes a target position (composed of full revolutions and an angle) and a feedback position, calculates the error, and multiplies it by a proportional gain (Kp) to produce a speed reference. The output is saturated to a defined limit. This controller forms the outermost loop in a cascaded position control system.
Typedef Documentation
vel_pos_ctrl_t
typedef ctl_vel_pos_controller_t vel_pos_ctrl_t
Definition at line 72 of file vel_pos_loop.h.
Function Documentation
ctl_attach_vel_pos_ctrl()
GMP_STATIC_INLINE void ctl_attach_vel_pos_ctrl (ctl_vel_pos_controller_t * ctrl, rotation_ift * pos_if, velocity_ift * spd_if)
Definition at line 171 of file vel_pos_loop.h.
References ctl_vel_pos_controller_t::pos_if, and ctl_vel_pos_controller_t::spd_if.
ctl_clear_vel_pos_ctrl()
GMP_STATIC_INLINE void ctl_clear_vel_pos_ctrl (ctl_vel_pos_controller_t * ctrl)
Initializes the velocity and position controller structure to safe defaults.
Parameters
[out] ctrl Pointer to the velocity and position controller structure. ctl_vel_pos_controller_t
Definition at line 82 of file vel_pos_loop.h.
References ctl_clear_divider(), ctl_clear_pid(), ctl_vel_pos_controller_t::cur_output, ctl_vel_pos_controller_t::div_position, ctl_vel_pos_controller_t::div_velocity, ctl_vel_pos_controller_t::pos_ctrl, and ctl_vel_pos_controller_t::vel_ctrl.
ctl_enable_position_ctrl()
GMP_STATIC_INLINE void ctl_enable_position_ctrl (ctl_vel_pos_controller_t * ctrl)
Definition at line 160 of file vel_pos_loop.h.
References ctl_vel_pos_controller_t::flag_enable_position_ctrl, and ctl_vel_pos_controller_t::flag_enable_velocity_ctrl.
ctl_enable_velocity_ctrl()
GMP_STATIC_INLINE void ctl_enable_velocity_ctrl (ctl_vel_pos_controller_t * ctrl)
Definition at line 154 of file vel_pos_loop.h.
References ctl_vel_pos_controller_t::flag_enable_position_ctrl, and ctl_vel_pos_controller_t::flag_enable_velocity_ctrl.
ctl_get_vel_pos_cmd()
GMP_STATIC_INLINE ctrl_gt ctl_get_vel_pos_cmd (ctl_vel_pos_controller_t * ctrl)
Definition at line 149 of file vel_pos_loop.h.
References ctl_vel_pos_controller_t::cur_output.
ctl_init_vel_pos_ctrl()
void ctl_init_vel_pos_ctrl (ctl_vel_pos_controller_t * ctrl, parameter_gt vel_kp, parameter_gt pos_kp, parameter_gt vel_ki, parameter_gt pos_ki, parameter_gt speed_limit, parameter_gt speed_slope_limit, parameter_gt cur_limit, uint32_t vel_division, uint32_t pos_division, parameter_gt fs)
Initializes the velocity and position controller structure to safe defaults.
Parameters
[out] ctrl Pointer to the velocity and position controller structure.
[in] vel_kp Proportional gain.
[in] pos_kp Proportional gain.
[in] vel_ki Integral gain.
[in] pos_ki Integral gain.
[in] speed_limit Maximum output speed reference.
[in] speed_slope_limit Maximum slope limit in pu/s.
[in] cur_limit Maximum output current limit.
[in] vel_division The frequency division factor for the velocity controller execution.
[in] pos_division The frequency division factor for the position controller execution.
[in] fs Controller execution frequency (Hz).
Definition at line 183 of file ctl_mc_motion.c.
References ctl_clear_vel_pos_ctrl(), ctl_init_divider(), ctl_init_pid(), ctl_init_slope_limiter(), ctl_set_pid_limit(), ctl_vel_pos_controller_t::cur_limit, ctl_vel_pos_controller_t::cur_output, ctl_vel_pos_controller_t::div_position, ctl_vel_pos_controller_t::div_velocity, ctl_vel_pos_controller_t::flag_enable_position_ctrl, ctl_vel_pos_controller_t::flag_enable_velocity_ctrl, fs, ctl_vel_pos_controller_t::pos_ctrl, ctl_vel_pos_controller_t::speed_limit, ctl_vel_pos_controller_t::target_angle, ctl_vel_pos_controller_t::target_revs, ctl_vel_pos_controller_t::target_velocity, ctl_vel_pos_controller_t::vel_ctrl, and ctl_vel_pos_controller_t::vel_traj.
ctl_set_target_velocity()
GMP_STATIC_INLINE void ctl_set_target_velocity (ctl_vel_pos_controller_t * ctrl, ctrl_gt spd)
Definition at line 166 of file vel_pos_loop.h.
References ctl_vel_pos_controller_t::target_velocity.
ctl_step_vel_pos_ctrl()
GMP_STATIC_INLINE void ctl_step_vel_pos_ctrl (ctl_vel_pos_controller_t * ctrl)
Executes one step of the velocity and position control loop.
Parameters
[out] ctrl Pointer to the velocity and position controller structure.
Definition at line 115 of file vel_pos_loop.h.
References ctl_step_divider(), ctl_step_pid_par(), ctl_vel_pos_controller_t::cur_output, ctl_vel_pos_controller_t::div_position, ctl_vel_pos_controller_t::div_velocity, ctl_vel_pos_controller_t::flag_enable_position_ctrl, ctl_vel_pos_controller_t::flag_enable_velocity_ctrl, ctl_vel_pos_controller_t::pos_ctrl, ctl_vel_pos_controller_t::pos_if, rotation_ift::position, rotation_ift::revolutions, ctl_vel_pos_controller_t::spd_if, velocity_ift::speed, ctl_vel_pos_controller_t::target_angle, ctl_vel_pos_controller_t::target_revs, ctl_vel_pos_controller_t::target_velocity, and ctl_vel_pos_controller_t::vel_ctrl.