GMP - CTL: Boost Controller API
Boost Controller API
Digital Power Control Library » Digital Power Topology Presets
Functions and data structures for Boost converter control.
Data Structures
struct boost_ctrl_t
Core data structure for the Boost controller.
Macros
#define CTL_BOOST_CTRL_UIN_MIN ((float2ctrl(0.01)))
Defines the minimum input voltage to avoid division by zero during duty cycle calculation.
#define UPPER_BRIDGE (0)
#define LOWER_BRIDGE (1)
#define CTL_BOOST_CTRL_POSITION UPPER_BRIDGE
Defines which switch in the half-bridge is being controlled by the PWM signal.
Functions
void ctl_init_boost_ctrl (boost_ctrl_t *boost, parameter_gt v_kp, parameter_gt v_Ti, parameter_gt v_Td, parameter_gt i_kp, parameter_gt i_Ti, parameter_gt i_Td, parameter_gt vo_min, parameter_gt vo_max, parameter_gt fc, parameter_gt fs)
Initializes the Boost controller with specified PID and filter parameters.
void ctl_attach_boost_ctrl_input (boost_ctrl_t *boost, adc_ift *uc, adc_ift *il, adc_ift *uin)
Attaches the controller to the physical ADC input interfaces.
GMP_STATIC_INLINE ctrl_gt ctl_step_boost_ctrl (boost_ctrl_t *boost)
Executes one step of the Boost control logic.
GMP_STATIC_INLINE ctrl_gt ctl_get_boost_ctrl_modulation (boost_ctrl_t *boost)
Gets the last calculated PWM duty cycle.
GMP_STATIC_INLINE void ctl_clear_boost_ctrl (boost_ctrl_t *boost)
Clears the internal states and integral terms of the PID controllers.
GMP_STATIC_INLINE void ctl_boost_ctrl_voltage_mode (boost_ctrl_t *boost)
Switches the controller to closed-loop Voltage mode.
GMP_STATIC_INLINE void ctl_set_boost_ctrl_voltage (boost_ctrl_t *boost, ctrl_gt v_set)
Sets the target output voltage in Voltage mode.
GMP_STATIC_INLINE void ctl_boost_ctrl_current_mode (boost_ctrl_t *boost)
Switches the controller to closed-loop Current mode.
GMP_STATIC_INLINE void ctl_set_boost_ctrl_current (boost_ctrl_t *boost, ctrl_gt i_set)
Sets the target inductor current in Current mode.
GMP_STATIC_INLINE void ctl_boost_ctrl_openloop_mode (boost_ctrl_t *boost)
Switches the controller to open-loop Voltage mode.
GMP_STATIC_INLINE void ctl_set_boost_ctrl_voltage_openloop (boost_ctrl_t *boost, ctrl_gt v_set)
Sets the target intermediate voltage command in open-loop mode.
GMP_STATIC_INLINE void ctl_disable_boost_ctrl (boost_ctrl_t *boost)
Disables the entire Boost controller system.
GMP_STATIC_INLINE void ctl_enable_boost_ctrl (boost_ctrl_t *boost)
Enables the entire Boost controller system.
Detailed Description
Functions and data structures for Boost converter control.
Contains all configurations, data structures, and functions for the Boost controller.
Boost Controller Usage Guide
This module implements a standard dual-loop (voltage and current) controller for a DC-DC Boost converter.
1. Initialization
Call ctl_init_boost_ctrl to configure the PID parameters for both the outer voltage loop and the inner current loop.
Call ctl_attach_boost_ctrl_input to link the controller to the ADC interfaces for sensing input/output voltages and inductor current.
2. Mode Selection
The controller supports several operating modes:
Voltage Mode: Closed-loop voltage control. Use ctl_boost_ctrl_voltage_mode to enter and ctl_set_boost_ctrl_voltage to set the target output voltage.
Current Mode: Closed-loop current control (voltage loop is bypassed). Use ctl_boost_ctrl_current_mode to enter and ctl_set_boost_ctrl_current to set the target inductor current.
Open Loop Mode: Directly control the output voltage command. Use ctl_boost_ctrl_openloop_mode to enter and ctl_set_boost_ctrl_voltage_openloop to set the voltage command.
3. Execution
Call ctl_step_boost_ctrl periodically in a timer ISR to execute one step of the control logic.
Call ctl_get_boost_ctrl_modulation to retrieve the calculated PWM duty cycle and apply it to your PWM peripheral.
4. Control
Use ctl_enable_boost_ctrl and ctl_disable_boost_ctrl for master control.
Use ctl_clear_boost_ctrl to reset PID integrators before enabling.
Macro Definition Documentation
CTL_BOOST_CTRL_POSITION
#define CTL_BOOST_CTRL_POSITION UPPER_BRIDGE
Defines which switch in the half-bridge is being controlled by the PWM signal.
UPPER_BRIDGE: The duty cycle D controls the upper switch. Transfer function M = 1/D.
LOWER_BRIDGE: The duty cycle D controls the lower switch. Transfer function M = 1/(1-D).
Definition at line 87 of file boost.h.
CTL_BOOST_CTRL_UIN_MIN
#define CTL_BOOST_CTRL_UIN_MIN ((float2ctrl(0.01)))
Defines the minimum input voltage to avoid division by zero during duty cycle calculation.
Definition at line 74 of file boost.h.
LOWER_BRIDGE
#define LOWER_BRIDGE (1)
Identifier for controlling the lower-side switch.
Definition at line 78 of file boost.h.
UPPER_BRIDGE
#define UPPER_BRIDGE (0)
Identifier for controlling the upper-side switch.
Definition at line 77 of file boost.h.
Function Documentation
ctl_attach_boost_ctrl_input()
void ctl_attach_boost_ctrl_input (boost_ctrl_t * boost, adc_ift * uc, adc_ift * il, adc_ift * uin)
Attaches the controller to the physical ADC input interfaces.
Parameters
[out] boost Pointer to the Boost controller instance.
[in] uc Pointer to the ADC interface for the output capacitor voltage.
[in] il Pointer to the ADC interface for the inductor current.
[in] uin Pointer to the ADC interface for the input voltage.
Definition at line 83 of file ctl_dp_basic.c.
References boost_ctrl_t::adc_il, boost_ctrl_t::adc_ui, and boost_ctrl_t::adc_uo.
ctl_boost_ctrl_current_mode()
GMP_STATIC_INLINE void ctl_boost_ctrl_current_mode (boost_ctrl_t * boost)
Switches the controller to closed-loop Current mode.
The outer voltage loop is disabled, and the inner current loop directly tracks the user-specified current setpoint.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 283 of file boost.h.
References boost_ctrl_t::flag_enable_current_ctrl, and boost_ctrl_t::flag_enable_voltage_ctrl.
ctl_boost_ctrl_openloop_mode()
GMP_STATIC_INLINE void ctl_boost_ctrl_openloop_mode (boost_ctrl_t * boost)
Switches the controller to open-loop Voltage mode.
Both PID loops are disabled. The output is determined directly by the value set with ctl_set_boost_ctrl_voltage_openloop.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 305 of file boost.h.
References boost_ctrl_t::flag_enable_current_ctrl, and boost_ctrl_t::flag_enable_voltage_ctrl.
ctl_boost_ctrl_voltage_mode()
GMP_STATIC_INLINE void ctl_boost_ctrl_voltage_mode (boost_ctrl_t * boost)
Switches the controller to closed-loop Voltage mode.
Both the inner current loop and outer voltage loop are enabled.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 261 of file boost.h.
References boost_ctrl_t::flag_enable_current_ctrl, and boost_ctrl_t::flag_enable_voltage_ctrl.
ctl_clear_boost_ctrl()
GMP_STATIC_INLINE void ctl_clear_boost_ctrl (boost_ctrl_t * boost)
Clears the internal states and integral terms of the PID controllers.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 247 of file boost.h.
References ctl_clear_pid(), boost_ctrl_t::current_ff, boost_ctrl_t::current_pid, boost_ctrl_t::voltage_ff, and boost_ctrl_t::voltage_pid.
ctl_disable_boost_ctrl()
GMP_STATIC_INLINE void ctl_disable_boost_ctrl (boost_ctrl_t * boost)
Disables the entire Boost controller system.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 326 of file boost.h.
References boost_ctrl_t::flag_enable_system.
ctl_enable_boost_ctrl()
GMP_STATIC_INLINE void ctl_enable_boost_ctrl (boost_ctrl_t * boost)
Enables the entire Boost controller system.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Definition at line 335 of file boost.h.
References boost_ctrl_t::current_ff, boost_ctrl_t::flag_enable_system, boost_ctrl_t::lpf_il, and ctl_low_pass_filter_t::out.
ctl_get_boost_ctrl_modulation()
GMP_STATIC_INLINE ctrl_gt ctl_get_boost_ctrl_modulation (boost_ctrl_t * boost)
Gets the last calculated PWM duty cycle.
Parameters
[in] boost Pointer to the Boost controller instance.
Returns
The last calculated PWM duty cycle (per-unit).
Definition at line 238 of file boost.h.
References boost_ctrl_t::pwm_out_pu.
ctl_init_boost_ctrl()
void ctl_init_boost_ctrl (boost_ctrl_t * boost, parameter_gt v_kp, parameter_gt v_Ti, parameter_gt v_Td, parameter_gt i_kp, parameter_gt i_Ti, parameter_gt i_Td, parameter_gt vo_min, parameter_gt vo_max, parameter_gt fc, parameter_gt fs)
Initializes the Boost controller with specified PID and filter parameters.
Parameters
[out] boost Pointer to the Boost controller instance to be initialized.
[in] v_kp Proportional gain for the voltage PID controller.
[in] v_Ti Integral time constant for the voltage PID controller.
[in] v_Td Derivative time constant for the voltage PID controller.
[in] i_kp Proportional gain for the current PID controller.
[in] i_Ti Integral time constant for the current PID controller.
[in] i_Td Derivative time constant for the current PID controller.
[in] vo_min Minimum output voltage for saturation, to prevent division by zero.
[in] vo_max Maximum output voltage for saturation.
[in] fc Cutoff frequency for the low-pass filters on sensor inputs.
[in] fs Controller execution frequency in Hz.
Definition at line 57 of file ctl_dp_basic.c.
References ctl_clear_boost_ctrl(), ctl_disable_boost_ctrl(), ctl_init_lp_filter(), ctl_init_pid_Tmode(), ctl_init_saturation(), boost_ctrl_t::current_pid, boost_ctrl_t::flag_enable_system, fs, boost_ctrl_t::lpf_il, boost_ctrl_t::lpf_ui, boost_ctrl_t::lpf_uo, boost_ctrl_t::modulation_saturation, and boost_ctrl_t::voltage_pid.
ctl_set_boost_ctrl_current()
GMP_STATIC_INLINE void ctl_set_boost_ctrl_current (boost_ctrl_t * boost, ctrl_gt i_set)
Sets the target inductor current in Current mode.
Parameters
[in,out] boost Pointer to the Boost controller instance.
[in] i_set The target inductor current.
Definition at line 295 of file boost.h.
References boost_ctrl_t::current_set.
ctl_set_boost_ctrl_voltage()
GMP_STATIC_INLINE void ctl_set_boost_ctrl_voltage (boost_ctrl_t * boost, ctrl_gt v_set)
Sets the target output voltage in Voltage mode.
Parameters
[in,out] boost Pointer to the Boost controller instance.
[in] v_set The target output voltage.
Definition at line 273 of file boost.h.
References boost_ctrl_t::voltage_set.
ctl_set_boost_ctrl_voltage_openloop()
GMP_STATIC_INLINE void ctl_set_boost_ctrl_voltage_openloop (boost_ctrl_t * boost, ctrl_gt v_set)
Sets the target intermediate voltage command in open-loop mode.
Parameters
[in,out] boost Pointer to the Boost controller instance.
[in] v_set The desired intermediate voltage command.
Definition at line 317 of file boost.h.
References boost_ctrl_t::voltage_out.
ctl_step_boost_ctrl()
GMP_STATIC_INLINE ctrl_gt ctl_step_boost_ctrl (boost_ctrl_t * boost)
Executes one step of the Boost control logic.
This function performs the cascaded voltage and current control loop calculations. It should be called periodically at the frequency specified during initialization.
Parameters
[in,out] boost Pointer to the Boost controller instance.
Returns
The calculated PWM duty cycle (per-unit).
Definition at line 178 of file boost.h.
References boost_ctrl_t::adc_il, boost_ctrl_t::adc_ui, boost_ctrl_t::adc_uo, ctl_div, ctl_step_lowpass_filter(), ctl_step_pid_ser(), ctl_step_saturation(), boost_ctrl_t::current_ff, boost_ctrl_t::current_pid, boost_ctrl_t::current_set, boost_ctrl_t::flag_enable_current_ctrl, boost_ctrl_t::flag_enable_system, boost_ctrl_t::flag_enable_voltage_ctrl, float2ctrl, boost_ctrl_t::lpf_il, boost_ctrl_t::lpf_ui, boost_ctrl_t::lpf_uo, boost_ctrl_t::modulation_saturation, ctl_low_pass_filter_t::out, boost_ctrl_t::pwm_out_pu, boost_ctrl_t::vo_sat, boost_ctrl_t::voltage_ff, boost_ctrl_t::voltage_out, boost_ctrl_t::voltage_pid, and boost_ctrl_t::voltage_set.