GMP - CTL: Lead-Lag Compensators
Lead-Lag Compensators
Control Template Library Intrinsic » Discrete Components
A library of discrete IIR filters for control loop compensation.
Data Structures
struct ctrl_lead_t
Data structure for a Lead compensator.
struct ctrl_lag_t
Data structure for a Lag compensator.
Functions
void ctl_init_lead (ctrl_lead_t *obj, parameter_gt K_D, parameter_gt tau_D, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
void ctl_init_lead_form2 (ctrl_lead_t *obj, parameter_gt alpha, parameter_gt T, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
void ctl_init_lead_form3 (ctrl_lead_t *obj, parameter_gt angle, parameter_gt fc, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
GMP_STATIC_INLINE void ctl_clear_lead (ctrl_lead_t *obj)
Clears the internal states of the lead compensator.
GMP_STATIC_INLINE ctrl_gt ctl_step_lead (ctrl_lead_t *obj, ctrl_gt input)
Executes one step of the lead compensator.
void ctl_init_lag (ctrl_lag_t *obj, parameter_gt tau_L, parameter_gt tau_P, parameter_gt fs)
Initializes a lag compensator from its continuous-time parameters.
GMP_STATIC_INLINE void ctl_clear_lag (ctrl_lag_t *obj)
Clears the internal states of the lag compensator.
GMP_STATIC_INLINE ctrl_gt ctl_step_lag (ctrl_lag_t *obj, ctrl_gt input)
Executes one step of the lag compensator.
Detailed Description
A library of discrete IIR filters for control loop compensation.
This file contains implementations for discrete-time lead and lag compensators. These are first-order IIR filters used to improve the stability (phase margin) and steady-state performance of a control loop. The continuous-time transfer functions are discretized using the Bilinear Transform:
\[ s = \frac{2}{T} \frac{1-z^{-1}}{1+z^{-1}} \]
The continuous-time transfer function is:
\[ H(s) = \frac{(\tau_D + K_D)s + 1}{\tau_D s + 1} \]
After discretization, it becomes a 1-Pole-1-Zero (1P1Z) filter.
Function Documentation
ctl_clear_lag()
GMP_STATIC_INLINE void ctl_clear_lag (ctrl_lag_t * obj)
Clears the internal states of the lag compensator.
Parameters
[out] obj Pointer to the lag compensator instance.
Definition at line 148 of file lead_lag.h.
References ctrl_lag_t::input_1, and ctrl_lag_t::output_1.
ctl_clear_lead()
GMP_STATIC_INLINE void ctl_clear_lead (ctrl_lead_t * obj)
Clears the internal states of the lead compensator.
Parameters
[out] obj Pointer to the lead compensator instance.
Definition at line 90 of file lead_lag.h.
References ctrl_lead_t::input_1, and ctrl_lead_t::output_1.
ctl_init_lag()
void ctl_init_lag (ctrl_lag_t * obj, parameter_gt tau_L, parameter_gt tau_P, parameter_gt fs)
Initializes a lag compensator from its continuous-time parameters.
Parameters
[out] obj Pointer to the lag compensator instance.
[in] tau_L Time constant of the lag network's zero.
[in] tau_P Time constant of the lag network's pole.
[in] fs Sampling frequency (Hz).
Definition at line 1567 of file ctl_component_discrete.c.
References ctrl_lag_t::a1, ctrl_lag_t::b0, ctrl_lag_t::b1, ctl_clear_lag(), float2ctrl, and fs.
ctl_init_lead()
void ctl_init_lead (ctrl_lead_t * obj, parameter_gt K_D, parameter_gt tau_D, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
Parameters
[out] obj Pointer to the lead compensator instance.
[in] K_D Proportional gain of the derivative term.
[in] tau_D Time constant of the derivative term's pole.
[in] fs Sampling frequency (Hz).
Definition at line 1470 of file ctl_component_discrete.c.
References ctrl_lead_t::a1, ctrl_lead_t::b0, ctrl_lead_t::b1, ctl_clear_lead(), float2ctrl, and fs.
ctl_init_lead_form2()
void ctl_init_lead_form2 (ctrl_lead_t * obj, parameter_gt alpha, parameter_gt T, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
Parameters
[out] obj Pointer to the lead compensator instance.
[in] alpha compensator coefficient.
[in] T Time constant of the derivative term's pole.
[in] fs Sampling frequency (Hz).
Definition at line 1505 of file ctl_component_discrete.c.
References ctrl_lead_t::a1, alpha, ctrl_lead_t::b0, ctrl_lead_t::b1, ctl_clear_lead(), float2ctrl, and fs.
ctl_init_lead_form3()
void ctl_init_lead_form3 (ctrl_lead_t * obj, parameter_gt angle, parameter_gt fc, parameter_gt fs)
Initializes a lead compensator from its continuous-time parameters.
Parameters
[out] obj Pointer to the lead compensator instance.
[in] angle compensator angle at the frequency, rad.
[in] fc compensator frequency Hz.
[in] fs Sampling frequency (Hz).
Definition at line 1540 of file ctl_component_discrete.c.
References alpha, ctl_init_lead_form2(), CTL_PARAM_CONST_PI, and fs.
ctl_step_lag()
GMP_STATIC_INLINE ctrl_gt ctl_step_lag (ctrl_lag_t * obj, ctrl_gt input)
Executes one step of the lag compensator.
Implements the difference equation: u(n) = a1*u(n-1) + b0*e(n) + b1*e(n-1).
Parameters
[in,out] obj Pointer to the lag compensator instance.
[in] input The current input to the compensator, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 161 of file lead_lag.h.
References ctrl_lag_t::a1, ctrl_lag_t::b0, ctrl_lag_t::b1, ctl_mul, input, ctrl_lag_t::input_1, output, and ctrl_lag_t::output_1.
ctl_step_lead()
GMP_STATIC_INLINE ctrl_gt ctl_step_lead (ctrl_lead_t * obj, ctrl_gt input)
Executes one step of the lead compensator.
Implements the difference equation: u(n) = a1*u(n-1) + b0*e(n) + b1*e(n-1).
Parameters
[in,out] obj Pointer to the lead compensator instance.
[in] input The current input to the compensator, e(n).
Returns
ctrl_gt The calculated output, u(n).
Definition at line 103 of file lead_lag.h.
References ctrl_lead_t::a1, ctrl_lead_t::b0, ctrl_lead_t::b1, ctl_mul, input, ctrl_lead_t::input_1, output, and ctrl_lead_t::output_1.