GMP - CTL: suite/mcs_pmsm_nt/implement/simulate/xplt.peripheral.cpp File Reference
xplt.peripheral.cpp File Reference
#include <gmp_core.hpp>
#include "user_main.h"
#include <xplt.peripheral.h>
#include <ctrl_rt_trace.h>
#include <conio.h>
Macros
#define ISR_LOCAL_BUF_SIZE 1024
Enumerations
enum trace_rt_nodes { TRT_TEST = 0 , TRT_NODE_NUMBER }
Functions
void setup_peripheral (void)
void at_device_flush_rx_buffer ()
void send_monitor_data (void)
Variables
tri_ptr_adc_channel_t uuvw
adc_gt uuvw_src [3]
tri_ptr_adc_channel_t iuvw
adc_gt iuvw_src [3]
ptr_adc_channel_t udc
adc_gt udc_src
ptr_adc_channel_t idc
adc_gt idc_src
trace_rt_node_t * trt_node [TRT_NODE_NUMBER]
Macro Definition Documentation
ISR_LOCAL_BUF_SIZE
#define ISR_LOCAL_BUF_SIZE 1024
Definition at line 116 of file xplt.peripheral.cpp.
Enumeration Type Documentation
trace_rt_nodes
enum trace_rt_nodes
Enumerator
TRT_TEST
TRT_NODE_NUMBER
Definition at line 46 of file xplt.peripheral.cpp.
Function Documentation
at_device_flush_rx_buffer()
void at_device_flush_rx_buffer ()
Definition at line 119 of file xplt.peripheral.cpp.
References at_dev, and ISR_LOCAL_BUF_SIZE.
send_monitor_data()
void send_monitor_data (void)
Definition at line 153 of file xplt.peripheral.cpp.
setup_peripheral()
void setup_peripheral (void)
Definition at line 58 of file xplt.peripheral.cpp.
References ctl_attach_mtr_current_ctrl_port(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_ptr_adc_channel(), ctl_init_tri_ptr_adc_channel(), CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_BASE, CTRL_DC_CURRENT_BIAS, CTRL_DC_CURRENT_SENSITIVITY, CTRL_DC_VOLTAGE_BIAS, CTRL_DC_VOLTAGE_SENSITIVITY, CTRL_INVERTER_CURRENT_BIAS, CTRL_INVERTER_CURRENT_SENSITIVITY, CTRL_INVERTER_VOLTAGE_BIAS, CTRL_INVERTER_VOLTAGE_SENSITIVITY, CTRL_VOLTAGE_BASE, idc, idc_src, iuvw, iuvw_src, mtr_ctrl, pos_enc, rg, spd_enc, trt_node, TRT_TEST, udc, udc_src, uuvw, and uuvw_src.
Variable Documentation
idc
ptr_adc_channel_t idc
Definition at line 42 of file xplt.peripheral.cpp.
idc_src
adc_gt idc_src
Definition at line 43 of file xplt.peripheral.cpp.
iuvw
tri_ptr_adc_channel_t iuvw
Definition at line 36 of file xplt.peripheral.cpp.
iuvw_src
adc_gt iuvw_src[3]
Definition at line 37 of file xplt.peripheral.cpp.
trt_node
trace_rt_node_t* trt_node[TRT_NODE_NUMBER]
Definition at line 52 of file xplt.peripheral.cpp.
udc
ptr_adc_channel_t udc
Definition at line 40 of file xplt.peripheral.cpp.
udc_src
adc_gt udc_src
Definition at line 41 of file xplt.peripheral.cpp.
uuvw
tri_ptr_adc_channel_t uuvw
Definition at line 32 of file xplt.peripheral.cpp.
uuvw_src
adc_gt uuvw_src[3]
Definition at line 33 of file xplt.peripheral.cpp.