GMP - CTL: component/motor_control/basic/mtr_protection.h File Reference
mtr_protection.h File Reference
#include <ctl/component/intrinsic/basic/divider.h>
Data Structures
union mtr_protect_error_t
Error Code Union Allows accessing individual flags or the whole word efficiently.
struct ctl_mtr_protect_t
Motor Protection Module Structure.
Macros
#define MTR_PROT_NONE (0x00000000)
#define MTR_PROT_OVER_VOLT (0x00000001)
#define MTR_PROT_UNDER_VOLT (0x00000002)
#define MTR_PROT_OVER_CURR (0x00000004)
#define MTR_PROT_DEVIATION (0x00000008)
#define MTR_PROT_MTR_OVER_TEMP (0x00000010)
#define MTR_PROT_INV_OVER_TEMP (0x00000020)
Functions
GMP_STATIC_INLINE void ctl_clear_mtr_protect (ctl_mtr_protect_t *prot)
void ctl_init_mtr_protect (ctl_mtr_protect_t *prot, parameter_gt fs)
void ctl_attach_mtr_protect_port (ctl_mtr_protect_t *prot, ctrl_gt *u_dc, ctl_vector2_t *i_meas, ctl_vector2_t *i_ref, adc_ift *mtr_temp, adc_ift *inv_temp)
GMP_STATIC_INLINE fast_gt ctl_mtr_protect_debounce (fast_gt condition, uint16_t *counter, uint16_t limit)
Counter-based Debounce Logic.
GMP_STATIC_INLINE fast_gt ctl_is_greater (ctrl_gt val, ctrl_gt limit)
GMP_STATIC_INLINE fast_gt ctl_is_less (ctrl_gt val, ctrl_gt limit)
GMP_STATIC_INLINE fast_gt ctl_is_greater_ot (adc_gt temp, adc_gt limit_temp)
GMP_STATIC_INLINE fast_gt ctl_is_less_ot (adc_gt temp, adc_gt limit_temp)
GMP_STATIC_INLINE void ctl_set_mtr_protect_mask (ctl_mtr_protect_t *prot, uint32_t mask)
GMP_STATIC_INLINE uint32_t ctl_get_mtr_protect_mask (ctl_mtr_protect_t *prot)
GMP_STATIC_INLINE fast_gt ctl_step_mtr_protect_fast (ctl_mtr_protect_t *prot)
ISR Level Protection Step.
fast_gt ctl_dispatch_mtr_protect_slow (ctl_mtr_protect_t *prot)
Main Loop Protection Dispatch. This calling frequency of this function should be less than 1kHz.
Macro Definition Documentation
MTR_PROT_DEVIATION
#define MTR_PROT_DEVIATION (0x00000008)
Definition at line 34 of file mtr_protection.h.
MTR_PROT_INV_OVER_TEMP
#define MTR_PROT_INV_OVER_TEMP (0x00000020)
Definition at line 36 of file mtr_protection.h.
MTR_PROT_MTR_OVER_TEMP
#define MTR_PROT_MTR_OVER_TEMP (0x00000010)
Definition at line 35 of file mtr_protection.h.
MTR_PROT_NONE
#define MTR_PROT_NONE (0x00000000)
Definition at line 30 of file mtr_protection.h.
MTR_PROT_OVER_CURR
#define MTR_PROT_OVER_CURR (0x00000004)
Definition at line 33 of file mtr_protection.h.
MTR_PROT_OVER_VOLT
#define MTR_PROT_OVER_VOLT (0x00000001)
Definition at line 31 of file mtr_protection.h.
MTR_PROT_UNDER_VOLT
#define MTR_PROT_UNDER_VOLT (0x00000002)
Definition at line 32 of file mtr_protection.h.
Function Documentation
ctl_attach_mtr_protect_port()
void ctl_attach_mtr_protect_port (ctl_mtr_protect_t * prot, ctrl_gt * u_dc, ctl_vector2_t * i_meas, ctl_vector2_t * i_ref, adc_ift * mtr_temp, adc_ift * inv_temp)
Definition at line 327 of file ctl_mc_basic.c.
References ctl_mtr_protect_t::ptr_idq, ctl_mtr_protect_t::ptr_inv_temp, ctl_mtr_protect_t::ptr_mtr_temp, ctl_mtr_protect_t::ptr_ref, and ctl_mtr_protect_t::ptr_udc.
ctl_clear_mtr_protect()
GMP_STATIC_INLINE void ctl_clear_mtr_protect (ctl_mtr_protect_t * prot)
Definition at line 104 of file mtr_protection.h.
References mtr_protect_error_t::all, ctl_mtr_protect_t::cnt_dev, ctl_mtr_protect_t::cnt_inv_ot, ctl_mtr_protect_t::cnt_mtr_ot, ctl_mtr_protect_t::cnt_oc, ctl_mtr_protect_t::cnt_ov, ctl_mtr_protect_t::cnt_uv, ctl_mtr_protect_t::error_code, and MTR_PROT_NONE.
ctl_dispatch_mtr_protect_slow()
fast_gt ctl_dispatch_mtr_protect_slow (ctl_mtr_protect_t * prot)
Main Loop Protection Dispatch. This calling frequency of this function should be less than 1kHz.
Returns
1 if fault active, 0 if safe
Definition at line 342 of file ctl_mc_basic.c.
References mtr_protect_error_t::all, mtr_protect_error_t::bit, ctl_mtr_protect_t::cnt_inv_ot, ctl_mtr_protect_t::cnt_mtr_ot, ctl_mtr_protect_t::cnt_uv, ctl_is_greater_ot(), ctl_is_less(), ctl_mtr_protect_debounce(), ctl_mtr_protect_t::error_code, ctl_mtr_protect_t::error_mask, mtr_protect_error_t::inv_over_temp, ctl_mtr_protect_t::limit_cnt_inv_ot, ctl_mtr_protect_t::limit_cnt_mtr_ot, ctl_mtr_protect_t::limit_cnt_uv, ctl_mtr_protect_t::limit_inv_ot, ctl_mtr_protect_t::limit_mtr_ot, ctl_mtr_protect_t::limit_uv_pu, mtr_protect_error_t::mtr_over_temp, MTR_PROT_NONE, ctl_mtr_protect_t::ptr_inv_temp, ctl_mtr_protect_t::ptr_mtr_temp, ctl_mtr_protect_t::ptr_udc, and mtr_protect_error_t::under_voltage.
ctl_get_mtr_protect_mask()
GMP_STATIC_INLINE uint32_t ctl_get_mtr_protect_mask (ctl_mtr_protect_t * prot)
Definition at line 172 of file mtr_protection.h.
References mtr_protect_error_t::all, and ctl_mtr_protect_t::error_mask.
ctl_init_mtr_protect()
void ctl_init_mtr_protect (ctl_mtr_protect_t * prot, parameter_gt fs)
Definition at line 296 of file ctl_mc_basic.c.
References mtr_protect_error_t::all, ctl_clear_mtr_protect(), ctl_mtr_protect_t::error_mask, float2ctrl, fs, ctl_mtr_protect_t::limit_cnt_dev, ctl_mtr_protect_t::limit_cnt_inv_ot, ctl_mtr_protect_t::limit_cnt_mtr_ot, ctl_mtr_protect_t::limit_cnt_oc, ctl_mtr_protect_t::limit_cnt_ov, ctl_mtr_protect_t::limit_cnt_uv, ctl_mtr_protect_t::limit_dev_sq_pu, ctl_mtr_protect_t::limit_inv_ot, ctl_mtr_protect_t::limit_mtr_ot, ctl_mtr_protect_t::limit_oc_sq_pu, ctl_mtr_protect_t::limit_ov_pu, and ctl_mtr_protect_t::limit_uv_pu.
ctl_is_greater()
GMP_STATIC_INLINE fast_gt ctl_is_greater (ctrl_gt val, ctrl_gt limit)
Definition at line 148 of file mtr_protection.h.
ctl_is_greater_ot()
GMP_STATIC_INLINE fast_gt ctl_is_greater_ot (adc_gt temp, adc_gt limit_temp)
Definition at line 157 of file mtr_protection.h.
ctl_is_less()
GMP_STATIC_INLINE fast_gt ctl_is_less (ctrl_gt val, ctrl_gt limit)
Definition at line 152 of file mtr_protection.h.
ctl_is_less_ot()
GMP_STATIC_INLINE fast_gt ctl_is_less_ot (adc_gt temp, adc_gt limit_temp)
Definition at line 162 of file mtr_protection.h.
ctl_mtr_protect_debounce()
GMP_STATIC_INLINE fast_gt ctl_mtr_protect_debounce (fast_gt condition, uint16_t * counter, uint16_t limit)
Counter-based Debounce Logic.
Returns
1 if confirmed fault, 0 otherwise
Definition at line 129 of file mtr_protection.h.
References counter.
ctl_set_mtr_protect_mask()
GMP_STATIC_INLINE void ctl_set_mtr_protect_mask (ctl_mtr_protect_t * prot, uint32_t mask)
Definition at line 167 of file mtr_protection.h.
References mtr_protect_error_t::all, and ctl_mtr_protect_t::error_mask.
ctl_step_mtr_protect_fast()
GMP_STATIC_INLINE fast_gt ctl_step_mtr_protect_fast (ctl_mtr_protect_t * prot)
ISR Level Protection Step.
Returns
1 if fault active, 0 if safe
Definition at line 181 of file mtr_protection.h.
References mtr_protect_error_t::all, mtr_protect_error_t::bit, ctl_mtr_protect_t::cnt_dev, ctl_mtr_protect_t::cnt_oc, ctl_mtr_protect_t::cnt_ov, ctl_is_greater(), ctl_mtr_protect_debounce(), ctl_mul, mtr_protect_error_t::deviation, ctl_mtr_protect_t::error_code, ctl_mtr_protect_t::error_mask, ctl_mtr_protect_t::limit_cnt_dev, ctl_mtr_protect_t::limit_cnt_oc, ctl_mtr_protect_t::limit_cnt_ov, ctl_mtr_protect_t::limit_dev_sq_pu, ctl_mtr_protect_t::limit_oc_sq_pu, ctl_mtr_protect_t::limit_ov_pu, MTR_PROT_NONE, mtr_protect_error_t::over_current, mtr_protect_error_t::over_voltage, ctl_mtr_protect_t::ptr_idq, ctl_mtr_protect_t::ptr_ref, and ctl_mtr_protect_t::ptr_udc.