GMP - CTL: suite/mcs_pmsm_smo/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
Variables
pmsm_smo_controller_t pmsm_ctrl
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_system = 0
uint16_t sgen_out = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 35 of file ctl_main.c.
References pmsm_smo_controller_init_t::acc_limit_max, pmsm_smo_controller_init_t::acc_limit_min, CONTROLLER_FREQUENCY, ctl_enable_output(), ctl_enable_pmsm_smo(), ctl_enable_pmsm_smo_ctrl(), ctl_init_pmsm_smo_bare_controller(), CTL_PARAM_CONST_PI, ctl_pmsm_smo_ctrl_current_mode(), ctl_pmsm_smo_ctrl_voltage_mode(), ctl_set_pmsm_smo_ctrl_idq_ff(), ctl_set_pmsm_smo_ctrl_vdq_ff(), pmsm_smo_controller_init_t::current_limit_max, pmsm_smo_controller_init_t::current_limit_min, pmsm_smo_controller_init_t::current_pid_gain, pmsm_smo_controller_init_t::current_Td, pmsm_smo_controller_init_t::current_Ti, flag_enable_system, float2ctrl, pmsm_smo_controller_init_t::fs, pmsm_smo_controller_init_t::i_base, pmsm_smo_controller_init_t::Ld, pmsm_smo_controller_init_t::Lq, MOTOR_PARAM_LS, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RS, MTR_CTRL_CURRENT_BASE, MTR_CTRL_CURRENT_LOOP_BW, MTR_CTRL_VOLTAGE_BASE, pmsm_ctrl, pmsm_smo_controller_init_t::pole_pairs, pmsm_smo_controller_init_t::ramp_target_freq, pmsm_smo_controller_init_t::ramp_target_freq_slope, pmsm_smo_controller_init_t::Rs, pmsm_smo_controller_init_t::smo_fc_e, pmsm_smo_controller_init_t::smo_fc_omega, pmsm_smo_controller_init_t::smo_k_slide, pmsm_smo_controller_init_t::smo_kp, pmsm_smo_controller_init_t::smo_Td, pmsm_smo_controller_init_t::smo_Ti, SPD_CONTROLLER_PWM_DIVISION, pmsm_smo_controller_init_t::spd_ctrl_div, pmsm_smo_controller_init_t::spd_pid_gain, pmsm_smo_controller_init_t::spd_Td, pmsm_smo_controller_init_t::spd_Ti, pmsm_smo_controller_init_t::speed_base_rpm, pmsm_smo_controller_init_t::u_base, pmsm_smo_controller_init_t::voltage_limit_max, and pmsm_smo_controller_init_t::voltage_limit_min.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 144 of file ctl_main.c.
References adc_calibrator, ctl_is_adc_calibrator_cmpt(), ctl_set_pmsm_smo_ctrl_speed(), ctl_switch_pmsm_smo_ctrl_using_smo(), flag_enable_adc_calibrator, float2ctrl, index_adc_calibrator, MTR_ADC_IDC, and pmsm_ctrl.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 27 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
Definition at line 28 of file ctl_main.c.
flag_enable_system
volatile fast_gt flag_enable_system = 0
Definition at line 32 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator = 0
Definition at line 29 of file ctl_main.c.
pmsm_ctrl
pmsm_smo_controller_t pmsm_ctrl
Definition at line 24 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 142 of file ctl_main.c.