GMP - CTL: suite/mcs_pmsm_nt/implement/common/ctl_main.h File Reference
ctl_main.h File Reference
#include <xplt.peripheral.h>
#include <ctl/component/interface/adc_channel.h>
#include <ctl/component/interface/pwm_channel.h>
#include <ctl/component/interface/pwm_modulator.h>
#include <ctl/component/motor_control/basic/encoder.h>
#include <ctl/component/motor_control/basic/mtr_protection.h>
#include <ctl/component/motor_control/basic/vf_generator.h>
#include <ctl/component/motor_control/current_loop/motor_current_ctrl.h>
#include <ctl/component/motor_control/motion/vel_pos_loop.h>
#include <ctl/component/motor_control/observer/pmsm.smo.h>
#include <ctl/framework/cia402_state_machine.h>
Functions
void clear_all_controllers ()
GMP_STATIC_INLINE void ctl_dispatch (void)
Variables
volatile fast_gt flag_system_running
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator
volatile fast_gt index_adc_calibrator
cia402_sm_t cia402_sm
ctl_mtr_protect_t protection
spwm_modulator_t spwm
mtr_current_ctrl_t mtr_ctrl
vel_pos_ctrl_t motion_ctrl
ctl_slope_f_pu_controller rg
pos_autoturn_encoder_t pos_enc
spd_calculator_t spd_enc
Function Documentation
clear_all_controllers()
void clear_all_controllers ()
Definition at line 266 of file ctl_main.c.
References ctl_clear_mtr_current_ctrl(), ctl_clear_npc_modulator(), ctl_clear_slope_f_pu(), ctl_clear_spwm_modulator(), ctl_clear_vel_pos_ctrl(), motion_ctrl, mtr_ctrl, rg, and spwm.
ctl_dispatch()
GMP_STATIC_INLINE void ctl_dispatch (void)
Definition at line 83 of file ctl_main.h.
References adc_calibrator, cia402_fault_request(), cia402_sm, CTL_CTRL_CONST_1_OVER_SQRT3, ctl_get_vel_pos_cmd(), ctl_mul, ctl_set_mtr_current_ctrl_ref(), ctl_step_adc_calibrator(), ctl_step_current_controller(), ctl_step_mtr_protect_fast(), ctl_step_npc_modulator(), ctl_step_pmsm_smo(), ctl_step_slope_f_pu(), ctl_step_spd_calc(), ctl_step_svpwm_modulator(), ctl_step_vel_pos_ctrl(), flag_enable_adc_calibrator, idc, index_adc_calibrator, iuvw, motion_ctrl, mtr_ctrl, phase_0, phase_alpha, phase_beta, protection, rg, spd_enc, spwm, udc, and uuvw.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator extern
Definition at line 47 of file ctl_main.c.
cia402_sm
cia402_sm_t cia402_sm extern
Definition at line 29 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator extern
Definition at line 48 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running extern
Definition at line 35 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator extern
Definition at line 49 of file ctl_main.c.
motion_ctrl
vel_pos_ctrl_t motion_ctrl extern
Definition at line 42 of file ctl_main.c.
mtr_ctrl
mtr_current_ctrl_t mtr_ctrl extern
Definition at line 40 of file ctl_main.c.
pos_enc
pos_autoturn_encoder_t pos_enc extern
Definition at line 31 of file xplt.peripheral.c.
protection
ctl_mtr_protect_t protection extern
Definition at line 30 of file ctl_main.c.
rg
ctl_slope_f_pu_controller rg extern
Definition at line 40 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc extern
Definition at line 32 of file ctl_main.c.
spwm
spwm_modulator_t spwm extern
Definition at line 36 of file ctl_main.c.