GMP - CTL: suite/pgs_1ph_dcac_dual_stage_rectifier/implement/simulate/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Enumerations
enum sinv_adc_index_items {
SINV_ADC_ID_IL = 0 , SINV_ADC_ID_IDC = 1 , SINV_ADC_ID_VDC = 2 , SINV_ADC_ID_IC = 3 ,
SINV_ADC_ID_VG = 4 , SINV_ADC_ID_IG = 5 , SINV_ADC_ID_BUCK_IL = 6 , SINV_ADC_ID_BUCK_VIN = 7 ,
SINV_ADC_ID_BUCK_VOUT = 8 , SINV_ADC_SENSOR_NUMBER = 9
}
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Variables
ptr_adc_channel_t sinv_adc [SINV_ADC_SENSOR_NUMBER]
pwm_channel_t sinv_pwm_out [3]
sinv_ctrl_t sinv_ctrl
buck_ctrl_t buck_ctrl
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
Enumeration Type Documentation
sinv_adc_index_items
enum sinv_adc_index_items
Enumerator
SINV_ADC_ID_IL
SINV_ADC_ID_IDC
SINV_ADC_ID_VDC
SINV_ADC_ID_IC
SINV_ADC_ID_VG
SINV_ADC_ID_IG
SINV_ADC_ID_BUCK_IL
SINV_ADC_ID_BUCK_VIN
SINV_ADC_ID_BUCK_VOUT
SINV_ADC_SENSOR_NUMBER
Definition at line 31 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 210 of file xplt.ctl_interface.h.
References flag_system_running.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 197 of file xplt.ctl_interface.h.
References buck_ctrl, ctl_enable_buck_ctrl(), ctl_enable_sinv_ctrl(), flag_system_running, and sinv_ctrl.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 56 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), i, sinv_adc, and SINV_ADC_SENSOR_NUMBER.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 65 of file xplt.ctl_interface.h.
References buck_ctrl, ctl_step_pwm_channel(), PHASE_L, PHASE_N, phasor_sin, simulink_tx_buffer, sinv_adc, SINV_ADC_ID_BUCK_IL, SINV_ADC_ID_BUCK_VIN, SINV_ADC_ID_BUCK_VOUT, SINV_ADC_ID_IC, SINV_ADC_ID_IDC, SINV_ADC_ID_IG, SINV_ADC_ID_IL, SINV_ADC_ID_VDC, SINV_ADC_ID_VG, sinv_ctrl, and sinv_pwm_out.
Variable Documentation
buck_ctrl
buck_ctrl_t buck_ctrl extern
Definition at line 38 of file ctl_main.c.
sinv_adc
ptr_adc_channel_t sinv_adc[SINV_ADC_SENSOR_NUMBER] extern
Definition at line 23 of file xplt.peripheral.c.
sinv_ctrl
sinv_ctrl_t sinv_ctrl extern
Definition at line 28 of file ctl_main.c.
sinv_pwm_out
pwm_channel_t sinv_pwm_out[3] extern
Definition at line 25 of file xplt.peripheral.c.