GMP - CTL: suite/dps_buck/implement/stm32f407/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
Enumerations
enum adc_result_nameplate_t { ADC_RESULT_UIN = 0 , ADC_RESULT_UOUT = 1 , ADC_RESULT_IL = 2 }
Functions
void setup_peripheral (void)
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
Variables
ptr_adc_channel_t uc
ptr_adc_channel_t uin
ptr_adc_channel_t il
pwm_channel_t pwm_out
uint32_t adc_results [8]
Enumeration Type Documentation
adc_result_nameplate_t
enum adc_result_nameplate_t
Enumerator
ADC_RESULT_UIN
ADC_RESULT_UOUT
ADC_RESULT_IL
Definition at line 66 of file xplt.peripheral.c.
Function Documentation
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * hadc)
Definition at line 236 of file xplt.peripheral.c.
References gmp_base_ctl_step().
setup_peripheral()
void setup_peripheral (void)
Definition at line 79 of file xplt.peripheral.c.
References ADC_RESULT_IL, ADC_RESULT_UIN, ADC_RESULT_UOUT, adc_results, boost_ctrl, CONTROLLER_PWM_CMP_MAX, ctl_attach_boost_ctrl_input(), ctl_init_ptr_adc_channel(), ctl_init_pwm_channel(), hadc1, htim1, htim3, il, pwm_out, uc, and uin.
Variable Documentation
adc_results
uint32_t adc_results[8]
Definition at line 63 of file xplt.peripheral.c.
il
ptr_adc_channel_t il
Definition at line 55 of file xplt.peripheral.c.
pwm_out
pwm_channel_t pwm_out
Definition at line 60 of file xplt.peripheral.c.
uc
ptr_adc_channel_t uc
Definition at line 53 of file xplt.peripheral.c.
uin
ptr_adc_channel_t uin
Definition at line 54 of file xplt.peripheral.c.