GMP - CTL: suite/mcs_pmsm/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
fast_gt ctl_adc_calibrate (void)
fast_gt ctl_motor_identify (void)
fast_gt ctl_ready_mainloop (void)
Variables
pmsm_controller_t pmsm_ctrl
spd_calculator_t spd_enc
ctl_slope_f_controller rg
volatile fast_gt flag_system_enable = 0
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
volatile fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_motor_identify = 0
uint32_t counter
uint16_t sgen_out = 0
fast_gt firsttime_flag = 0
fast_gt startup_flag = 0
fast_gt started_flag = 0
time_gt tick_bias = 0
Function Documentation
ctl_adc_calibrate()
fast_gt ctl_adc_calibrate (void)
Definition at line 236 of file ctl_main.c.
References adc_calibrator, ctl_clear_adc_calibrator(), ctl_clear_pmsm_ctrl(), ctl_div, ctl_enable_adc_calibrator(), ctl_enable_pmsm_ctrl_output(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, MTR_ADC_IDC, and pmsm_ctrl.
ctl_init()
void ctl_init (void)
Definition at line 61 of file ctl_main.c.
References pmsm_controller_init_t::acc_limit_max, pmsm_controller_init_t::acc_limit_min, adc_calibrator, ctl_attach_mtr_position(), ctl_attach_mtr_velocity(), ctl_disable_output(), ctl_disable_pmsm_ctrl_output(), ctl_enable_adc_calibrator(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_init_const_f_controller(), ctl_init_const_slope_f_controller(), ctl_init_pmsm_controller(), ctl_init_spd_calculator(), CTL_PARAM_CONST_2PI, ctl_pmsm_ctrl_current_mode(), ctl_pmsm_ctrl_velocity_mode(), ctl_pmsm_ctrl_voltage_mode(), ctl_set_autoturn_pos_encoder_offset(), ctl_set_pmsm_ctrl_idq_ff(), ctl_set_pmsm_ctrl_speed(), ctl_set_pmsm_ctrl_vdq_ff(), CTRL_FS, pmsm_controller_init_t::current_limit_max, pmsm_controller_init_t::current_limit_min, pmsm_controller_init_t::current_pid_gain, pmsm_controller_init_t::current_Td, pmsm_controller_init_t::current_Ti, flag_enable_adc_calibrator, float2ctrl, pmsm_controller_init_t::fs, MOTOR_PARAM_LS, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RS, MTR_CTRL_CURRENT_BASE, MTR_CTRL_CURRENT_LOOP_BW, MTR_CTRL_SPEED_LOOP_BW, MTR_CTRL_VOLTAGE_BASE, MTR_ENCODER_LINES, MTR_ENCODER_OFFSET, pmsm_ctrl, pos_enc, rg, SPD_CONTROLLER_PWM_DIVISION, pmsm_controller_init_t::spd_ctrl_div, spd_enc, pmsm_controller_init_t::spd_pid_gain, pmsm_controller_init_t::spd_Td, pmsm_controller_init_t::spd_Ti, pmsm_controller_init_t::voltage_limit_max, and pmsm_controller_init_t::voltage_limit_min.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 188 of file ctl_main.c.
References ctl_clear_pmsm_ctrl(), ctl_clear_slope_f(), ctl_disable_output(), ctl_enable_output(), ctl_enable_pmsm_ctrl(), ctl_ready_mainloop(), CTRL_STARTUP_DELAY, firsttime_flag, flag_system_enable, pmsm_ctrl, rg, started_flag, startup_flag, and tick_bias.
ctl_motor_identify()
fast_gt ctl_motor_identify (void)
Definition at line 294 of file ctl_main.c.
ctl_ready_mainloop()
fast_gt ctl_ready_mainloop (void)
Definition at line 303 of file ctl_main.c.
References ctl_adc_calibrate(), ctl_motor_identify(), and SPECIFY_ENABLE_ADC_CALIBRATE.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 51 of file ctl_main.c.
counter
uint32_t counter
Definition at line 58 of file ctl_main.c.
firsttime_flag
fast_gt firsttime_flag = 0
Definition at line 183 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
Definition at line 52 of file ctl_main.c.
flag_enable_motor_identify
volatile fast_gt flag_enable_motor_identify = 0
Definition at line 56 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable = 0
Definition at line 47 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator = 0
Definition at line 53 of file ctl_main.c.
pmsm_ctrl
pmsm_controller_t pmsm_ctrl
Definition at line 24 of file ctl_main.c.
rg
ctl_slope_f_controller rg
Definition at line 40 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 181 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc
Definition at line 32 of file ctl_main.c.
started_flag
fast_gt started_flag = 0
Definition at line 185 of file ctl_main.c.
startup_flag
fast_gt startup_flag = 0
Definition at line 184 of file ctl_main.c.
tick_bias
time_gt tick_bias = 0
Definition at line 186 of file ctl_main.c.