GMP - CTL: suite/mcs_pmsm_smo/implement/simulate/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 96 of file xplt.ctl_interface.h.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 89 of file xplt.ctl_interface.h.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 35 of file xplt.ctl_interface.h.
References ctl_set_pmsm_smo_ctrl_vdq_ff(), ctl_step_autoturn_pos_encoder(), ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), float2ctrl, iabc, idc, pmsm_ctrl, pos_enc, simulink_rx_buffer, uabc, and udc.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 56 of file xplt.ctl_interface.h.
References ctl_calc_pwm_tri_channel(), MOTOR_PARAM_MAX_SPEED, phase_A, phase_B, phase_C, phase_d, phase_q, pmsm_ctrl, pwm_out, and simulink_tx_buffer.