GMP - CTL: suite/mcs_acm/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
Variables
acm_sensored_bare_controller_t acm_ctrl
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_system = 0
uint16_t sgen_out = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 55 of file ctl_main.c.
References acm_sensored_bare_controller_init_t::acc_limit_max, acm_sensored_bare_controller_init_t::acc_limit_min, acm_ctrl, adc_calibrator, acm_sensored_bare_controller_init_t::base_freq, acm_sensored_bare_controller_init_t::base_spd, CONTROLLER_FREQUENCY, ctl_acm_sensored_ctrl_current_mode(), ctl_acm_sensored_ctrl_voltage_mode(), ctl_attach_acm_sensored_bare_rotor_postion(), ctl_disable_acm_sensored_ctrl_output(), ctl_enable_acm_sensored_ctrl(), ctl_enable_adc_calibrator(), ctl_enable_output(), ctl_init_acm_sensored_bare_controller(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_set_acm_sensored_ctrl_idq_ff(), ctl_set_acm_sensored_ctrl_speed(), ctl_set_acm_sensored_ctrl_vdq_ff(), ctl_set_autoturn_pos_encoder_offset(), acm_sensored_bare_controller_init_t::current_limit_max, acm_sensored_bare_controller_init_t::current_limit_min, acm_sensored_bare_controller_init_t::current_pid_gain, acm_sensored_bare_controller_init_t::current_Td, acm_sensored_bare_controller_init_t::current_Ti, flag_enable_adc_calibrator, flag_enable_system, float2ctrl, acm_sensored_bare_controller_init_t::fs, index_adc_calibrator, acm_sensored_bare_controller_init_t::Lr, MOTOR_PARAM_L1R, MOTOR_PARAM_LM, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RATED_FREQUENCY, MOTOR_PARAM_RR, MTR_CTRL_SPEED_LOOP_BW, MTR_ENCODER_LINES, MTR_ENCODER_OFFSET, acm_sensored_bare_controller_init_t::pole_pairs, pos_enc, acm_sensored_bare_controller_init_t::Rr, SPD_CONTROLLER_PWM_DIVISION, acm_sensored_bare_controller_init_t::spd_ctrl_div, acm_sensored_bare_controller_init_t::spd_pid_gain, acm_sensored_bare_controller_init_t::spd_Td, acm_sensored_bare_controller_init_t::spd_Ti, acm_sensored_bare_controller_init_t::target_freq_slope, acm_sensored_bare_controller_init_t::voltage_limit_max, and acm_sensored_bare_controller_init_t::voltage_limit_min.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 202 of file ctl_main.c.
References acm_ctrl, adc_calibrator, ctl_acm_sensored_ctrl_velocity_mode(), ctl_clear_adc_calibrator(), ctl_disable_output(), ctl_div, ctl_enable_acm_sensored_ctrl_output(), ctl_enable_adc_calibrator(), ctl_enable_output(), ctl_get_adc_calibrator_result(), ctl_get_mtr_velocity(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), ctl_mul, flag_enable_adc_calibrator, float2ctrl, iabc, idc, index_adc_calibrator, and MTR_ADC_IDC.
Variable Documentation
acm_ctrl
acm_sensored_bare_controller_t acm_ctrl
Definition at line 24 of file ctl_main.c.
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 47 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
Definition at line 48 of file ctl_main.c.
flag_enable_system
volatile fast_gt flag_enable_system = 0
Definition at line 52 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator = 0
Definition at line 49 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 200 of file ctl_main.c.