GMP - CTL: suite/mcs_pmsm/implement/f280039c_iris_node/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
#define BOARD_PIN_MAPPING
#define PHASE_U_BASE IRIS_EPWM1_BASE
#define PHASE_V_BASE IRIS_EPWM2_BASE
#define PHASE_W_BASE IRIS_EPWM3_BASE
#define EQEP_Encoder_BASE IRIS_EQEP1_BASE
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Variables
adc_gt uabc_raw [3]
adc_gt iabc_raw [3]
adc_gt udc_raw
adc_gt idc_raw
pmsm_controller_t pmsm_ctrl
uint32_t output_voltage_compare
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 16 of file xplt.ctl_interface.h.
BOARD_PIN_MAPPING
#define BOARD_PIN_MAPPING
Definition at line 29 of file xplt.ctl_interface.h.
EQEP_Encoder_BASE
#define EQEP_Encoder_BASE IRIS_EQEP1_BASE
Definition at line 59 of file xplt.ctl_interface.h.
PHASE_U_BASE
#define PHASE_U_BASE IRIS_EPWM1_BASE
Definition at line 32 of file xplt.ctl_interface.h.
PHASE_V_BASE
#define PHASE_V_BASE IRIS_EPWM2_BASE
Definition at line 33 of file xplt.ctl_interface.h.
PHASE_W_BASE
#define PHASE_W_BASE IRIS_EPWM3_BASE
Definition at line 34 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 157 of file xplt.ctl_interface.h.
References GPIO_WritePin().
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 144 of file xplt.ctl_interface.h.
References GPIO_WritePin().
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 79 of file xplt.ctl_interface.h.
References ctl_step_autoturn_pos_encoder(), ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), EQEP_Encoder_BASE, iabc, iabc_raw, idc, phase_U, phase_V, phase_W, pos_enc, uabc, uabc_raw, udc, and udc_raw.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 116 of file xplt.ctl_interface.h.
References ctl_calc_pwm_tri_channel(), phase_A, phase_U, PHASE_U_BASE, phase_V, PHASE_V_BASE, phase_W, PHASE_W_BASE, pmsm_ctrl, pwm_out, and rg.
GPIO_WritePin()
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)
Variable Documentation
iabc_raw
adc_gt iabc_raw[3] extern
Definition at line 37 of file xplt.peripheral.c.
idc_raw
adc_gt idc_raw extern
Definition at line 39 of file xplt.peripheral.c.
output_voltage_compare
uint32_t output_voltage_compare extern
pmsm_ctrl
pmsm_controller_t pmsm_ctrl extern
Definition at line 24 of file ctl_main.c.
uabc_raw
adc_gt uabc_raw[3] extern
Definition at line 36 of file xplt.peripheral.c.
udc_raw
adc_gt udc_raw extern
Definition at line 38 of file xplt.peripheral.c.