GMP - CTL: suite/mcs_pmsm_mtpa/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
#include <ctl/component/motor_control/current_loop/current_distributor.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
Variables
pmsm_mtpa_bare_controller_t pmsm_mtpa_ctrl
spd_calculator_t spd_enc
ctl_slope_f_controller slope_f
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_system = 1
uint16_t sgen_out = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 57 of file ctl_main.c.
References adc_calibrator, CONTROLLER_FREQUENCY, ctl_attach_mtr_position(), ctl_attach_mtr_velocity(), ctl_disable_pmsm_mtpa_ctrl_output(), ctl_enable_adc_calibrator(), ctl_enable_output(), ctl_enable_pmsm_mtpa_ctrl(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_init_const_f_controller(), ctl_init_const_slope_f_controller(), ctl_init_pmsm_mtpa_bare_controller(), ctl_init_spd_calculator(), ctl_pmsm_mtpa_ctrl_current_mode(), ctl_pmsm_mtpa_ctrl_velocity_mode(), ctl_pmsm_mtpa_ctrl_voltage_mode(), ctl_set_autoturn_pos_encoder_offset(), ctl_set_pmsm_mtpa_ctrl_idq_ff(), ctl_set_pmsm_mtpa_ctrl_speed(), ctl_set_pmsm_mtpa_ctrl_vdq_ff(), ctl_const_f_controller::enc, flag_enable_adc_calibrator, flag_enable_system, float2ctrl, index_adc_calibrator, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MTR_CTRL_CURRENT_BASE, MTR_CTRL_SPEED_LOOP_BW, MTR_CTRL_VOLTAGE_BASE, MTR_ENCODER_LINES, MTR_ENCODER_OFFSET, pmsm_mtpa_ctrl, pos_enc, slope_f, SPD_CONTROLLER_PWM_DIVISION, and spd_enc.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 203 of file ctl_main.c.
References adc_calibrator, ctl_clear_adc_calibrator(), ctl_disable_output(), ctl_div, ctl_enable_adc_calibrator(), ctl_enable_output(), ctl_enable_pmsm_mtpa_ctrl_output(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, MTR_ADC_IDC, and pmsm_mtpa_ctrl.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 49 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
Definition at line 50 of file ctl_main.c.
flag_enable_system
volatile fast_gt flag_enable_system = 1
Definition at line 54 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator = 0
Definition at line 51 of file ctl_main.c.
pmsm_mtpa_ctrl
pmsm_mtpa_bare_controller_t pmsm_mtpa_ctrl
Definition at line 26 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 201 of file ctl_main.c.
slope_f
ctl_slope_f_controller slope_f
Definition at line 44 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc
Definition at line 34 of file ctl_main.c.