GMP - CTL: suite/pgs_1ph_dcac_dual_stage_rectifier/implement/stm32f407/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
Enumerations
enum adc_result_nameplate_t { ADC_RESULT_IL = 3 , ADC_RESULT_IG = 1 , ADC_RESULT_UC = 0 , ADC_RESULT_UDC = 2 }
Functions
void setup_peripheral (void)
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Variables
ptr_adc_channel_t sinv_il
ptr_adc_channel_t sinv_ig
ptr_adc_channel_t sinv_uc
ptr_adc_channel_t sinv_udc
qpr_ctrl_t qpr_test
pwm_channel_t sinv_pwm_out [2]
uint32_t adc_results [8]
Enumeration Type Documentation
adc_result_nameplate_t
enum adc_result_nameplate_t
Enumerator
ADC_RESULT_IL
ADC_RESULT_IG
ADC_RESULT_UC
ADC_RESULT_UDC
Definition at line 70 of file xplt.peripheral.c.
Function Documentation
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Definition at line 201 of file xplt.peripheral.c.
References gmp_base_ctl_step(), and htim1.
setup_peripheral()
void setup_peripheral (void)
Definition at line 89 of file xplt.peripheral.c.
References ADC_RESULT_IG, ADC_RESULT_IL, ADC_RESULT_UC, ADC_RESULT_UDC, adc_results, CONTROLLER_PWM_CMP_MAX, ctl_init_ptr_adc_channel(), ctl_init_pwm_channel(), hadc1, hdac, htim1, htim3, sinv_ig, sinv_il, sinv_pwm_out, sinv_uc, and sinv_udc.
Variable Documentation
adc_results
uint32_t adc_results[8]
Definition at line 67 of file xplt.peripheral.c.
qpr_test
qpr_ctrl_t qpr_test
Definition at line 59 of file xplt.peripheral.c.
sinv_ig
ptr_adc_channel_t sinv_ig
Definition at line 55 of file xplt.peripheral.c.
sinv_il
ptr_adc_channel_t sinv_il
Definition at line 54 of file xplt.peripheral.c.
sinv_pwm_out
pwm_channel_t sinv_pwm_out[2]
Definition at line 64 of file xplt.peripheral.c.
sinv_uc
ptr_adc_channel_t sinv_uc
Definition at line 56 of file xplt.peripheral.c.
sinv_udc
ptr_adc_channel_t sinv_udc
Definition at line 57 of file xplt.peripheral.c.