GMP - CTL: suite/pgs_1ph_dcac_inv/implement/simulate/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
#include <xplt.peripheral.h>
Functions
void setup_peripheral (void)
Variables
ptr_adc_channel_t sinv_adc [SINV_ADC_SENSOR_NUMBER]
pwm_channel_t sinv_pwm_out [2]
Function Documentation
setup_peripheral()
void setup_peripheral (void)
Definition at line 32 of file xplt.peripheral.c.
References CONTROLLER_PWM_CMP_MAX, ctl_attach_sinv_with_adc(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_ptr_adc_channel(), ctl_init_pwm_channel(), CTRL_ADC_RESOLUTION, CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_ADC_BIAS, CTRL_CURRENT_ADC_GAIN, CTRL_CURRENT_BASE, CTRL_VOLTAGE_ADC_BIAS, CTRL_VOLTAGE_ADC_GAIN, CTRL_VOLTAGE_BASE, simulink_rx_buffer, sinv_adc, SINV_ADC_ID_IC, SINV_ADC_ID_IDC, SINV_ADC_ID_IG, SINV_ADC_ID_IL, SINV_ADC_ID_VDC, SINV_ADC_ID_VG, sinv_ctrl, and sinv_pwm_out.
Variable Documentation
sinv_adc
ptr_adc_channel_t sinv_adc[SINV_ADC_SENSOR_NUMBER]
Definition at line 23 of file xplt.peripheral.c.
sinv_pwm_out
pwm_channel_t sinv_pwm_out[2]
Definition at line 25 of file xplt.peripheral.c.