GMP - CTL: suite/mcs_pmsm_nt/implement/stm32g431/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <xplt.peripheral.h>
#include "main.h"
Macros
#define _FILE_CTL_INTERFACE_H_
#define TIM_CCER_MASK
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_fast_enable_output ()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
TIM_CCER_MASK
#define TIM_CCER_MASK
Value:
(TIM_CCER_CC1E | TIM_CCER_CC1NE | \
TIM_CCER_CC2E | TIM_CCER_CC2NE | \
TIM_CCER_CC3E | TIM_CCER_CC3NE)
Definition at line 83 of file xplt.ctl_interface.h.
Function Documentation
ctl_fast_disable_output()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Definition at line 114 of file xplt.ctl_interface.h.
References ctl_disable_gfl_inv(), htim1, inv_ctrl, and TIM_CCER_MASK.
ctl_fast_enable_output()
GMP_STATIC_INLINE void ctl_fast_enable_output ()
Definition at line 89 of file xplt.ctl_interface.h.
References ctl_enable_gfl_inv(), htim1, inv_ctrl, and TIM_CCER_MASK.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 31 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), hadc1, hadc2, iabc, iabc_src, idc, idc_src, iuvw, phase_A, phase_B, phase_C, udc, udc_src, uuvw, vabc, and vabc_src.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 63 of file xplt.ctl_interface.h.
References hdac1, htim1, iabc, iuvw, phase_C, phase_U, phase_V, phase_W, and spwm.