GMP - CTL: suite/pgs_3ph_grid_inverter/implement/stm32f407/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
#include <ext/encoder/as5048/as5048a.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Variables
ctrl_gt sinv_pwm_pu [2]
pwm_channel_t sinv_pwm_out [2]
ptr_adc_channel_t sinv_il
ptr_adc_channel_t sinv_ig
ptr_adc_channel_t sinv_uc
ptr_adc_channel_t sinv_udc
ctrl_gt modulate_target
qpr_ctrl_t qpr_test
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 20 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 121 of file xplt.ctl_interface.h.
References flag_error, and htim1.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 100 of file xplt.ctl_interface.h.
References ctl_clear_pid(), ctl_clear_pr_controller(), ctl_clear_qpr_controller(), flag_error, and htim1.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 57 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), sinv_ig, sinv_il, sinv_uc, and sinv_udc.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 75 of file xplt.ctl_interface.h.
References ctl_mul, hdac, htim1, sinv_ig, sinv_pwm_out, and sinv_pwm_pu.
Variable Documentation
modulate_target
ctrl_gt modulate_target extern
qpr_test
qpr_ctrl_t qpr_test extern
Definition at line 59 of file xplt.peripheral.c.
sinv_ig
ptr_adc_channel_t sinv_ig extern
Definition at line 55 of file xplt.peripheral.c.
sinv_il
ptr_adc_channel_t sinv_il extern
Definition at line 54 of file xplt.peripheral.c.
sinv_pwm_out
pwm_channel_t sinv_pwm_out[2] extern
Definition at line 25 of file xplt.peripheral.c.
sinv_pwm_pu
ctrl_gt sinv_pwm_pu[2] extern
sinv_uc
ptr_adc_channel_t sinv_uc extern
Definition at line 56 of file xplt.peripheral.c.
sinv_udc
ptr_adc_channel_t sinv_udc extern
Definition at line 57 of file xplt.peripheral.c.