GMP - CTL: suite/mcs_pmsm_nt/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
#include <core/pm/function_scheduler.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
gmp_task_status_t tsk_protect (gmp_task_t *tsk)
void ctl_enable_pwm ()
硬件PWM输出使能/禁止
void ctl_disable_pwm ()
void clear_all_controllers ()
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
Variables
cia402_sm_t cia402_sm
ctl_mtr_protect_t protection
spwm_modulator_t spwm
mtr_current_ctrl_t mtr_ctrl
mtr_current_init_t mtr_ctrl_init
vel_pos_ctrl_t motion_ctrl
ctl_slope_f_pu_controller rg
pos_autoturn_encoder_t pos_enc
spd_calculator_t spd_enc
volatile fast_gt flag_system_running = 0
volatile fast_gt flag_error = 0
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
volatile fast_gt index_adc_calibrator = 0
Function Documentation
clear_all_controllers()
void clear_all_controllers ()
Definition at line 266 of file ctl_main.c.
References ctl_clear_mtr_current_ctrl(), ctl_clear_npc_modulator(), ctl_clear_slope_f_pu(), ctl_clear_spwm_modulator(), ctl_clear_vel_pos_ctrl(), motion_ctrl, mtr_ctrl, rg, and spwm.
ctl_disable_pwm()
void ctl_disable_pwm (void)
Definition at line 261 of file ctl_main.c.
References ctl_fast_disable_output().
ctl_enable_pwm()
void ctl_enable_pwm (void)
硬件PWM输出使能/禁止
Note
在 Operation Enabled 状态下为 true，其他状态为 false
Parameters
enable true: 开启PWM驱动; false: 封锁PWM（高阻态或特定电平）
Definition at line 256 of file ctl_main.c.
References ctl_fast_enable_output().
ctl_exec_adc_calibration()
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
Note
通常在 Not Ready 或 Switch On Disabled 状态下调用
Returns
true: 校准完成且成功; false: 失败或正在进行中
Definition at line 279 of file ctl_main.c.
References adc_calibrator, clear_all_controllers(), ctl_clear_adc_calibrator(), ctl_div, ctl_enable_adc_calibrator(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, idc, index_adc_calibrator, iuvw, and uuvw.
ctl_init()
void ctl_init (void)
Definition at line 71 of file ctl_main.c.
References adc_calibrator, CIA402_CMD_ENABLE_OPERATION, cia402_sm, CONTROLLER_FREQUENCY, ctl_attach_mtr_current_ctrl_port(), ctl_attach_mtr_protect_port(), ctl_attach_vel_pos_ctrl(), ctl_auto_tuning_mtr_current_ctrl(), ctl_auto_tuning_pmsm_smo(), ctl_disable_mtr_current_ctrl(), ctl_enable_adc_calibrator(), ctl_enable_mtr_current_ctrl(), ctl_enable_velocity_ctrl(), ctl_fast_disable_output(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_init_const_slope_f_pu_controller(), ctl_init_mtr_current_ctrl(), ctl_init_mtr_protect(), ctl_init_npc_modulator(), ctl_init_pmsm_smo(), ctl_init_spd_calculator(), ctl_init_spwm_modulator(), ctl_init_vel_pos_ctrl(), ctl_set_autoturn_pos_encoder_mech_offset(), ctl_set_mtr_current_ctrl_ref(), ctl_set_mtr_current_ctrl_vdq_ref(), ctl_set_mtr_protect_mask(), ctl_set_target_velocity(), CTRL_CURRENT_BASE, CTRL_POS_DIV, CTRL_POS_ENC_BIAS, CTRL_POS_ENC_FS, CTRL_PWM_CMP_MAX, CTRL_PWM_DEADBAND_CMP, CTRL_SPD_DIV, CTRL_VOLTAGE_BASE, flag_enable_adc_calibrator, float2ctrl, init_cia402_state_machine(), iuvw, motion_ctrl, MOTOR_PARAM_LS, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RATED_FREQUENCY, MOTOR_PARAM_RATED_VOLTAGE, MOTOR_PARAM_RS, mtr_ctrl, mtr_ctrl_init, MTR_PROT_DEVIATION, pos_enc, protection, rg, spd_enc, spwm, and udc.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 219 of file ctl_main.c.
References cia402_dispatch(), and cia402_sm.
tsk_protect()
gmp_task_status_t tsk_protect (gmp_task_t * tsk)
Definition at line 229 of file ctl_main.c.
References cia402_fault_request(), cia402_sm, ctl_dispatch_mtr_protect_slow(), ctl_get_mtr_protect_mask(), ctl_set_mtr_protect_mask(), mtr_ctrl, MTR_PROT_DEVIATION, and protection.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 63 of file ctl_main.c.
cia402_sm
cia402_sm_t cia402_sm
Definition at line 29 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
Definition at line 64 of file ctl_main.c.
flag_error
volatile fast_gt flag_error = 0
Definition at line 60 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running = 0
Definition at line 59 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator = 0
Definition at line 66 of file ctl_main.c.
motion_ctrl
vel_pos_ctrl_t motion_ctrl
Definition at line 42 of file ctl_main.c.
mtr_ctrl
mtr_current_ctrl_t mtr_ctrl
Definition at line 40 of file ctl_main.c.
mtr_ctrl_init
mtr_current_init_t mtr_ctrl_init
Definition at line 41 of file ctl_main.c.
pos_enc
pos_autoturn_encoder_t pos_enc
Definition at line 46 of file ctl_main.c.
protection
ctl_mtr_protect_t protection
Definition at line 30 of file ctl_main.c.
rg
ctl_slope_f_pu_controller rg
Definition at line 45 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc
Definition at line 47 of file ctl_main.c.
spwm
spwm_modulator_t spwm
Definition at line 36 of file ctl_main.c.