GMP - CTL: suite/pgs_3ph_GFL_inverter/implement/common/ctl_main.h File Reference
ctl_main.h File Reference
#include <xplt.peripheral.h>
#include <ctl/component/interface/adc_channel.h>
#include <ctl/component/interface/pwm_channel.h>
#include <ctl/component/digital_power/three_phase/three_phase_GFL.h>
#include <ctl/component/digital_power/three_phase/three_phase_additional.h>
#include <ctl/component/interface/pwm_modulator.h>
#include <ctl/framework/cia402_state_machine.h>
Functions
GMP_STATIC_INLINE void ctl_dispatch (void)
Variables
volatile fast_gt flag_system_running
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator
volatile fast_gt index_adc_calibrator
cia402_sm_t cia402_sm
spwm_modulator_t spwm
gfl_inv_ctrl_init_t gfl_init
gfl_inv_ctrl_t inv_ctrl
gfl_pq_ctrl_t pq_ctrl
inv_neg_ctrl_init_t gfl_neg_init
inv_neg_ctrl_t neg_current_ctrl
ctl_triangle_wave_generator_t tri_wave
Function Documentation
ctl_dispatch()
GMP_STATIC_INLINE void ctl_dispatch (void)
Definition at line 73 of file ctl_main.h.
References adc_calibrator, ctl_set_gfl_inv_current(), ctl_step_adc_calibrator(), ctl_step_gfl_inv_ctrl(), ctl_step_gfl_pq(), ctl_step_neg_inv_ctrl(), ctl_step_npc_modulator(), ctl_step_spwm_modulator(), ctl_step_triangle_wave_generator(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, inv_ctrl, iuvw, neg_current_ctrl, phase_0, phase_A, phase_B, phase_d, phase_q, pq_ctrl, spwm, tri_wave, udc, uuvw, and vabc.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator extern
Definition at line 47 of file ctl_main.c.
cia402_sm
cia402_sm_t cia402_sm extern
Definition at line 29 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator extern
Definition at line 48 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running extern
Definition at line 35 of file ctl_main.c.
gfl_init
gfl_inv_ctrl_init_t gfl_init extern
Definition at line 40 of file ctl_main.c.
gfl_neg_init
inv_neg_ctrl_init_t gfl_neg_init extern
Definition at line 38 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator extern
Definition at line 49 of file ctl_main.c.
inv_ctrl
gfl_inv_ctrl_t inv_ctrl extern
Definition at line 41 of file ctl_main.c.
neg_current_ctrl
inv_neg_ctrl_t neg_current_ctrl extern
Definition at line 39 of file ctl_main.c.
pq_ctrl
gfl_pq_ctrl_t pq_ctrl extern
Definition at line 37 of file ctl_main.c.
spwm
spwm_modulator_t spwm extern
Definition at line 36 of file ctl_main.c.
tri_wave
ctl_triangle_wave_generator_t tri_wave extern
Definition at line 57 of file ctl_main.c.