GMP - CTL: suite/mcs_pmsm/implement/common/ctl_main.h File Reference
ctl_main.h File Reference
#include <ctl/component/motor_control/basic/vf_generator.h>
#include <ctl/component/motor_control/basic/encoder.h>
#include <ctl/component/motor_control/pmsm_controller/pmsm_ctrl.h>
#include <ctl/component/interface/pwm_channel.h>
#include <ctl/component/interface/adc_channel.h>
#include <ctl/component/intrinsic/discrete/biquad_filter.h>
#include <xplt.peripheral.h>
Enumerations
enum adc_index_t {
MTR_ADC_UA = 0 , MTR_ADC_UB , MTR_ADC_UC , MTR_ADC_IA ,
MTR_ADC_IB , MTR_ADC_IC , MTR_ADC_UDC , MTR_ADC_IDC
}
Functions
GMP_STATIC_INLINE void ctl_dispatch (void)
Variables
spd_calculator_t spd_enc
ctl_slope_f_controller rg
pmsm_controller_t pmsm_ctrl
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator
volatile fast_gt index_adc_calibrator
Enumeration Type Documentation
adc_index_t
enum adc_index_t
Enumerator
MTR_ADC_UA
MTR_ADC_UB
MTR_ADC_UC
MTR_ADC_IA
MTR_ADC_IB
MTR_ADC_IC
MTR_ADC_UDC
MTR_ADC_IDC
Definition at line 63 of file ctl_main.h.
Function Documentation
ctl_dispatch()
GMP_STATIC_INLINE void ctl_dispatch (void)
Definition at line 77 of file ctl_main.h.
References adc_calibrator, ctl_step_adc_calibrator(), ctl_step_const_f_controller(), ctl_step_pmsm_ctrl(), ctl_step_slope_f(), ctl_step_spd_calc(), flag_enable_adc_calibrator, index_adc_calibrator, pmsm_ctrl, rg, and spd_enc.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator extern
Definition at line 47 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator extern
Definition at line 48 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator extern
Definition at line 49 of file ctl_main.c.
pmsm_ctrl
pmsm_controller_t pmsm_ctrl extern
Definition at line 24 of file ctl_main.c.
rg
ctl_slope_f_controller rg extern
Definition at line 40 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc extern
Definition at line 32 of file ctl_main.c.