GMP - CTL: suite/pgs_3ph_grid_inverter/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
#include <ctl/component/digital_power/three_phase/three_phase_dc_ac.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
fast_gt ctl_adc_calibrate (void)
fast_gt ctl_ready_mainloop (void)
Variables
inv_ctrl_t inv_ctrl
volatile fast_gt flag_system_enable = 0
volatile fast_gt flag_system_running = 0
volatile fast_gt flag_error = 0
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
volatile fast_gt index_adc_calibrator = 0
uint16_t sgen_out = 0
fast_gt firsttime_flag = 0
fast_gt startup_flag = 0
fast_gt started_flag = 0
time_gt tick_bias = 0
Function Documentation
ctl_adc_calibrate()
fast_gt ctl_adc_calibrate (void)
Definition at line 242 of file ctl_main.c.
References adc_calibrator, ctl_clear_adc_calibrator(), ctl_clear_three_phase_inv(), ctl_div, ctl_enable_adc_calibrator(), ctl_enable_three_phase_inverter(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, inv_ctrl, iuvw, uuvw, and vabc.
ctl_init()
void ctl_init (void)
Definition at line 43 of file ctl_main.c.
References adc_calibrator, CONTROLLER_FREQUENCY, ctl_disable_output(), ctl_disable_three_phase_feedforward(), ctl_disable_three_phase_harm_ctrl(), ctl_disable_three_phase_negative_ctrl(), ctl_enable_adc_calibrator(), ctl_enable_three_phase_harm_ctrl(), ctl_enable_three_phase_negative_current_ctrl(), ctl_enable_three_phase_negative_voltage_ctrl(), ctl_init_adc_calibrator(), ctl_init_three_phase_inv(), ctl_set_three_phase_inv_current(), ctl_set_three_phase_inv_current_mode(), ctl_set_three_phase_inv_freerun(), ctl_set_three_phase_inv_openloop_mode(), ctl_set_three_phase_inv_voltage(), ctl_set_three_phase_inv_voltage_mode(), ctl_set_three_phase_inv_voltage_openloop(), CTRL_CURRENT_BASE, CTRL_VOLTAGE_BASE, flag_enable_adc_calibrator, float2ctrl, init(), and inv_ctrl.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 196 of file ctl_main.c.
References ctl_disable_output(), ctl_enable_output(), ctl_ready_mainloop(), firsttime_flag, flag_system_enable, started_flag, startup_flag, and tick_bias.
ctl_ready_mainloop()
fast_gt ctl_ready_mainloop (void)
Definition at line 380 of file ctl_main.c.
References ctl_abs, ctl_adc_calibrate(), ctl_clear_three_phase_inv(), ctl_get_three_phase_pll_error(), ctl_is_three_phase_inverter_mode(), CTRL_SPLL_EPSILON, and inv_ctrl.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 38 of file ctl_main.c.
firsttime_flag
fast_gt firsttime_flag = 0
Definition at line 191 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 1
Definition at line 39 of file ctl_main.c.
flag_error
volatile fast_gt flag_error = 0
Definition at line 35 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable = 0
Definition at line 29 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running = 0
Definition at line 34 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator = 0
Definition at line 40 of file ctl_main.c.
inv_ctrl
inv_ctrl_t inv_ctrl
Definition at line 25 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 190 of file ctl_main.c.
started_flag
fast_gt started_flag = 0
Definition at line 193 of file ctl_main.c.
startup_flag
fast_gt startup_flag = 0
Definition at line 192 of file ctl_main.c.
tick_bias
time_gt tick_bias = 0
Definition at line 194 of file ctl_main.c.