GMP - CTL: suite/mcs_pmsm_nt/implement/common/user_main.c File Reference
user_main.c File Reference
#include <gmp_core.h>
#include "user_main.h"
Functions
at_status_t enable_handler (at_device_entity_t *dev, at_cmd_type_t type, char *args, uint16_t len)
at_status_t poweroff_handler (at_device_entity_t *dev, at_cmd_type_t type, char *args, uint16_t len)
at_status_t rst_handler (at_device_entity_t *dev, at_cmd_type_t type, char *args, uint16_t len)
void at_device_error_handler (at_device_entity_t *dev, at_error_code_t code)
gmp_task_status_t tsk_blink (gmp_task_t *tsk)
void at_device_flush_rx_buffer ()
gmp_task_status_t tsk_at_device (gmp_task_t *tsk)
void send_monitor_data (void)
gmp_task_status_t tsk_monitor (gmp_task_t *tsk)
gmp_task_status_t tsk_protect (gmp_task_t *tsk)
GMP_NO_OPT_PREFIX void init (void)
GMP_NO_OPT_PREFIX void mainloop (void)
Variables
at_device_entity_t at_dev
time_gt uart_last_tick
gmp_scheduler_t sched
at_device_cmd_t at_cmds []
gmp_task_t tasks []
Function Documentation
at_device_error_handler()
void at_device_error_handler (at_device_entity_t * dev, at_error_code_t code)
Definition at line 65 of file user_main.c.
at_device_flush_rx_buffer()
void at_device_flush_rx_buffer ()
Definition at line 316 of file xplt.peripheral.c.
References at_dev, and ISR_LOCAL_BUF_SIZE.
enable_handler()
at_status_t enable_handler (at_device_entity_t * dev, at_cmd_type_t type, char * args, uint16_t len)
Definition at line 20 of file user_main.c.
References CIA402_CMD_ENABLE_OPERATION, cia402_send_cmd(), and cia402_sm.
init()
GMP_NO_OPT_PREFIX void init (void)
Definition at line 135 of file user_main.c.
References at_cmds, at_dev, at_device_error_handler(), i, sched, and tasks.
mainloop()
GMP_NO_OPT_PREFIX void mainloop (void)
Definition at line 151 of file user_main.c.
References sched.
poweroff_handler()
at_status_t poweroff_handler (at_device_entity_t * dev, at_cmd_type_t type, char * args, uint16_t len)
Definition at line 35 of file user_main.c.
References CIA402_CMD_DISABLE_VOLTAGE, cia402_send_cmd(), and cia402_sm.
rst_handler()
at_status_t rst_handler (at_device_entity_t * dev, at_cmd_type_t type, char * args, uint16_t len)
Definition at line 50 of file user_main.c.
References cia402_fault_reset(), and cia402_sm.
send_monitor_data()
void send_monitor_data (void)
Definition at line 251 of file xplt.peripheral.c.
References CAN_SCALE_FACTOR, can_data_t::i32, inv_ctrl, phase_A, phase_d, and phase_q.
tsk_at_device()
gmp_task_status_t tsk_at_device (gmp_task_t * tsk)
Definition at line 99 of file user_main.c.
References at_dev, and at_device_flush_rx_buffer().
tsk_blink()
gmp_task_status_t tsk_blink (gmp_task_t * tsk)
Definition at line 89 of file user_main.c.
tsk_monitor()
gmp_task_status_t tsk_monitor (gmp_task_t * tsk)
Definition at line 111 of file user_main.c.
References send_monitor_data().
tsk_protect()
gmp_task_status_t tsk_protect (gmp_task_t * tsk)
Definition at line 229 of file ctl_main.c.
References cia402_fault_request(), cia402_sm, ctl_dispatch_mtr_protect_slow(), ctl_get_mtr_protect_mask(), ctl_set_mtr_protect_mask(), mtr_ctrl, MTR_PROT_DEVIATION, and protection.
Variable Documentation
at_cmds
at_device_cmd_t at_cmds[]
Initial value:
                    = {
{"PWMON", 4, 0, enable_handler, "Enable Controller Operation."},
{"PWROFF", 4, 0, poweroff_handler, "Power off"},
{"RST", 3, 0, rst_handler, "Reset Sys"}}
Definition at line 80 of file user_main.c.
at_dev
at_device_entity_t at_dev
Definition at line 12 of file user_main.c.
sched
gmp_scheduler_t sched
Definition at line 14 of file user_main.c.
tasks
gmp_task_t tasks[]
Initial value:
             = {
{"protect", tsk_protect, 1000, 0, 1, NULL},
{"blink_led", tsk_blink, 1000, 100, 1, NULL},
{"at_device", tsk_at_device, 5, 1, 1, NULL},
{"monitor_data", tsk_monitor, 2, 0, 1, NULL}}
Definition at line 124 of file user_main.c.
uart_last_tick
time_gt uart_last_tick
Definition at line 13 of file user_main.c.