GMP - CTL: suite/pgs_1ph_dcac_inv/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
#include <ctl/component/digital_power/single_phase/single_phase_dc_ac.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
fast_gt ctl_ready_mainloop (void)
Variables
sinv_ctrl_t sinv_ctrl
ctl_pid_t current_outer
ctrl_gt ig_rms_ref = float2ctrl(0.1)
volatile fast_gt flag_system_enable = 0
volatile fast_gt flag_system_running = 0
volatile fast_gt flag_error = 0
uint16_t sgen_out = 0
fast_gt firsttime_flag = 0
fast_gt startup_flag = 0
fast_gt started_flag = 0
time_gt tick_bias = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 41 of file ctl_main.c.
References CONTROLLER_FREQUENCY, ctl_disable_output(), ctl_disable_sinv_harm_ctrl(), ctl_enable_sinv_harm_ctrl(), ctl_init_sinv_ctrl(), ctl_set_sinv_current_closeloop_inverter(), ctl_set_sinv_current_ref(), ctl_set_sinv_freerun(), ctl_set_sinv_openloop_inverter(), ctl_set_sinv_pll(), ctl_set_sinv_voltage_closeloop_inverter(), ctl_set_sinv_voltage_closeloop_rectifier(), ctl_set_sinv_voltage_ref(), current_outer, flag_system_enable, float2ctrl, init(), and sinv_ctrl.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 217 of file ctl_main.c.
References ctl_disable_output(), ctl_enable_output(), ctl_ready_mainloop(), firsttime_flag, flag_system_enable, started_flag, startup_flag, and tick_bias.
ctl_ready_mainloop()
fast_gt ctl_ready_mainloop (void)
Definition at line 267 of file ctl_main.c.
References ctl_abs, ctl_clear_sinv(), ctl_get_spll_error_fbk(), ctl_is_sinv_inverter_mode(), CTRL_SPLL_EPSILON, and sinv_ctrl.
Variable Documentation
current_outer
ctl_pid_t current_outer
Definition at line 27 of file ctl_main.c.
firsttime_flag
fast_gt firsttime_flag = 0
Definition at line 212 of file ctl_main.c.
flag_error
volatile fast_gt flag_error = 0
Definition at line 38 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable = 0
Definition at line 32 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running = 0
Definition at line 37 of file ctl_main.c.
ig_rms_ref
ctrl_gt ig_rms_ref = float2ctrl(0.1)
Definition at line 28 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 211 of file ctl_main.c.
sinv_ctrl
sinv_ctrl_t sinv_ctrl
Definition at line 25 of file ctl_main.c.
started_flag
fast_gt started_flag = 0
Definition at line 214 of file ctl_main.c.
startup_flag
fast_gt startup_flag = 0
Definition at line 213 of file ctl_main.c.
tick_bias
time_gt tick_bias = 0
Definition at line 215 of file ctl_main.c.