GMP - CTL: suite/pgs_3ph_grid_inverter/implement/f280039c_iris_node/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
#define BOARD_PIN_MAPPING
#define PHASE_U_BASE IRIS_EPWM1_BASE
#define PHASE_V_BASE IRIS_EPWM2_BASE
#define PHASE_W_BASE IRIS_EPWM3_BASE
#define PWM_ENABLE_PORT IRIS_GPIO1
#define PWM_RESET_PORT IRIS_GPIO3
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
BOARD_PIN_MAPPING
#define BOARD_PIN_MAPPING
Definition at line 30 of file xplt.ctl_interface.h.
PHASE_U_BASE
#define PHASE_U_BASE IRIS_EPWM1_BASE
Definition at line 33 of file xplt.ctl_interface.h.
PHASE_V_BASE
#define PHASE_V_BASE IRIS_EPWM2_BASE
Definition at line 34 of file xplt.ctl_interface.h.
PHASE_W_BASE
#define PHASE_W_BASE IRIS_EPWM3_BASE
Definition at line 35 of file xplt.ctl_interface.h.
PWM_ENABLE_PORT
#define PWM_ENABLE_PORT IRIS_GPIO1
Definition at line 38 of file xplt.ctl_interface.h.
PWM_RESET_PORT
#define PWM_RESET_PORT IRIS_GPIO3
Definition at line 39 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 160 of file xplt.ctl_interface.h.
References ctl_disable_three_phase_inverter(), GPIO_WritePin(), inv_ctrl, PHASE_U_BASE, PHASE_V_BASE, PHASE_W_BASE, and PWM_ENABLE_PORT.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 142 of file xplt.ctl_interface.h.
References ctl_enable_three_phase_inverter(), GPIO_WritePin(), inv_ctrl, PHASE_U_BASE, PHASE_V_BASE, PHASE_W_BASE, PWM_ENABLE_PORT, and PWM_RESET_PORT.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 71 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), iabc, iabc_src, idc, idc_src, INV_IA, INV_IA_RESULT_BASE, INV_IB, INV_IB_RESULT_BASE, INV_IC, INV_IC_RESULT_BASE, INV_IU, INV_IU_RESULT_BASE, INV_IV, INV_IV_RESULT_BASE, INV_IW, INV_IW_RESULT_BASE, INV_UA, INV_UA_RESULT_BASE, INV_UB, INV_UB_RESULT_BASE, INV_UC, INV_UC_RESULT_BASE, INV_UU, INV_UU_RESULT_BASE, INV_UV, INV_UV_RESULT_BASE, INV_UW, INV_UW_RESULT_BASE, INV_VBUS, INV_VBUS_RESULT_BASE, iuvw, iuvw_src, phase_A, phase_B, phase_C, phase_U, phase_V, phase_W, udc, udc_src, uuvw, uuvw_src, vabc, and vabc_src.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 103 of file xplt.ctl_interface.h.
References ctl_calc_pwm_tri_channel(), iabc, iuvw, phase_C, phase_U, PHASE_U_BASE, phase_V, PHASE_V_BASE, phase_W, PHASE_W_BASE, and pwm_out.
GPIO_WritePin()
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)