GMP - CTL: suite/dps_buck/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
#include <ctl/component/intrinsic/continuous/continuous_pid.h>
#include <ctl/component/digital_power/basic/buck.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
fast_gt ctl_ready_mainloop (void)
Variables
volatile fast_gt flag_system_enable = 0
volatile fast_gt flag_system_running = 0
volatile fast_gt flag_error = 0
buck_ctrl_t buck_ctrl
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_system = 0
uint16_t sgen_out = 0
fast_gt firsttime_flag = 0
fast_gt startup_flag = 0
fast_gt started_flag = 0
time_gt tick_bias = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 49 of file ctl_main.c.
References boost_ctrl, buck_ctrl, CONTROLLER_FREQUENCY, ctl_buck_ctrl_current_mode(), ctl_buck_ctrl_openloop_mode(), ctl_buck_ctrl_voltage_mode(), ctl_disable_output(), ctl_init_buck_ctrl(), ctl_set_buck_ctrl_current(), ctl_set_buck_ctrl_voltage(), ctl_set_buck_ctrl_voltage_openloop(), and float2ctrl.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 105 of file ctl_main.c.
References ctl_disable_output(), ctl_enable_output(), ctl_ready_mainloop(), firsttime_flag, flag_system_enable, started_flag, startup_flag, and tick_bias.
ctl_ready_mainloop()
fast_gt ctl_ready_mainloop (void)
Definition at line 155 of file ctl_main.c.
References buck_ctrl, and ctl_clear_buck_ctrl().
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 41 of file ctl_main.c.
buck_ctrl
buck_ctrl_t buck_ctrl
Definition at line 38 of file ctl_main.c.
firsttime_flag
fast_gt firsttime_flag = 0
Definition at line 100 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
Definition at line 42 of file ctl_main.c.
flag_enable_system
volatile fast_gt flag_enable_system = 0
Definition at line 46 of file ctl_main.c.
flag_error
volatile fast_gt flag_error = 0
Definition at line 35 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable = 0
Definition at line 29 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running = 0
Definition at line 34 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator = 0
Definition at line 43 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 98 of file ctl_main.c.
started_flag
fast_gt started_flag = 0
Definition at line 102 of file ctl_main.c.
startup_flag
fast_gt startup_flag = 0
Definition at line 101 of file ctl_main.c.
tick_bias
time_gt tick_bias = 0
Definition at line 103 of file ctl_main.c.