GMP - CTL: suite/mcs_acm/implement/stm32g431/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
Functions
void setup_peripheral (void)
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
Variables
uint32_t adc1_res [ADC1_SEQ_SIZE] = {0}
uint32_t adc2_res [ADC2_SEQ_SIZE] = {0}
tri_ptr_adc_channel_t uabc
tri_ptr_adc_channel_t iabc
ptr_adc_channel_t udc
ptr_adc_channel_t idc
pwm_tri_channel_t pwm_out
adc_gt uabc_raw [3]
adc_gt iabc_raw [3]
adc_gt udc_raw
adc_gt idc_raw
ext_as5048a_encoder_t pos_enc
Function Documentation
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * hadc)
Definition at line 130 of file xplt.peripheral.c.
References gmp_base_ctl_step(), and hadc2.
setup_peripheral()
void setup_peripheral (void)
Definition at line 53 of file xplt.peripheral.c.
References adc1_res, ADC1_SEQ_SIZE, adc2_res, ADC2_SEQ_SIZE, CONTROLLER_PWM_CMP_MAX, ctl_attach_mtr_adc_channels(), ctl_attach_mtr_position(), ctl_init_ptr_adc_channel(), ctl_init_pwm_tri_channel(), ctl_init_tri_ptr_adc_channel(), float2ctrl, hadc1, hadc2, htim1, iabc, iabc_raw, idc, idc_raw, MTR_CTRL_CURRENT_BIAS, MTR_CTRL_CURRENT_GAIN, MTR_CTRL_VOLTAGE_BIAS, MTR_CTRL_VOLTAGE_GAIN, pmsm_ctrl, pos_enc, pwm_out, uabc, uabc_raw, udc, and udc_raw.
Variable Documentation
adc1_res
uint32_t adc1_res[ADC1_SEQ_SIZE] = {0}
Definition at line 24 of file xplt.peripheral.c.
adc2_res
uint32_t adc2_res[ADC2_SEQ_SIZE] = {0}
Definition at line 25 of file xplt.peripheral.c.
iabc
tri_ptr_adc_channel_t iabc
Definition at line 29 of file xplt.peripheral.c.
iabc_raw
adc_gt iabc_raw[3]
Definition at line 40 of file xplt.peripheral.c.
idc
ptr_adc_channel_t idc
Definition at line 32 of file xplt.peripheral.c.
idc_raw
adc_gt idc_raw
Definition at line 42 of file xplt.peripheral.c.
pos_enc
ext_as5048a_encoder_t pos_enc
Definition at line 45 of file xplt.peripheral.c.
pwm_out
pwm_tri_channel_t pwm_out
Definition at line 36 of file xplt.peripheral.c.
uabc
tri_ptr_adc_channel_t uabc
Definition at line 28 of file xplt.peripheral.c.
uabc_raw
adc_gt uabc_raw[3]
Definition at line 39 of file xplt.peripheral.c.
udc
ptr_adc_channel_t udc
Definition at line 31 of file xplt.peripheral.c.
udc_raw
adc_gt udc_raw
Definition at line 41 of file xplt.peripheral.c.