GMP - CTL: suite/mcs_pmsm_hfi/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
Variables
pmsm_bare_controller_t pmsm_ctrl
spd_calculator_t spd_enc
ctl_slope_f_controller rg
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
fast_gt index_adc_calibrator = 0
volatile fast_gt flag_enable_system = 0
uint16_t sgen_out = 0
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 55 of file ctl_main.c.
References adc_calibrator, CONTROLLER_FREQUENCY, ctl_attach_mtr_position(), ctl_attach_mtr_velocity(), ctl_disable_pmsm_ctrl_output(), ctl_enable_adc_calibrator(), ctl_enable_output(), ctl_enable_pmsm_ctrl(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_init_const_f_controller(), ctl_init_const_slope_f_controller(), ctl_init_spd_calculator(), ctl_pmsm_ctrl_current_mode(), ctl_pmsm_ctrl_velocity_mode(), ctl_pmsm_ctrl_voltage_mode(), ctl_set_autoturn_pos_encoder_offset(), ctl_set_pmsm_ctrl_idq_ff(), ctl_set_pmsm_ctrl_speed(), ctl_set_pmsm_ctrl_vdq_ff(), flag_enable_adc_calibrator, flag_enable_system, float2ctrl, index_adc_calibrator, MOTOR_PARAM_LS, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RS, MTR_CTRL_CURRENT_BASE, MTR_CTRL_CURRENT_LOOP_BW, MTR_CTRL_SPEED_LOOP_BW, MTR_CTRL_VOLTAGE_BASE, MTR_ENCODER_LINES, MTR_ENCODER_OFFSET, pmsm_ctrl, pos_enc, rg, SPD_CONTROLLER_PWM_DIVISION, and spd_enc.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 183 of file ctl_main.c.
References adc_calibrator, ctl_clear_adc_calibrator(), ctl_div, ctl_enable_adc_calibrator(), ctl_enable_pmsm_ctrl_output(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), ctl_set_pmsm_ctrl_speed(), flag_enable_adc_calibrator, float2ctrl, iabc, idc, index_adc_calibrator, MTR_ADC_IDC, and pmsm_ctrl.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 47 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator = 0
Definition at line 48 of file ctl_main.c.
flag_enable_system
volatile fast_gt flag_enable_system = 0
Definition at line 52 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator = 0
Definition at line 49 of file ctl_main.c.
pmsm_ctrl
pmsm_bare_controller_t pmsm_ctrl
Definition at line 24 of file ctl_main.c.
rg
ctl_slope_f_controller rg
Definition at line 42 of file ctl_main.c.
sgen_out
uint16_t sgen_out = 0
Definition at line 181 of file ctl_main.c.
spd_enc
spd_calculator_t spd_enc
Definition at line 32 of file ctl_main.c.