GMP - CTL: suite/mcs_pmsm_nt/implement/f280039c_iris_node/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
#include <xplt.peripheral.h>
Data Structures
union can_data_t
Macros
#define CAN_SCALE_FACTOR 10000
#define ISR_LOCAL_BUF_SIZE 16
Functions
void setup_peripheral (void)
interrupt void MainISR (void)
void reset_controller (void)
interrupt void INT_IRIS_CAN_0_ISR (void)
interrupt void INT_IRIS_CAN_1_ISR (void)
void send_monitor_data (void)
interrupt void INT_IRIS_UART_RS232_RX_ISR (void)
void at_device_flush_rx_buffer ()
interrupt void INT_IRIS_UART_USB_RX_ISR (void)
Variables
tri_ptr_adc_channel_t uuvw
adc_gt uuvw_src [3]
tri_ptr_adc_channel_t iuvw
adc_gt iuvw_src [3]
tri_ptr_adc_channel_t vabc
adc_gt vabc_src [3]
tri_ptr_adc_channel_t iabc
adc_gt iabc_src [3]
ptr_adc_channel_t udc
adc_gt udc_src
ptr_adc_channel_t idc
adc_gt idc_src
Macro Definition Documentation
CAN_SCALE_FACTOR
#define CAN_SCALE_FACTOR 10000
Definition at line 180 of file xplt.peripheral.c.
ISR_LOCAL_BUF_SIZE
#define ISR_LOCAL_BUF_SIZE 16
Definition at line 314 of file xplt.peripheral.c.
Function Documentation
at_device_flush_rx_buffer()
void at_device_flush_rx_buffer ()
Definition at line 316 of file xplt.peripheral.c.
INT_IRIS_CAN_0_ISR()
interrupt void INT_IRIS_CAN_0_ISR (void)
Definition at line 189 of file xplt.peripheral.c.
References CAN_SCALE_FACTOR, CIA402_CMD_DISABLE_VOLTAGE, CIA402_CMD_ENABLE_OPERATION, cia402_send_cmd(), cia402_sm, ctl_set_gfl_inv_voltage_openloop(), float2ctrl, and inv_ctrl.
INT_IRIS_CAN_1_ISR()
interrupt void INT_IRIS_CAN_1_ISR (void)
Definition at line 236 of file xplt.peripheral.c.
INT_IRIS_UART_RS232_RX_ISR()
interrupt void INT_IRIS_UART_RS232_RX_ISR (void)
Definition at line 301 of file xplt.peripheral.c.
INT_IRIS_UART_USB_RX_ISR()
interrupt void INT_IRIS_UART_USB_RX_ISR (void)
Definition at line 332 of file xplt.peripheral.c.
References at_device_flush_rx_buffer().
MainISR()
interrupt void MainISR (void)
Definition at line 124 of file xplt.peripheral.c.
References gmp_base_ctl_step(), GPIO_WritePin(), and SYSTEM_LED.
reset_controller()
void reset_controller (void)
Definition at line 164 of file xplt.peripheral.c.
References GPIO_WritePin(), i, and PWM_RESET_PORT.
send_monitor_data()
void send_monitor_data (void)
Definition at line 251 of file xplt.peripheral.c.
setup_peripheral()
void setup_peripheral (void)
Definition at line 46 of file xplt.peripheral.c.
References ctl_attach_gfl_inv(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_ptr_adc_channel(), ctl_init_tri_ptr_adc_channel(), CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_BASE, CTRL_DC_CURRENT_BIAS, CTRL_DC_CURRENT_SENSITIVITY, CTRL_DC_VOLTAGE_BIAS, CTRL_DC_VOLTAGE_SENSITIVITY, CTRL_GRID_CURRENT_BIAS, CTRL_GRID_CURRENT_SENSITIVITY, CTRL_GRID_VOLTAGE_BIAS, CTRL_GRID_VOLTAGE_SENSITIVITY, CTRL_INVERTER_CURRENT_BIAS, CTRL_INVERTER_CURRENT_SENSITIVITY, CTRL_INVERTER_VOLTAGE_BIAS, CTRL_INVERTER_VOLTAGE_SENSITIVITY, CTRL_VOLTAGE_BASE, iabc, iabc_src, idc, idc_src, inv_ctrl, iuvw, iuvw_src, reset_controller(), udc, udc_src, uuvw, uuvw_src, vabc, and vabc_src.
Variable Documentation
iabc
tri_ptr_adc_channel_t iabc
Definition at line 33 of file xplt.peripheral.c.
iabc_src
adc_gt iabc_src[3]
Definition at line 34 of file xplt.peripheral.c.
idc
ptr_adc_channel_t idc
Definition at line 39 of file xplt.peripheral.c.
idc_src
adc_gt idc_src
Definition at line 40 of file xplt.peripheral.c.
iuvw
tri_ptr_adc_channel_t iuvw
Definition at line 25 of file xplt.peripheral.c.
iuvw_src
adc_gt iuvw_src[3]
Definition at line 26 of file xplt.peripheral.c.
udc
ptr_adc_channel_t udc
Definition at line 37 of file xplt.peripheral.c.
udc_src
adc_gt udc_src
Definition at line 38 of file xplt.peripheral.c.
uuvw
tri_ptr_adc_channel_t uuvw
Definition at line 21 of file xplt.peripheral.c.
uuvw_src
adc_gt uuvw_src[3]
Definition at line 22 of file xplt.peripheral.c.
vabc
tri_ptr_adc_channel_t vabc
Definition at line 29 of file xplt.peripheral.c.
vabc_src
adc_gt vabc_src[3]
Definition at line 30 of file xplt.peripheral.c.