GMP - CTL: suite/pgs_3ph_GFL_inverter/implement/f280039c_iris_node/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)
GMP_STATIC_INLINE void ctl_fast_enable_output ()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 16 of file xplt.ctl_interface.h.
Function Documentation
ctl_fast_disable_output()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Definition at line 152 of file xplt.ctl_interface.h.
References CONTROLLER_LED, ctl_disable_gfl_inv(), GPIO_WritePin(), inv_ctrl, PHASE_U_BASE, PHASE_V_BASE, PHASE_W_BASE, and PWM_ENABLE_PORT.
ctl_fast_enable_output()
GMP_STATIC_INLINE void ctl_fast_enable_output ()
Definition at line 134 of file xplt.ctl_interface.h.
References CONTROLLER_LED, ctl_enable_gfl_inv(), GPIO_WritePin(), inv_ctrl, PHASE_U_BASE, PHASE_V_BASE, PHASE_W_BASE, PWM_ENABLE_PORT, and PWM_RESET_PORT.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 27 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), iabc, iabc_src, idc, idc_src, INV_IA, INV_IA_RESULT_BASE, INV_IB, INV_IB_RESULT_BASE, INV_IBUS, INV_IBUS_RESULT_BASE, INV_IC, INV_IC_RESULT_BASE, INV_IU, INV_IU_RESULT_BASE, INV_IV, INV_IV_RESULT_BASE, INV_IW, INV_IW_RESULT_BASE, INV_UA, INV_UA_RESULT_BASE, INV_UB, INV_UB_RESULT_BASE, INV_UC, INV_UC_RESULT_BASE, INV_UU, INV_UU_RESULT_BASE, INV_UV, INV_UV_RESULT_BASE, INV_UW, INV_UW_RESULT_BASE, INV_VBUS, INV_VBUS_RESULT_BASE, iuvw, iuvw_src, phase_A, phase_B, phase_C, phase_U, phase_V, phase_W, udc, udc_src, uuvw, uuvw_src, vabc, and vabc_src.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 59 of file xplt.ctl_interface.h.
References iabc, inv_ctrl, iuvw, NPC_IDX_PHASE_A_INNER, NPC_IDX_PHASE_A_OUTER, NPC_IDX_PHASE_B_INNER, NPC_IDX_PHASE_B_OUTER, NPC_IDX_PHASE_C_INNER, NPC_IDX_PHASE_C_OUTER, phase_A, phase_C, phase_U, PHASE_U_BASE, phase_V, PHASE_V_BASE, phase_W, PHASE_W_BASE, phasor_cos, and spwm.
GPIO_WritePin()
void GPIO_WritePin (uint16_t gpioNumber, uint16_t outVal)