GMP - CTL: suite/mcs_pmsm_nt/implement/simulate/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
Enumerations
enum inv_adc_index_items {
INV_ADC_ID_UDC = 0 , INV_ADC_ID_UA = 1 , INV_ADC_ID_UB = 2 , INV_ADC_ID_UC = 3 ,
INV_ADC_ID_IA = 4 , INV_ADC_ID_IB = 5 , INV_ADC_ID_IC = 6 , INV_ADC_SENSOR_NUMBER = 7
}
enum digital_index_items { MTR1_ENCODER_OUTPUT = 0 , MTR1_ENCODER_TURNS = 1 , DIGITAL_INDEX_NUMBER = 2 }
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_fast_enable_output ()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Enumeration Type Documentation
digital_index_items
enum digital_index_items
Enumerator
MTR1_ENCODER_OUTPUT
MTR1_ENCODER_TURNS
DIGITAL_INDEX_NUMBER
Definition at line 43 of file xplt.ctl_interface.h.
inv_adc_index_items
enum inv_adc_index_items
Enumerator
INV_ADC_ID_UDC
INV_ADC_ID_UA
INV_ADC_ID_UB
INV_ADC_ID_UC
INV_ADC_ID_IA
INV_ADC_ID_IB
INV_ADC_ID_IC
INV_ADC_SENSOR_NUMBER
Definition at line 28 of file xplt.ctl_interface.h.
Function Documentation
ctl_fast_disable_output()
GMP_STATIC_INLINE void ctl_fast_disable_output ()
Definition at line 107 of file xplt.ctl_interface.h.
References flag_system_running.
ctl_fast_enable_output()
GMP_STATIC_INLINE void ctl_fast_enable_output ()
Definition at line 99 of file xplt.ctl_interface.h.
References flag_system_running.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 55 of file xplt.ctl_interface.h.
References ctl_step_autoturn_pos_encoder(), ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), idc, INV_ADC_ID_IA, INV_ADC_ID_IB, INV_ADC_ID_IC, INV_ADC_ID_UA, INV_ADC_ID_UB, INV_ADC_ID_UC, INV_ADC_ID_UDC, iuvw, iuvw_src, MTR1_ENCODER_OUTPUT, phase_U, phase_V, phase_W, pos_enc, simulink_rx_buffer, udc, udc_src, uuvw, and uuvw_src.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 79 of file xplt.ctl_interface.h.
References mtr_ctrl, phase_A, phase_B, phase_U, phase_V, phase_W, simulink_tx_buffer, and spwm.