GMP - CTL: suite/dps_boost/implement/simulate/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Variables
ptr_adc_channel_t boost_adc_channel [ADC_BOOST_CHANNEL_NUM]
pwm_channel_t pwm_out
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 79 of file xplt.ctl_interface.h.
References flag_system_running.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 68 of file xplt.ctl_interface.h.
References boost_ctrl, ctl_enable_boost_ctrl(), and flag_system_running.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 36 of file xplt.ctl_interface.h.
References ADC_BOOST_CHANNEL_NUM, boost_adc_channel, and ctl_step_ptr_adc_channel().
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 45 of file xplt.ctl_interface.h.
References ADC_RESULT_IL, ADC_RESULT_UIN, ADC_RESULT_UOUT, boost_adc_channel, boost_ctrl, ctl_get_boost_ctrl_modulation(), ctl_step_pwm_channel(), pwm_out, and simulink_tx_buffer.
Variable Documentation
boost_adc_channel
ptr_adc_channel_t boost_adc_channel[ADC_BOOST_CHANNEL_NUM] extern
Definition at line 25 of file xplt.peripheral.c.
pwm_out
pwm_channel_t pwm_out extern
Definition at line 33 of file xplt.peripheral.c.