GMP - CTL: suite/pgs_3ph_GFL_inverter/implement/stm32g431/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
#include <xplt.peripheral.h>
Macros
#define UART_RX_DMA_BUFFER_SIZE 32
Functions
void setup_peripheral (void)
void HAL_ADCEx_InjectedConvCpltCallback (ADC_HandleTypeDef *hadc)
Injected conversion complete callback in non blocking mode.
void send_monitor_data (void)
void at_device_flush_rx_buffer ()
void HAL_UARTEx_RxEventCallback (UART_HandleTypeDef *huart, uint16_t Size)
Reception Event Callback (Rx event notification called after use of advanced reception service).
Variables
tri_ptr_adc_channel_t uuvw
adc_gt uuvw_src [3]
tri_ptr_adc_channel_t iuvw
adc_gt iuvw_src [3]
tri_ptr_adc_channel_t vabc
adc_gt vabc_src [3]
tri_ptr_adc_channel_t iabc
adc_gt iabc_src [3]
ptr_adc_channel_t udc
adc_gt udc_src
ptr_adc_channel_t idc
adc_gt idc_src
uint8_t uart_rx_dma_buffer [UART_RX_DMA_BUFFER_SIZE]
uint32_t counter
Macro Definition Documentation
UART_RX_DMA_BUFFER_SIZE
#define UART_RX_DMA_BUFFER_SIZE 32
Definition at line 43 of file xplt.peripheral.c.
Function Documentation
at_device_flush_rx_buffer()
void at_device_flush_rx_buffer ()
Definition at line 294 of file xplt.peripheral.c.
HAL_ADCEx_InjectedConvCpltCallback()
void HAL_ADCEx_InjectedConvCpltCallback (ADC_HandleTypeDef * hadc)
Injected conversion complete callback in non blocking mode.
Parameters
hadc pointer to a ADC_HandleTypeDef structure that contains the configuration information for the specified ADC.
Return values
None
Definition at line 171 of file xplt.peripheral.c.
References counter, gmp_base_ctl_step(), and hadc1.
HAL_UARTEx_RxEventCallback()
void HAL_UARTEx_RxEventCallback (UART_HandleTypeDef * huart, uint16_t Size)
Reception Event Callback (Rx event notification called after use of advanced reception service).
Parameters
huart UART handle
Size Number of data available in application reception buffer (indicates a position in reception buffer until which, data are available)
Return values
None
Definition at line 306 of file xplt.peripheral.c.
References at_dev, hdma_usart2_rx, huart2, uart_rx_dma_buffer, and UART_RX_DMA_BUFFER_SIZE.
send_monitor_data()
void send_monitor_data (void)
Definition at line 246 of file xplt.peripheral.c.
setup_peripheral()
void setup_peripheral (void)
Definition at line 52 of file xplt.peripheral.c.
References ctl_attach_gfl_inv(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_ptr_adc_channel(), ctl_init_tri_ptr_adc_channel(), CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_BASE, CTRL_DC_CURRENT_BIAS, CTRL_DC_CURRENT_SENSITIVITY, CTRL_DC_VOLTAGE_BIAS, CTRL_DC_VOLTAGE_SENSITIVITY, CTRL_GRID_CURRENT_BIAS, CTRL_GRID_CURRENT_SENSITIVITY, CTRL_GRID_VOLTAGE_BIAS, CTRL_GRID_VOLTAGE_SENSITIVITY, CTRL_INVERTER_CURRENT_BIAS, CTRL_INVERTER_CURRENT_SENSITIVITY, CTRL_INVERTER_VOLTAGE_BIAS, CTRL_INVERTER_VOLTAGE_SENSITIVITY, CTRL_VOLTAGE_BASE, hadc1, hadc2, hdac1, hdma_usart2_rx, htim1, htim3, htim4, huart2, iabc, iabc_src, idc, idc_src, inv_ctrl, iuvw, iuvw_src, uart_rx_dma_buffer, UART_RX_DMA_BUFFER_SIZE, udc, udc_src, uuvw, uuvw_src, vabc, and vabc_src.
Variable Documentation
counter
uint32_t counter
Definition at line 46 of file xplt.peripheral.c.
iabc
tri_ptr_adc_channel_t iabc
Definition at line 33 of file xplt.peripheral.c.
iabc_src
adc_gt iabc_src[3]
Definition at line 34 of file xplt.peripheral.c.
idc
ptr_adc_channel_t idc
Definition at line 39 of file xplt.peripheral.c.
idc_src
adc_gt idc_src
Definition at line 40 of file xplt.peripheral.c.
iuvw
tri_ptr_adc_channel_t iuvw
Definition at line 25 of file xplt.peripheral.c.
iuvw_src
adc_gt iuvw_src[3]
Definition at line 26 of file xplt.peripheral.c.
uart_rx_dma_buffer
uint8_t uart_rx_dma_buffer[UART_RX_DMA_BUFFER_SIZE]
Definition at line 44 of file xplt.peripheral.c.
udc
ptr_adc_channel_t udc
Definition at line 37 of file xplt.peripheral.c.
udc_src
adc_gt udc_src
Definition at line 38 of file xplt.peripheral.c.
uuvw
tri_ptr_adc_channel_t uuvw
Definition at line 21 of file xplt.peripheral.c.
uuvw_src
adc_gt uuvw_src[3]
Definition at line 22 of file xplt.peripheral.c.
vabc
tri_ptr_adc_channel_t vabc
Definition at line 29 of file xplt.peripheral.c.
vabc_src
adc_gt vabc_src[3]
Definition at line 30 of file xplt.peripheral.c.