GMP - CTL: suite/mcs_pmsm_nt/implement/f280049c/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
#include <xplt.peripheral.h>
#include <ctl/component/dsa/dsa_trigger.h>
Data Structures
union can_data_t
Macros
#define DLOG_MEM_LENGTH 100
#define CAN_SCALE_FACTOR 10000
#define ISR_LOCAL_BUF_SIZE 16
Functions
void setup_peripheral (void)
interrupt void MainISR (void)
interrupt void INT_IRIS_CAN_0_ISR (void)
interrupt void INT_IRIS_CAN_1_ISR (void)
void send_monitor_data (void)
void at_device_flush_rx_buffer ()
interrupt void INT_IRIS_UART_USB_RX_ISR (void)
Variables
tri_ptr_adc_channel_t uuvw
adc_gt uuvw_src [3]
tri_ptr_adc_channel_t iuvw
adc_gt iuvw_src [3]
ptr_adc_channel_t udc
adc_gt udc_src
ptr_adc_channel_t idc
adc_gt idc_src
basic_trigger_t trigger
ctrl_gt dlog_mem1 [DLOG_MEM_LENGTH]
ctrl_gt dlog_mem2 [DLOG_MEM_LENGTH]
Macro Definition Documentation
CAN_SCALE_FACTOR
#define CAN_SCALE_FACTOR 10000
Definition at line 168 of file xplt.peripheral.c.
DLOG_MEM_LENGTH
#define DLOG_MEM_LENGTH 100
Definition at line 38 of file xplt.peripheral.c.
ISR_LOCAL_BUF_SIZE
#define ISR_LOCAL_BUF_SIZE 16
Definition at line 281 of file xplt.peripheral.c.
Function Documentation
at_device_flush_rx_buffer()
void at_device_flush_rx_buffer ()
Definition at line 283 of file xplt.peripheral.c.
References at_dev, and ISR_LOCAL_BUF_SIZE.
INT_IRIS_CAN_0_ISR()
interrupt void INT_IRIS_CAN_0_ISR (void)
Definition at line 177 of file xplt.peripheral.c.
References CIA402_CMD_DISABLE_VOLTAGE, CIA402_CMD_ENABLE_OPERATION, cia402_send_cmd(), and cia402_sm.
INT_IRIS_CAN_1_ISR()
interrupt void INT_IRIS_CAN_1_ISR (void)
Definition at line 224 of file xplt.peripheral.c.
INT_IRIS_UART_USB_RX_ISR()
interrupt void INT_IRIS_UART_USB_RX_ISR (void)
Definition at line 299 of file xplt.peripheral.c.
References at_device_flush_rx_buffer().
MainISR()
interrupt void MainISR (void)
Definition at line 107 of file xplt.peripheral.c.
References dlog_mem1, dlog_mem2, dsa_get_trigger_index(), dsa_step_trigger(), gmp_base_ctl_step(), GPIO_WritePin(), mtr_ctrl, phase_alpha, phase_beta, SYSTEM_LED, and trigger.
send_monitor_data()
void send_monitor_data (void)
Definition at line 239 of file xplt.peripheral.c.
References CAN_SCALE_FACTOR, can_data_t::i32, motion_ctrl, mtr_ctrl, phase_alpha, phase_beta, phase_d, phase_q, phase_U, and phase_V.
setup_peripheral()
void setup_peripheral (void)
Definition at line 48 of file xplt.peripheral.c.
References ctl_attach_mtr_current_ctrl_port(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_ptr_adc_channel(), ctl_init_tri_ptr_adc_channel(), CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_BASE, CTRL_DC_CURRENT_BIAS, CTRL_DC_CURRENT_SENSITIVITY, CTRL_DC_VOLTAGE_BIAS, CTRL_DC_VOLTAGE_SENSITIVITY, CTRL_INVERTER_CURRENT_BIAS, CTRL_INVERTER_CURRENT_SENSITIVITY, CTRL_INVERTER_VOLTAGE_BIAS, CTRL_INVERTER_VOLTAGE_SENSITIVITY, CTRL_VOLTAGE_BASE, DLOG_MEM_LENGTH, dsa_init_basic_trigger(), idc, idc_src, iuvw, iuvw_src, mtr_ctrl, pos_enc, rg, spd_enc, trigger, udc, udc_src, uuvw, and uuvw_src.
Variable Documentation
dlog_mem1
ctrl_gt dlog_mem1[DLOG_MEM_LENGTH]
Definition at line 41 of file xplt.peripheral.c.
dlog_mem2
ctrl_gt dlog_mem2[DLOG_MEM_LENGTH]
Definition at line 42 of file xplt.peripheral.c.
idc
ptr_adc_channel_t idc
Definition at line 33 of file xplt.peripheral.c.
idc_src
adc_gt idc_src
Definition at line 34 of file xplt.peripheral.c.
iuvw
tri_ptr_adc_channel_t iuvw
Definition at line 27 of file xplt.peripheral.c.
iuvw_src
adc_gt iuvw_src[3]
Definition at line 28 of file xplt.peripheral.c.
trigger
basic_trigger_t trigger
Definition at line 37 of file xplt.peripheral.c.
udc
ptr_adc_channel_t udc
Definition at line 31 of file xplt.peripheral.c.
udc_src
adc_gt udc_src
Definition at line 32 of file xplt.peripheral.c.
uuvw
tri_ptr_adc_channel_t uuvw
Definition at line 23 of file xplt.peripheral.c.
uuvw_src
adc_gt uuvw_src[3]
Definition at line 24 of file xplt.peripheral.c.