GMP - CTL: suite/pgs_3ph_grid_inverter/implement/simulate/xplt.ctl_interface.h File Reference
xplt.ctl_interface.h File Reference
#include <ctl/component/motor_control/basic/std_sil_motor_interface.h>
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_INTERFACE_H_
Enumerations
enum inv_adc_index_items {
INV_ADC_ID_IDC = 0 , INV_ADC_ID_VDC = 1 , INV_ADC_ID_UAB = 2 , INV_ADC_ID_UBC = 3 ,
INV_ADC_ID_IA = 4 , INV_ADC_ID_IB = 5 , INV_ADC_ID_IC = 6 , INV_ADC_SENSOR_NUMBER = 7
}
Functions
GMP_STATIC_INLINE void ctl_input_callback (void)
GMP_STATIC_INLINE void ctl_output_callback (void)
GMP_STATIC_INLINE void ctl_enable_output ()
GMP_STATIC_INLINE void ctl_disable_output ()
Variables
inv_ctrl_t inv_ctrl
Macro Definition Documentation
_FILE_CTL_INTERFACE_H_
#define _FILE_CTL_INTERFACE_H_
Definition at line 18 of file xplt.ctl_interface.h.
Enumeration Type Documentation
inv_adc_index_items
enum inv_adc_index_items
Enumerator
INV_ADC_ID_IDC
INV_ADC_ID_VDC
INV_ADC_ID_UAB
INV_ADC_ID_UBC
INV_ADC_ID_IA
INV_ADC_ID_IB
INV_ADC_ID_IC
INV_ADC_SENSOR_NUMBER
Definition at line 31 of file xplt.ctl_interface.h.
Function Documentation
ctl_disable_output()
GMP_STATIC_INLINE void ctl_disable_output (void)
Definition at line 208 of file xplt.ctl_interface.h.
References flag_system_running.
ctl_enable_output()
GMP_STATIC_INLINE void ctl_enable_output (void)
Definition at line 197 of file xplt.ctl_interface.h.
References ctl_enable_three_phase_inverter(), flag_system_running, and inv_ctrl.
ctl_input_callback()
GMP_STATIC_INLINE void ctl_input_callback (void)
Definition at line 52 of file xplt.ctl_interface.h.
References ctl_step_ptr_adc_channel(), ctl_step_tri_ptr_adc_channel(), iabc, iabc_src, idc, idc_src, INV_ADC_ID_IA, INV_ADC_ID_IB, INV_ADC_ID_IC, INV_ADC_ID_IDC, INV_ADC_ID_UAB, INV_ADC_ID_UBC, INV_ADC_ID_VDC, iuvw, iuvw_src, phase_A, phase_B, phase_C, phase_U, phase_V, phase_W, simulink_rx_buffer, udc, udc_src, uuvw, uuvw_src, vabc, and vabc_src.
ctl_output_callback()
GMP_STATIC_INLINE void ctl_output_callback (void)
Definition at line 85 of file xplt.ctl_interface.h.
References ctl_calc_pwm_tri_channel(), inv_ctrl, phase_A, phase_alpha, phase_B, phase_beta, phase_d, phase_q, phase_U, phase_V, phase_W, phasor_cos, phasor_sin, pwm_out, and simulink_tx_buffer.
Variable Documentation
inv_ctrl
inv_ctrl_t inv_ctrl extern
Definition at line 41 of file ctl_main.c.