GMP - CTL: suite/mcs_pmsm_smo/implement/f280049c/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
Functions
void setup_peripheral (void)
interrupt void MainISR (void)
interrupt void INT_EPWMU_ISR (void)
Variables
tri_ptr_adc_channel_t uabc
tri_ptr_adc_channel_t iabc
ptr_adc_channel_t udc
ptr_adc_channel_t idc
pwm_tri_channel_t pwm_out
adc_gt uabc_raw [3]
adc_gt iabc_raw [3]
adc_gt udc_raw
adc_gt idc_raw
ext_as5048a_encoder_t pos_enc
Function Documentation
INT_EPWMU_ISR()
interrupt void INT_EPWMU_ISR (void)
Definition at line 148 of file xplt.peripheral.c.
MainISR()
interrupt void MainISR (void)
Definition at line 118 of file xplt.peripheral.c.
References gmp_base_ctl_step().
setup_peripheral()
void setup_peripheral (void)
Definition at line 50 of file xplt.peripheral.c.
References CONTROLLER_PWM_CMP_MAX, ctl_attach_mtr_adc_channels(), ctl_attach_mtr_position(), ctl_attach_pmsm_smo_bare_output(), ctl_init_ptr_adc_channel(), ctl_init_pwm_tri_channel(), ctl_init_tri_ptr_adc_channel(), float2ctrl, iabc, iabc_raw, idc, idc_raw, MOTOR_PARAM_POLE_PAIRS, MTR_CTRL_CURRENT_BIAS, MTR_CTRL_CURRENT_GAIN, MTR_CTRL_VOLTAGE_BIAS, MTR_CTRL_VOLTAGE_GAIN, pmsm_ctrl, pos_enc, pwm_out, uabc, uabc_raw, udc, and udc_raw.
Variable Documentation
iabc
tri_ptr_adc_channel_t iabc
Definition at line 26 of file xplt.peripheral.c.
iabc_raw
adc_gt iabc_raw[3]
Definition at line 37 of file xplt.peripheral.c.
idc
ptr_adc_channel_t idc
Definition at line 29 of file xplt.peripheral.c.
idc_raw
adc_gt idc_raw
Definition at line 39 of file xplt.peripheral.c.
pos_enc
ext_as5048a_encoder_t pos_enc
Definition at line 42 of file xplt.peripheral.c.
pwm_out
pwm_tri_channel_t pwm_out
Definition at line 33 of file xplt.peripheral.c.
uabc
tri_ptr_adc_channel_t uabc
Definition at line 25 of file xplt.peripheral.c.
uabc_raw
adc_gt uabc_raw[3]
Definition at line 36 of file xplt.peripheral.c.
udc
ptr_adc_channel_t udc
Definition at line 28 of file xplt.peripheral.c.
udc_raw
adc_gt udc_raw
Definition at line 38 of file xplt.peripheral.c.