GMP - CTL: suite/dps_boost/implement/common/user_main.h File Reference
user_main.h File Reference
Functions
void init (void)
void mainloop (void)
void setup_peripheral (void)
void ctl_init (void)
void ctl_mainloop (void)
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 55 of file ctl_main.c.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 140 of file ctl_main.c.
init()
void init (void)
Definition at line 18 of file user_main.c.
mainloop()
void mainloop (void)
Definition at line 24 of file user_main.c.
setup_peripheral()
void setup_peripheral (void)
Definition at line 40 of file xplt.peripheral.c.
References ctl_attach_mtr_adc_channels(), ctl_attach_mtr_position(), ctl_attach_pmsm_output(), ctl_init_autoturn_pos_encoder(), ctl_init_pwm_tri_channel(), CTRL_PWM_CMP_MAX, iabc, idc, MOTOR_PARAM_POLE_PAIRS, pmsm_ctrl, pos_enc, pwm_out, uabc, and udc.