GMP - CTL: suite/pgs_3ph_GFL_inverter/implement/common/ctl_main.c File Reference
ctl_main.c File Reference
#include <gmp_core.h>
#include <ctrl_settings.h>
#include "ctl_main.h"
#include <xplt.peripheral.h>
Functions
void ctl_init ()
void ctl_mainloop (void)
void ctl_enable_pwm ()
硬件PWM输出使能/禁止
void ctl_disable_pwm ()
fast_gt ctl_check_pll_locked (void)
启动/复位锁相环 (PLL)
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
Variables
cia402_sm_t cia402_sm
spwm_modulator_t spwm
gfl_pq_ctrl_t pq_ctrl
inv_neg_ctrl_init_t gfl_neg_init
inv_neg_ctrl_t neg_current_ctrl
gfl_inv_ctrl_init_t gfl_init
gfl_inv_ctrl_t inv_ctrl
volatile fast_gt flag_system_running = 0
volatile fast_gt flag_error = 0
adc_bias_calibrator_t adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 0
volatile fast_gt index_adc_calibrator = 0
ctl_triangle_wave_generator_t tri_wave
Function Documentation
ctl_check_pll_locked()
fast_gt ctl_check_pll_locked (void)
启动/复位锁相环 (PLL)
Note
在 Ready to Switch On 状态下必须启动 PLL
Definition at line 217 of file ctl_main.c.
References ctl_abs, ctl_get_gfl_pll_error(), ctl_is_gfl_grid_connected(), CTRL_SPLL_EPSILON, and inv_ctrl.
ctl_disable_pwm()
void ctl_disable_pwm (void)
Definition at line 206 of file ctl_main.c.
References ctl_clear_gfl_inv(), ctl_clear_gfl_pq(), ctl_clear_neg_inv(), ctl_fast_disable_output(), inv_ctrl, neg_current_ctrl, and pq_ctrl.
ctl_enable_pwm()
void ctl_enable_pwm (void)
硬件PWM输出使能/禁止
Note
在 Operation Enabled 状态下为 true，其他状态为 false
Parameters
enable true: 开启PWM驱动; false: 封锁PWM（高阻态或特定电平）
Definition at line 201 of file ctl_main.c.
References ctl_fast_enable_output().
ctl_exec_adc_calibration()
fast_gt ctl_exec_adc_calibration (void)
执行ADC偏置校准
Note
通常在 Not Ready 或 Switch On Disabled 状态下调用
Returns
true: 校准完成且成功; false: 失败或正在进行中
Definition at line 235 of file ctl_main.c.
References adc_calibrator, ctl_clear_adc_calibrator(), ctl_clear_gfl_inv_with_PLL(), ctl_div, ctl_enable_adc_calibrator(), ctl_get_adc_calibrator_result(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), flag_enable_adc_calibrator, iabc, idc, index_adc_calibrator, inv_ctrl, iuvw, uuvw, and vabc.
ctl_init()
void ctl_init (void)
Definition at line 63 of file ctl_main.c.
References adc_calibrator, CIA402_CMD_ENABLE_OPERATION, cia402_sm, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCHED_ON, CONTROLLER_FREQUENCY, ctl_attach_gfl_pq_to_core(), ctl_attach_neg_inv_to_gfl(), ctl_auto_tuning_gfl_inv(), ctl_auto_tuning_neg_inv(), ctl_enable_adc_calibrator(), ctl_enable_gfl_inv_active_damp(), ctl_enable_gfl_inv_decouple(), ctl_enable_gfl_inv_lead_compensator(), ctl_enable_gfl_inv_pll(), ctl_enable_neg_current_inv(), ctl_fast_disable_output(), ctl_init_adc_calibrator(), ctl_init_gfl_inv(), ctl_init_gfl_pq(), ctl_init_neg_inv(), ctl_init_npc_modulator(), ctl_init_spwm_modulator(), ctl_init_triangle_wave_generator(), ctl_set_gfl_inv_current(), ctl_set_gfl_inv_current_mode(), ctl_set_gfl_inv_grid_connect(), ctl_set_gfl_inv_openloop_mode(), ctl_set_gfl_inv_voltage_openloop(), CTRL_CURRENT_BASE, CTRL_PWM_CMP_MAX, CTRL_PWM_DEADBAND_CMP, CTRL_VOLTAGE_BASE, flag_enable_adc_calibrator, float2ctrl, gfl_init, gfl_neg_init, iabc, init_cia402_state_machine(), inv_ctrl, neg_current_ctrl, phase_A, phase_B, phase_C, phase_d, phase_q, pq_ctrl, spwm, and tri_wave.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 191 of file ctl_main.c.
References cia402_dispatch(), and cia402_sm.
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator
Definition at line 52 of file ctl_main.c.
cia402_sm
cia402_sm_t cia402_sm
Definition at line 27 of file ctl_main.c.
flag_enable_adc_calibrator
volatile fast_gt flag_enable_adc_calibrator = 0
Definition at line 54 of file ctl_main.c.
flag_error
volatile fast_gt flag_error = 0
Definition at line 49 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running = 0
Definition at line 48 of file ctl_main.c.
gfl_init
gfl_inv_ctrl_init_t gfl_init
Definition at line 40 of file ctl_main.c.
gfl_neg_init
inv_neg_ctrl_init_t gfl_neg_init
Definition at line 38 of file ctl_main.c.
index_adc_calibrator
volatile fast_gt index_adc_calibrator = 0
Definition at line 55 of file ctl_main.c.
inv_ctrl
gfl_inv_ctrl_t inv_ctrl
Definition at line 41 of file ctl_main.c.
neg_current_ctrl
inv_neg_ctrl_t neg_current_ctrl
Definition at line 39 of file ctl_main.c.
pq_ctrl
gfl_pq_ctrl_t pq_ctrl
Definition at line 37 of file ctl_main.c.
spwm
spwm_modulator_t spwm
Definition at line 33 of file ctl_main.c.
tri_wave
ctl_triangle_wave_generator_t tri_wave
Definition at line 57 of file ctl_main.c.