GMP - CTL: suite/pgs_1ph_dcac_dual_stage_rectifier/implement/common/ctl_main.h File Reference
ctl_main.h File Reference
#include <ctl/component/motor_control/basic/vf_generator.h>
#include <ctl\component\motor_control\basic\encoder.h>
#include <ctl/component/interface/pwm_channel.h>
#include <ctl/component/interface/adc_channel.h>
#include <xplt.peripheral.h>
#include <ctl/component/intrinsic/discrete/signal_generator.h>
#include <ctl/component/digital_power/single_phase/single_phase_dc_ac.h>
#include <ctl/component/digital_power/basic/buck.h>
Functions
GMP_STATIC_INLINE void ctl_dispatch (void)
Variables
volatile fast_gt flag_system_enable
volatile fast_gt flag_system_running
sinv_ctrl_t sinv_ctrl
buck_ctrl_t buck_ctrl
ctl_pid_t current_outer
ctrl_gt ig_rms_ref
ctrl_gt V_set
Function Documentation
ctl_dispatch()
GMP_STATIC_INLINE void ctl_dispatch (void)
Definition at line 50 of file ctl_main.h.
References buck_ctrl, ctl_set_buck_ctrl_voltage(), ctl_step_buck_ctrl(), ctl_step_sinv(), sinv_ctrl, and V_set.
Variable Documentation
buck_ctrl
buck_ctrl_t buck_ctrl extern
Definition at line 38 of file ctl_main.c.
current_outer
ctl_pid_t current_outer extern
Definition at line 30 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable extern
Definition at line 30 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running extern
Definition at line 35 of file ctl_main.c.
ig_rms_ref
ctrl_gt ig_rms_ref extern
Definition at line 31 of file ctl_main.c.
sinv_ctrl
sinv_ctrl_t sinv_ctrl extern
Definition at line 28 of file ctl_main.c.
V_set
ctrl_gt V_set extern
Definition at line 29 of file ctl_main.c.