GMP - CTL: suite/dps_dcac_rectifier_spfc/implement/simulate/xplt.peripheral.c File Reference
xplt.peripheral.c File Reference
#include <gmp_core.h>
#include "user_main.h"
#include <xplt.peripheral.h>
Functions
void setup_peripheral (void)
Variables
ptr_adc_channel_t boost_adc_channel [ADC_BOOST_CHANNEL_NUM]
pwm_channel_t pwm_out
Function Documentation
setup_peripheral()
void setup_peripheral (void)
Definition at line 33 of file xplt.peripheral.c.
References ADC_RESULT_IL, ADC_RESULT_UIN, ADC_RESULT_UOUT, boost_adc_channel, boost_ctrl, CONTROLLER_PWM_CMP_MAX, ctl_attach_boost_ctrl_input(), ctl_bias_calc_via_Vref_Vbias(), ctl_init_ptr_adc_channel(), ctl_init_pwm_channel(), CTRL_ADC_RESOLUTION, CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_ADC_BIAS, CTRL_CURRENT_ADC_GAIN, CTRL_CURRENT_BASE, CTRL_VOLTAGE_ADC_GAIN, CTRL_VOLTAGE_BASE, pwm_out, and simulink_rx_buffer.
Variable Documentation
boost_adc_channel
ptr_adc_channel_t boost_adc_channel[ADC_BOOST_CHANNEL_NUM]
Definition at line 25 of file xplt.peripheral.c.
pwm_out
pwm_channel_t pwm_out
Definition at line 26 of file xplt.peripheral.c.