GMP - CTL: tb/GMP_CTL_Intrinsic_UT/common/user_main.h File Reference
user_main.h File Reference
Functions
void init (void)
void mainloop (void)
void setup_peripheral (void)
void ctl_init (void)
void ctl_mainloop (void)
Function Documentation
ctl_init()
void ctl_init (void)
Definition at line 55 of file ctl_main.c.
References acm_sensored_bare_controller_init_t::acc_limit_max, pmsm_controller_init_t::acc_limit_max, pmsm_smo_controller_init_t::acc_limit_max, acm_sensored_bare_controller_init_t::acc_limit_min, pmsm_controller_init_t::acc_limit_min, pmsm_smo_controller_init_t::acc_limit_min, acm_ctrl, adc_calibrator, acm_sensored_bare_controller_init_t::base_freq, acm_sensored_bare_controller_init_t::base_spd, boost_ctrl, buck_ctrl, CIA402_CMD_ENABLE_OPERATION, cia402_sm, CIA402_SM_READY_TO_SWITCH_ON, CIA402_SM_SWITCHED_ON, CONTROLLER_FREQUENCY, ctl_acm_sensored_ctrl_current_mode(), ctl_acm_sensored_ctrl_voltage_mode(), ctl_attach_acm_sensored_bare_rotor_postion(), ctl_attach_gfl_pq_to_core(), ctl_attach_mtr_current_ctrl_port(), ctl_attach_mtr_position(), ctl_attach_mtr_protect_port(), ctl_attach_mtr_velocity(), ctl_attach_neg_inv_to_gfl(), ctl_attach_vel_pos_ctrl(), ctl_auto_tuning_gfl_inv(), ctl_auto_tuning_mtr_current_ctrl(), ctl_auto_tuning_neg_inv(), ctl_auto_tuning_pmsm_smo(), ctl_boost_ctrl_current_mode(), ctl_boost_ctrl_openloop_mode(), ctl_boost_ctrl_voltage_mode(), ctl_buck_ctrl_current_mode(), ctl_buck_ctrl_openloop_mode(), ctl_buck_ctrl_voltage_mode(), ctl_disable_acm_sensored_ctrl_output(), ctl_disable_mppt_PnO_algo(), ctl_disable_mtr_current_ctrl(), ctl_disable_output(), ctl_disable_pmsm_ctrl_output(), ctl_disable_pmsm_mtpa_ctrl_output(), ctl_disable_sinv_harm_ctrl(), ctl_disable_three_phase_feedforward(), ctl_disable_three_phase_harm_ctrl(), ctl_disable_three_phase_negative_ctrl(), ctl_enable_acm_sensored_ctrl(), ctl_enable_adc_calibrator(), ctl_enable_gfl_inv_active_damp(), ctl_enable_gfl_inv_decouple(), ctl_enable_gfl_inv_lead_compensator(), ctl_enable_gfl_inv_pll(), ctl_enable_mtr_current_ctrl(), ctl_enable_neg_current_inv(), ctl_enable_output(), ctl_enable_pmsm_ctrl(), ctl_enable_pmsm_mtpa_ctrl(), ctl_enable_pmsm_smo(), ctl_enable_pmsm_smo_ctrl(), ctl_enable_sinv_harm_ctrl(), ctl_enable_three_phase_harm_ctrl(), ctl_enable_three_phase_negative_current_ctrl(), ctl_enable_three_phase_negative_voltage_ctrl(), ctl_enable_velocity_ctrl(), ctl_fast_disable_output(), ctl_init_acm_sensored_bare_controller(), ctl_init_adc_calibrator(), ctl_init_autoturn_pos_encoder(), ctl_init_boost_ctrl(), ctl_init_buck_ctrl(), ctl_init_const_f_controller(), ctl_init_const_slope_f_controller(), ctl_init_const_slope_f_pu_controller(), ctl_init_gfl_inv(), ctl_init_gfl_pq(), ctl_init_mppt_PnO_algo(), ctl_init_mtr_current_ctrl(), ctl_init_mtr_protect(), ctl_init_neg_inv(), ctl_init_npc_modulator(), ctl_init_pmsm_controller(), ctl_init_pmsm_mtpa_bare_controller(), ctl_init_pmsm_smo(), ctl_init_pmsm_smo_bare_controller(), ctl_init_sinv_ctrl(), ctl_init_spd_calculator(), ctl_init_spwm_modulator(), ctl_init_three_phase_inv(), ctl_init_triangle_wave_generator(), ctl_init_vel_pos_ctrl(), CTL_PARAM_CONST_2PI, CTL_PARAM_CONST_PI, ctl_pmsm_ctrl_current_mode(), ctl_pmsm_ctrl_velocity_mode(), ctl_pmsm_ctrl_voltage_mode(), ctl_pmsm_mtpa_ctrl_current_mode(), ctl_pmsm_mtpa_ctrl_velocity_mode(), ctl_pmsm_mtpa_ctrl_voltage_mode(), ctl_pmsm_smo_ctrl_current_mode(), ctl_pmsm_smo_ctrl_voltage_mode(), ctl_set_acm_sensored_ctrl_idq_ff(), ctl_set_acm_sensored_ctrl_speed(), ctl_set_acm_sensored_ctrl_vdq_ff(), ctl_set_autoturn_pos_encoder_mech_offset(), ctl_set_autoturn_pos_encoder_offset(), ctl_set_boost_ctrl_current(), ctl_set_boost_ctrl_voltage(), ctl_set_boost_ctrl_voltage_openloop(), ctl_set_buck_ctrl_current(), ctl_set_buck_ctrl_voltage(), ctl_set_buck_ctrl_voltage_openloop(), ctl_set_gfl_inv_current(), ctl_set_gfl_inv_current_mode(), ctl_set_gfl_inv_grid_connect(), ctl_set_gfl_inv_openloop_mode(), ctl_set_gfl_inv_voltage_openloop(), ctl_set_mtr_current_ctrl_ref(), ctl_set_mtr_current_ctrl_vdq_ref(), ctl_set_mtr_protect_mask(), ctl_set_pmsm_ctrl_idq_ff(), ctl_set_pmsm_ctrl_speed(), ctl_set_pmsm_ctrl_vdq_ff(), ctl_set_pmsm_mtpa_ctrl_idq_ff(), ctl_set_pmsm_mtpa_ctrl_speed(), ctl_set_pmsm_mtpa_ctrl_vdq_ff(), ctl_set_pmsm_smo_ctrl_idq_ff(), ctl_set_pmsm_smo_ctrl_vdq_ff(), ctl_set_sinv_current_closeloop_inverter(), ctl_set_sinv_current_ref(), ctl_set_sinv_freerun(), ctl_set_sinv_openloop_inverter(), ctl_set_sinv_pll(), ctl_set_sinv_voltage_closeloop_inverter(), ctl_set_sinv_voltage_closeloop_rectifier(), ctl_set_sinv_voltage_ref(), ctl_set_target_velocity(), ctl_set_three_phase_inv_current(), ctl_set_three_phase_inv_current_mode(), ctl_set_three_phase_inv_freerun(), ctl_set_three_phase_inv_openloop_mode(), ctl_set_three_phase_inv_voltage(), ctl_set_three_phase_inv_voltage_mode(), ctl_set_three_phase_inv_voltage_openloop(), CTRL_CURRENT_BASE, CTRL_FS, CTRL_POS_DIV, CTRL_POS_ENC_BIAS, CTRL_POS_ENC_FS, CTRL_PWM_CMP_MAX, CTRL_PWM_DEADBAND_CMP, CTRL_SPD_DIV, CTRL_VOLTAGE_BASE, acm_sensored_bare_controller_init_t::current_limit_max, pmsm_controller_init_t::current_limit_max, pmsm_smo_controller_init_t::current_limit_max, acm_sensored_bare_controller_init_t::current_limit_min, pmsm_controller_init_t::current_limit_min, pmsm_smo_controller_init_t::current_limit_min, current_outer, acm_sensored_bare_controller_init_t::current_pid_gain, pmsm_controller_init_t::current_pid_gain, pmsm_smo_controller_init_t::current_pid_gain, acm_sensored_bare_controller_init_t::current_Td, pmsm_controller_init_t::current_Td, pmsm_smo_controller_init_t::current_Td, acm_sensored_bare_controller_init_t::current_Ti, pmsm_controller_init_t::current_Ti, pmsm_smo_controller_init_t::current_Ti, ctl_const_f_controller::enc, flag_enable_adc_calibrator, flag_enable_system, flag_system_enable, float2ctrl, acm_sensored_bare_controller_init_t::fs, pmsm_controller_init_t::fs, pmsm_smo_controller_init_t::fs, gfl_init, gfl_neg_init, pmsm_smo_controller_init_t::i_base, iabc, index_adc_calibrator, init(), init_cia402_state_machine(), inv_ctrl, iuvw, pmsm_smo_controller_init_t::Ld, pmsm_smo_controller_init_t::Lq, acm_sensored_bare_controller_init_t::Lr, motion_ctrl, MOTOR_PARAM_L1R, MOTOR_PARAM_LM, MOTOR_PARAM_LS, MOTOR_PARAM_MAX_SPEED, MOTOR_PARAM_POLE_PAIRS, MOTOR_PARAM_RATED_FREQUENCY, MOTOR_PARAM_RATED_VOLTAGE, MOTOR_PARAM_RR, MOTOR_PARAM_RS, mtr_ctrl, MTR_CTRL_CURRENT_BASE, MTR_CTRL_CURRENT_LOOP_BW, mtr_ctrl_init, MTR_CTRL_SPEED_LOOP_BW, MTR_CTRL_VOLTAGE_BASE, MTR_ENCODER_LINES, MTR_ENCODER_OFFSET, MTR_PROT_DEVIATION, neg_current_ctrl, phase_A, phase_B, phase_C, phase_d, phase_q, pmsm_ctrl, pmsm_mtpa_ctrl, acm_sensored_bare_controller_init_t::pole_pairs, pmsm_smo_controller_init_t::pole_pairs, pos_enc, pq_ctrl, protection, pmsm_smo_controller_init_t::ramp_target_freq, pmsm_smo_controller_init_t::ramp_target_freq_slope, rg, acm_sensored_bare_controller_init_t::Rr, pmsm_smo_controller_init_t::Rs, sinv_ctrl, slope_f, pmsm_smo_controller_init_t::smo_fc_e, pmsm_smo_controller_init_t::smo_fc_omega, pmsm_smo_controller_init_t::smo_k_slide, pmsm_smo_controller_init_t::smo_kp, pmsm_smo_controller_init_t::smo_Td, pmsm_smo_controller_init_t::smo_Ti, SPD_CONTROLLER_PWM_DIVISION, acm_sensored_bare_controller_init_t::spd_ctrl_div, pmsm_controller_init_t::spd_ctrl_div, pmsm_smo_controller_init_t::spd_ctrl_div, spd_enc, acm_sensored_bare_controller_init_t::spd_pid_gain, pmsm_controller_init_t::spd_pid_gain, pmsm_smo_controller_init_t::spd_pid_gain, acm_sensored_bare_controller_init_t::spd_Td, pmsm_controller_init_t::spd_Td, pmsm_smo_controller_init_t::spd_Td, acm_sensored_bare_controller_init_t::spd_Ti, pmsm_controller_init_t::spd_Ti, pmsm_smo_controller_init_t::spd_Ti, pmsm_smo_controller_init_t::speed_base_rpm, spwm, acm_sensored_bare_controller_init_t::target_freq_slope, tri_wave, pmsm_smo_controller_init_t::u_base, udc, acm_sensored_bare_controller_init_t::voltage_limit_max, pmsm_controller_init_t::voltage_limit_max, pmsm_smo_controller_init_t::voltage_limit_max, acm_sensored_bare_controller_init_t::voltage_limit_min, pmsm_controller_init_t::voltage_limit_min, and pmsm_smo_controller_init_t::voltage_limit_min.
ctl_mainloop()
void ctl_mainloop (void)
Definition at line 140 of file ctl_main.c.
References acm_ctrl, adc_calibrator, cia402_dispatch(), cia402_sm, ctl_acm_sensored_ctrl_velocity_mode(), ctl_clear_adc_calibrator(), ctl_clear_pmsm_ctrl(), ctl_clear_slope_f(), ctl_disable_output(), ctl_div, ctl_enable_acm_sensored_ctrl_output(), ctl_enable_adc_calibrator(), ctl_enable_mppt_PnO_algo(), ctl_enable_output(), ctl_enable_pmsm_ctrl(), ctl_enable_pmsm_ctrl_output(), ctl_enable_pmsm_mtpa_ctrl_output(), ctl_get_adc_calibrator_result(), ctl_get_mtr_velocity(), ctl_is_adc_calibrator_cmpt(), ctl_is_adc_calibrator_result_valid(), ctl_mul, ctl_ready_mainloop(), ctl_set_pmsm_ctrl_speed(), ctl_set_pmsm_smo_ctrl_speed(), ctl_switch_pmsm_smo_ctrl_using_smo(), CTRL_STARTUP_DELAY, firsttime_flag, flag_enable_adc_calibrator, flag_system_enable, float2ctrl, iabc, idc, index_adc_calibrator, MTR_ADC_IDC, pmsm_ctrl, pmsm_mtpa_ctrl, rg, started_flag, startup_flag, and tick_bias.
init()
void init (void)
Definition at line 18 of file user_main.c.
References at_cmds, at_dev, at_device_error_handler(), i, sched, and tasks.
mainloop()
void mainloop (void)
Definition at line 24 of file user_main.c.
References sched.
setup_peripheral()
void setup_peripheral (void)
Definition at line 40 of file xplt.peripheral.c.
References acm_ctrl, adc1_res, ADC1_SEQ_SIZE, adc2_res, ADC2_SEQ_SIZE, ADC_RESULT_IG, ADC_RESULT_IL, ADC_RESULT_UC, ADC_RESULT_UDC, ADC_RESULT_UIN, ADC_RESULT_UOUT, adc_results, boost_adc_channel, boost_ctrl, buck_adc_channel, buck_ctrl, CONTROLLER_PWM_CMP_MAX, ctl_attach_acm_sensored_bare_output(), ctl_attach_boost_ctrl_input(), ctl_attach_buck_ctrl_input(), ctl_attach_gfl_inv(), ctl_attach_mtr_adc_channels(), ctl_attach_mtr_current_ctrl_port(), ctl_attach_mtr_position(), ctl_attach_pmsm_mtpa_bare_output(), ctl_attach_pmsm_output(), ctl_attach_pmsm_smo_bare_output(), ctl_attach_sinv_with_adc(), ctl_attach_three_phase_inv(), ctl_bias_calc_via_Vref_Vbias(), ctl_gain_calc_generic(), ctl_init_autoturn_pos_encoder(), ctl_init_ptr_adc_channel(), ctl_init_pwm_channel(), ctl_init_pwm_tri_channel(), ctl_init_tri_ptr_adc_channel(), CTRL_ADC_RESOLUTION, CTRL_ADC_VOLTAGE_REF, CTRL_CURRENT_ADC_BIAS, CTRL_CURRENT_ADC_GAIN, CTRL_CURRENT_BASE, CTRL_DC_CURRENT_BIAS, CTRL_DC_CURRENT_SENSITIVITY, CTRL_DC_VOLTAGE_BIAS, CTRL_DC_VOLTAGE_SENSITIVITY, CTRL_GRID_CURRENT_BIAS, CTRL_GRID_CURRENT_SENSITIVITY, CTRL_GRID_VOLTAGE_BIAS, CTRL_GRID_VOLTAGE_SENSITIVITY, CTRL_INVERTER_CURRENT_BIAS, CTRL_INVERTER_CURRENT_SENSITIVITY, CTRL_INVERTER_VOLTAGE_BIAS, CTRL_INVERTER_VOLTAGE_SENSITIVITY, CTRL_PWM_CMP_MAX, CTRL_VOLTAGE_ADC_BIAS, CTRL_VOLTAGE_ADC_GAIN, CTRL_VOLTAGE_BASE, dlog, DLOG_MEM_LENGTH, dlogCh1, dlogCh2, dlogCh3, dlogCh4, dsa_init_basic_trigger(), float2ctrl, hadc1, hadc2, hdac, hdac1, hdma_usart2_rx, htim1, htim3, htim4, huart2, iabc, iabc_raw, iabc_src, idc, idc_raw, idc_src, il, inv_ctrl, iuvw, iuvw_src, MOTOR_PARAM_POLE_PAIRS, mtr_ctrl, MTR_CTRL_CURRENT_BIAS, MTR_CTRL_CURRENT_GAIN, MTR_CTRL_VOLTAGE_BIAS, MTR_CTRL_VOLTAGE_GAIN, MTR_ENCODER_OFFSET, pmsm_ctrl, pmsm_mtpa_ctrl, pos_enc, pwm_out, reset_controller(), rg, simulink_rx_buffer, sinv_adc, SINV_ADC_ID_BUCK_IL, SINV_ADC_ID_BUCK_VIN, SINV_ADC_ID_BUCK_VOUT, SINV_ADC_ID_IC, SINV_ADC_ID_IDC, SINV_ADC_ID_IG, SINV_ADC_ID_IL, SINV_ADC_ID_VDC, SINV_ADC_ID_VG, sinv_ctrl, sinv_ig, sinv_il, sinv_pwm_out, sinv_uc, sinv_udc, spd_enc, trigger, trt_node, TRT_TEST, uabc, uabc_raw, uart_rx_dma_buffer, UART_RX_DMA_BUFFER_SIZE, uc, udc, udc_raw, udc_src, uin, uuvw, uuvw_src, vabc, and vabc_src.