GMP - CTL: tb/GMP_CTL_Intrinsic_UT/common/ctl_main.h File Reference
ctl_main.h File Reference
#include <ctl/component/interface/pwm_channel.h>
#include <ctl/component/interface/adc_channel.h>
#include <ctl\component\digital_power\basic/boost.h>
#include <ctl/component/digital_power/mppt/PnO_algorithm.h>
#include <xplt.peripheral.h>
Macros
#define _FILE_CTL_MAIN_H_
Enumerations
enum adc_result_nameplate_t { ADC_RESULT_IL = 0 , ADC_RESULT_UIN = 1 , ADC_RESULT_UOUT = 2 , ADC_BOOST_CHANNEL_NUM = 3 }
Functions
GMP_STATIC_INLINE void ctl_dispatch (void)
Variables
adc_bias_calibrator_t adc_calibrator
fast_gt flag_enable_adc_calibrator
fast_gt index_adc_calibrator
volatile fast_gt flag_system_enable
volatile fast_gt flag_system_running
boost_ctrl_t boost_ctrl
Macro Definition Documentation
_FILE_CTL_MAIN_H_
#define _FILE_CTL_MAIN_H_
Definition at line 23 of file ctl_main.h.
Enumeration Type Documentation
adc_result_nameplate_t
enum adc_result_nameplate_t
Enumerator
ADC_RESULT_IL
ADC_RESULT_UIN
ADC_RESULT_UOUT
ADC_BOOST_CHANNEL_NUM
Definition at line 31 of file ctl_main.h.
Function Documentation
ctl_dispatch()
GMP_STATIC_INLINE void ctl_dispatch (void)
Definition at line 55 of file ctl_main.h.
References boost_ctrl, ctl_set_boost_ctrl_voltage_openloop(), ctl_step_boost_ctrl(), and ctl_step_mppt_PnO_algo().
Variable Documentation
adc_calibrator
adc_bias_calibrator_t adc_calibrator extern
Definition at line 47 of file ctl_main.c.
boost_ctrl
boost_ctrl_t boost_ctrl extern
Definition at line 39 of file ctl_main.c.
flag_enable_adc_calibrator
fast_gt flag_enable_adc_calibrator extern
Definition at line 48 of file ctl_main.c.
flag_system_enable
volatile fast_gt flag_system_enable extern
Definition at line 30 of file ctl_main.c.
flag_system_running
volatile fast_gt flag_system_running extern
Definition at line 35 of file ctl_main.c.
index_adc_calibrator
fast_gt index_adc_calibrator extern
Definition at line 49 of file ctl_main.c.