/**
 * @file bias_model.h
 * @author Javnson (javnson@zju.edu.cn)
 * @brief Provides helper functions to calculate ADC bias values for common sensor configurations.
 * @version 0.2
 * @date 2025-03-21
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

#ifndef _FILE_BIAS_MODEL_H_
#define _FILE_BIAS_MODEL_H_

#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

/**
 * @defgroup ADC_BIAS_MODELS ADC Bias Calculation Models
 * @ingroup GMP_CTL_COMMON_INTERFACES
 * @brief A collection of functions to determine ADC bias values from circuit parameters.
 *
 * @details The bias value is typically represented in a per-unit (p.u.) system,
 * where the value is normalized with respect to the ADC's reference voltage (Vref).
 * These models help in calculating the expected digital offset for various analog
 * sensor front-end circuits. The calculated bias is essential for correctly
 * interpreting the ADC output.
 */

/*---------------------------------------------------------------------------*/
/* ADC Bias Calculation Models                                               */
/*---------------------------------------------------------------------------*/

/**
 * @addtogroup ADC_BIAS_MODELS
 * @{
 */

/**
 * @brief Calculates the ADC bias in per-unit based on the reference and bias voltages.
 * @details This is the most direct way to calculate bias if the absolute voltages are known.
 * The formula is:
 * @f$
 * \text{bias}_{\text{p.u.}} = \frac{V_{\text{bias}}}{V_{\text{ref}}}
 * @f$
 * @param Vref The ADC reference voltage.
 * @param Vbias The bias voltage applied to the sensor or ADC input.
 * @return The calculated bias in per-unit.
 */
GMP_STATIC_INLINE parameter_gt ctl_bias_calc_via_Vref_Vbias(parameter_gt Vref, parameter_gt Vbias)
{
    // Ensure Vref is not zero to avoid division by zero.
    gmp_base_assert(Vref != 0);
    return Vbias / Vref;
}

/**
 * @brief Calculates the bias generated by a resistive voltage divider.
 * @details This model is for circuits where the bias is set by a voltage divider
 * connected between Vref and GND.
 * The formula is:
 * @f$
 * \text{bias}_{\text{p.u.}} = \frac{R_2}{R_1 + R_2}
 * @f$
 * @param R1 The resistance of the resistor connected between Vref and the output tap.
 * @param R2 The resistance of the resistor connected between the output tap and GND.
 * @return The calculated bias in per-unit.
 */
GMP_STATIC_INLINE parameter_gt ctl_bias_calc_via_res_divider(parameter_gt R1, parameter_gt R2)
{
    parameter_gt R_total = R1 + R2;
    // Ensure total resistance is not zero to avoid division by zero.
    gmp_base_assert(R_total != 0);
    return R2 / R_total;
}

/**
 * @}
 */

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _FILE_BIAS_MODEL_H_
