# This file is generated by AI.

import os
import shutil
import argparse
import filecmp

def copy_file_if_different(source_path, target_path):
    """
    如果源文件和目标文件内容不同，则复制源文件到目标文件位置
    
    参数:
        source_path (str): 源文件路径
        target_path (str): 目标文件路径
    """
    # 检查源文件是否存在
    if not os.path.exists(source_path):
        print(f"错误：源文件 '{source_path}' 不存在！")
        return False
    
    # 检查目标文件是否存在
    if not os.path.exists(os.path.dirname(target_path)):
        print(f"错误：目标文件的目录 '{os.path.dirname(target_path)}' 不存在！")
        return False
    
    # 检查是否是同一文件
    if os.path.samefile(source_path, target_path):
        print(f"注意：源文件和目标文件是同一个文件，无需复制。")
        return False
    
    # 比较文件内容
    if filecmp.cmp(source_path, target_path, shallow=False):
        print(f"文件 '{source_path}' 和 '{target_path}' 内容相同，无需复制。")
        return False
    
    # 复制文件
    try:
        shutil.copyfile(source_path, target_path)
        print(f"成功：已将 '{source_path}' 复制到 '{target_path}'。")
        return True
    except Exception as e:
        print(f"错误：复制文件时出错 - {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description='比较两个文件，如果内容不同则复制源文件到目标位置')
    parser.add_argument('source', help='源文件路径')
    parser.add_argument('target', help='目标文件路径')
    
    args = parser.parse_args()
    
    # 获取文件的绝对路径
    source_path = os.path.abspath(args.source)
    target_path = os.path.abspath(args.target)
    
    copy_file_if_different(source_path, target_path)

if __name__ == "__main__":
    main()