"""
Generate Motor_Model.h from the user-configured motor parameters.

Only parameters with non-None values are emitted.
Auto-calc parameters are written using the formula macro.
"""

import os
from datetime import datetime
from typing import Optional

from .model import (
    MotorParamDef,
    PARAM_DEFS,
    PARAMS_BY_CATEGORY,
    CATEGORY_ORDER,
    ParamCategory,
)


def _format_value(param: MotorParamDef, value: Optional[float], flux_locked: bool) -> str:
    """Format a single #define line for one parameter."""
    macro = param.macro

    # Flux with auto-calc locked → always use formula macro
    if param.auto_calc and flux_locked and macro == "MOTOR_PARAM_FLUX":
        return (
            f"#define {macro} "
            f"((MOTOR_PARAM_CALCULATE_FLUX_BY_KV(\\\n"
            f"        MOTOR_PARAM_KV, MOTOR_PARAM_POLE_PAIRS)))"
        )

    if value is None:
        # Not filled in – skip with a comment
        return f"// #define {macro}  /* 未填写 */"

    # Format the numeric value
    if param.decimals == 0:
        formatted = str(int(value))
    else:
        formatted = f"{value:.{param.decimals}f}"
        # Strip trailing zeros but always keep at least ".0"
        if "." in formatted:
            formatted = formatted.rstrip("0")
            if formatted.endswith("."):
                formatted += "0"
        formatted += "f"

    return f"#define {macro} (({formatted}))"


def generate_motor_model(
    params: dict[str, Optional[float]],
    output_path: str,
    *,
    preset_name: str = "",
    flux_locked: bool = True,
) -> str:
    """
    Generate Motor_Model.h content and write to output_path.

    Parameters
    ----------
    params : dict
        macro_name → float value or None.
    output_path : str
        Destination file path.
    preset_name : str
        Name of the source preset (for the header comment).
    flux_locked : bool
        Whether FLUX is auto-calculated from KV.

    Returns
    -------
    str
        The generated file content.
    """
    lines: list[str] = []
    indent = "    "

    # -- Header --
    lines.append("/**")
    lines.append(f" * @file Motor_Model.h")
    lines.append(f" * @brief User-configured motor parameters.")
    if preset_name:
        lines.append(f" * @note Based on preset: {preset_name}")
    lines.append(f" * @note Generated by MotorAI Hardware Config on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(" */")
    lines.append("")
    guard = "_FILE_MOTOR_MODEL_H_"
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")

    # -- Includes --
    lines.append('#include <ctl/component/motor_control/consultant/unit_consultant.h>')
    lines.append("")

    # -- Parameters grouped by category --
    for cat in CATEGORY_ORDER:
        cat_params = [p for p in PARAM_DEFS if p.category == cat]
        # Write section comment
        lines.append(f"// {'='*60}")
        lines.append(f"// {cat.label}")
        lines.append(f"// {'='*60}")

        for p in cat_params:
            value = params.get(p.macro)
            line = _format_value(p, value, flux_locked)
            lines.append(line)

        lines.append("")

    # -- Footer --
    lines.append(f"#endif // {guard}")
    lines.append("")

    content = "\n".join(lines)

    # Ensure output directory exists
    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with open(output_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)

    return content
